/*#################################################################################################################*/
/************** INICIAR PROCESSO ****************/
%INCLUDE '/dados/infor/suporte/FuncoesInfor.sas';
%LET Keypass=simulacao-portabilidade-consignado-64ecf2b5-f397-447f-90bb-112d0076acb2;
%ProcessoIniciar();
/************************************************/	

LIBNAME DB2CDC DB2 SCHEMA=DB2CDC DATABASE=BDB2P04 AUTHDOMAIN='DB2SGCEN';
LIBNAME DB2BIC 	db2 AUTHDOMAIN=DB2SGCEN schema=DB2BIC database=BDB2P04;



/*CONTROLE DE DATAS*/
DATA _NULL_;
	D1 = TODAY();
/*	D1 = diaUtilAnterior(TODAY());*/
/*	D1 = diaUtilAnterior(MDY(10,01,2018));*/
	D2 = diaUtilAnterior(D1);
	D3 = diaUtilAnterior(D2);
	D4 = diaUtilAnterior(D3);

	AAAAMM = Put(D1, yymmn6.);
	MMAAAA = Put(D1, mmyyn6.);
	MM = Put(D1, MONTH.);
	AAAA = Put(D1, YEAR.);
	INICIO = MDY(10,22,2018);

	CALL SYMPUT('INICIO',COMPRESS(INICIO,' '));

	CALL SYMPUT('DATA_HOJE',COMPRESS(TODAY(),' '));
	CALL SYMPUT('D1',COMPRESS(D1,' '));
	CALL SYMPUT('D2',COMPRESS(D2,' '));
	CALL SYMPUT('D3',COMPRESS(D3,' '));
	CALL SYMPUT('D4',COMPRESS(D4,' '));
	CALL SYMPUT('AAAAMM',COMPRESS(AAAAMM,' '));
	CALL SYMPUT('MMAAAA',COMPRESS(MMAAAA,' '));
	CALL SYMPUT('MM',COMPRESS(MM,' '));
	CALL SYMPUT('AAAA',COMPRESS(AAAA,' '));
RUN; 

%PUT &AAAA;



/*SIMULAÇÕES NO SISTEM CDC ####################################################################################*/
PROC SQL;
	CREATE TABLE WORK.MAX_SIMULACAO_CDC AS 
		SELECT
			t1.CD_CLI_SMLC AS CD_CLI, 
			MAX(t1.TS_SMLC) AS TS_SMLC
		FROM DB2CDC.SMLC_CPRV_CDC t1
		WHERE 
			DATEPART(t1.TS_SMLC)>=&INICIO.
			AND t1.CD_CLI_SMLC>0
		GROUP BY 1
;QUIT;


PROC SQL;
	CREATE TABLE WORK.SLMC_CDC_TT AS 
		SELECT
			t1.CD_CLI_SMLC AS CD_CLI,
			t1.TS_SMLC, 
			INPUT(t1.CD_DDD_CLI_SMLC||t1.NR_TEL_CLI_SMLC,11.) AS FONE_SLMC,
			t1.VL_SDO_DVDR_OTR AS VLR_SDO,
			t1.CD_LNCD
		FROM DB2CDC.SMLC_CPRV_CDC t1
		WHERE 
			t1.CD_CLI_SMLC > 0
			AND DATEPART(t1.TS_SMLC)>=&INICIO.
;QUIT;


PROC SQL;
	CREATE TABLE WORK.SLMC_CDC_TT AS 
		SELECT
			t1.CD_CLI,
			t3.CD_PRF_DEPE AS PREFDEP, 
          	t3.NR_SEQL_CTRA_ATB AS CTRA, 
          	t3.CD_TIP_CTRA AS TP_CTRA,
			t1.TS_SMLC,
			t1.FONE_SLMC, 
			t1.VLR_SDO,
			t1.CD_LNCD
		FROM WORK.SLMC_CDC_TT t1
		LEFT JOIN COMUM.PAI_REL_&AAAAMM. t3 ON(t1.CD_CLI=t3.CD_CLI)
;QUIT;


PROC SQL;
	CREATE TABLE WORK.SLMC_CDC_MAX AS 
		SELECT
			t1.CD_CLI, 
			t1.PREFDEP, 
			t1.CTRA, 
			t1.TP_CTRA,
			t1.TS_SMLC, 
			t1.FONE_SLMC, 
			t1.VLR_SDO,
			t1.CD_LNCD
		FROM WORK.SLMC_CDC_TT t1
		INNER JOIN WORK.MAX_SIMULACAO_CDC t2 ON (t1.CD_CLI=t2.CD_CLI AND t1.TS_SMLC=t2.TS_SMLC)
;QUIT;

PROC SQL;
	CREATE TABLE WORK.QNT_SLMC_CLI AS 
		SELECT 
			t1.CD_CLI, 
			(COUNT(t1.CD_CLI)) AS QNT_SLMC_CLI
		FROM WORK.SLMC_CDC_TT t1
		GROUP BY 1;
QUIT;


PROC SQL;
	CREATE TABLE WORK.SLMC_CDC_MAX AS 
		SELECT 
			t1.CD_CLI, 
			t1.PREFDEP, 
			t1.CTRA, 
			t1.TP_CTRA, 
			t1.TS_SMLC, 
			t1.FONE_SLMC, 
			t1.VLR_SDO, 
			t1.CD_LNCD,
			t2.QNT_SLMC_CLI
		FROM WORK.SLMC_CDC_MAX t1
		LEFT JOIN WORK.QNT_SLMC_CLI t2 ON (t1.CD_CLI=t2.CD_CLI)
;QUIT;


PROC SQL;
	CREATE TABLE WORK.CLI_SMLC AS 
		SELECT DISTINCT 
				t1.CD_CLI
			FROM WORK.SLMC_CDC_MAX t1;
QUIT;


/*SIMULAÇÕES NO SISTEM CDC - FIM ####################################################################################*/









/*CLIENTES QUE SOLICITARAM CONTADO NO SISTEMA BIC ###################################################################*/


PROC SQL;
	CREATE TABLE SLTC_DIA AS
		SELECT 
			t1.CD_CLI, 
			t1.TS_INRO_CLI,
			INPUT(COMPRESS(t1.TX_PTL_INRO_CLI,"1234567890", 'kis'),11.) AS FONE_BIC
		FROM DB2BIC.INRO_CLI t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.CD_CLI)
		WHERE 
				CD_TRAN_INRO_SIS IN ('PCD00001')
			AND DATEPART(TS_INRO_CLI) >= &INICIO.
;QUIT;


PROC SQL;
	CREATE TABLE SLTC_ATU AS
		SELECT 
			t1.CD_CLI, 
			t1.TS_INRO_CLI,
			INPUT(COMPRESS(t1.TX_PTL_INRO_CLI,"1234567890", 'kis'),11.) AS FONE_BIC
		FROM DB2BIC.AUX_INRO_CLI_ATU t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.cd_cli)
		WHERE 
				CD_TRAN_INRO_SIS IN ('PCD00001')
			AND DATEPART(TS_INRO_CLI) >= &INICIO.
;QUIT;

PROC SQL;
	CREATE TABLE SLTC_ANT AS
		SELECT 
			t1.CD_CLI, 
			t1.TS_INRO_CLI,
			INPUT(COMPRESS(t1.TX_PTL_INRO_CLI,"1234567890", 'kis'),11.) AS FONE_BIC
		FROM DB2BIC.AUX_INRO_CLI_ANT t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.cd_cli)
		WHERE 
				CD_TRAN_INRO_SIS IN ('PCD00001')
			AND DATEPART(TS_INRO_CLI) >= &INICIO.
;QUIT;

PROC SQL;
	CREATE TABLE SLTC_CMPR AS
		SELECT 
			t1.CD_CLI, 
			t1.TS_INRO_CLI,
			INPUT(COMPRESS(t1.TX_PTL_INRO_CLI,"1234567890", 'kis'),11.) AS FONE_BIC
		FROM DB2BIC.AUX_INRO_CLI_CMPR t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.cd_cli)
		WHERE 
				CD_TRAN_INRO_SIS IN ('PCD00001')
			AND DATEPART(TS_INRO_CLI) >= &INICIO.
;QUIT;

DATA SLTC;
	SET SLTC_DIA SLTC_ATU SLTC_ANT SLTC_CMPR;
RUN;

PROC SQL;
	CREATE TABLE SLTC_MAX_CLI AS
		SELECT DISTINCT 
			CD_CLI,
			MAX(TS_INRO_CLI) format=datetime25.6 AS TS_INRO_CLI
		FROM SLTC
		GROUP BY 1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.SLTC_MAX AS 
		SELECT DISTINCT
			t1.CD_CLI, 
			t1.TS_INRO_CLI AS TS_SLCT_CLI, 
			t1.FONE_BIC 
		FROM WORK.SLTC t1
		INNER JOIN WORK.SLTC_MAX_CLI t2 ON (t1.CD_CLI=t2.CD_CLI AND t1.TS_INRO_CLI=t2.TS_INRO_CLI)
;QUIT;

/*CLIENTES QUE SOLICITARAM CONTADO NO SISTEMA BIC - FIM ############################################################*/





/*CLIENTES QUE FORAM CONTATADOS NO SISTEMA BIC ####### ############################################################*/
 

PROC SQL;
	CREATE TABLE CTTD_DIA AS
		SELECT 
			t1.CD_CLI,
			t1.TS_INRO_CLI,
			t1.CD_SUB_RSTD_INRO
		FROM DB2BIC.INRO_CLI t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.CD_CLI)
		WHERE 
				t1.CD_TIP_CNL = 55
			AND t1.CD_TRAN_INRO_SIS = 'REL02'
			AND t1.CD_SUB_ASNT_INRO = 83
			AND DATEPART(t1.TS_INRO_CLI) >= &INICIO.
;QUIT;

PROC SQL;
	CREATE TABLE CTTD_ATU AS
		SELECT 
			t1.CD_CLI,
			t1.TS_INRO_CLI,
			t1.CD_SUB_RSTD_INRO
		FROM DB2BIC.AUX_INRO_CLI_ATU t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.cd_cli)
		WHERE 
				t1.CD_TIP_CNL = 55
			AND t1.CD_TRAN_INRO_SIS = 'REL02'
			AND t1.CD_SUB_ASNT_INRO = 83
			AND DATEPART(t1.TS_INRO_CLI) >= &INICIO.
;QUIT;

PROC SQL;
	CREATE TABLE CTTD_ANT AS
		SELECT 
			t1.CD_CLI,
			t1.TS_INRO_CLI,
			t1.CD_SUB_RSTD_INRO
		FROM DB2BIC.AUX_INRO_CLI_ANT t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.cd_cli)
		WHERE 
				t1.CD_TIP_CNL = 55
			AND t1.CD_TRAN_INRO_SIS = 'REL02'
			AND t1.CD_SUB_ASNT_INRO = 83
			AND DATEPART(t1.TS_INRO_CLI) >= &INICIO.
;QUIT;

PROC SQL;
	CREATE TABLE CTTD_CMPR AS
		SELECT 
			t1.CD_CLI,
			t1.TS_INRO_CLI,
			t1.CD_SUB_RSTD_INRO
		FROM DB2BIC.AUX_INRO_CLI_CMPR t1
		INNER JOIN CLI_SMLC t2 ON (t1.CD_CLI=t2.cd_cli)
		WHERE 
				t1.CD_TIP_CNL = 55
			AND t1.CD_TRAN_INRO_SIS = 'REL02'
			AND t1.CD_SUB_ASNT_INRO = 83
			AND DATEPART(t1.TS_INRO_CLI) >= &INICIO.
;QUIT;


DATA CTTD;
	SET CTTD_DIA CTTD_ATU CTTD_ANT CTTD_CMPR;
RUN;


PROC SQL;
	CREATE TABLE CTTD_MAX_CLI AS
		SELECT DISTINCT 
			CD_CLI,
			MAX(TS_INRO_CLI) format=datetime25.6 AS TS_INRO_CLI
		FROM CTTD
		GROUP BY 1;
QUIT;


PROC SQL;
	CREATE TABLE WORK.CTTD_MAX AS 
		SELECT DISTINCT
			t1.CD_CLI, 
			t1.TS_INRO_CLI AS TS_CTTD, 
			t1.CD_SUB_RSTD_INRO 
		FROM WORK.CTTD t1
		INNER JOIN WORK.CTTD_MAX_CLI t2 ON (t1.CD_CLI=t2.CD_CLI AND t1.TS_INRO_CLI=t2.TS_INRO_CLI)
;QUIT;

/*CLIENTES QUE FORAM CONTATADOS NO SISTEMA BIC - FIM ## ############################################################*/



/*###############################################################################################################*/



/*###############################################################################################################*/

PROC SQL;
	CREATE TABLE WORK.ANLT AS 
		SELECT 
			&D1. FORMAT=YYMMDDD10. AS POSICAO, 
			t1.PREFDEP, 
			t1.CTRA, 
			t1.CD_CLI,
			t1.TS_SMLC FORMAT=DateTimeMysql., 
			t1.VLR_SDO, 
			IFN(t1.CD_LNCD = 2887, 1, 0) AS CLI_ELG,
			t1.QNT_SLMC_CLI,
			t2.TS_SLCT_CLI FORMAT=DateTimeMysql.,  
			t3.TS_CTTD FORMAT=DateTimeMysql.,  
			t3.CD_SUB_RSTD_INRO,
			t2.FONE_BIC,
			t1.FONE_SLMC,
			IFN(t2.TS_SLCT_CLI IS NOT MISSING, 1, 0) AS SLCT,
			IFN(t3.TS_CTTD IS NOT MISSING, 1, 0) AS CTTD
		FROM WORK.SLMC_CDC_MAX t1
		LEFT JOIN WORK.SLTC_MAX t2 ON (t1.CD_CLI=t2.CD_CLI)
		LEFT JOIN WORK.CTTD_MAX t3 ON (t1.CD_CLI=t3.CD_CLI)
		WHERE t1.PREFDEP IS NOT MISSING and ctra <>.
;QUIT;



PROC SQL;
	CREATE TABLE WORK.PARA_SUMARIZACAO AS 
		SELECT 
			t1.PREFDEP, 
			t1.CTRA, 
			SUM(t1.QNT_SLMC_CLI) AS QNT_SLMC_CLI,
			COUNT(DISTINCT(t1.CD_CLI)) AS QNT_CLI, 
			SUM(t1.VLR_SDO) FORMAT=17.2 AS SUM_VLR_SDO,

			COUNT(DISTINCT(IFN(t1.CTRA<>7002, t1.CD_CLI, .))) AS QNT_CLI_CTRA, 
			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.CLI_ELG=1, t1.CD_CLI, .))) AS QNT_CLI_CTRA_ELG, 
			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1, t1.CD_CLI, .))) AS QNT_CLI_CTRA_SLCT,
			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1, t1.CD_CLI, .))) AS QNT_CLI_CTRA_SLCT_CTTD,
			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=0 AND t1.CTTD=1, t1.CD_CLI, .))) AS QNT_CLI_CTRA_CTTD,

/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1, t1.CD_CLI, .))) AS QNT_CLI_CTRA_TT,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=4, t1.CD_CLI, .))) AS QNT_CLI_CTRA_4,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=5, t1.CD_CLI, .))) AS QNT_CLI_CTRA_5,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=12, t1.CD_CLI, .))) AS QNT_CLI_CTRA_12,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=19, t1.CD_CLI, .))) AS QNT_CLI_CTRA_19,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=22, t1.CD_CLI, .))) AS QNT_CLI_CTRA_22,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=91, t1.CD_CLI, .))) AS QNT_CLI_CTRA_91,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=99, t1.CD_CLI, .))) AS QNT_CLI_CTRA_99,*/
/*			COUNT(DISTINCT(IFN(t1.CTRA<>7002 AND t1.SLCT=1 AND t1.CTTD=1 AND t1.CLI_ELG=1 AND t1.CD_SUB_RSTD_INRO=551, t1.CD_CLI, .))) AS QNT_CLI_CTRA_551,*/

			COUNT(DISTINCT(IFN(t1.CTRA=7002,t1.CD_CLI,.))) AS QNT_CLI_GRP, 
			COUNT(DISTINCT(IFN(t1.CTRA=7002 AND t1.CLI_ELG=1,t1.CD_CLI,.))) AS QNT_CLI_GRP_ELG,
			COUNT(DISTINCT(IFN(t1.CTRA=7002 AND t1.SLCT=1, t1.CD_CLI, .))) AS QNT_CLI_GRP_SLCT, 
			COUNT(DISTINCT(IFN(t1.CTRA=7002 AND t1.SLCT=1 AND t1.CTTD=1, t1.CD_CLI, .))) AS QNT_CLI_GRP_SLCT_CTTD,
			COUNT(DISTINCT(IFN(t1.CTRA=7002 AND t1.SLCT=0 AND t1.CTTD=1, t1.CD_CLI, .))) AS QNT_CLI_GRP_CTTD

/*			COUNT(DISTINCT(IFN(t1.TS_SLCT_CLI IS NOT MISSING,t1.CD_CLI,.))) AS QNT_CLI_SLCT,*/
/*			COUNT(DISTINCT(IFN(t1.CD_SUB_RSTD_INRO IS NOT MISSING,t1.CD_CLI,.))) AS QNT_CLI_CTTD*/
		FROM WORK.ANLT t1
		GROUP BY 1,2
;QUIT;

/*TABELA COLUNAS PARA FUNCAO SUMARIZACAO*/
PROC SQL;
	DROP TABLE ColunasSumarizador;
	CREATE TABLE ColunasSumarizador (Coluna CHAR(50), Tipo CHAR(10) );
		/*COLUNAS PARA SUMARIZACAO*/
		INSERT INTO ColunasSumarizador VALUES ('QNT_SLMC_CLI', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('SUM_VLR_SDO', 'SUM');

		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_ELG', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_SLCT', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_SLCT_CTTD', 'SUM');	
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_CTTD', 'SUM');	

/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_TT', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_4', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_5', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_12', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_19', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_22', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_91', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_99', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTRA_551', 'SUM');*/
	
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_GRP', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_GRP_ELG', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_GRP_SLCT', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_GRP_SLCT_CTTD', 'SUM');
		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_GRP_CTTD', 'SUM');
		

/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_SLCT', 'SUM');*/
/*		INSERT INTO ColunasSumarizador VALUES ('QNT_CLI_CTTD', 'SUM');	*/
QUIT;

%SumarizadorCNX(TblSASValores=PARA_SUMARIZACAO, TblSASColunas=ColunasSumarizador,  NivelCTRA=1, PAA_PARA_AGENCIA=0, TblSaida=FINAL, AAAAMM=&AAAAMM.);


PROC SQL;
	CREATE TABLE WORK.FINAL_REL AS 
		SELECT 
			&D1. FORMAT=YYMMDDD10. AS POSICAO,
			t1.PREFDEP, 
			t1.CTRA, 
			t1.QNT_SLMC_CLI FORMAT=32.,  
			t1.QNT_CLI FORMAT=32.,  
			t1.SUM_VLR_SDO FORMAT=32., 
			t1.QNT_CLI_CTRA FORMAT=32., 
			t1.QNT_CLI_CTRA_ELG FORMAT=32.,  
			t1.QNT_CLI_CTRA_SLCT FORMAT=32., 
			t1.QNT_CLI_CTRA_SLCT_CTTD FORMAT=32.,  
			t1.QNT_CLI_CTRA_CTTD FORMAT=32., 
			COALESCE((t1.QNT_CLI_CTRA_SLCT_CTTD/t1.QNT_CLI_CTRA_SLCT)*100,0) FORMAT=32.2 AS PC_CTRA_CTTD,

			t1.QNT_CLI_GRP FORMAT=32., 
			t1.QNT_CLI_GRP_ELG FORMAT=32., 
			t1.QNT_CLI_GRP_SLCT FORMAT=32.,  
			t1.QNT_CLI_GRP_SLCT_CTTD FORMAT=32.,  
			t1.QNT_CLI_GRP_CTTD FORMAT=32.,
			COALESCE((t1.QNT_CLI_GRP_SLCT_CTTD/t1.QNT_CLI_GRP_SLCT)*100,0) FORMAT=32.2 AS PC_GRP_CTTD
		FROM WORK.FINAL t1 where ctra<>.;
QUIT;



PROC SQL;
	CREATE TABLE WORK.ANLT_REL AS 
		SELECT 
			t1.POSICAO, 
			t1.PREFDEP, 
			t1.CTRA, 
			t1.CD_CLI, 
			t1.TS_SMLC, 
			t1.VLR_SDO,
			t1.CLI_ELG, 
			t1.QNT_SLMC_CLI, 
			t1.TS_SLCT_CLI, 
			t1.TS_CTTD, 
			t1.CD_SUB_RSTD_INRO, 
			t1.FONE_BIC, 
			t1.FONE_SLMC,
			t1.SLCT,
			t1.CTTD
		FROM WORK.ANLT t1;
QUIT;


PROC SQL;
	CREATE TABLE DMN_SUB_RSTD (ID NUM, NOME CHAR(40) );
		INSERT INTO DMN_SUB_RSTD VALUES (12, 'Tem interesse, mas não atende requisitos');
		INSERT INTO DMN_SUB_RSTD VALUES (19, 'Cliente não quer tratar por telefone');
		INSERT INTO DMN_SUB_RSTD VALUES (22, 'Proposta acolhida');
		INSERT INTO DMN_SUB_RSTD VALUES (91, 'Dúvidas esclarecidas');
		INSERT INTO DMN_SUB_RSTD VALUES (99, 'Cliente contatado');
		INSERT INTO DMN_SUB_RSTD VALUES (551, 'Contato agendado');	
QUIT;


/*#################################################################################################################*/
/*#################################################################################################################*/
/*EXPORTAR REL*/
/*#################################################################################################################*/

/*TABELA AUXILIAR DE TABELAS DE CARGA E ROTINAS DO SISTEMA REL*/
PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
		/*TABELAS PARA EXPORTAÇÃO > VALUES('TABELA_SAS', 'ROTINA') > INICIAR PELA PRINCIPAL*/
		INSERT INTO TABELAS_EXPORTAR_REL VALUES('FINAL_REL', 'simulacao-portabilidade-consignado');
		INSERT INTO TABELAS_EXPORTAR_REL VALUES('ANLT_REL', 'clientes');
		INSERT INTO TABELAS_EXPORTAR_REL VALUES('DMN_SUB_RSTD', 'status-contato');
QUIT;

%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);


/*#################################################################################################################*/
/*#################################################################################################################*/
/*************************************************/;
/* TRECHO DE CÓDIGO INCLUÍDO PELO FF */;

%include "/dados/gestao/rotinas/_macros/macros_uteis.sas";
 
%processCheckOut(
    uor_resp = 341556
    ,funci_resp = &sysuserid
    /*,tipo = Indicador
    ,sistema = Indicador
    ,rotina = I0123 Indicador de Alguma Coisa*/
    ,mailto= 'F8369937' 'F2986408' 'F6794004' 'F7176219' 'F8176496' 'F9457977' 'F9631159'
);
