
%INCLUDE '/dados/infor/suporte/FuncoesInfor.sas';

LIBNAME ATB DB2 DATABASE=BDB2P04 SCHEMA=DB2ATB AUTHDOMAIN=DB2SGCEN;

Libname DIRAO "/dados/dirao/publico";


%diasUteis(%sysfunc(today()), 5);
			%GLOBAL DiaUtil_D0 DiaUtil_D1;


			data arq;

				format 
					anomes yymmn6.
					mesano z6.
					DiaUtil_D1 date9.
					mes z2.
					ano 4.;

                anomes = '28JUN2019'd;				
				mesano = 062019;
                DiaUtil_D1 = '28JUN2019'd;				
				mes = 06;
				ano = 2019;

			run;

			%put &D_mais_2;
			%put &DiaUtil_D0;

			proc sql;
				select anomes, DiaUtil_D1,   mes, ano, mesano

				into :anomes, :DiaUtil_D1, :mes, :ano, :mesano
					from arq;
			quit;

			%put &anomes &mesano &DiaUtil_D1 &ano &mes;


DATA _NULL_;
D1=DiaUtilAnterior(Today());
CALL SYMPUT('D1',D1);
run;


/****************************/
/****************************/
/*PROCESSAMENTO DO RELATÓRIO*/
/****************************/
/****************************/

/***/
/***/


PROC SQL;

    CREATE TABLE PERDAS_ESTOQUE AS
    SELECT 
	NR_UNCO_CTR_OPR,
    CD_PSS_CLI_OPR AS MCI,
	SALDO,
	DT_PDA_POS_2010
    FROM DIRAO.LST_QLF_GECEN_PEC_Pda 
    WHERE DT_PDA_POS_2010 >= '01JAN2014'd AND DT_PDA_POS_2010 <= '30JUN2019'd;
         
QUIT;



/***/
/***/
/***/
/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_JUL
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01JAN2014'd AND DT_PDA_POS_2010 < '01JAN2019'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_JUL) AS VALOR_PERDAS_JUL
		  		  
   FROM COMP_PERDAS_JUL t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_JUL
		  		  
   FROM COMP_PERDAS_JUL t1
   LEFT JOIN comum.pai_rel_201901 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_JUL OUT=COMP_PERDAS_JUL REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_JUL) AS VALOR_PERDAS_JUL
		  		  
   FROM COMP_PERDAS_JUL t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/
/***/
/***/
/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_AGO
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01FEB2014'd AND DT_PDA_POS_2010 < '01FEB2019'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_AGO) AS VALOR_PERDAS_AGO
		  		  
   FROM COMP_PERDAS_AGO t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_AGO
		  		  
   FROM COMP_PERDAS_AGO t1
   LEFT JOIN comum.pai_rel_201902 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_AGO OUT=COMP_PERDAS_AGO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_AGO) AS VALOR_PERDAS_AGO
		  		  
   FROM COMP_PERDAS_AGO t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/
/***/
/***/
/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_SET
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01MAR2014'd AND DT_PDA_POS_2010 < '01MAR2019'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_SET) AS VALOR_PERDAS_SET
		  		  
   FROM COMP_PERDAS_SET t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_SET
		  		  
   FROM COMP_PERDAS_SET t1
   LEFT JOIN comum.pai_rel_201903 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_SET OUT=COMP_PERDAS_SET REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_SET) AS VALOR_PERDAS_SET
		  		  
   FROM COMP_PERDAS_SET t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/****/
/****/
/****/
/****/


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_OUT
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01APR2014'd AND DT_PDA_POS_2010 < '01APR2019'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_OUT) AS VALOR_PERDAS_OUT
		  		  
   FROM COMP_PERDAS_OUT t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_OUT
		  		  
   FROM COMP_PERDAS_OUT t1
   LEFT JOIN comum.pai_rel_201904 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_OUT OUT=COMP_PERDAS_OUT REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_OUT) AS VALOR_PERDAS_OUT
		  		  
   FROM COMP_PERDAS_OUT t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/****/
/****/
/****/
/****/


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_NOV
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01MAY2014'd AND DT_PDA_POS_2010 < '01MAY2019'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_NOV) AS VALOR_PERDAS_NOV
		  		  
   FROM COMP_PERDAS_NOV t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_NOV
		  		  
   FROM COMP_PERDAS_NOV t1
   LEFT JOIN comum.pai_rel_201905 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_NOV OUT=COMP_PERDAS_NOV REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_NOV) AS VALOR_PERDAS_NOV
		  		  
   FROM COMP_PERDAS_NOV t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;



/****/
/****/
/****/
/****/


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_DEZ
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01JUN2014'd AND DT_PDA_POS_2010 < '01JUN2019'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_DEZ) AS VALOR_PERDAS_DEZ
		  		  
   FROM COMP_PERDAS_DEZ t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_DEZ
		  		  
   FROM COMP_PERDAS_DEZ t1
   LEFT JOIN comum.pai_rel_201906 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_DEZ OUT=COMP_PERDAS_DEZ REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_DEZ) AS VALOR_PERDAS_DEZ
		  		  
   FROM COMP_PERDAS_DEZ t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/****/
/****/
/****/


PROC SQL;

   CREATE TABLE COMP_PERDAS_1 AS
 
   SELECT 
            t1.PREFIXO AS PREFIXO_1, t2.PREFIXO AS PREFIXO_2, t3.PREFIXO AS PREFIXO_3, t4.PREFIXO AS PREFIXO_4, t5.PREFIXO AS PREFIXO_5, t6.PREFIXO AS PREFIXO_6,
            t1.CARTEIRA AS CARTEIRA_1, t2.CARTEIRA AS CARTEIRA_2, t3.CARTEIRA AS CARTEIRA_3, t4.CARTEIRA AS CARTEIRA_4, t5.CARTEIRA AS CARTEIRA_5, t6.CARTEIRA AS CARTEIRA_6,
            VALOR_PERDAS_JUL, VALOR_PERDAS_AGO, VALOR_PERDAS_SET, VALOR_PERDAS_OUT, VALOR_PERDAS_NOV, VALOR_PERDAS_DEZ
          		  		  
   FROM COMP_PERDAS_JUL t1
   FULL JOIN COMP_PERDAS_AGO t2 ON t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA
   FULL JOIN COMP_PERDAS_SET t3 ON t1.PREFIXO = t3.PREFIXO AND t1.CARTEIRA = t3.CARTEIRA
   FULL JOIN COMP_PERDAS_OUT t4 ON t1.PREFIXO = t4.PREFIXO AND t1.CARTEIRA = t4.CARTEIRA
   FULL JOIN COMP_PERDAS_NOV t5 ON t1.PREFIXO = t5.PREFIXO AND t1.CARTEIRA = t5.CARTEIRA
   FULL JOIN COMP_PERDAS_DEZ t6 ON t1.PREFIXO = t6.PREFIXO AND t1.CARTEIRA = t6.CARTEIRA
      
   ORDER BY 1,2;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_1 OUT=COMP_PERDAS_1 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_2 AS
 
   SELECT 

   IFN(PREFIXO_1 <> 0, PREFIXO_1, IFN(PREFIXO_2 <> 0, PREFIXO_2, IFN(PREFIXO_3 <> 0, PREFIXO_3, IFN(PREFIXO_4 <> 0, PREFIXO_4, IFN(PREFIXO_5 <> 0, PREFIXO_5, PREFIXO_6))))) AS PREFIXO,
   IFN(CARTEIRA_1 <> 0, CARTEIRA_1, IFN(CARTEIRA_2 <> 0, CARTEIRA_2, IFN(CARTEIRA_3 <> 0, CARTEIRA_3, IFN(CARTEIRA_4 <> 0, CARTEIRA_4, IFN(CARTEIRA_5 <> 0, CARTEIRA_5, CARTEIRA_6))))) AS CARTEIRA,
   VALOR_PERDAS_JUL, VALOR_PERDAS_AGO, VALOR_PERDAS_SET, VALOR_PERDAS_OUT, VALOR_PERDAS_NOV, VALOR_PERDAS_DEZ,
   (VALOR_PERDAS_DEZ) AS VALOR_PERDAS_SEM
          		  		  
   FROM COMP_PERDAS_1 t1
   ORDER BY 1,2;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_3 AS
 
   SELECT 
   DISTINCT PREFIXO,
   CARTEIRA,
   
   SUM(VALOR_PERDAS_JUL) AS VALOR_PERDAS_JUL, SUM(VALOR_PERDAS_AGO) AS VALOR_PERDAS_AGO, SUM(VALOR_PERDAS_SET) AS VALOR_PERDAS_SET, SUM(VALOR_PERDAS_OUT) AS VALOR_PERDAS_OUT,
   SUM(VALOR_PERDAS_NOV) AS VALOR_PERDAS_NOV, SUM(VALOR_PERDAS_DEZ) AS VALOR_PERDAS_DEZ, SUM(VALOR_PERDAS_SEM) AS VALOR_PERDAS_SEM
          		  		  
   FROM COMP_PERDAS_2 t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_4 AS
 
   SELECT *	  
   FROM COMP_PERDAS_3
   WHERE PREFIXO <> 0
   ORDER BY 1,2;

QUIT;


/*******************************/
/*******************************/
/*******************************/

/*ATB*/

PROC SQL;
CREATE TABLE ATB_JANEIRO AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CTRA
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201901 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 01 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE ATB_FEVEREIRO AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CTRA
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201902 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 02 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE ATB_MARCO AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CTRA
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201903 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 03 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE ATB_ABRIL AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CTRA
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201904 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 04 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE ATB_MAIO AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CTRA
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201905 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 05 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE ATB_JUNHO AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CTRA
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201906 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 06 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
   CREATE TABLE COMP_PERDAS_REC AS 
   SELECT DISTINCT 

   t1.CD_CLI AS MCI, 
   put(t1.dt_lcto_RAO,yymmn6.) as ANOMES, 
   (SUM(t1.VL_LCTO_RAO)) FORMAT=COMMAX19.2 AS VALOR_REC

FROM dirao.BASE_DIRAO_RAO_P_DIRCO_NOVA t1
WHERE t1.CD_CNL_CTRC NOT IN ( 1, 11, 1008) and ((calculated anomes)="201901" OR (calculated anomes)="201902" OR (calculated anomes)="201903" OR (calculated anomes)="201904" OR (calculated anomes)="201905" OR (calculated anomes)="201906")
GROUP BY 1,2
ORDER BY 1,2;
QUIT;


/*JULHO*/
/*JULHO*/
/*JULHO*/
/*JULHO*/


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201901"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_JUL) AS VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_JUL_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_JUL_REC t1
   LEFT JOIN comum.pai_rel_201901 t2 ON MCI = t2.CD_CLI
   INNER JOIN ATB_JANEIRO t3 ON t2.CD_PRF_DEPE = t3.PREFIXO AND t2.NR_SEQL_CTRA_ATB = t3.CTRA
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_JUL_REC OUT=COMP_PERDAS_JUL_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_JUL) AS VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_JUL_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_JUL_REC AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CARTEIRA, VL_RLZD AS VALOR_REC_JUL
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201901 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 01 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


/*AGOSTO*/
/*AGOSTO*/
/*AGOSTO*/
/*AGOSTO*/

PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201902"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_AGO) AS VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_AGO_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_AGO_REC t1
   LEFT JOIN comum.pai_rel_201902 t2 ON MCI = t2.CD_CLI
   INNER JOIN ATB_FEVEREIRO t3 ON t2.CD_PRF_DEPE = t3.PREFIXO AND t2.NR_SEQL_CTRA_ATB = t3.CTRA
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_AGO_REC OUT=COMP_PERDAS_AGO_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_AGO) AS VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_AGO_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_AGO_REC_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CARTEIRA, VL_RLZD AS VALOR_REC_AGO_ACUM
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201902 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 02 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_AGO_REC AS 
SELECT DISTINCT t1.PREFIXO, t1.CARTEIRA, 

IFN((t1.VALOR_REC_AGO_ACUM - t2.VALOR_REC_JUL) < 0, t1.VALOR_REC_AGO_ACUM, (t1.VALOR_REC_AGO_ACUM - t2.VALOR_REC_JUL)) AS VALOR_REC_AGO

FROM COMP_PERDAS_AGO_REC_ACUM t1
LEFT JOIN COMP_PERDAS_JUL_REC t2 ON (t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA)
ORDER BY 1, 2;
QUIT;


/*SETEMBRO*/
/*SETEMBRO*/
/*SETEMBRO*/
/*SETEMBRO*/


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201903"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_SET) AS VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_SET_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_SET_REC t1
   LEFT JOIN comum.pai_rel_201903 t2 ON MCI = t2.CD_CLI
   INNER JOIN ATB_MARCO t3 ON t2.CD_PRF_DEPE = t3.PREFIXO AND t2.NR_SEQL_CTRA_ATB = t3.CTRA
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_SET_REC OUT=COMP_PERDAS_SET_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_SET) AS VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_SET_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_SET_REC_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CARTEIRA, VL_RLZD AS VALOR_REC_SET_ACUM
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201903 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 03 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_SET_REC AS 
SELECT DISTINCT t1.PREFIXO, t1.CARTEIRA, 

IFN((t1.VALOR_REC_SET_ACUM - t2.VALOR_REC_AGO_ACUM) < 0, t1.VALOR_REC_SET_ACUM, (t1.VALOR_REC_SET_ACUM - t2.VALOR_REC_AGO_ACUM)) AS VALOR_REC_SET

FROM COMP_PERDAS_SET_REC_ACUM t1
LEFT JOIN COMP_PERDAS_AGO_REC_ACUM t2 ON (t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA)
ORDER BY 1, 2;
QUIT;


/*OUTUBRO*/
/*OUTUBRO*/
/*OUTUBRO*/
/*OUTUBRO*/


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201904"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_OUT) AS VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_OUT_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_OUT_REC t1
   LEFT JOIN comum.pai_rel_201904 t2 ON MCI = t2.CD_CLI
   INNER JOIN ATB_ABRIL t3 ON t2.CD_PRF_DEPE = t3.PREFIXO AND t2.NR_SEQL_CTRA_ATB = t3.CTRA
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_OUT_REC OUT=COMP_PERDAS_OUT_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_OUT) AS VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_OUT_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_OUT_REC_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CARTEIRA, VL_RLZD AS VALOR_REC_OUT_ACUM
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201904 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 04 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_OUT_REC AS 
SELECT DISTINCT t1.PREFIXO, t1.CARTEIRA, 

IFN((t1.VALOR_REC_OUT_ACUM - t2.VALOR_REC_SET_ACUM) < 0, t1.VALOR_REC_OUT_ACUM, (t1.VALOR_REC_OUT_ACUM - t2.VALOR_REC_SET_ACUM)) AS VALOR_REC_OUT

FROM COMP_PERDAS_OUT_REC_ACUM t1
LEFT JOIN COMP_PERDAS_SET_REC_ACUM t2 ON (t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA)
ORDER BY 1, 2;
QUIT;


/*NOVEMBRO*/
/*NOVEMBRO*/
/*NOVEMBRO*/
/*NOVEMBRO*/


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201905"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_NOV) AS VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_NOV_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_NOV_REC t1
   LEFT JOIN comum.pai_rel_201905 t2 ON MCI = t2.CD_CLI
   INNER JOIN ATB_MAIO t3 ON t2.CD_PRF_DEPE = t3.PREFIXO AND t2.NR_SEQL_CTRA_ATB = t3.CTRA
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_NOV_REC OUT=COMP_PERDAS_NOV_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_NOV) AS VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_NOV_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_NOV_REC_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CARTEIRA, VL_RLZD AS VALOR_REC_NOV_ACUM
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201905 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 05 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_NOV_REC AS 
SELECT DISTINCT t1.PREFIXO, t1.CARTEIRA, 

IFN((t1.VALOR_REC_NOV_ACUM - t2.VALOR_REC_OUT_ACUM) < 0, t1.VALOR_REC_NOV_ACUM, (t1.VALOR_REC_NOV_ACUM - t2.VALOR_REC_OUT_ACUM)) AS VALOR_REC_NOV

FROM COMP_PERDAS_NOV_REC_ACUM t1
LEFT JOIN COMP_PERDAS_OUT_REC_ACUM t2 ON (t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA)
ORDER BY 1, 2;
QUIT;


/*DEZEMBRO*/
/*DEZEMBRO*/
/*DEZEMBRO*/
/*DEZEMBRO*/


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201906"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_DEZ) AS VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_DEZ_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_DEZ_REC t1
   LEFT JOIN comum.pai_rel_201906 t2 ON MCI = t2.CD_CLI
   INNER JOIN ATB_JUNHO t3 ON t2.CD_PRF_DEPE = t3.PREFIXO AND t2.NR_SEQL_CTRA_ATB = t3.CTRA
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_DEZ_REC OUT=COMP_PERDAS_DEZ_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_DEZ) AS VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_DEZ_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_DEZ_REC_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , nr_seql_ctra as CARTEIRA, VL_RLZD AS VALOR_REC_DEZ_ACUM
FROM ATB.vl_aprd_cpnt_ctra t1
LEFT JOIN IGR.IGRREDE_201906 t2 ON t1.cd_uor_ctra = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 06 and cd_cpnt_mod_avlc = 35839
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_DEZ_REC AS 
SELECT DISTINCT t1.PREFIXO, t1.CARTEIRA, 

IFN((t1.VALOR_REC_DEZ_ACUM - t2.VALOR_REC_NOV_ACUM) < 0, t1.VALOR_REC_DEZ_ACUM, (t1.VALOR_REC_DEZ_ACUM - t2.VALOR_REC_NOV_ACUM)) AS VALOR_REC_DEZ

FROM COMP_PERDAS_DEZ_REC_ACUM t1
LEFT JOIN COMP_PERDAS_NOV_REC_ACUM t2 ON (t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA)
ORDER BY 1, 2;
QUIT;


/***/
/***/
/***/
/***/
/***/
/***/
/***/
/***/
/***/
/***/
/***/
/***/


PROC SQL;

   CREATE TABLE COMP_REC_1 AS
 
   SELECT 
            t1.PREFIXO AS PREFIXO_1, t2.PREFIXO AS PREFIXO_2, t3.PREFIXO AS PREFIXO_3, t4.PREFIXO AS PREFIXO_4, t5.PREFIXO AS PREFIXO_5, t6.PREFIXO AS PREFIXO_6,
            t1.CARTEIRA AS CARTEIRA_1, t2.CARTEIRA  AS CARTEIRA_2, t3.CARTEIRA  AS CARTEIRA_3, t4.CARTEIRA  AS CARTEIRA_4, t5.CARTEIRA  AS CARTEIRA_5, t6.CARTEIRA  AS CARTEIRA_6,
            VALOR_REC_JUL, VALOR_REC_AGO, VALOR_REC_SET, VALOR_REC_OUT , VALOR_REC_NOV , VALOR_REC_DEZ
          		  		  
   FROM COMP_PERDAS_JUL_REC t1
   FULL JOIN COMP_PERDAS_AGO_REC t2 ON t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA
   FULL JOIN COMP_PERDAS_SET_REC t3 ON t1.PREFIXO = t3.PREFIXO AND t1.CARTEIRA = t3.CARTEIRA
   FULL JOIN COMP_PERDAS_OUT_REC t4 ON t1.PREFIXO = t4.PREFIXO AND t1.CARTEIRA = t4.CARTEIRA
   FULL JOIN COMP_PERDAS_NOV_REC t5 ON t1.PREFIXO = t5.PREFIXO AND t1.CARTEIRA = t5.CARTEIRA
   FULL JOIN COMP_PERDAS_DEZ_REC t6 ON t1.PREFIXO = t6.PREFIXO AND t1.CARTEIRA = t6.CARTEIRA
   
   ORDER BY 1,2;

QUIT;


PROC STDIZE DATA=COMP_REC_1 OUT=COMP_REC_1 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_REC_2 AS
 
   SELECT 

   IFN(PREFIXO_1 <> 0, PREFIXO_1, IFN(PREFIXO_2 <> 0, PREFIXO_2, IFN(PREFIXO_3 <> 0, PREFIXO_3, IFN(PREFIXO_4 <> 0, PREFIXO_4, IFN(PREFIXO_5 <> 0, PREFIXO_5, PREFIXO_6))))) AS PREFIXO,
   IFN(CARTEIRA_1 <> 0, CARTEIRA_1, IFN(CARTEIRA_2 <> 0, CARTEIRA_2, IFN(CARTEIRA_3 <> 0, CARTEIRA_3, IFN(CARTEIRA_4 <> 0, CARTEIRA_4, IFN(CARTEIRA_5 <> 0, CARTEIRA_5, CARTEIRA_6))))) AS CARTEIRA,
   VALOR_REC_JUL, VALOR_REC_AGO, VALOR_REC_SET, VALOR_REC_OUT, VALOR_REC_NOV, VALOR_REC_DEZ,
   (VALOR_REC_JUL + VALOR_REC_AGO + VALOR_REC_SET + VALOR_REC_OUT + VALOR_REC_NOV + VALOR_REC_DEZ) AS VALOR_REC_SEM
          		  		  
   FROM COMP_REC_1 t1
   ORDER BY 1,2;

QUIT;


PROC SQL;

   CREATE TABLE COMP_REC_3 AS
 
   SELECT 
   DISTINCT PREFIXO,
   CARTEIRA,
   
   SUM(VALOR_REC_JUL) AS VALOR_REC_JUL, SUM(VALOR_REC_AGO) AS VALOR_REC_AGO, SUM(VALOR_REC_SET) AS VALOR_REC_SET, SUM(VALOR_REC_OUT) AS VALOR_REC_OUT,
   SUM(VALOR_REC_NOV) AS VALOR_REC_NOV, SUM(VALOR_REC_DEZ) AS VALOR_REC_DEZ, SUM(VALOR_REC_SEM) AS VALOR_REC_SEM
          		  		  
   FROM COMP_REC_2 t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;

   CREATE TABLE COMP_REC_4 AS
 
   SELECT *	  
   FROM COMP_REC_3
   WHERE PREFIXO <> 0
   ORDER BY 1,2;

QUIT;


/*******************/
/*******************/
/*******************/
/*******************/
/**JUNTANDO PERDAS COM REC**/


PROC SQL;

   CREATE TABLE COMP_1 AS
 
   SELECT DISTINCT t1.PREFIXO AS PREFIXO_1, t2.PREFIXO AS PREFIXO_2, t1.CARTEIRA AS CARTEIRA_1, t2.CARTEIRA AS CARTEIRA_2,

   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   VALOR_PERDAS_DEZ,
   VALOR_REC_DEZ
          		  		  
   FROM COMP_PERDAS_4  t1
   FULL JOIN COMP_REC_4 t2 ON t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA 
   ORDER BY 1,2,3,4;

QUIT;


PROC STDIZE DATA=COMP_1 OUT=COMP_1 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_2 AS
 
   SELECT DISTINCT 

   IFN(PREFIXO_1 <> 0, PREFIXO_1, PREFIXO_2) AS PREFDEP, IFN(CARTEIRA_1 <> 0, CARTEIRA_1, CARTEIRA_2) AS CTRA,

   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   VALOR_PERDAS_DEZ,
   VALOR_REC_DEZ    
          		  		  
   FROM COMP_1  
   ORDER BY 1,2;

QUIT;


data COMP_2;
format posicao yymmdd10.;
set COMP_2;
posicao = &D1;
run;


/*TABELA COLUNAS PARA FUNCAO SUMARIZACAO*/

PROC SQL;
DROP TABLE COLUNAS_SUMARIZAR;
CREATE TABLE COLUNAS_SUMARIZAR (Coluna CHAR(50), Tipo CHAR(10));
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_SEM', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_SEM', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_JUL', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_JUL', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_AGO', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_AGO', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_SET', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_SET', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_OUT', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_OUT', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_NOV', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_NOV', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_DEZ', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_DEZ', 'SUM');

QUIT;


/*FUNCAO DE SUMARIZACAO*/ 
%SumarizadorCNX( TblSASValores=COMP_2,  TblSASColunas=COLUNAS_SUMARIZAR,  NivelCTRA=1,  PAA_PARA_AGENCIA=0,  TblSaida=COMP_2, AAAAMM=&ANOMES.); 


PROC STDIZE DATA=COMP_2 OUT=COMP_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_3 AS
 
   SELECT DISTINCT 
   POSICAO,
   PREFDEP,
   CTRA,
   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   VALOR_PERDAS_DEZ,
   VALOR_REC_DEZ
          		  		  
   FROM COMP_2  
   ORDER BY 2,3;

QUIT;


/***/
/***/


/*SUBSTITUINDO A SUMARIZAÇÃO PELO CONEXAO*/
/*SUBSTITUINDO A SUMARIZAÇÃO PELO CONEXAO*/
/*SUBSTITUINDO A SUMARIZAÇÃO PELO CONEXAO*/
/*SUBSTITUINDO A SUMARIZAÇÃO PELO CONEXAO*/


/**/
/**/
/**/
/**/


PROC SQL;
CREATE TABLE COMP_PERDAS_JAN_REC_PREF AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , 0 as CARTEIRA, VL_RLZD AS VALOR_REC_JAN
FROM ATB.vl_aprd_cpnt_uor t1
LEFT JOIN IGR.IGRREDE_201901 t2 ON t1.cd_uor = input(t2.UOR, 9.)
WHERE aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 01 and cd_cpnt_mod_avlc = 35837
ORDER BY 1, 2;
QUIT;

/**/

PROC SQL;
CREATE TABLE COMP_PERDAS_FEV_REC_PREF_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , 0 as CARTEIRA, VL_RLZD AS VALOR_REC_FEV
FROM ATB.vl_aprd_cpnt_uor t1
LEFT JOIN IGR.IGRREDE_201902 t2 ON t1.cd_uor = input(t2.UOR, 9.)
WHERE aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 02 and cd_cpnt_mod_avlc = 35837
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_FEV_REC_PREF AS 
SELECT DISTINCT t1.PREFIXO , t2.CARTEIRA, 

IFN((VALOR_REC_FEV - t2.VALOR_REC_JAN) < 0, t1.VALOR_REC_FEV, (VALOR_REC_FEV - t2.VALOR_REC_JAN)) AS VALOR_REC_FEV

FROM COMP_PERDAS_FEV_REC_PREF_ACUM t1
LEFT JOIN COMP_PERDAS_JAN_REC_PREF t2 ON t1.PREFIXO = t2.PREFIXO
ORDER BY 1, 2;
QUIT;

/**/

PROC SQL;
CREATE TABLE COMP_PERDAS_MAR_REC_PREF_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , 0 as CARTEIRA, VL_RLZD AS VALOR_REC_MAR
FROM ATB.vl_aprd_cpnt_uor t1
LEFT JOIN IGR.IGRREDE_201903 t2 ON t1.cd_uor = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 03 and cd_cpnt_mod_avlc = 35837
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_MAR_REC_PREF AS 
SELECT DISTINCT t1.PREFIXO , t2.CARTEIRA, 

IFN((VALOR_REC_MAR - t2.VALOR_REC_FEV) < 0, t1.VALOR_REC_MAR, (VALOR_REC_MAR - t2.VALOR_REC_FEV)) AS VALOR_REC_MAR

FROM COMP_PERDAS_MAR_REC_PREF_ACUM t1
LEFT JOIN COMP_PERDAS_FEV_REC_PREF_ACUM t2 ON t1.PREFIXO = t2.PREFIXO
ORDER BY 1, 2;
QUIT;

/**/

PROC SQL;
CREATE TABLE COMP_PERDAS_ABR_REC_PREF_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , 0 as CARTEIRA, VL_RLZD AS VALOR_REC_ABR
FROM ATB.vl_aprd_cpnt_uor t1
LEFT JOIN IGR.IGRREDE_201904 t2 ON t1.cd_uor = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 04 and cd_cpnt_mod_avlc = 35837
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_ABR_REC_PREF AS 
SELECT DISTINCT t1.PREFIXO , t2.CARTEIRA, 

IFN((VALOR_REC_ABR - t2.VALOR_REC_MAR) < 0, t1.VALOR_REC_ABR, (VALOR_REC_ABR - t2.VALOR_REC_MAR)) AS VALOR_REC_ABR

FROM COMP_PERDAS_ABR_REC_PREF_ACUM t1
LEFT JOIN COMP_PERDAS_MAR_REC_PREF_ACUM t2 ON t1.PREFIXO = t2.PREFIXO
ORDER BY 1, 2;
QUIT;


/**/

PROC SQL;
CREATE TABLE COMP_PERDAS_MAI_REC_PREF_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , 0 as CARTEIRA, VL_RLZD AS VALOR_REC_MAI
FROM ATB.vl_aprd_cpnt_uor t1
LEFT JOIN IGR.IGRREDE_201905 t2 ON t1.cd_uor = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 05 and cd_cpnt_mod_avlc = 35837
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_MAI_REC_PREF AS 
SELECT DISTINCT t1.PREFIXO , t2.CARTEIRA, 

IFN((VALOR_REC_MAI - t2.VALOR_REC_ABR) < 0, t1.VALOR_REC_MAI, (VALOR_REC_MAI - t2.VALOR_REC_ABR)) AS VALOR_REC_MAI

FROM COMP_PERDAS_MAI_REC_PREF_ACUM t1
LEFT JOIN COMP_PERDAS_ABR_REC_PREF_ACUM t2 ON t1.PREFIXO = t2.PREFIXO
ORDER BY 1, 2;
QUIT;


/**/

PROC SQL;
CREATE TABLE COMP_PERDAS_JUN_REC_PREF_ACUM AS 
SELECT DISTINCT input(t2.PREFDEP, 4.) AS PREFIXO , 0 as CARTEIRA, VL_RLZD AS VALOR_REC_JUN
FROM ATB.vl_aprd_cpnt_uor t1
LEFT JOIN IGR.IGRREDE_201906 t2 ON t1.cd_uor = input(t2.UOR, 9.)
where aa_vl_aprd_cpnt = 2019 and mm_vl_aprd_cpnt = 06 and cd_cpnt_mod_avlc = 35837
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE COMP_PERDAS_JUN_REC_PREF AS 
SELECT DISTINCT t1.PREFIXO , t2.CARTEIRA, 

IFN((VALOR_REC_JUN - t2.VALOR_REC_MAI) < 0, t1.VALOR_REC_JUN, (VALOR_REC_JUN - t2.VALOR_REC_MAI)) AS VALOR_REC_JUN

FROM COMP_PERDAS_JUN_REC_PREF_ACUM t1
LEFT JOIN COMP_PERDAS_MAI_REC_PREF_ACUM t2 ON t1.PREFIXO = t2.PREFIXO
ORDER BY 1, 2;
QUIT;


/**/

PROC SQL;

   CREATE TABLE COMP_3_NOVO AS
 
   SELECT DISTINCT 
   t1.POSICAO,
   t1.PREFDEP,
   t1.CTRA,
   t1.VALOR_PERDAS_SEM,
   /*VALOR_REC_SEM,*/

   t1.VALOR_PERDAS_JUL,   
   IFN(CTRA <> 0, t1.VALOR_REC_JUL, t2.VALOR_REC_JAN) AS VALOR_REC_JUL,

   t1.VALOR_PERDAS_AGO,
   IFN(CTRA <> 0, t1.VALOR_REC_AGO, t3.VALOR_REC_FEV) AS VALOR_REC_AGO,

   t1.VALOR_PERDAS_SET,
   IFN(CTRA <> 0, t1.VALOR_REC_SET, t4.VALOR_REC_MAR) AS VALOR_REC_SET,

   t1.VALOR_PERDAS_OUT,
   IFN(CTRA <> 0, t1.VALOR_REC_OUT, t5.VALOR_REC_ABR) AS VALOR_REC_OUT,

   t1.VALOR_PERDAS_NOV,
   IFN(CTRA <> 0, t1.VALOR_REC_NOV, t6.VALOR_REC_MAI) AS VALOR_REC_NOV,

   t1.VALOR_PERDAS_DEZ,
   IFN(CTRA <> 0, t1.VALOR_REC_DEZ, t7.VALOR_REC_JUN) AS VALOR_REC_DEZ
    
   FROM COMP_3 t1 

   LEFT JOIN COMP_PERDAS_JAN_REC_PREF t2 ON t1.PREFDEP = t2.PREFIXO
   LEFT JOIN COMP_PERDAS_FEV_REC_PREF t3 ON t1.PREFDEP = t3.PREFIXO
   LEFT JOIN COMP_PERDAS_MAR_REC_PREF t4 ON t1.PREFDEP = t4.PREFIXO
   LEFT JOIN COMP_PERDAS_ABR_REC_PREF t5 ON t1.PREFDEP = t5.PREFIXO
   LEFT JOIN COMP_PERDAS_MAI_REC_PREF t6 ON t1.PREFDEP = t6.PREFIXO
   LEFT JOIN COMP_PERDAS_JUN_REC_PREF t7 ON t1.PREFDEP = t7.PREFIXO

   ORDER BY 2,3;

QUIT;


PROC SQL;

   CREATE TABLE COMP_3_NOVO_2 AS
 
   SELECT DISTINCT 

   t1.POSICAO,
   t1.PREFDEP,
   t1.CTRA,
   t1.VALOR_PERDAS_SEM,
   (t1.VALOR_REC_JUL + t1.VALOR_REC_AGO + t1.VALOR_REC_SET + t1.VALOR_REC_OUT + t1.VALOR_REC_NOV + t1.VALOR_REC_DEZ) AS VALOR_REC_SEM,

   t1.VALOR_PERDAS_JUL,   
   t1.VALOR_REC_JUL,

   t1.VALOR_PERDAS_AGO,
   t1.VALOR_REC_AGO,

   t1.VALOR_PERDAS_SET,
   t1.VALOR_REC_SET,

   t1.VALOR_PERDAS_OUT,
   t1.VALOR_REC_OUT,

   t1.VALOR_PERDAS_NOV,
   t1.VALOR_REC_NOV,

   t1.VALOR_PERDAS_DEZ,
   t1.VALOR_REC_DEZ
    
   FROM COMP_3_NOVO t1 

   ORDER BY 2,3;

QUIT;


/***/
/***/
/***/
/***/


PROC SQL;
   CREATE TABLE COMP_4 AS
 
   SELECT 
   POSICAO,
   PREFDEP,
   CTRA,

   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   (VALOR_REC_SEM / VALOR_PERDAS_SEM) *100 AS PERSEM FORMAT 32.2,

   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   (VALOR_REC_JUL / VALOR_PERDAS_JUL) *100 AS PERJUL FORMAT 32.2,

   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   (VALOR_REC_AGO / VALOR_PERDAS_AGO) *100 AS PERAGO FORMAT 32.2,

   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   (VALOR_REC_SET / VALOR_PERDAS_SET) *100 AS PERSET FORMAT 32.2,

   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   (VALOR_REC_OUT / VALOR_PERDAS_OUT) *100 AS PEROUT FORMAT 32.2,

   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   (VALOR_REC_NOV / VALOR_PERDAS_NOV) *100 AS PERNOV FORMAT 32.2,

   VALOR_PERDAS_DEZ,
   VALOR_REC_DEZ,
   (VALOR_REC_DEZ / VALOR_PERDAS_DEZ) *100 AS PERDEZ FORMAT 32.2  
          		  		  
   FROM COMP_3_NOVO_2 
   ORDER BY 2,3;

QUIT;


PROC STDIZE DATA=COMP_4 OUT=COMP_4 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



/*Rel 528*/


%LET Usuario=f7176219;
%LET Keypass=bonus-rec-perdas-S58qpmu1h2mOD3TcHHc2q5tU8v0bVo5m7WZzPgrW365EzD4xIS;
%LET Rotina=bonus-rec-perdas;
%ProcessoIniciar();


PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('COMP_4', 'bonus-rec-perdas');
	;
QUIT;


%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);

x cd /dados/dirao/publico ;
x chmod 2777 *;




