
%INCLUDE '/dados/infor/suporte/FuncoesInfor.sas';

LIBNAME REL DB2 DATABASE=BDB2P04 SCHEMA=DB2REL AUTHDOMAIN=DB2SGCEN;

LIBNAME ATA "/dados/infor/producao";

/*%EncarteirarCNX(tabela_cli=base_mci, tabela_saida=encarteiramento, aaaamm=&AnoMes., so_ag_paa=1);*/


PROC SQL;
   CREATE TABLE TESTE_1 AS 
   SELECT DISTINCT

      t1.CD_TIP_CTRA,
      COUNT(CD_CLI) AS QTDE 

      FROM COMUM.PAI_REL_201908 t1
      	  WHERE t1.CD_TIP_CTRA IS NOT MISSING
		  GROUP BY t1.CD_TIP_CTRA 
;

QUIT;

			
PROC SQL;
   CREATE TABLE TESTE_2 AS 
   SELECT DISTINCT

      t1.CD_TIP_CTRA,
	  t1.QTDE,
	  t2.*

      FROM TESTE_1 t1
	  INNER JOIN REL.TIP_CTRA t2 ON t1.CD_TIP_CTRA = t2.CD_TIP_CTRA

	  WHERE t1.CD_TIP_CTRA IS NOT MISSING;

QUIT;


PROC SQL;
   CREATE TABLE TESTE_3 AS 
   SELECT DISTINCT

      /*NR_SEQL_CTRA*/
      t1.NR_SEQL_CTRA_ATB,
      COUNT(CD_CLI) AS QTDE 

      FROM COMUM.PAI_REL_201908 t1
      	  WHERE t1.CD_TIP_CTRA IS NOT MISSING
		  GROUP BY t1.NR_SEQL_CTRA_ATB 
;

QUIT;


PROC SQL;
   CREATE TABLE TESTE_4 AS 
   SELECT DISTINCT

      t1.NR_SEQL_CTRA,
      t1.NR_SEQL_CTRA_ATB      

      FROM COMUM.PAI_REL_201908 t1
      	  WHERE t1.CD_TIP_CTRA IS NOT MISSING AND t1.NR_SEQL_CTRA = t1.NR_SEQL_CTRA_ATB
		  
;

QUIT;


PROC SQL;
   CREATE TABLE TESTE_5 AS 
   SELECT DISTINCT

      t1.CD_PRF_DEPE,
      COUNT(CD_CLI) AS QTDE 

      FROM COMUM.PAI_REL_201908 t1
      	  WHERE t1.CD_PRF_DEPE IS NOT MISSING
		  GROUP BY t1.CD_PRF_DEPE 
;

QUIT;


PROC SQL;
   CREATE TABLE TESTE_6 AS 
   SELECT DISTINCT

      t1.TIPODEP
      FROM IGR.IGRREDE_201908 t1     	  
		  
;

QUIT;


PROC SQL;
   CREATE TABLE TESTE_7 AS 
   SELECT DISTINCT

      t1.TipoGeral
      FROM IGR.IGRREDE_201907 t1     	  
		  
;

QUIT;

x cd /dados/infor/producao/bonus_dirco_1s19 ;
x cd /dados/dirao/publico ;
x chmod 2777 *;




