

%INCLUDE '/dados/infor/suporte/FuncoesInfor.sas';

%LET Tx_Fon=6162;

LIBNAME DB2BIC DB2 DATABASE=BDB2P04 SCHEMA=DB2BIC AUTHDOMAIN=DB2SGCEN;
LIBNAME DB2GAT DB2 DATABASE=BDB2P04 SCHEMA=DB2GAT AUTHDOMAIN=DB2SGCEN;

LIBNAME AUX "/dados/infor/producao/Tempo_Resposta_PF_PJ";


DATA _NULL_;

/*D1 = '01JAN2019'd*/	
D1 = diaUtilAnterior(TODAY());
CALL SYMPUT('D1',COMPRESS(D1,' '));

/*ANOMES = 201901*/
ANOMES = Put(D1, yymmn6.);
CALL SYMPUT('ANOMES',COMPRESS(ANOMES,' '));

/*MESANO = 012019*/
MESANO=PUT(D1,mmyyn6.);
CALL SYMPUT('MESANO', COMPRESS(MESANO,' '));

/*ANO_ATUAL = 2019*/
ANO_ATUAL = 2019;
CALL SYMPUT('ANO_ATUAL',COMPRESS(ANO_ATUAL,' '));

/*MES_POSICAO = 01*/
MES_POSICAO = Put(MONTH (diaUtilAnterior(TODAY())), Z2.);
CALL SYMPUT('MES_POSICAO', COMPRESS(MES_POSICAO,' '));

RUN;

%Put &D1 &ANOMES &MESANO &ANO_ATUAL &MES_POSICAO;


PROC SQL;

   CREATE TABLE DEPENDENCIAS AS SELECT 

   INPUT(PrefDep, d4.) as PREFIXO, 
   INPUT(TipoDep, d3.) as TIPO_DEPENDENCIA,
   INPUT(UOR, d9.) as UOR,
   INPUT(GrupoFixo, d4.) as CD_AGRUPAMENTO_FIXO

   FROM IGR.DEPENDENCIAS_&ANOMES.
   WHERE SB = "00" AND STATUS = "A"; 

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES AS SELECT
          DISTINCT t1.CD_CLI AS MCI,

          t1.CD_PRF_DEPE AS PREFIXO, 
          t1.NR_SEQL_CTRA_ATB AS CARTEIRA, 
          t1.CD_TIP_CTRA AS TIPO_CARTEIRA,
		  t2.TIPO_DEPENDENCIA,          
          t2.CD_AGRUPAMENTO_FIXO,
		  t2.UOR
		  
      FROM COMUM.PAI_REL_&ANOMES. t1
      INNER JOIN DEPENDENCIAS t2 ON (t1.CD_PRF_DEPE = t2.PREFIXO);

QUIT;



/*******FERIADOS NACIONAIS*******/
/*******FERIADOS NACIONAIS*******/
/*******FERIADOS NACIONAIS*******/
/*******FERIADOS NACIONAIS*******/


PROC SQL;

     CREATE TABLE PREFIXO_FERIADO AS SELECT DISTINCT
           
	      t1.PREFIXO		  
		  
      FROM CLIENTES t1;

QUIT;


Data TAB_1;
format DT_FER yymmdd10.;
set PREFIXO_FERIADO;
DT_FER = '04MAR2019'd;
IND_FERIADO = 1;
run;


Data TAB_2;
format DT_FER yymmdd10.;
set PREFIXO_FERIADO;
DT_FER = '05MAR2019'd;
IND_FERIADO = 1;
run;


Data TAB_3;
format DT_FER yymmdd10.;
set PREFIXO_FERIADO;
DT_FER = '19APR2019'd;
IND_FERIADO = 1;
run;


Data TAB_4;
format DT_FER yymmdd10.;
set PREFIXO_FERIADO;
DT_FER = '01MAY2019'd;
IND_FERIADO = 1;
run;


Data TAB_5;
format DT_FER yymmdd10.;
set PREFIXO_FERIADO;
DT_FER = '20JUN2019'd;
IND_FERIADO = 1;
run;


Data TAB_6;
format DT_FER yymmdd10.;
set PREFIXO_FERIADO;
DT_FER = '25DEC2018'd;
IND_FERIADO = 1;
run;


Data TAB_7;
format DT_FER yymmdd10.;
set PREFIXO_FERIADO;
DT_FER = '01JAN2019'd;
IND_FERIADO = 1;
run;


PROC SQL;

CREATE TABLE PREFIXO_FERIADO_1 AS
 
   SELECT * FROM TAB_1
   OUTER UNION CORR
   SELECT * FROM TAB_2
   OUTER UNION CORR
   SELECT * FROM TAB_3
   OUTER UNION CORR
   SELECT * FROM TAB_4
   OUTER UNION CORR
   SELECT * FROM TAB_5
   OUTER UNION CORR
   SELECT * FROM TAB_6
   OUTER UNION CORR
   SELECT * FROM TAB_7;

Quit;


PROC SQL;

CREATE TABLE PREFIXO_FERIADO_1 AS SELECT *

FROM PREFIXO_FERIADO_1

ORDER BY 2;

Quit;


/*******FALE COM*******/
/*******FALE COM*******/
/*******FALE COM*******/
/*******FALE COM*******/

/*MES CORRENTE*/

PROC SQL;

   CREATE TABLE BASE_FALECOM_BIC_PF AS SELECT DISTINCT 

      t1.CD_CLI AS MCI,
	  t1.TS_INRO_CLI AS TS,
	  t1.DT_INCL_REG_INRO AS DATA,
	  t1.TX_PTL_INRO_CLI AS PTL,
	  t1.CD_TRAN_INRO_SIS
		  
      FROM DB2BIC.AUX_INRO_CLI_ATU t1
	  /*FROM DB2BIC.AUX_INRO_CLI_ANT t1*/
	  /*FROM DB2BIC.AUX_INRO_CLI_CMPR t1*/
      WHERE t1.CD_TRAN_INRO_SIS IN ("MIV10014", "MIV10016", "MIV10017");

QUIT;


/*ABERTURAS DO MES ANTERIOR*/

PROC SQL;

   CREATE TABLE BASE_FALECOM_BIC_PF_ANTERIOR AS SELECT DISTINCT 

      t1.CD_CLI AS MCI,
	  t1.TS_INRO_CLI AS TS,
	  t1.DT_INCL_REG_INRO AS DATA,
	  t1.TX_PTL_INRO_CLI AS PTL,
	  t1.CD_TRAN_INRO_SIS
		  
      FROM DB2BIC.AUX_INRO_CLI_ANT t1
	  /*FROM DB2BIC.AUX_INRO_CLI_CMPR t1*/
      WHERE t1.CD_TRAN_INRO_SIS IN ("MIV10014");

QUIT;


PROC SQL;

   CREATE TABLE FALECOM_ABERTURA_CORRENTE AS SELECT DISTINCT

      t1.MCI AS MCI_ABERTURA,
	  t1.TS AS TS_ABERTURA,
	  t1.DATA AS DATA_ABERTURA,
	  t1.PTL AS PTL_ABERTURA
		  
      FROM BASE_FALECOM_BIC_PF t1
      WHERE CD_TRAN_INRO_SIS = "MIV10014" AND MONTH(t1.DATA) = &MES_POSICAO. AND YEAR(t1.DATA) = &ANO_ATUAL. AND t1.DATA <= &D1;

QUIT;


PROC SQL;

   CREATE TABLE FALECOM_ABERTURA_ANTERIOR_1 AS SELECT DISTINCT

      t1.MCI AS MCI_ABERTURA,
	  t1.TS AS TS_ABERTURA,
	  t1.DATA AS DATA_ABERTURA,
	  t1.PTL AS PTL_ABERTURA
		  
      FROM BASE_FALECOM_BIC_PF_ANTERIOR t1
      WHERE CD_TRAN_INRO_SIS = "MIV10014" AND MONTH(t1.DATA) = (&MES_POSICAO. + 11)  AND YEAR(t1.DATA) = (&ANO_ATUAL. -1) ;

QUIT;


PROC SQL;

CREATE TABLE FALECOM_ABERTURA AS 
   SELECT * FROM FALECOM_ABERTURA_CORRENTE
   OUTER UNION CORR
SELECT * FROM FALECOM_ABERTURA_ANTERIOR_1;

Quit;


PROC SQL;

   CREATE TABLE FALECOM_FECHAMENTO AS SELECT DISTINCT

      t1.MCI AS MCI_FECHAMENTO,
	  t1.TS AS TS_FECHAMENTO,
	  t1.DATA AS DATA_FECHAMENTO,
	  t1.PTL AS PTL_FECHAMENTO	  
		  
      FROM BASE_FALECOM_BIC_PF t1
      WHERE t1.CD_TRAN_INRO_SIS IN ('MIV10016', 'MIV10017') AND MONTH(t1.DATA) = &MES_POSICAO. AND YEAR(t1.DATA) = &ANO_ATUAL. AND t1.DATA <= &D1;

QUIT;


PROC SQL;

   CREATE TABLE FALECOM_FECHAMENTO_2 AS SELECT DISTINCT

      t1.MCI_FECHAMENTO,
	  t1.TS_FECHAMENTO,
	  t1.DATA_FECHAMENTO,
	  t1.PTL_FECHAMENTO
		  
      FROM FALECOM_FECHAMENTO t1
	  GROUP BY 4
      HAVING MIN(t1.TS_FECHAMENTO) = t1.TS_FECHAMENTO;

QUIT;


PROC SQL;

      CREATE TABLE FALECOM_1 AS SELECT 

	  t1.MCI_ABERTURA AS MCI,
	  t1.TS_ABERTURA,
	  t2.TS_FECHAMENTO,
      TIMEPART(t1.TS_ABERTURA) FORMAT=TIME8. AS HMS_Abertura,
	  TIMEPART(t2.TS_FECHAMENTO) FORMAT=TIME8. AS HMS_Fechamento,
	  t1.DATA_ABERTURA,
	  t2.DATA_FECHAMENTO,
	  WEEKDAY(t1.DATA_ABERTURA) AS D_SEM_ABERTURA,
	  WEEKDAY(t2.DATA_FECHAMENTO) AS D_SEM_FECHAMENTO,
	  t1.PTL_ABERTURA AS PTL
		  
      FROM FALECOM_ABERTURA t1
      INNER JOIN FALECOM_FECHAMENTO_2 t2 ON (t1.MCI_ABERTURA = t2.MCI_FECHAMENTO AND t1.PTL_ABERTURA = t2.PTL_FECHAMENTO);      

QUIT;


/********ENCARTEIRANDO*********/
/********ENCARTEIRANDO*********/
/********ENCARTEIRANDO*********/
/********ENCARTEIRANDO*********/


PROC SQL;

      CREATE TABLE FALECOM_2 AS SELECT DISTINCT
      
	  t2.PREFIXO,
	  t2.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      t1.HMS_Abertura,
	  t1.HMS_Fechamento,
	  t1.DATA_ABERTURA FORMAT yymmdd10.,
	  t1.DATA_FECHAMENTO FORMAT yymmdd10.,
	  t1.D_SEM_ABERTURA,
	  t1.D_SEM_FECHAMENTO	  
		  
      FROM FALECOM_1 t1
      INNER JOIN CLIENTES t2 ON (t1.MCI = t2.MCI);      

QUIT;


/********TRATAMENTO FERIADO*********/
/********TRATAMENTO FERIADO*********/
/********TRATAMENTO FERIADO*********/
/********TRATAMENTO FERIADO*********/


PROC SQL;

      CREATE TABLE FALECOM_3 AS SELECT 
      
	  t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      t1.HMS_Abertura,
	  t1.HMS_Fechamento,
	  t1.DATA_ABERTURA,
	  t1.DATA_FECHAMENTO,
	  t1.D_SEM_ABERTURA,
	  t1.D_SEM_FECHAMENTO,
	  t2.IND_FERIADO AS IND_FER_ABERT,
	  t3.IND_FERIADO AS IND_FER_FECH
	  
      FROM FALECOM_2 t1
      LEFT JOIN PREFIXO_FERIADO_1 t2 ON (t1.PREFIXO = t2.PREFIXO AND t1.DATA_ABERTURA = t2.DT_FER)
	  LEFT JOIN PREFIXO_FERIADO_1 t3 ON (t1.PREFIXO = t3.PREFIXO AND t1.DATA_ABERTURA = t3.DT_FER)
      GROUP BY 1,2,3;      

QUIT;


PROC STDIZE OUT=FALECOM_3 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

      CREATE TABLE FALECOM_4 AS SELECT 
      
	  t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      t1.HMS_ABERTURA,
	  t1.HMS_FECHAMENTO,
	  t1.DATA_ABERTURA,
	  t1.DATA_FECHAMENTO,
	  t1.D_SEM_ABERTURA,
	  t1.D_SEM_FECHAMENTO,
	  t1.IND_FER_ABERT,
	  t1.IND_FER_FECH,

      IFN(DATA_ABERTURA = '04JUL2019'd, DATA_ABERTURA + 2, IFN(IND_FER_ABERT = 1, DATA_ABERTURA + 1, DATA_ABERTURA)) FORMAT  yymmdd10. AS DATA_ABERTURA_NOVO_1,
      IFN(DATA_ABERTURA = '04MAR2019'd, "8:0:0"t, IFN(IND_FER_ABERT = 1, "8:0:0"t, HMS_ABERTURA)) FORMAT = TIME8. AS HMS_ABERTURA_NOVO_1,
	  
      IFN(DATA_FECHAMENTO = '04MAR2019'd, DATA_FECHAMENTO + 2, IFN(IND_FER_FECH = 1, DATA_FECHAMENTO + 1, DATA_FECHAMENTO)) FORMAT  yymmdd10. AS DATA_FECHAMENTO_NOVO_1,
	  IFN(DATA_FECHAMENTO = '04MAR2019'd, "8:0:0"t, IFN(IND_FER_FECH = 1, "8:0:0"t, HMS_FECHAMENTO)) FORMAT = TIME8. AS HMS_FECHAMENTO_NOVO_1
		  
      FROM FALECOM_3 t1;      

QUIT;


/**************************************/


PROC SQL;

   CREATE TABLE FALECOM_5 AS SELECT DISTINCT

      t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      t1.HMS_ABERTURA,
	  t1.HMS_FECHAMENTO,
	  t1.DATA_ABERTURA,
	  t1.DATA_FECHAMENTO,
	  t1.D_SEM_ABERTURA,
	  t1.D_SEM_FECHAMENTO,
	  t1.IND_FER_ABERT,
	  t1.IND_FER_FECH,
	  t1.DATA_ABERTURA_NOVO_1,
	  t1.DATA_FECHAMENTO_NOVO_1,
	  t1.HMS_ABERTURA_NOVO_1,
	  t1.HMS_FECHAMENTO_NOVO_1,
      
	  IFN(HOUR(t1.HMS_ABERTURA) > 18, IFN(t1.D_SEM_ABERTURA IN (2,3,4,5,6), t1.DATA_ABERTURA + 1, IFN(t1.D_SEM_ABERTURA IN (1), t1.DATA_ABERTURA + 2, t1.DATA_ABERTURA + 3))
      , t1.DATA_ABERTURA) FORMAT yymmdd10. AS DATA_ABERTURA_NOVO_2,
	  
      IFN(t1.D_SEM_ABERTURA IN (3,4,5,6,7), IFN(HOUR(t1.HMS_ABERTURA) < 8, "8:0:0"t, IFN(HOUR(t1.HMS_ABERTURA) > 18, "18:0:0"t, t1.HMS_ABERTURA)), 
      IFN(t1.D_SEM_ABERTURA IN (1,2), "8:0:0"t, t1.HMS_ABERTURA)) FORMAT=TIME8. AS HMS_ABERTURA_NOVO_2,
  
      IFN(HOUR(t1.HMS_FECHAMENTO) > 18, IFN(t1.D_SEM_FECHAMENTO IN (2,3,4,5,6), t1.DATA_FECHAMENTO + 1, IFN(t1.D_SEM_FECHAMENTO IN (1), t1.DATA_FECHAMENTO + 2, t1.DATA_FECHAMENTO + 3))
      , t1.DATA_FECHAMENTO) FORMAT yymmdd10. AS DATA_FECHAMENTO_NOVO_2,

      IFN(t1.D_SEM_FECHAMENTO IN (3,4,5,6,7), IFN(HOUR(t1.HMS_FECHAMENTO) < 8, "8:0:0"t, IFN(HOUR(t1.HMS_FECHAMENTO) > 18, "18:0:0"t, t1.HMS_FECHAMENTO)), 
      IFN(t1.D_SEM_FECHAMENTO IN (1,2), "8:0:0"t, t1.HMS_FECHAMENTO)) FORMAT=TIME8. AS HMS_FECHAMENTO_NOVO_2
             
   FROM FALECOM_4 t1;

QUIT;


PROC SQL;

      CREATE TABLE FALECOM_6 AS SELECT 
      
	  t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      t1.HMS_ABERTURA,
	  t1.HMS_FECHAMENTO,
	  t1.DATA_ABERTURA,
	  t1.DATA_FECHAMENTO,
	  t1.D_SEM_ABERTURA,
	  t1.D_SEM_FECHAMENTO,
	  t1.IND_FER_ABERT,
	  t1.IND_FER_FECH,
	  t1.DATA_ABERTURA_NOVO_1,
	  t1.DATA_FECHAMENTO_NOVO_1,
	  t1.HMS_ABERTURA_NOVO_1,
	  t1.HMS_FECHAMENTO_NOVO_1,
	  t1.DATA_ABERTURA_NOVO_2,
	  t1.DATA_FECHAMENTO_NOVO_2,
	  t1.HMS_ABERTURA_NOVO_2,
	  t1.HMS_FECHAMENTO_NOVO_2,

      IFN(DATA_ABERTURA = '04JUL2019'd, DATA_ABERTURA + 2, IFN(IND_FER_ABERT = 1, DATA_ABERTURA + 1, DATA_ABERTURA)) FORMAT  yymmdd10. AS DATA_ABERTURA_NOVO_3,
      IFN(DATA_ABERTURA = '04MAR2019'd, "8:0:0"t, IFN(IND_FER_ABERT = 1, "8:0:0"t, HMS_ABERTURA)) FORMAT = TIME8. AS HMS_ABERTURA_NOVO_3,
	  
      IFN(DATA_FECHAMENTO = '04MAR2019'd, DATA_FECHAMENTO + 2, IFN(IND_FER_FECH = 1, DATA_FECHAMENTO + 1, DATA_FECHAMENTO)) FORMAT  yymmdd10. AS DATA_FECHAMENTO_NOVO_3,
	  IFN(DATA_FECHAMENTO = '04MAR2019'd, "8:0:0"t, IFN(IND_FER_FECH = 1, "8:0:0"t, HMS_FECHAMENTO)) FORMAT = TIME8. AS HMS_FECHAMENTO_NOVO_3
		  
      FROM FALECOM_5 t1;      

QUIT;


/********CALCULO TEMPO*********/
/********CALCULO TEMPO*********/
/********CALCULO TEMPO*********/
/********CALCULO TEMPO*********/


PROC SQL;

   CREATE TABLE FALECOM_7 AS SELECT DISTINCT

      t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.DATA_ABERTURA_NOVO_3,
	  t1.DATA_FECHAMENTO_NOVO_3,
	  t1.HMS_ABERTURA_NOVO_3,
	  t1.HMS_FECHAMENTO_NOVO_3,

      (t1.DATA_FECHAMENTO_NOVO_3 - t1.DATA_ABERTURA_NOVO_3) AS DIF_TEMP_1,
	  (t1.HMS_FECHAMENTO_NOVO_3 - t1.HMS_ABERTURA_NOVO_3) FORMAT = TIME8. AS DIF_TEMP_2 

	      
      FROM FALECOM_6 t1;

QUIT;


/***AJUSTANDO A DIFERENCA DE DIAS***/
/***AJUSTANDO A DIFERENCA DE DIAS***/
/***AJUSTANDO A DIFERENCA DE DIAS***/
/***AJUSTANDO A DIFERENCA DE DIAS***/

Data AUXILIAR_SABDOM;
 
        INPUT  CHAVE 2.
              SD date9.;

    CARDS;
1 01DEC2018
1 02DEC2018
1 08DEC2018
1 09DEC2018
1 15DEC2018
1 16DEC2018
1 22DEC2018
1 23DEC2018
1 29JAN2018
1 30JAN2018
1 05JAN2019
1 06JAN2019
1 12JAN2019
1 13JAN2019
1 19JAN2019
1 20JAN2019
1 26JAN2019
1 27JAN2019
1 02FEB2019
1 03FEB2019
1 09FEB2019
1 10FEB2019
1 16FEB2019
1 17FEB2019
1 23FEB2019
1 24FEB2019
1 02MAR2019
1 03MAR2019
1 09MAR2019
1 10MAR2019
1 16MAR2019
1 17MAR2019
1 23MAR2019
1 24MAR2019
1 30MAR2019
1 31MAR2019
1 06APR2019
1 07APR2019
1 13APR2019
1 14APR2019
1 20APR2019
1 21APR2019
1 27APR2019
1 28APR2019
1 04MAY2019
1 05MAY2019
1 11MAY2019
1 12MAY2019
1 18MAY2019
1 19MAY2019
1 25MAY2019
1 26MAY2019
1 01JUN2019
1 02JUN2019
1 08JUN2019
1 09JUN2019
1 15JUN2019
1 16JUN2019
1 22JUN2019
1 23JUN2019
1 29JUN2019
1 30JUN2019
;

run;


PROC SQL;

   CREATE TABLE AUXILIAR_SABDOM_2 AS SELECT DISTINCT

      CHAVE,
      SD format yymmdd10. AS DT_FER
	  	      
   FROM AUXILIAR_SABDOM t1;

QUIT;


PROC SQL;

     CREATE TABLE LISTA_PREFIXOS AS SELECT DISTINCT
           
	      t1.PREFIXO		  
		  
      FROM CLIENTES t1;

QUIT;


Data LISTA_PREFIXOS_1;
SET PREFIXO_FERIADO;
IND_FERIADO = 1;
run;


PROC SQL;

   CREATE TABLE JUNTANDO AS SELECT DISTINCT

     t1.PREFIXO,
	 t2.DT_FER	 
	  	      
   FROM LISTA_PREFIXOS_1 t1
   INNER JOIN AUXILIAR_SABDOM_2 t2 ON t1.IND_FERIADO = t2.CHAVE
   ORDER BY 1;

QUIT;


/********/

PROC SQL;

CREATE TABLE PREFIXO_FERIADO_2 AS SELECT 

   t1.PREFIXO,
   t1.DT_FER

FROM PREFIXO_FERIADO_1 t1
ORDER BY 2;

Quit;


PROC SQL;

CREATE TABLE JUNTANDO AS
 
   SELECT * FROM JUNTANDO
   OUTER UNION CORR
   SELECT * FROM PREFIXO_FERIADO_2;

Quit;



/***TIRAMOS OS FERIADOS DA CONTAGEM DE DIAS***/
/***TIRAMOS OS FERIADOS DA CONTAGEM DE DIAS***/

PROC SQL;

   CREATE TABLE FALECOM_CORRECAO AS SELECT DISTINCT

      t1.PREFIXO, t2.DT_FER, t1.DATA_ABERTURA_NOVO_3, t1.DATA_FECHAMENTO_NOVO_3
	  	      
      FROM FALECOM_7 t1
      INNER JOIN JUNTANDO t2 ON t1.PREFIXO = t2.PREFIXO
      WHERE DT_FER > t1.DATA_ABERTURA_NOVO_3 AND DT_FER < t1.DATA_FECHAMENTO_NOVO_3;

QUIT;


PROC SQL;

   CREATE TABLE FALECOM_CORRECAO_2 AS SELECT DISTINCT

      t1.PREFIXO, t1.DATA_ABERTURA_NOVO_3, t1.DATA_FECHAMENTO_NOVO_3, COUNT(DT_FER) AS CONTAGEM
	  	      
   FROM FALECOM_CORRECAO t1
   GROUP BY 1, 2, 3;

QUIT;


PROC SQL;

   CREATE TABLE FALECOM_CORRECAO_3 AS SELECT DISTINCT

      t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.DATA_ABERTURA_NOVO_3,
	  t1.DATA_FECHAMENTO_NOVO_3,
	  t1.HMS_ABERTURA_NOVO_3,
	  t1.HMS_FECHAMENTO_NOVO_3,
      t1.DIF_TEMP_1,
	  t1.DIF_TEMP_2,
      t2.CONTAGEM 
	      
      FROM FALECOM_7 t1

   LEFT JOIN FALECOM_CORRECAO_2 t2 ON t1.PREFIXO = t2.PREFIXO AND t1.DATA_ABERTURA_NOVO_3 = t2.DATA_ABERTURA_NOVO_3 AND t1.DATA_FECHAMENTO_NOVO_3 = t2.DATA_FECHAMENTO_NOVO_3;

QUIT;


PROC STDIZE DATA=FALECOM_CORRECAO_3 OUT=FALECOM_CORRECAO_3 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE FALECOM_7_CORRIGIDO AS SELECT DISTINCT

      t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.DATA_ABERTURA_NOVO_3,
	  t1.DATA_FECHAMENTO_NOVO_3,
	  t1.HMS_ABERTURA_NOVO_3,
	  t1.HMS_FECHAMENTO_NOVO_3,
      (t1.DIF_TEMP_1 - t1.CONTAGEM) AS DIF_TEMP_1,
	  t1.DIF_TEMP_2       
	      
      FROM FALECOM_CORRECAO_3 t1;

QUIT;


/***CALCULANDO***/

 
PROC SQL;

   CREATE TABLE FALECOM_8 AS SELECT DISTINCT

      t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.DATA_ABERTURA_NOVO_3,
	  t1.DATA_FECHAMENTO_NOVO_3,
	  t1.HMS_ABERTURA_NOVO_3,
	  t1.HMS_FECHAMENTO_NOVO_3,
	  t1.DIF_TEMP_1,
	  t1.DIF_TEMP_2,
      
	  IFN(t1.DIF_TEMP_2 < 0, (DIF_TEMP_1 - 1)*600, DIF_TEMP_1*600) AS DIF_TEMP_1_NOVO,
	  IFN(t1.DIF_TEMP_2 < 0, ((HOUR(t1.DIF_TEMP_2)*60) + MINUTE(t1.DIF_TEMP_2) + 600), ((HOUR(t1.DIF_TEMP_2)*60) + MINUTE(t1.DIF_TEMP_2))) AS DIF_TEMP_2_NOVO
	  	       
      FROM FALECOM_7 t1;

QUIT;


PROC SQL;

   CREATE TABLE FALECOM_9 AS SELECT DISTINCT

      t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.DATA_ABERTURA_NOVO_3,
	  t1.DATA_FECHAMENTO_NOVO_3,
	  t1.HMS_ABERTURA_NOVO_3,
	  t1.HMS_FECHAMENTO_NOVO_3,
	  (t1.DIF_TEMP_1_NOVO + t1.DIF_TEMP_2_NOVO) AS START
	  
    FROM FALECOM_8 t1;

QUIT;


/***COLOCANDO A REGUA***/

PROC SQL;

   CREATE TABLE FALECOM_10 AS SELECT DISTINCT

      t1.PREFIXO,
	  t1.CARTEIRA,
	  t1.PTL,
	  t1.MCI,
	  t1.DATA_ABERTURA_NOVO_3,
	  t1.DATA_FECHAMENTO_NOVO_3,
	  t1.HMS_ABERTURA_NOVO_3,
	  t1.HMS_FECHAMENTO_NOVO_3,
	  t1.START,

      IFN(START >= 120, 0, IFN(START >= 105, 5, IFN(START >= 90, 10, IFN(START >= 75, 15, IFN(START >= 60, 20, 25 ))))) AS PONTOS
    	  
    FROM FALECOM_9 t1;

QUIT;


PROC SQL;

   CREATE TABLE FALECOM_11 AS SELECT DISTINCT

      t1.PREFIXO AS PREFDEP,
	  t1.CARTEIRA AS CTRA,
	  AVG(t1.PONTOS) FORMAR 32.2 AS PONTOS
    	  
    FROM FALECOM_10 t1
    GROUP BY 1,2;

QUIT;


/************GAT TELEFONICO**************/
/************GAT TELEFONICO**************/
/************GAT TELEFONICO**************/
/************GAT TELEFONICO**************/


PROC SQL;

   CREATE TABLE GAT_TELEFONICO AS SELECT DISTINCT

      CD_CLI AS MCI,
	  NR_PTL_ATDT AS PROTOCOLO,
	  TS_SLCT_ATDT AS TS_ABERTURA,
	  TS_FIM_ATDT_TELC AS TS_FECHAMENTO
 
   FROM DB2GAT.FILA_ATDT_TELC t1
   WHERE CD_CLI <> 0 AND TS_FIM_ATDT_TELC IS NOT MISSING
   ORDER BY 3;

QUIT;


PROC SQL;

      CREATE TABLE GAT_TELEFONICO_1 AS SELECT 

	  t1.MCI,
	  t1.PROTOCOLO,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      TIMEPART(t1.TS_ABERTURA) FORMAT=TIME8. AS HMS_ABERTURA,
	  TIMEPART(t1.TS_FECHAMENTO) FORMAT=TIME8. AS HMS_FECHAMENTO,
	  DATEPART(t1.TS_ABERTURA) FORMAT yymmdd10. AS DATA_ABERTURA,
	  DATEPART(t1.TS_FECHAMENTO) FORMAT yymmdd10. AS DATA_FECHAMENTO
		  
      FROM GAT_TELEFONICO t1;      

QUIT;


PROC SQL;

      CREATE TABLE GAT_TELEFONICO_2 AS SELECT 

	  t1.MCI,
	  t1.PROTOCOLO,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      t1.HMS_ABERTURA,
	  t1.HMS_FECHAMENTO,
	  t1.DATA_ABERTURA,
	  t1.DATA_FECHAMENTO,
	  WEEKDAY(t1.DATA_ABERTURA) AS D_SEM_ABERTURA,
	  WEEKDAY(t1.DATA_ABERTURA) AS D_SEM_FECHAMENTO
		  
      FROM GAT_TELEFONICO_1 t1;      

QUIT;


PROC SQL;

      CREATE TABLE GAT_TELEFONICO_3 AS SELECT 

	  t1.MCI,
	  t1.PROTOCOLO,
	  t1.TS_ABERTURA,
	  t1.TS_FECHAMENTO,
      t1.HMS_ABERTURA,
	  t1.HMS_FECHAMENTO,
	  t1.DATA_ABERTURA,
	  t1.DATA_FECHAMENTO,
	  t1.D_SEM_ABERTURA,
	  t1.D_SEM_FECHAMENTO,
	  (t1.DATA_FECHAMENTO - t1.DATA_ABERTURA) AS DIF_TEMP_1,
	  (t1.HMS_FECHAMENTO - t1.HMS_ABERTURA) FORMAT=TIME8. AS DIF_TEMP_2

      FROM GAT_TELEFONICO_2 t1;      

QUIT;



/************GAT PRESENCIAL**************/
/************GAT PRESENCIAL**************/
/************GAT PRESENCIAL**************/
/************GAT PRESENCIAL**************/

PROC SQL;

   CREATE TABLE GAT_PRESENCIAL_5 AS SELECT DISTINCT

      t1.NR_SLCT_ATDT,
	  t2.CD_CLI AS MCI,
	  t1.TS_INC_ATDT,
	  t1.TS_FIM_ATDT   
 
   FROM DB2GAT.HST_PTL_ATDT t1
   INNER JOIN DB2GAT.HST_SLCT_ATDT t2 ON t1.CD_UOR_SLCT = t2.CD_UOR_SLCT AND t1.NR_SLCT_ATDT = t2.NR_SLCT_ATDT AND t1.DT_HST_PTL_ATDT = t2.DT_HST_SLCT_ATDT
   WHERE YEAR(t1.TS_FIM_ATDT) = 2019;

QUIT;



PROC SQL;

   CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=DB23P41);
   CREATE TABLE AUX.GAT_PRESENCIAL_6 AS

   SELECT 
    
      NR_SLCT_ATDT,
	  CD_CLI,
	  TS_INC_ATDT,
	  TS_FIM_ATDT  

   FROM CONNECTION TO DB2
      (SELECT 

      t1.NR_SLCT_ATDT,
	  t2.CD_CLI,
	  t1.TS_INC_ATDT,
	  t1.TS_FIM_ATDT

      FROM DB2GAT.HST_PTL_ATDT t1

	  INNER JOIN DB2GAT.HST_SLCT_ATDT t2 ON (t1.CD_UOR_SLCT = t2.CD_UOR_SLCT AND t1.NR_SLCT_ATDT = t2.NR_SLCT_ATDT AND t1.DT_HST_PTL_ATDT = t2.DT_HST_SLCT_ATDT)

	  WHERE YEAR(t1.TS_FIM_ATDT) = 2019);

   DISCONNECT FROM DB2;

QUIT;














































