

%include '/dados/infor/suporte/FuncoesInfor.sas';

LIBNAME PGT DB2 DATABASE=BDB2P04 SCHEMA=DB2PGT AUTHDOMAIN=DB2SGCEN;
LIBNAME DEB DB2 DATABASE=BDB2P04 SCHEMA=DB2DEB AUTHDOMAIN=DB2SGCEN;
LIBNAME ATB DB2 DATABASE=BDB2P04 SCHEMA=DB2ATB AUTHDOMAIN=DB2SGCEN;
LIBNAME TFA DB2 DATABASE=BDB2P04 SCHEMA=DB2TFA AUTHDOMAIN=DB2SGCEN;
LIBNAME CDC DB2 DATABASE=BDB2P04 SCHEMA=DB2CDC AUTHDOMAIN=DB2SGCEN;
LIBNAME PRD DB2 DATABASE=BDB2P04 SCHEMA=DB2PRD AUTHDOMAIN=DB2SGCEN;
LIBNAME VIP DB2 DATABASE=BDB2P04 SCHEMA=DB2VIP AUTHDOMAIN=DB2SGCEN;
LIBNAME CRS DB2 DATABASE=BDB2P04 SCHEMA=DB2CRS AUTHDOMAIN=DB2SGCEN;
LIBNAME OPR DB2 DATABASE=BDB2P04 SCHEMA=DB2OPR AUTHDOMAIN=DB2SGCEN;
LIBNAME BIC DB2 DATABASE=BDB2P04 SCHEMA=DB2BIC AUTHDOMAIN=DB2SGCEN;


libname CDC2 '/dados/gecen/interno/bases/cdc';
libname AUX '/dados/infor/producao/aux_fopag_var_dired';


DATA _NULL_;
	   
    D1=DiaUtilAnterior(Today());
	CALL SYMPUT('D1',D1);
	CALL SYMPUT('AnoMes',Put(D1, yymmn6.));
	CALL SYMPUT('LMT',"'"||Put(D1, yymmdd10.)||"'");


    DT_IN=primeiroDiaUtilMes(DiaUtilAnterior(Today()));
	CALL SYMPUT('DT_IN',"'"||Put(DT_IN, yymmdd10.)||"'");

    DT_FIM=DiaUtilAnterior(Today());
	CALL SYMPUT('DT_FIM',"'"||Put(DT_FIM, yymmdd10.)||"'");

	MES_POSICAO = Put(MONTH (diaUtilAnterior(TODAY())), Z2.);
    CALL SYMPUT('MES_POSICAO', COMPRESS(MES_POSICAO,' '));

	DATA_BASE = '31Dec2100'd;
	CALL SYMPUT('DATA_BASE',COMPRESS(DATA_BASE,' '));

RUN;


%Put &D1 &AnoMes &LMT  &DT_IN &DT_FIM  &MES_POSICAO &DATA_BASE;


/******************************************************************/
/******************************************************************/
/************ FOPAG VAREJO ENCARTEIRADO MCI PAGADOR ***************/
/******************************************************************/
/******************************************************************/


PROC SQL;
   CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
   CREATE TABLE AUX_PGT AS
   SELECT CD_CLI, CD_CTR_PGTO, DT_CTR_PGTO Format ddmmyy10.
   FROM CONNECTION TO DB2
      (SELECT CD_CLI, CD_CTR_PGTO, DT_CTR_PGTO
       FROM DB2PGT.CTR_PGTO A
	   INNER JOIN DB2MCI.CLIENTE B ON(A.CD_CLI=B.COD)
	   WHERE IN_EST_CTR_PGTO='A' AND COD_TIPO=2);
   DISCONNECT FROM DB2;
QUIT;


PROC SQL;
	CREATE TABLE PGT_FILTRADA AS
		SELECT A.* FROM AUX_PGT A
		INNER JOIN (SELECT CD_CLI, CD_CTR_PGTO, MIN(DT_CTR_PGTO) AS K
					FROM AUX_PGT GROUP BY 1, 2) B 
                    ON(A.CD_CLI=B.CD_CLI AND A.DT_CTR_PGTO=B.K)
					WHERE DT_CTR_PGTO BETWEEN MDY(1, 1, 2018) AND &D1  
		ORDER BY 1, 2;
QUIT;


PROC SQL;
	CREATE TABLE BASE_MCI AS
		SELECT DISTINCT CD_CLI
			FROM PGT_FILTRADA
				ORDER BY 1;
	CREATE INDEX CD_CLI ON BASE_MCI(CD_CLI);
QUIT;



/*ENCARTEIRANDO MCI PAGADOR*/


%Macro Encarteiramento(TP=1);

	DATA _NULL_;
		IF &TP NE 2 THEN
			CALL SYMPUT('TBL','COMUM.PAI_REL_'||Put(&AnoMes, Z6.));
		ELSE CALL SYMPUT('TBL','COMUM.PAI_REL_PJ_'||Put(&AnoMes, Z6.));
	RUN;

	%Put &TBL;

	PROC SQL;
		CREATE TABLE ENCARTEIRAMENTO AS 
			SELECT DISTINCT A.CD_CLI AS CD_CLI, CD_PRF_DEPE AS PrefDep,
				NR_SEQL_CTRA AS Carteira, CD_TIP_CTRA AS TC
			FROM &TBL A
				INNER JOIN BASE_MCI B ON(A.CD_CLI=B.CD_CLI)
					WHERE CD_PRF_DEPE NOT IN(4777 8008 9940 9777);
		CREATE INDEX CD_CLI ON ENCARTEIRAMENTO(CD_CLI);
	QUIT;

	PROC SQL NOPRINT;
		SELECT COUNT(*) INTO :Q
			FROM (SELECT CD_CLI
			FROM ENCARTEIRAMENTO
				GROUP BY 1
					HAVING COUNT(*)>1);
	QUIT;

	%Put &Q;

	%IF &Q>0 %THEN
		%DO;

			DATA DUPLICADOS;
				SET ENCARTEIRAMENTO(Obs=0);
			RUN;

			PROC SQL;
				CREATE TABLE AUX_D AS
					SELECT CD_CLI
						FROM ENCARTEIRAMENTO
							GROUP BY 1
								HAVING COUNT(*)>1;
			RUN;

			DATA AUX_D(DROP=Seq);
				SET AUX_D;
				Seq+1;
				Grupo=CEIL(Seq/5957);
			RUN;

			PROC SQL NOPRINT;
				SELECT MAX(Grupo) INTO: Q
					FROM AUX_D;
			QUIT;

			%PUT &Q;

			%DO I=1 %TO &Q;

				PROC SQL NOPRINT;
					SELECT CD_CLI INTO: Var Separated By ', '
						FROM AUX_D
							WHERE Grupo=&I;
				QUIT;

				PROC SQL;
					CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
					INSERT INTO DUPLICADOS
						SELECT A.*, Carteira, TC
							FROM CONNECTION TO DB2
								(SELECT COD, COD_PREF_AGEN
									FROM DB2MCI.CLIENTE
										WHERE COD IN(&Var)
											ORDER BY COD;) A
												INNER JOIN ENCARTEIRAMENTO B ON(A.COD=B.CD_CLI AND A.COD_PREF_AGEN=B.PrefDep);
					DISCONNECT FROM DB2;
				QUIT;

				DATA ENCARTEIRAMENTO;
					SET ENCARTEIRAMENTO(WHERE=(CD_CLI NOT IN(&Var.)));
					BY CD_CLI;
				RUN;

			%END;

			PROC SORT DATA=DUPLICADOS;
				BY CD_CLI;
			RUN;

			DATA ENCARTEIRAMENTO;
				SET ENCARTEIRAMENTO DUPLICADOS;
				BY CD_CLI;
			RUN;

			PROC DELETE DATA=DUPLICADOS AUX_D;
			RUN;

		%END;

	PROC SQL NOPRINT;
		SELECT COUNT(*) INTO: Q
			FROM (SELECT DISTINCT A.CD_CLI
			FROM BASE_MCI A
				LEFT JOIN ENCARTEIRAMENTO B ON(A.CD_CLI=B.CD_CLI)
					WHERE B.CD_CLI Is Missing);
	QUIT;

	%Put &Q;

	%IF &Q>0 %THEN
		%DO;

			DATA PERDIDOS_X;
				SET ENCARTEIRAMENTO(Obs=0);
			RUN;

			PROC SQL;
				CREATE TABLE AUX_P AS
					SELECT DISTINCT A.CD_CLI
						FROM BASE_MCI A
							LEFT JOIN ENCARTEIRAMENTO B ON(A.CD_CLI=B.CD_CLI)
								WHERE B.CD_CLI Is Missing;
			RUN;

			DATA AUX_P(DROP=Seq);
				SET AUX_P;
				Seq+1;
				Grupo=CEIL(Seq/5957);
			RUN;

			PROC SQL NOPRINT;
				SELECT MAX(Grupo) INTO: Q
					FROM AUX_P;
			QUIT;

			%PUT &Q;

			%DO I=1 %TO &Q;

				PROC SQL NOPRINT;
					SELECT CD_CLI Format 9. INTO: Var Separated By ', '
						FROM AUX_P
							WHERE Grupo=&I AND CD_CLI NE .;
				QUIT;

				PROC SQL;
					CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
					INSERT INTO PERDIDOS_X
						SELECT *
							FROM CONNECTION TO DB2
								(SELECT COD AS CD_CLI, COD_PREF_AGEN AS PREFIXO, 
									7002 AS CARTEIRA, 700 AS TC
								FROM DB2MCI.CLIENTE
									WHERE COD IN(&Var)
										ORDER BY COD;);
					DISCONNECT FROM DB2;
				QUIT;

			%END;

			PROC SORT DATA=PERDIDOS_X;
				BY CD_CLI;
			RUN;

			DATA ENCARTEIRAMENTO;
				SET ENCARTEIRAMENTO PERDIDOS_X;
				BY CD_CLI;
			RUN;

			PROC DELETE DATA=AUX_P PERDIDOS_X;
			RUN;

		%END;

	PROC SQL NOPRINT;
		SELECT Input(PrefDep,4.) INTO: Var Separated By ' '
			FROM IGR.IGRREDE_&AnoMes
				WHERE PrefDep NE '4777' AND TipoDep In('01' '09') AND PrefSupEst NE '8481';
	QUIT;

	DATA _NULL_;
		IF &AnoMes>201806 THEN
			CALL SYMPUT('LTC','10 16 50 56 57 60 77 303 315 321 322 328 700');
		ELSE CALL SYMPUT('LTC','10 16 50 56 57 60 303 315 321 322 328 700');
	RUN;

	DATA ENCARTEIRAMENTO;
		SET ENCARTEIRAMENTO;

		IF TC NOT IN(&LTC) AND PrefDep IN(&Var) THEN
			DO;
				Carteira=7002;
				TC=700;
			END;

		VAREJO=PrefDep IN(&Var);
	RUN;

%Mend;
%Encarteiramento(TP=2);



/*********************************/
/*MCI PAGADOR ENCARTEIRADO*/
/*********************************/

DATA BASE_PGT_PJ;
	MERGE ENCARTEIRAMENTO PGT_FILTRADA;
	BY CD_CLI;
RUN;

/*********************************/
/*VERIFICA SE HOUVE REMESSA*/
/*********************************/


/*********************************/
/*TIRAR OS MCI GOVERNO*/
/*********************************/

PROC SQL;
CREATE TABLE BASE_PGT_PJ AS SELECT t1.CD_CLI, t1.PrefDep, t1.Carteira, t1.TC, t1.VAREJO, t1.CD_CTR_PGTO, t1.DT_CTR_PGTO, t2.mci 
FROM BASE_PGT_PJ t1
LEFT JOIN BCN.BCN_GOV t2 ON t1.CD_CLI = T2.mci; 
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ OUT=BASE_PGT_PJ REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ AS SELECT t1.CD_CLI, t1.PrefDep, t1.Carteira, t1.TC, t1.VAREJO, t1.CD_CTR_PGTO, t1.DT_CTR_PGTO 
FROM BASE_PGT_PJ t1
where t1.mci = 0; 
QUIT;


PROC SQL;
	CREATE TABLE BASE_MCI AS
		SELECT DISTINCT CD_CLI
			FROM BASE_PGT_PJ
				ORDER BY 1;
	CREATE INDEX CD_CLI ON BASE_MCI(CD_CLI);
QUIT;


/*********************************/
/*TIRAR OS MCI GOVERNO*/
/*********************************/

/*********************************/
/*CONTINUA*/
/*********************************/


PROC SQL;
	DROP TABLE DB2SGCEN.FOPAG_180919;
	CREATE TABLE DB2SGCEN.FOPAG_180919 AS
		SELECT DISTINCT CD_CLI Format Z20.
			FROM BASE_MCI
				ORDER BY 1;
QUIT;


PROC SQL;
	CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
	CREATE TABLE REMESSA_FOPAG AS
		SELECT *
			FROM CONNECTION TO DB2
				(SELECT DISTINCT A.CD_CLI
				FROM DB2PGT.CTL_PGTO A
					INNER JOIN DB2SGCEN.FOPAG_180919 B ON(A.CD_CLI=B.CD_CLI)
						WHERE CD_PRD=127 AND CD_MDLD_PRD IN(1, 6) 
							AND DT_EFTC_PGTO BETWEEN '2018-01-01' AND &DT_FIM.
							AND CD_EST_CTL_PGTO IN ('PRO','PRH')
						GROUP BY A.CD_CLI);
	DISCONNECT FROM DB2;
	DROP TABLE DB2SGCEN.FOPAG_180919;
QUIT;


PROC SQL;
	CREATE TABLE RMSS AS
		SELECT DISTINCT CD_CLI
			FROM REMESSA_FOPAG
				ORDER BY 1;
QUIT;


DATA BASE_PGT_PJ;
	MERGE BASE_PGT_PJ(IN=A) RMSS(IN=B);
	BY CD_CLI;
	POSSUI_REMESSA=(A=B);
RUN;


/*********************************/
/*********TABELA PRINCIPAL********/
/*********TABELA PRINCIPAL********/
/*********************************/

PROC SQL;
   CREATE TABLE NOVA_BASE_PGT_PJ AS SELECT DISTINCT CD_CLI, PrefDep, Carteira, TC, VAREJO, CD_CTR_PGTO, DT_CTR_PGTO
   FROM BASE_PGT_PJ
   WHERE POSSUI_REMESSA=1;
QUIT;



/*********************************/
/*********************************/


PROC SQL;
	DROP TABLE DB2SGCEN.FOPAG_180919;
	CREATE TABLE DB2SGCEN.FOPAG_180919 AS
		SELECT DISTINCT CD_CLI Format Z20.
			FROM BASE_PGT_PJ
				WHERE POSSUI_REMESSA=1
					ORDER BY 1;
QUIT;


/*********************************/
/**VER DEPOIS: 1 HORA PRA RODAR***/
/*********************************/

PROC SQL;
	CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
	CREATE TABLE AUX.TBL_PGT AS
		SELECT CD_CLI AS MCI_PAGADOR, DT_EFTC_PGTO, CD_PRF_DEPE_ATU, NR_CC_ATU_BNFC, VL_PGTO, NR_DOC_BNFC_MCI AS MCI_RECEBEDOR,
			IFN(CD_MTV_DOC IN('10' '16'),100,IFN(CD_MTV_DOC='13',102,IFN(CD_MTV_DOC IN('14' '15'),105,101))) AS Finalidade
		FROM CONNECTION TO DB2
			(SELECT DISTINCT t1.*, B.DT_EFTC_PGTO
				FROM DB2PGT.HST_MVT_PGTO t1
					INNER JOIN DB2PGT.CTL_PGTO B ON(t1.CD_CLI=B.CD_CLI AND t1.CD_RMS_PGTO=B.CD_RMS_PGTO AND t1.DT_OGNL_PGTO=B.DT_OGNL_PGTO)
					INNER JOIN DB2SGCEN.FOPAG_180919 C ON(t1.CD_CLI=C.CD_CLI)
                    WHERE t1.CD_EST_PGTO='PRO' AND t1.CD_PRD=127 AND B.DT_EFTC_PGTO>='2018-01-01' AND B.DT_EFTC_PGTO<=&DT_FIM
						
							AND CD_MTV_DOC IN('10', '11', '12', '13', '14', '15', '16', '17'));
	DISCONNECT FROM DB2;
	DROP TABLE DB2SGCEN.FOPAG_180919;
QUIT;


/*********************************/
/*********************************/
/**ANALISE DA FINALIDADE*********/


PROC SQL;
	
	CREATE TABLE MCITESTE AS
		SELECT DISTINCT CD_CLI 
			FROM BASE_PGT_PJ
				WHERE POSSUI_REMESSA=1
					ORDER BY 1;

QUIT;


PROC SQL;
	
	CREATE TABLE TESTE AS
		SELECT DISTINCT T1.CD_CLI, T1.CD_MTV_DOC
		FROM PGT.HST_MVT_PGTO t1
		WHERE T1.CD_MTV_DOC NOT IN ('10', '11', '12', '13', '14', '15', '16', '17') AND t1.CD_EST_PGTO='PRO' AND t1.CD_PRD=127 
;

QUIT;


PROC SQL;
	
	CREATE TABLE TESTE_2 AS
		SELECT DISTINCT T1.CD_CLI, T1.CD_MTV_DOC
		FROM TESTE t1
		INNER JOIN MCITESTE t2 ON T1.CD_CLI = T2.CD_CLI
        WHERE CD_MTV_DOC NOT IN ('10', '11', '12', '13', '14', '15', '16', '17');

QUIT;


/*********************************/
/*********************************/

/**COLOCANDO OS VALORES DO PAGADOR ABAIXO**/

PROC SQL;
CREATE TABLE VALORES_1 AS SELECT DISTINCT t1.MCI_PAGADOR AS CD_CLI, SUM(t1.VL_PGTO) AS VALOR
FROM AUX.TBL_PGT t1
GROUP BY 1
ORDER BY 1;
QUIT;


DATA VALORES_1;
	MERGE ENCARTEIRAMENTO VALORES_1;
	BY CD_CLI;
RUN;


PROC STDIZE DATA=VALORES_1 OUT=VALORES_1 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE VALORES_1 AS SELECT DISTINCT PREFDEP, CARTEIRA, SUM(VALOR) AS VALOR
FROM VALORES_1 t1
GROUP BY 1,2
ORDER BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE VALORES_2 AS SELECT DISTINCT t1.MCI_PAGADOR, t1.VL_PGTO
FROM AUX.TBL_PGT t1
WHERE MONTH(DT_EFTC_PGTO) = MONTH(&D1.) -1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE VALORES_2 AS SELECT DISTINCT t1.MCI_PAGADOR AS CD_CLI, SUM(t1.VL_PGTO) AS VALOR
FROM VALORES_2 t1
GROUP BY 1
ORDER BY 1;
QUIT;


DATA VALORES_2;
	MERGE ENCARTEIRAMENTO VALORES_2;
	BY CD_CLI;
RUN;


PROC STDIZE DATA=VALORES_2 OUT=VALORES_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE VALORES_2 AS SELECT DISTINCT PREFDEP, CARTEIRA, SUM(VALOR) AS VALOR_MES_ANTERIOR
FROM VALORES_2 t1
GROUP BY 1,2
ORDER BY 1,2;
QUIT;


/**COLOCANDO OS VALORES DO PAGADOR ACIMA**/


PROC SQL;
CREATE TABLE BASE_PGT_PJ_2 AS SELECT PrefDep, Carteira, TC, VAREJO, CD_CLI AS MCI_PAGADOR, CD_CTR_PGTO AS NR_CONTRATO, 
DT_CTR_PGTO AS DT_CONTRATO, POSSUI_REMESSA, IFN(POSSUI_REMESSA=1,0,1) AS NAO_POSSUI_REMESSA
FROM BASE_PGT_PJ;
QUIT;


/*PRIMEIRO AGRUPAMENTO*/
PROC SQL;
CREATE TABLE BASE_PGT_PJ_3 AS SELECT PrefDep, Carteira, SUM(POSSUI_REMESSA) AS FOPAG_COM_REMESSA, SUM(NAO_POSSUI_REMESSA) AS FOPAG_SEM_REM, MAX(VAREJO) AS VAREJO
FROM BASE_PGT_PJ_2
GROUP BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_3 AS SELECT DISTINCT t1.PrefDep, t1.Carteira, t1.FOPAG_COM_REMESSA, t1.FOPAG_SEM_REM, t2.VALOR, t3.VALOR_MES_ANTERIOR, t1.VAREJO
FROM BASE_PGT_PJ_3 t1
left join VALORES_1 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
left join VALORES_2 t3 ON t1.PrefDep = t3.PrefDep AND t1.Carteira = t3.Carteira
GROUP BY 1,2;
QUIT;


/*voltar aqui*/
/*voltar aqui*/
/*voltar aqui*/
/*voltar aqui*/
/*voltar aqui*/


PROC SQL;
CREATE TABLE TABELA AS SELECT DISTINCT t1.MCI_RECEBEDOR, MAX(t1.DT_EFTC_PGTO) AS DT_EFTC_PGTO
FROM AUX.TBL_PGT t1
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE NOVA_TAB AS SELECT DISTINCT t1.MCI_RECEBEDOR, t2.MCI_PAGADOR
FROM TABELA t1
LEFT JOIN AUX.TBL_PGT t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR AND t1.DT_EFTC_PGTO = t2.DT_EFTC_PGTO
GROUP BY 1
ORDER BY 1;
QUIT;


/*TRAZENDO PROVENTISTAS*/


PROC SQL;
CREATE TABLE TBL_PGT_2 AS SELECT t2.PrefDep, t2.Carteira, t1.MCI_PAGADOR, COUNT(DISTINCT t1.MCI_RECEBEDOR) AS QTDE_PROVENTISTAS
FROM NOVA_TAB t1
INNER JOIN BASE_PGT_PJ_2 t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1,2,3;
QUIT;



/********************************************************/
/********************************************************/
/**COLOCANDO OS PROVENTISTAS QUE RECEBERAM NO MÊS ANTERIOR**/


PROC SQL;
CREATE TABLE proventistas_mes_atual_1 AS SELECT DISTINCT MCI_PAGADOR, MCI_RECEBEDOR
FROM AUX.TBL_PGT
WHERE MONTH(DT_EFTC_PGTO) = &MES_POSICAO. - 1
ORDER BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE proventistas_mes_atual_2 AS SELECT DISTINCT MCI_PAGADOR, COUNT(MCI_RECEBEDOR) AS QTDE_PROV_MES_ATUAL 
FROM proventistas_mes_atual_1
GROUP BY 1
ORDER BY 1,2;
QUIT;


/****************************************/
/****************************************/

PROC SQL;
CREATE TABLE TBL_PGT_2 AS SELECT t1.PrefDep, t1.Carteira, t1.MCI_PAGADOR, t1.QTDE_PROVENTISTAS, t2.QTDE_PROV_MES_ATUAL
FROM TBL_PGT_2 t1
LEFT JOIN proventistas_mes_atual_2 t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1,2,3;
QUIT;


PROC STDIZE DATA=TBL_PGT_2 OUT=BASE_TBL_PGT_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE TBL_PGT_2 AS SELECT t1.PrefDep, t1.Carteira, SUM(QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(QTDE_PROV_MES_ATUAL) AS QTDE_PROV_MES_ANTERIOR
FROM TBL_PGT_2 t1
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=TBL_PGT_2 OUT=BASE_TBL_PGT_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*SEGUNDO AGRUPAMENTO*/
PROC SQL;
CREATE TABLE BASE_PGT_PJ_4 AS SELECT *
FROM BASE_PGT_PJ_3 t1
LEFT JOIN TBL_PGT_2 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
GROUP BY t1.PrefDep, t1.Carteira;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_4 OUT=BASE_PGT_PJ_4 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*BASE_PGT_PJ_4*/
/*BASE_PGT_PJ_4*/
/*BASE_PGT_PJ_4*/
/*BASE_PGT_PJ_4*/

/*CONTAS CORRENTES NOVAS*/
/*CONTAS CORRENTES NOVAS*/
/*CONTAS CORRENTES NOVAS*/
/*CONTAS CORRENTES NOVAS*/





/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/

PROC SQL;
	CREATE TABLE TABELA_MCI_RECEBEDOR AS
		SELECT DISTINCT MCI_RECEBEDOR
			FROM AUX.TBL_PGT
				ORDER BY 1;
QUIT;


PROC SQL;
                
                         CREATE TABLE CONSULTA_CHEQUE AS SELECT
                        
                         C.DEB307_COD_BDC AS CD_CLI, C.DEB307_AGENCIA AS AGC, C.DEB307_CONTA AS CTA, C.DEB307_DT_ABERTURA AS DT_ABERTURA,
                         A.DT_VNCT, A.CD_PRD, A.CD_MDLD, IFC(A.CD_PRD=6,'CC',IFC(A.CD_PRD=8,'CH','NN')) AS T

                         FROM OPR.CTR_OPR A

                         INNER JOIN DEB.TDEB307 C ON A.CD_PRF_DEPE_CDU=C.DEB307_AGENCIA AND A.NR_CTR_OPR=C.DEB307_CONTA

                         INNER JOIN TABELA_MCI_RECEBEDOR B ON C.DEB307_COD_BDC=B.MCI_RECEBEDOR

						 WHERE A.CD_PRD=8 OR A.CD_PRD=6
                         
                         ORDER BY 1;
                
QUIT;


PROC SQL;
                
                         CREATE TABLE CONSULTA_CHEQUE_1 AS SELECT
                        
                         CD_CLI, AGC, CTA, DT_ABERTURA, DT_VNCT, CD_PRD, CD_MDLD, T 

                         FROM CONSULTA_CHEQUE

                         WHERE  DT_VNCT>=Today() AND DT_ABERTURA BETWEEN '01JAN2018'd AND &D1. 
                         
                         ORDER BY 1;
                
QUIT;


/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/
/***********************************************************/


PROC SQL;
CREATE TABLE PROV_CC_NOVA AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, IFN(t2.CD_CLI IS NOT NULL AND T2.T = 'CC',1,0) AS IND_CONTAS_NOVAS, IFN(t2.CD_CLI IS NOT NULL AND T2.T = 'CH',1,0) AS IND_CHEQUE_NOVO
FROM AUX.TBL_PGT t1
LEFT JOIN CONSULTA_CHEQUE_1 t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI AND CD_PRF_DEPE_ATU = AGC AND NR_CC_ATU_BNFC = CTA
GROUP BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE NOVO_PROV AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, SUM(IND_CONTAS_NOVAS) AS IND_CONTAS_NOVAS, 
SUM(IND_CHEQUE_NOVO) AS IND_CHEQUE_NOVO
FROM NOVA_TAB t1
LEFT JOIN PROV_CC_NOVA t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR AND t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE NOVO_PROV_2 AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, IFN(IND_CONTAS_NOVAS>=1,1,0) AS IND_CONTAS_NOVAS, 
IFN(IND_CHEQUE_NOVO>=1,1,0) AS IND_CHEQUE_NOVO
FROM NOVO_PROV t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE PROV_CC_NOVA_1 AS SELECT DISTINCT t1.MCI_PAGADOR, t2.PrefDep, t2.Carteira, SUM(t1.IND_CONTAS_NOVAS) AS QTDE_CONTAS_NOVAS, SUM(t1.IND_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO
FROM NOVO_PROV_2 t1
LEFT JOIN BASE_PGT_PJ_2 t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1,2;
QUIT;


/*TERCEIRO AGRUPAMENTO*/


PROC SQL;
CREATE TABLE BASE_PGT_PJ_5 AS SELECT t1.PrefDep, t1.Carteira, SUM(t2.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t2.QTDE_CHEQUE_NOVO) as QTDE_CHEQUE_NOVO
FROM BASE_PGT_PJ_4 t1
LEFT JOIN PROV_CC_NOVA_1 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_5 OUT=BASE_PGT_PJ_5 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_6 AS SELECT t1.PrefDep, t1.Carteira, t2.FOPAG_COM_REMESSA, t2.VALOR, t2.VALOR_MES_ANTERIOR, t2.FOPAG_SEM_REM, t2.QTDE_PROVENTISTAS, t1.QTDE_CONTAS_NOVAS, 
t1.QTDE_CHEQUE_NOVO, VAREJO, t2.QTDE_PROVENTISTAS, t2.QTDE_PROV_MES_ANTERIOR
FROM BASE_PGT_PJ_5 t1
LEFT JOIN BASE_PGT_PJ_4 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_6 OUT=BASE_PGT_PJ_6 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*PACOTE*/
/*PACOTE*/
/*PACOTE*/
/*PACOTE*/


/*BASE_PGT_PJ_6*/
/*BASE_PGT_PJ_6*/
/*BASE_PGT_PJ_6*/
/*BASE_PGT_PJ_6*/


PROC SQL;
	DROP TABLE DB2SGCEN.TAB_PROV_77;
	CREATE TABLE DB2SGCEN.TAB_PROV_77 AS
		SELECT CD_PRF_DEPE_ATU FORMAT Z20. AS AGC, NR_CC_ATU_BNFC FORMAT Z20. AS CTA
			FROM AUX.TBL_PGT
            ORDER BY 1,2;
QUIT;


   PROC SQL;
                CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
                CREATE TABLE AUX.BASE_TFA AS
                    SELECT AGENCIA, CONTA, COD_PCTE, DATA_ALTERA, DATA_ENCERRA
                    FROM CONNECTION TO DB2
                        (SELECT DISTINCT t1.T700COD_AGEN AS AGENCIA,
                            t1.T700NMRO_CNTA AS CONTA,
                            t1.T700COD_PCTE AS COD_PCTE,
							t1.T700DATA_ALTERA AS DATA_ALTERA,
                            t1.T700DATA_ENCERR AS DATA_ENCERRA
                            FROM DB2TFA.TTFA700 t1
                            INNER JOIN DB2SGCEN.TAB_PROV_77 t2 on (t1.T700COD_AGEN=t2.AGC and t1.T700NMRO_CNTA=t2.CTA) ) A
                     
					 /*HERE DATA_ALTERA<=&DT_FIM AND DATA_ENCERRA>=&DT_IN*/

                     ORDER BY 1, 2;
                DISCONNECT FROM DB2;
				DROP TABLE DB2SGCEN.TAB_PROV_77;
    QUIT;


/* VALOR DO PACOTE */
/* VALOR DO PACOTE */


PROC SQL;
CREATE TABLE TFA_PACOTE AS SELECT DISTINCT t1.COD_PCTE, T715VLR_TRFA AS VLR_TRFA
FROM AUX.BASE_TFA t1
LEFT JOIN TFA.TTFA715 t2 ON t1.COD_PCTE = t2.T715COD_PCTE
WHERE T2.T715DATA_FIM_VLDD=&DATA_BASE.
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE BASE_TFA_2 AS SELECT *
FROM AUX.BASE_TFA t1
LEFT JOIN TFA_PACOTE t2 ON t1.COD_PCTE = t2.COD_PCTE;
QUIT;


PROC STDIZE DATA=BASE_TFA_2 OUT=BASE_TFA_2 REPONLY MISSING=0;
VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_TFA_3 AS SELECT DISTINCT MCI_PAGADOR, MCI_RECEBEDOR, VLR_TRFA
FROM AUX.TBL_PGT t1
LEFT JOIN BASE_TFA_2 t2 ON t1.CD_PRF_DEPE_ATU= t2.AGENCIA AND t1.NR_CC_ATU_BNFC = t2.CONTA
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_TFA_3 OUT=BASE_TFA_3 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_TFA_3_B AS SELECT DISTINCT t1.MCI_PAGADOR, t1.MCI_RECEBEDOR, VLR_TRFA
FROM NOVA_TAB t1
LEFT JOIN BASE_TFA_3 t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR AND t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE BASE_TFA_4 AS SELECT DISTINCT MCI_PAGADOR, SUM(VLR_TRFA) AS VL_TRFA
FROM BASE_TFA_3_B t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE BASE_TFA_5 AS SELECT DISTINCT t1.MCI_PAGADOR, PrefDep, Carteira, VL_TRFA
FROM PROV_CC_NOVA_1 t1
LEFT JOIN BASE_TFA_4 t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE BASE_TFA_6 AS SELECT DISTINCT PrefDep, Carteira, SUM(VL_TRFA) AS VL_TRFA
FROM BASE_TFA_5 t1
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_TFA_6 OUT=BASE_TFA_6 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_TFA_7 AS SELECT DISTINCT *
FROM BASE_TFA_6 t1
WHERE PrefDep <>0
GROUP BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_7 AS SELECT *
FROM BASE_PGT_PJ_6 t1
LEFT JOIN BASE_TFA_7 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_7 OUT=BASE_PGT_PJ_7 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*CDC*/
/*CDC*/
/*CDC*/


PROC SQL;

CREATE TABLE CLIENTES_FOPAG AS
SELECT DISTINCT MCI_RECEBEDOR
FROM AUX.TBL_PGT
ORDER BY 1;

QUIT;


PROC SQL;
CREATE TABLE OPER_CDC AS SELECT t2.CD_CLI, t2.NR_CTR_OPR, t2.CD_PRD_LNCD, t2.CD_MDLD_PRD_LNCD, t2.CD_LNCD, t2.DT_FRMZ_CTR_CDC, t2.vlr_TOT_DESEMBOLSO,
IFC(t2.CD_PRD_LNCD=52 AND t2.CD_MDLD_PRD_LNCD=53,'CDC_ECF',
IFC(t2.CD_PRD_LNCD=52 AND t2.CD_MDLD_PRD_LNCD=29,'CDC_SAL','CDC_OUTROS')) AS TIPO_CDC

FROM CLIENTES_FOPAG t1
INNER JOIN CDC2.cdc_saldo_cdc t2 ON t1.MCI_RECEBEDOR=t2.CD_CLI

WHERE t2.DT_FRMZ_CTR_CDC>='01JAN2018'd AND t2.DT_FRMZ_CTR_CDC<&D1 
ORDER BY 1;
QUIT;


/*novo_codigo*/

PROC SQL;
CREATE TABLE OPER_CDC_2_SEP_ANTE AS SELECT DISTINCT t1.CD_CLI, t1.TIPO_CDC, t1.VLR_TOT_DESEMBOLSO
FROM OPER_CDC t1
WHERE t1.TIPO_CDC='CDC_ECF'
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE OPER_CDC_2_SEP_1 AS SELECT DISTINCT t1.CD_CLI, SUM(t1.VLR_TOT_DESEMBOLSO) AS VL_CDC_ECF
FROM OPER_CDC_2_SEP_ANTE t1
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE OPER_CDC_2_SEP_2_ANTE AS SELECT DISTINCT t1.CD_CLI, t1.TIPO_CDC, t1.VLR_TOT_DESEMBOLSO
FROM OPER_CDC t1
WHERE t1.TIPO_CDC='CDC_SAL'
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE OPER_CDC_2_SEP_2 AS SELECT DISTINCT t1.CD_CLI, SUM(t1.VLR_TOT_DESEMBOLSO) AS VL_CDC_SAL 
FROM OPER_CDC_2_SEP_2_ANTE t1
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE OPER_CDC_2_SEP_3_ANTE AS SELECT DISTINCT t1.CD_CLI, t1.TIPO_CDC, t1.VLR_TOT_DESEMBOLSO
FROM OPER_CDC t1
WHERE t1.TIPO_CDC <>'CDC_ECF' and t1.TIPO_CDC <>'CDC_SAL'
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE OPER_CDC_2_SEP_3 AS SELECT DISTINCT t1.CD_CLI, SUM(t1.VLR_TOT_DESEMBOLSO) AS VL_CDC_OUTROS 
FROM OPER_CDC_2_SEP_3_ANTE t1
GROUP BY 1
ORDER BY 1;
QUIT;


DATA OPER_CDC_2;
MERGE OPER_CDC_2_SEP_1 OPER_CDC_2_SEP_2 OPER_CDC_2_SEP_3;
BY CD_CLI;
RUN;


PROC STDIZE DATA=OPER_CDC_2 OUT=OPER_CDC_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*fim novo_codigo*/


PROC SQL;
CREATE TABLE CLIENTES_FOPAG_2 AS
SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR
FROM NOVA_TAB t1
LEFT JOIN AUX.TBL_PGT t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR AND t1.MCI_PAGADOR = t2.MCI_RECEBEDOR
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE OPER_CDC_3 AS SELECT DISTINCT *
FROM OPER_CDC_2 t1
LEFT JOIN CLIENTES_FOPAG_2 t2 ON t1.CD_CLI = t2.MCI_RECEBEDOR;
QUIT;


PROC SQL;
CREATE TABLE OPER_CDC_4 AS SELECT DISTINCT MCI_PAGADOR, SUM(VL_CDC_ECF) AS VL_CDC_ECF, SUM(VL_CDC_SAL) AS VL_CDC_SAL,  SUM(VL_CDC_OUTROS) AS VL_CDC_OUTROS
FROM OPER_CDC_3 t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE BASE_CARTEIRA AS SELECT DISTINCT t1.MCI_PAGADOR, t1.PrefDep, t1.Carteira, t2.VL_CDC_ECF, t2.VL_CDC_SAL, t2.VL_CDC_OUTROS
FROM PROV_CC_NOVA_1 t1
LEFT JOIN OPER_CDC_4 t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1;
QUIT;


PROC STDIZE DATA=BASE_CARTEIRA OUT=BASE_CARTEIRA REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_8 AS SELECT PrefDep, Carteira, sum(VL_CDC_ECF) as VL_CDC_ECF, sum(VL_CDC_SAL) as VL_CDC_SAL, sum(VL_CDC_OUTROS) as VL_CDC_OUTROS
FROM BASE_CARTEIRA
GROUP BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_9 AS SELECT *
FROM BASE_PGT_PJ_7 t1
LEFT JOIN BASE_PGT_PJ_8 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_9 OUT=BASE_PGT_PJ_9 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/****************************************/

/*Fatura cartão*/
/*Fatura cartão*/
/*Fatura cartão*/
/*Fatura cartão*/


/*COMPRAS A VISTA*/
proc sql;
                connect to db2 (authdomain=db2sgcen database=bdb2p04);
                create table CRED_COMP_VISTA as
                    select * from connection to db2

                    (select

                        t2.cd_cli,
                        t2.cd_mdld_crt,
                        MAX(t1.dt_mvt_ct_crt) as DATA_UTLZ,
                        SUM(t1.vl_mvt_ct_crt) as VALOR

                    from db2vip.mvt_ct_crt t1,
				        db2vip.ct_crt t2,
                        db2vip.ettc_item t3,
                        db2vip.fat_ct_crt t4,
                        db2vip.tip_tran t5

                    where (t1.nr_seql_fat_ct_crt = t4.nr_seql_fat_ct_crt
                        and t4.nr_ctr_opr_ct_crt = t2.nr_ct_crt
						and t1.cd_tip_tran = t5.cd_tran)
                        and t5.cd_item_ettc = t3.cd_item_ettc 

						and t3.cd_item_ettc in (27, 28, 29, 31, 32, 33)
                        and t1.dt_mvt_ct_crt >= '2018-01-01'
                        and t1.dt_mvt_ct_crt <= &LMT. 
                   
                        

                    group by t2.cd_cli, t2.cd_mdld_crt);

                disconnect from db2;

            quit;


/*PAGAMENTO DE CONTAS*/
 proc sql;
                connect to db2 (authdomain=db2sgcen database=bdb2p04);
                create table CRED_PAG_CONTA as
                    select * from connection to db2
                    (select distinct

                        t2.cd_cli,    
                        t2.cd_mdld_crt,
                        max(t1.dt_pgto_ct) as DATA_UTLZ,
                        sum(t1.vl_pgto_rlzd) as VALOR

                    from db2vip.pgto_ct_pcl_unco t1
                    inner join db2vip.ct_crt t2 on (t1.nr_ct_crt = t2.nr_ct_crt)
                            
                            where dt_pgto_ct >= '2018-01-01'  and dt_pgto_ct <= &LMT. 

                            group by t2.cd_cli, t2.cd_mdld_crt);

                disconnect from db2;

 quit;


/*CONTAS PARCELADAS*/
 proc sql;
                connect to db2 (authdomain=db2sgcen database=bdb2p04);
                create table CRED_CONTA_PARC as
                    select * from connection to db2

                        (select
                        t2.cd_cli,
                        t2.cd_mdld_crt,
                        max(t1.DT_CPR) as data_utlz,
                        sum(t1.vl_cpr_real) as valor

                    from db2vip.cpr_pcld t1
                        inner join db2vip.ct_crt t2 on (t1.nr_ct_crt = t2.nr_ct_crt)

                           WHERE t1.DT_CPR >= '2018-01-01' and t1.DT_CPR <= &LMT.

                                and t1.tip_tran in ( '01', '02', '51', '52', '53' )


                            group by t2.cd_cli, t2.cd_mdld_crt);
                disconnect from db2;
            quit;


			proc sql;
                create table FATURA_CRED as
                    select * from CRED_COMP_VISTA
                        outer union corr
                            select * from CRED_PAG_CONTA
                                outer union corr
                                    select * from CRED_CONTA_PARC;
            quit;


/*AGRUPANDO*/

PROC SQL;

CREATE TABLE CLIENTES_FOPAG_27 AS
SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR
FROM NOVA_TAB t1
INNER JOIN AUX.TBL_PGT t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR AND t1.MCI_PAGADOR = t2.MCI_PAGADOR
ORDER BY 1;

QUIT;


PROC SQL;
CREATE TABLE CRED_DES AS
SELECT MCI_RECEBEDOR, VALOR
FROM CLIENTES_FOPAG_27 t1
LEFT JOIN FATURA_CRED t2 ON t1.MCI_RECEBEDOR = t2.cd_cli
GROUP BY 1
ORDER BY 1;
QUIT;


PROC STDIZE DATA=CRED_DES OUT=CRED_DES REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

CREATE TABLE CRED_DES_2 AS
SELECT DISTINCT MCI_RECEBEDOR, SUM(VALOR) AS VALOR
FROM CRED_DES t1
GROUP BY 1;

QUIT;


PROC SQL;
CREATE TABLE CRED_DES_3 AS SELECT DISTINCT MCI_PAGADOR, VALOR AS VALOR_FATURA 
FROM CRED_DES_2 t1
LEFT JOIN CLIENTES_FOPAG_27 t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR;
QUIT;


PROC SQL;
CREATE TABLE BASE_CARTEIRA_2 AS SELECT DISTINCT t1.MCI_PAGADOR, t1.PrefDep, t1.Carteira, t2.VALOR_FATURA
FROM PROV_CC_NOVA_1 t1
LEFT JOIN CRED_DES_3 t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_10 AS SELECT PrefDep, Carteira, sum(VALOR_FATURA) as VALOR_FATURA
FROM BASE_CARTEIRA_2
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_10 OUT=BASE_PGT_PJ_10 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_11 AS SELECT *
FROM BASE_PGT_PJ_9 t1
LEFT JOIN BASE_PGT_PJ_10 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
GROUP BY 1,2;
QUIT;

PROC STDIZE DATA=BASE_PGT_PJ_11 OUT=BASE_PGT_PJ_11 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;




/****************************************/


/*LOB VAI*/
/*LOB VAI*/
/*LOB VAI*/
/*LOB VAI*/


PROC SQL;

DROP TABLE DB2SGCEN.CLIENTES_FOPAG_54;
CREATE TABLE DB2SGCEN.CLIENTES_FOPAG_54 AS
SELECT DISTINCT MCI_RECEBEDOR Format Z20.
FROM AUX.TBL_PGT
GROUP BY 1
ORDER BY 1;

QUIT;


PROC SQL;

CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
CREATE TABLE LOB_VAI_BASE_NOVO AS SELECT DISTINCT MCI_RECEBEDOR, CD_TIP_OPC_BCRO, TS_RCBT_SLR
FROM CONNECTION TO DB2 
(SELECT DISTINCT t1.MCI_RECEBEDOR, t2.CD_TIP_OPC_BCRO, t2.TS_RCBT_SLR
FROM DB2SGCEN.CLIENTES_FOPAG_54 t1
LEFT JOIN DB2CRS.RCBT_SLR_FUN t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI
WHERE t2.CD_TIP_OPC_BCRO = 4) 

/*WHERE DATEPART(TS_RCBT_SLR)>= 2018-10-01 AND DATEPART(TS_RCBT_SLR)<= 2018-10-08*/

GROUP BY 1
ORDER BY 1;
DISCONNECT FROM DB2;
DROP TABLE DB2SGCEN.CLIENTES_FOPAG_54;
   
QUIT;


PROC SQL;

CREATE TABLE LOB_VAI_BASE_2 AS
SELECT DISTINCT MCI_RECEBEDOR, CD_TIP_OPC_BCRO, TS_RCBT_SLR
FROM LOB_VAI_BASE_NOVO
WHERE YEAR(DATEPART(TS_RCBT_SLR)) = 2018 AND DATEPART(TS_RCBT_SLR) < TODAY()
GROUP BY 1
ORDER BY 1;

/*MONTH(DATEPART(TS_RCBT_SLR)) = &MES_POSICAO. AND*/

QUIT;


PROC SQL;

CREATE TABLE CLIENTES_FOPAG_63 AS
SELECT DISTINCT MCI_RECEBEDOR
FROM AUX.TBL_PGT
GROUP BY 1
ORDER BY 1;

QUIT;


/*LOB VAI FINAL*/
PROC SQL;

CREATE TABLE LOB_VAI_BASE_FINAL AS
SELECT DISTINCT t1.MCI_RECEBEDOR, IFN(CD_TIP_OPC_BCRO=4,1,0) AS LOB_VAI
FROM CLIENTES_FOPAG_63 t1
LEFT JOIN LOB_VAI_BASE_2 t2 on t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR
GROUP BY 1
ORDER BY 1;

QUIT;


PROC SQL;
CREATE TABLE LOB_VAI_BASE_FINAL_2 AS SELECT DISTINCT T2.MCI_PAGADOR, SUM(T1.LOB_VAI) AS LOB_VAI
FROM LOB_VAI_BASE_FINAL t1
LEFT JOIN CLIENTES_FOPAG_2 t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE BASE_CARTEIRA_4 AS SELECT DISTINCT t1.MCI_PAGADOR, t1.PrefDep, t1.Carteira, t2.LOB_VAI
FROM PROV_CC_NOVA_1 t1
LEFT JOIN LOB_VAI_BASE_FINAL_2 t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_12 AS SELECT PrefDep, Carteira, sum(LOB_VAI) as LOB_VAI
FROM BASE_CARTEIRA_4
GROUP BY 1,2;
QUIT;

PROC STDIZE DATA=BASE_PGT_PJ_12 OUT=BASE_PGT_PJ_12 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_12 AS SELECT PrefDep, Carteira, LOB_VAI
FROM BASE_PGT_PJ_12
WHERE PrefDep <>0
GROUP BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_14 AS SELECT t1.PrefDep, t1.Carteira AS CTRA, FOPAG_COM_REMESSA, FOPAG_SEM_REM, QTDE_PROVENTISTAS,
QTDE_CONTAS_NOVAS, VL_TRFA, VL_CDC_ECF, VL_CDC_SAL, VL_CDC_OUTROS, VALOR_FATURA, QTDE_CHEQUE_NOVO, LOB_VAI, T1.VAREJO, T1.QTDE_PROV_MES_ANTERIOR,
VALOR, VALOR_MES_ANTERIOR
FROM BASE_PGT_PJ_11 t1
LEFT JOIN BASE_PGT_PJ_12 t2 ON t1.PrefDep = t2.PrefDep AND t1.Carteira = t2.Carteira
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_14 OUT=BASE_PGT_PJ_14 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


data BASE_PGT_PJ_14;
format posicao yymmdd10.;
set BASE_PGT_PJ_14;
posicao = &D1;
run;


PROC STDIZE DATA=BASE_PGT_PJ_14 OUT=BASE_PGT_PJ_14 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE BASE_PGT_PJ_15 AS SELECT t1.posicao, t1.PrefDep, t1.CTRA, t1.FOPAG_COM_REMESSA, t1.FOPAG_SEM_REM, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI, T1.QTDE_PROV_MES_ANTERIOR
, VALOR, VALOR_MES_ANTERIOR
FROM BASE_PGT_PJ_14 t1
WHERE VAREJO = 1
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=BASE_PGT_PJ_15 OUT=BASE_PGT_PJ_15 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



/*********************************************/
/*********************************************/
/*********************************************/


/*TABELA COLUNAS PARA FUNCAO SUMARIZACAO*/

PROC SQL;
DROP TABLE COLUNAS_SUMARIZAR;
CREATE TABLE COLUNAS_SUMARIZAR (Coluna CHAR(50), Tipo CHAR(10));
INSERT INTO COLUNAS_SUMARIZAR VALUES ('FOPAG_COM_REMESSA', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('FOPAG_SEM_REM', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_PROVENTISTAS', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_CONTAS_NOVAS', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_TRFA', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_CDC_ECF', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_CDC_SAL', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_CDC_OUTROS', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_FATURA', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_CHEQUE_NOVO', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('LOB_VAI', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_PROV_MES_ANTERIOR', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_MES_ANTERIOR', 'SUM');
QUIT;


/*FUNCAO DE SUMARIZACAO*/ 
%SumarizadorCNX( TblSASValores=BASE_PGT_PJ_15,  TblSASColunas=COLUNAS_SUMARIZAR,  NivelCTRA=1,  PAA_PARA_AGENCIA=1,  TblSaida=BASE_PGT_PJ_15, AAAAMM=&ANOMES.); 


PROC SQL;
CREATE TABLE BASE_PGT_PJ_20 AS SELECT t1.posicao, t1.PrefDep as prefixo, t1.CTRA as carteira, t1.FOPAG_COM_REMESSA, t1.FOPAG_SEM_REM, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI, t1.QTDE_PROV_MES_ANTERIOR,
VALOR, VALOR_MES_ANTERIOR
FROM BASE_PGT_PJ_15 t1;
QUIT;


/********************************************************************/
/*******************************ATACADO*****************************/
/********************************************************************/

PROC SQL;
CREATE TABLE ATACADO AS SELECT t1.posicao, t1.PrefDep, t1.CTRA, t1.FOPAG_COM_REMESSA, t1.FOPAG_SEM_REM, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI, t1.QTDE_PROV_MES_ANTERIOR,
VALOR, VALOR_MES_ANTERIOR
FROM BASE_PGT_PJ_14 t1
WHERE VAREJO = 0
GROUP BY 1,2;
QUIT;


PROC STDIZE DATA=ATACADO OUT=ATACADO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



/*********************************************/
/*********************************************/
/*********************************************/



PROC SQL;
CREATE TABLE ATACADO_1 AS SELECT t1.posicao, t1.PrefDep, t1.CTRA, t1.FOPAG_COM_REMESSA, t1.FOPAG_SEM_REM, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI,
t2.NomeDep, t2.PrefSureg, t2.PrefSuper, t2.PrefDir, t2.PrefVice, T1.QTDE_PROV_MES_ANTERIOR, VALOR, VALOR_MES_ANTERIOR
FROM ATACADO t1
LEFT JOIN COMUM.DEPENDENCIAS t2 ON t1.PrefDep = input(t2.PREFDEP, 4.)
where t2.SB = "00" 
GROUP BY 1,2,3;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_AGENCIA AS SELECT DISTINCT t1.PrefDep, 0 as CTRA, SUM(t1.FOPAG_COM_REMESSA) AS FOPAG_COM_REMESSA, 
SUM(t1.FOPAG_SEM_REM) AS FOPAG_SEM_REM, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR) AS VALOR, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1 t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_GEREV AS SELECT DISTINCT INPUT(t1.PrefSureg, 4.) as PrefDep, 0 as CTRA, SUM(t1.FOPAG_COM_REMESSA) AS FOPAG_COM_REMESSA, 
SUM(t1.FOPAG_SEM_REM) AS FOPAG_SEM_REM, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR) AS VALOR, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1 t1
WHERE PrefSureg <> "0000"
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_SUPER AS SELECT DISTINCT INPUT(t1.PrefSuper, 4.) as PrefDep, 0 as CTRA, SUM(t1.FOPAG_COM_REMESSA) AS FOPAG_COM_REMESSA, 
SUM(t1.FOPAG_SEM_REM) AS FOPAG_SEM_REM, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR) AS VALOR, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1 t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_DIR AS SELECT DISTINCT INPUT(t1.PrefDir, 4.) as PrefDep, 0 as CTRA, SUM(t1.FOPAG_COM_REMESSA) AS FOPAG_COM_REMESSA, 
SUM(t1.FOPAG_SEM_REM) AS FOPAG_SEM_REM, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR) AS VALOR, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1 t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_VICE AS SELECT DISTINCT INPUT(t1.PrefVice, 4.) as PrefDep, 0 as CTRA, SUM(t1.FOPAG_COM_REMESSA) AS FOPAG_COM_REMESSA, 
SUM(t1.FOPAG_SEM_REM) AS FOPAG_SEM_REM, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR) AS VALOR, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1 t1
GROUP BY 1;
QUIT;


DATA ATACADO_FINAL;
	MERGE ATACADO_AGENCIA ATACADO_GEREV ATACADO_SUPER ATACADO_DIR ATACADO_VICE;
	BY PrefDep;	
RUN;


data ATACADO_FINAL;
format posicao yymmdd10.;
set ATACADO_FINAL;
posicao = &D1;
run;


PROC SQL;
CREATE TABLE ATACADO_FINAL AS SELECT *
FROM ATACADO t1
UNION SELECT *
FROM ATACADO_FINAL;
QUIT;



PROC SQL;
CREATE TABLE BASE_PGT_PJ_30 AS SELECT t1.posicao, t1.PrefDep as prefixo, t1.CTRA as carteira, t1.FOPAG_COM_REMESSA, t1.FOPAG_SEM_REM, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI, T1.QTDE_PROV_MES_ANTERIOR,
t1.VALOR, t1.VALOR_MES_ANTERIOR
FROM ATACADO_FINAL t1;
QUIT;


/*UNINDO AS TABELAS*/


proc sql;
                create table BASE_PGT_PJ_40 as
                    select * from BASE_PGT_PJ_20
                        outer union corr
                            select * from BASE_PGT_PJ_30;
quit;


PROC STDIZE DATA=BASE_PGT_PJ_40 OUT=BASE_PGT_PJ_40 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



/********************************************************************/
/********************************************************************/
/********************************************************************/
/*****************************DETALHES*******************************/
/********************************************************************/
/********************************************************************/
/********************************************************************/


PROC SQL;
CREATE TABLE DETALHES AS SELECT PREFDEP, CARTEIRA, VAREJO, MCI_PAGADOR
FROM BASE_PGT_PJ_2
WHERE POSSUI_REMESSA = 1 
GROUP BY 1,2
ORDER BY 1,2;
QUIT;


PROC STDIZE DATA=DETALHES OUT=DETALHES REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_2 AS SELECT t2.PREFDEP, t2.CARTEIRA, t2.VAREJO, t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, t1.VL_PGTO
FROM AUX.TBL_PGT t1
INNER JOIN DETALHES t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
WHERE t1.fINALIDADE IN (100,101,102,105)
GROUP BY 1,2
ORDER BY 1,2;
QUIT;


PROC STDIZE DATA=DETALHES_2 OUT=DETALHES_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_3 AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, t1.PREFDEP, t1.CARTEIRA, t1.VAREJO, SUM(t1.VL_PGTO) AS VL_PGTO
FROM DETALHES_2 t1
GROUP BY 1, 2
ORDER BY 2,3,1;
QUIT;


/*TARIFAS*/


PROC SQL;
CREATE TABLE MCI_PACOTE AS SELECT MCI_RECEBEDOR, VLR_TRFA
FROM BASE_TFA_3 t1
GROUP BY 1,2
ORDER BY 1;
QUIT;


PROC STDIZE DATA=MCI_PACOTE OUT=MCI_PACOTE REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE MCI_PACOTE_2 AS SELECT DISTINCT MCI_RECEBEDOR, SUM(VLR_TRFA) AS VLR_TRFA
FROM MCI_PACOTE t1
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_4 AS SELECT DISTINCT *
FROM DETALHES_3 t1
LEFT JOIN MCI_PACOTE_2 t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR
GROUP BY 1
ORDER BY 1;
QUIT;


PROC STDIZE DATA=DETALHES_4 OUT=DETALHES_4 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*LOB*/


PROC SQL;
CREATE TABLE DETALHES_5 AS SELECT DISTINCT * 
FROM DETALHES_4 t1
LEFT JOIN LOB_VAI_BASE_FINAL t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR
GROUP BY 1
ORDER BY 1;
QUIT;


PROC STDIZE DATA=DETALHES_5 OUT=DETALHES_5 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*CDC*/


PROC STDIZE DATA=OPER_CDC_2 OUT=OPER_CDC_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



PROC SQL;
CREATE TABLE DETALHES_6 AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, t1.PREFDEP, t1.CARTEIRA, t1.VAREJO, t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI, t2.VL_CDC_ECF, t2.VL_CDC_SAL, t2.VL_CDC_OUTROS
FROM DETALHES_5 t1
LEFT JOIN OPER_CDC_2 t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI
GROUP BY 1
order by 1;
QUIT;


PROC STDIZE DATA=DETALHES_6 OUT=DETALHES_6 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_7 AS SELECT DISTINCT t1.PREFDEP as prefixo, t1.CARTEIRA, t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, 
t1.VL_CDC_OUTROS, T1.VAREJO
FROM DETALHES_6 t1
GROUP BY 3
order by 1,2;
QUIT;


/*encarteiramento*/


PROC SQL;
	CREATE TABLE BASE_MCI_2 AS
		SELECT DISTINCT MCI_RECEBEDOR as CD_CLI
			FROM DETALHES_7
				ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_8 AS SELECT DISTINCT t1.prefixo, t1.CARTEIRA, t2.CD_PRF_DEPE AS PREFIXO_RECEB, t2.NR_SEQL_CTRA_ATB AS CARTEIRA_RECEB, t1.MCI_RECEBEDOR, 
t1.MCI_PAGADOR, t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, T1.VAREJO
FROM DETALHES_7 t1
LEFT JOIN COMUM.PAI_REL_&ANOMES. t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI;
QUIT;


PROC STDIZE DATA=DETALHES_8 OUT=DETALHES_8 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_11 AS SELECT DISTINCT t1.prefixo, t1.CARTEIRA, t1.MCI_PAGADOR, t1.PREFIXO_RECEB, t1.CARTEIRA_RECEB, t1.MCI_RECEBEDOR, 
t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VAREJO, count(t1.PREFIXO_RECEB) as CONTA
FROM DETALHES_8 t1
group by 6;
QUIT;


/*CONTATOS*/


PROC SQL;
        CREATE TABLE GESTAO_BIC_ATU AS SELECT t1.CD_CLI, t1.TS_INRO_CLI, t1.CD_TRAN_INRO_SIS, t2.CD_FMA_CTT FROM BIC.AUX_INRO_CLI_ATU t1
        LEFT join BIC.INRO_HMNO_CLI t2 on (t1.CD_CLI = t2.CD_CLI AND t1.TS_INRO_CLI = t2.TS_INRO_CLI)

        WHERE CD_TRAN_INRO_SIS IN ('BIC00005', 'COC02', 'REL02', 'REL10', 'REL04', 'SMI02', 'SMI03', 'SMI04', 'MIV10011', 'MIV10012', 'SMI10001', 'CPG009', 'BPR00013',
        'BPR00018', 'BPR00019', 'SOL954', 'RDO00010', 'GFI00004', 'GFI00005', 'GFI00035', 'ACO00005', 'ACO00006', 'ACO00109', 'ACO005', 'GAT2')

        AND t2.CD_FMA_CTT NOT IN (5);
QUIT;


PROC SQL;
        CREATE TABLE GESTAO_BIC_ANT AS SELECT t1.CD_CLI, t1.TS_INRO_CLI, t1.CD_TRAN_INRO_SIS, t2.CD_FMA_CTT FROM BIC.AUX_INRO_CLI_ANT t1
        LEFT join BIC.INRO_HMNO_CLI t2 on (t1.CD_CLI = t2.CD_CLI AND t1.TS_INRO_CLI = t2.TS_INRO_CLI)

        WHERE CD_TRAN_INRO_SIS IN ('BIC00005', 'COC02', 'REL02', 'REL10', 'REL04', 'SMI02', 'SMI03', 'SMI04', 'MIV10011', 'MIV10012', 'SMI10001', 'CPG009', 'BPR00013',
        'BPR00018', 'BPR00019', 'SOL954', 'RDO00010', 'GFI00004', 'GFI00005', 'GFI00035', 'ACO00005', 'ACO00006', 'ACO00109', 'ACO005', 'GAT2')

        AND t2.CD_FMA_CTT NOT IN (5);
QUIT;


PROC SQL;
	CREATE TABLE BASE_MCI_5 AS
		SELECT DISTINCT MCI_RECEBEDOR as CD_CLI
			FROM DETALHES_11
				ORDER BY 1;
QUIT;


PROC SQL;
        CREATE TABLE GESTAO_BIC_2 AS SELECT * FROM GESTAO_BIC_ATU t1
        INNER join BASE_MCI_5 t2 on (t1.CD_CLI = t2.CD_CLI);
QUIT;


PROC SQL;
        CREATE TABLE GESTAO_BIC_3 AS SELECT DISTINCT CD_CLI, COUNT(CD_CLI) AS NR_CONTATO FROM GESTAO_BIC_2 t1
        GROUP BY CD_CLI;
QUIT;


PROC SQL;
        CREATE TABLE GESTAO_BIC_2_B AS SELECT * FROM GESTAO_BIC_ANT t1
        INNER join BASE_MCI_5 t2 on (t1.CD_CLI = t2.CD_CLI);
QUIT;


PROC SQL;
        CREATE TABLE GESTAO_BIC_3_B AS SELECT DISTINCT CD_CLI, COUNT(CD_CLI) AS NR_CONTATO_ANT FROM GESTAO_BIC_2_B t1
        GROUP BY CD_CLI;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_12 AS SELECT DISTINCT t1.prefixo, t1.CARTEIRA, t1.MCI_PAGADOR, t1.PREFIXO_RECEB, t1.CARTEIRA_RECEB, t1.MCI_RECEBEDOR, 
t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VAREJO, t2.NR_CONTATO
FROM DETALHES_11 t1
LEFT JOIN GESTAO_BIC_3 t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI;
QUIT;


PROC STDIZE DATA=DETALHES_12 OUT=DETALHES_12 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE DETALHES_12_B AS SELECT DISTINCT t1.prefixo, t1.CARTEIRA, t1.MCI_PAGADOR, t1.PREFIXO_RECEB, t1.CARTEIRA_RECEB, t1.MCI_RECEBEDOR, 
t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VAREJO, t1.NR_CONTATO, t2.NR_CONTATO_ANT
FROM DETALHES_12 t1
LEFT JOIN GESTAO_BIC_3_B t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI;
QUIT;


PROC STDIZE DATA=DETALHES_12_B OUT=DETALHES_12_B REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/***/


PROC SQL;
CREATE TABLE DET_VAR AS SELECT DISTINCT t1.prefixo, t1.carteira, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, 
t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.PREFIXO_RECEB, t1.CARTEIRA_RECEB, t1.MCI_PAGADOR, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DETALHES_12_B t1
WHERE t1.VAREJO = 1;
QUIT;


PROC STDIZE DATA=DET_VAR OUT=DET_VAR REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



PROC STDIZE DATA=DET_VAR OUT=DET_VAR_PAGADOR REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



/*DET_VAR INVERTENDO O ENCARTEIRAMENTO*/


PROC SQL;
CREATE TABLE DET_VAR AS SELECT DISTINCT t1.PREFIXO_RECEB AS prefixo, t1.CARTEIRA_RECEB AS carteira, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, 
t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.prefixo AS PREFIXO_RECEB, t1.carteira AS CARTEIRA_RECEB, t1.MCI_PAGADOR, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DET_VAR t1
WHERE t1.PREFIXO_RECEB <> 0 AND t1.CARTEIRA_RECEB <> 0;
QUIT;

/*FIM*/

/**********************************************/

/*Deixando apenas os clientes que receberam no mes*/

PROC SQL;
CREATE TABLE proventistas_mes_atual_detalhes AS SELECT DISTINCT MCI_RECEBEDOR
FROM AUX.TBL_PGT
WHERE MONTH(DT_EFTC_PGTO) = &MES_POSICAO.
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE DET_VAR AS SELECT DISTINCT t1.prefixo, t1.carteira, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI,
t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.PREFIXO_RECEB, t1.CARTEIRA_RECEB, t1.MCI_PAGADOR, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DET_VAR t1
INNER JOIN proventistas_mes_atual_detalhes t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR;
QUIT;




/*DETALHES DO ATACADO*/

PROC SQL;
CREATE TABLE DET_ATA AS SELECT DISTINCT t1.PREFIXO, t1.CARTEIRA, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, 
t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.PREFIXO_RECEB, T1.CARTEIRA_RECEB, t1.MCI_PAGADOR, NR_CONTATO, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DETALHES_12_B t1
WHERE T1.VAREJO = 0;
QUIT;


PROC STDIZE DATA=DET_ATA OUT=DET_ATA REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC STDIZE DATA=DET_ATA OUT=DET_ATA_PAGADOR REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE DET_ATA_PAGADOR AS SELECT DISTINCT t1.PREFIXO_RECEB as PREFIXO, T1.CARTEIRA_RECEB AS CARTEIRA, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, 
t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.PREFIXO AS PREFIXO_RECEB, t1.CARTEIRA AS CARTEIRA_RECEB, t1.MCI_PAGADOR, NR_CONTATO, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DET_ATA_PAGADOR t1;
QUIT;






/*****************************/
/*DET_ATA INVERTENDO O ENCARTEIRAMENTO*/


PROC SQL;
CREATE TABLE DET_ATA AS SELECT DISTINCT t1.PREFIXO_RECEB AS prefixo, t1.CARTEIRA_RECEB AS carteira, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, 
t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.prefixo AS PREFIXO_RECEB, t1.carteira AS CARTEIRA_RECEB, t1.MCI_PAGADOR, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DET_ATA t1
WHERE t1.PREFIXO_RECEB <> 0 AND t1.CARTEIRA_RECEB <> 0;
QUIT;


/*Deixando apenas os clientes que receberam no mes*/


PROC SQL;
CREATE TABLE DET_ATA AS SELECT DISTINCT t1.prefixo, t1.carteira, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, t1.LOB_VAI,
t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.PREFIXO_RECEB, t1.CARTEIRA_RECEB, t1.MCI_PAGADOR, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DET_ATA t1
INNER JOIN proventistas_mes_atual_detalhes t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR;
QUIT;


/*FIM*/


PROC SQL;
CREATE TABLE DET_JUNTOS AS SELECT DISTINCT t1.prefixo, t1.carteira, t1.MCI_RECEBEDOR, t1.VL_PGTO, t1.VLR_TRFA, 
t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.PREFIXO_RECEB, t1.CARTEIRA_RECEB, t1.MCI_PAGADOR, t1.NR_CONTATO, t1.NR_CONTATO_ANT
FROM DETALHES_12_B t1
;
QUIT;




/******************************************************************/
/******************************************************************/
/******************************************************************/
/************ FOPAG VAREJO ENCARTEIRADO MCI RECEBEDOR *************/
/******************************************************************/
/******************************************************************/
/******************************************************************/


/**COLOCANDO OS VALORES DO PAGADOR ABAIXO**/


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_1 AS SELECT DISTINCT t1.MCI_RECEBEDOR, SUM(t1.VL_PGTO) AS VALOR_TOTAL
FROM AUX.TBL_PGT t1
GROUP BY 1
ORDER BY 1;
QUIT;

/**/

PROC SQL;
CREATE TABLE VAR_ATA AS SELECT DISTINCT t1.CD_CLI AS MCI_PAGADOR, t1.VAREJO
FROM BASE_PGT_PJ t1; 
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_1_ANT AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, t2.VAREJO
FROM AUX.TBL_PGT t1
LEFT JOIN VAR_ATA t2 ON t1.MCI_PAGADOR = t2.MCI_PAGADOR
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_2_ANT AS SELECT DISTINCT MCI_RECEBEDOR, max(VAREJO) as VAREJO
FROM NOVA_ESTRUTURA_1_ANT
group by 1
ORDER BY 1;
QUIT;

/**/

PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_1_B AS SELECT DISTINCT t1.MCI_RECEBEDOR, VALOR_TOTAL, VAREJO
FROM NOVA_ESTRUTURA_1 t1
LEFT JOIN NOVA_ESTRUTURA_2_ANT T2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_2 AS SELECT t2.CD_PRF_DEPE AS PREFIXO, t2.NR_SEQL_CTRA_ATB AS CARTEIRA, t1.MCI_RECEBEDOR, VALOR_TOTAL, VAREJO
FROM NOVA_ESTRUTURA_1_B t1
LEFT JOIN COMUM.PAI_REL_&ANOMES. t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI;
QUIT;


PROC SQL;
CREATE TABLE VALORES_2_B AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.VL_PGTO AS VALOR_MES_ANTERIOR
FROM AUX.TBL_PGT t1
WHERE MONTH(DT_EFTC_PGTO) = MONTH(&D1.) - 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE VALORES_2_B AS SELECT DISTINCT t1.MCI_RECEBEDOR, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM VALORES_2_B t1
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_3 AS SELECT PREFIXO, CARTEIRA, T1.MCI_RECEBEDOR, VALOR_TOTAL, VALOR_MES_ANTERIOR, VAREJO, IFN(VALOR_MES_ANTERIOR<>0,1,0) as coluna 
FROM NOVA_ESTRUTURA_2 t1
LEFT JOIN VALORES_2_B t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR;
QUIT;


PROC STDIZE DATA=NOVA_ESTRUTURA_3 OUT=NOVA_ESTRUTURA_3 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
CREATE TABLE IND_CC_CHEQUE AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.MCI_PAGADOR, 
IFN(t2.CD_CLI IS NOT NULL AND T2.T = 'CC',1,0) AS IND_CONTAS_NOVAS, IFN(t2.CD_CLI IS NOT NULL AND T2.T = 'CH',1,0) AS IND_CHEQUE_NOVO
FROM AUX.TBL_PGT t1
LEFT JOIN CONSULTA_CHEQUE_1 t2 ON t1.MCI_RECEBEDOR = t2.CD_CLI AND CD_PRF_DEPE_ATU = AGC AND NR_CC_ATU_BNFC = CTA
GROUP BY 1,2;
QUIT;


PROC SQL;
CREATE TABLE IND_CC_CHEQUE_2 AS SELECT DISTINCT t1.MCI_RECEBEDOR, MAX(IND_CONTAS_NOVAS) AS IND_CONTAS_NOVAS, MAX(IND_CHEQUE_NOVO) AS IND_CHEQUE_NOVO
FROM IND_CC_CHEQUE t1
GROUP BY 1
ORDER BY 1;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_4 AS SELECT *
FROM NOVA_ESTRUTURA_3 t1
LEFT JOIN IND_CC_CHEQUE_2 t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR;
QUIT;


PROC SQL;
CREATE TABLE TRAZENDO_DO_DETALHES AS SELECT DISTINCT t1.MCI_RECEBEDOR, t1.VLR_TRFA, t1.LOB_VAI, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS
FROM DETALHES_12_B t1
;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_5 AS SELECT *
FROM NOVA_ESTRUTURA_4 t1
LEFT JOIN TRAZENDO_DO_DETALHES t2 ON t1.MCI_RECEBEDOR = t2.MCI_RECEBEDOR;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_6 AS SELECT *
FROM NOVA_ESTRUTURA_5 t1
LEFT JOIN CRED_DES_2 T2 ON T1.MCI_RECEBEDOR = T2.MCI_RECEBEDOR;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_7 AS SELECT DISTINCT prefixo, carteira, COUNT(MCI_RECEBEDOR) AS QTDE_PROVENTISTAS, SUM(IND_CONTAS_NOVAS) AS QTDE_CONTAS_NOVAS, 
SUM(VLR_TRFA) AS VL_TRFA, SUM(VL_CDC_ECF) AS VL_CDC_ECF, SUM(VL_CDC_SAL) AS VL_CDC_SAL, SUM(VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(VALOR) AS VALOR_FATURA,
SUM(IND_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(LOB_VAI) AS LOB_VAI, SUM(VALOR_TOTAL) AS VALOR_TOTAL, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR, MAX(VAREJO) AS VAREJO,
sum(coluna) as QTDE_PROV_MES_ANTERIOR
FROM NOVA_ESTRUTURA_6
GROUP BY 1, 2
ORDER BY 1, 2;
QUIT;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_8 AS SELECT DISTINCT *
FROM NOVA_ESTRUTURA_7
WHERE prefixo <> 0 AND carteira <> 0
ORDER BY 1, 2;
QUIT;


data NOVA_ESTRUTURA_8;
format posicao yymmdd10.;
set NOVA_ESTRUTURA_8;
posicao = &D1;
run;


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_VAREJO AS SELECT posicao, prefixo as prefdep, carteira AS CTRA, QTDE_PROVENTISTAS, 
QTDE_CONTAS_NOVAS, VL_TRFA, VL_CDC_ECF, VL_CDC_SAL, VL_CDC_OUTROS, VALOR_FATURA, QTDE_CHEQUE_NOVO, LOB_VAI, QTDE_PROV_MES_ANTERIOR,
VALOR_TOTAL , VALOR_MES_ANTERIOR
FROM NOVA_ESTRUTURA_8 t1
WHERE VAREJO = 1;
QUIT;


/*TABELA COLUNAS PARA FUNCAO SUMARIZACAO*/

PROC SQL;
DROP TABLE COLUNAS_SUMARIZAR;
CREATE TABLE COLUNAS_SUMARIZAR (Coluna CHAR(50), Tipo CHAR(10));
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_PROVENTISTAS', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_CONTAS_NOVAS', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_TRFA', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_CDC_ECF', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_CDC_SAL', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VL_CDC_OUTROS', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_FATURA', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_CHEQUE_NOVO', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('LOB_VAI', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('QTDE_PROV_MES_ANTERIOR', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_TOTAL', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_MES_ANTERIOR', 'SUM');
QUIT;


/*FUNCAO DE SUMARIZACAO*/ 
%SumarizadorCNX( TblSASValores=NOVA_ESTRUTURA_VAREJO,  TblSASColunas=COLUNAS_SUMARIZAR,  NivelCTRA=1,  PAA_PARA_AGENCIA=1,  TblSaida=NOVA_ESTRUTURA_VAREJO_1, AAAAMM=&ANOMES.); 


PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_VAREJO_100 AS SELECT t1.posicao, t1.PrefDep as prefixo, t1.CTRA as carteira, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI, t1.QTDE_PROV_MES_ANTERIOR,
VALOR_TOTAL, VALOR_MES_ANTERIOR
FROM NOVA_ESTRUTURA_VAREJO_1 t1;
QUIT;


/**ATACADO**/

PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_ATACADO AS SELECT posicao, prefixo as prefdep, carteira AS CTRA, QTDE_PROVENTISTAS, 
QTDE_CONTAS_NOVAS, VL_TRFA, VL_CDC_ECF, VL_CDC_SAL, VL_CDC_OUTROS, VALOR_FATURA, QTDE_CHEQUE_NOVO, LOB_VAI, QTDE_PROV_MES_ANTERIOR,
VALOR_TOTAL , VALOR_MES_ANTERIOR
FROM NOVA_ESTRUTURA_8 t1
WHERE VAREJO = 0;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_1_SEGUNDO AS SELECT t1.posicao, t1.PrefDep, t1.CTRA, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI,
t2.NomeDep, t2.PrefSureg, t2.PrefSuper, t2.PrefDir, t2.PrefVice, T1.QTDE_PROV_MES_ANTERIOR, VALOR_TOTAL, VALOR_MES_ANTERIOR
FROM NOVA_ESTRUTURA_ATACADO t1
LEFT JOIN COMUM.DEPENDENCIAS t2 ON t1.PrefDep = input(t2.PREFDEP, 4.)
where t2.SB = "00" 
GROUP BY 1,2,3;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_AGENCIA_SEGUNDO AS SELECT DISTINCT t1.PrefDep, 0 as CTRA, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR_TOTAL) AS VALOR_TOTAL, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1_SEGUNDO t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_GEREV_SEGUNDO AS SELECT DISTINCT INPUT(t1.PrefSureg, 4.) as PrefDep, 0 as CTRA, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, 
SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR_TOTAL) AS VALOR_TOTAL, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1_SEGUNDO t1
WHERE PrefSureg <> "0000"
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_SUPER_SEGUNDO AS SELECT DISTINCT INPUT(t1.PrefSuper, 4.) as PrefDep, 0 as CTRA, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR_TOTAL) AS VALOR_TOTAL, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1_SEGUNDO t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_DIR_SEGUNDO AS SELECT DISTINCT INPUT(t1.PrefDir, 4.) as PrefDep, 0 as CTRA, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR_TOTAL) AS VALOR_TOTAL, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1_SEGUNDO t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE ATACADO_VICE_SEGUNDO AS SELECT DISTINCT INPUT(t1.PrefVice, 4.) as PrefDep, 0 as CTRA, SUM(t1.QTDE_PROVENTISTAS) AS QTDE_PROVENTISTAS, 
SUM(t1.QTDE_CONTAS_NOVAS) as QTDE_CONTAS_NOVAS, SUM(t1.VL_TRFA) as VL_TRFA, 
SUM(t1.VL_CDC_ECF) AS VL_CDC_ECF, SUM(t1.VL_CDC_SAL) AS VL_CDC_SAL, SUM(t1.VL_CDC_OUTROS) AS VL_CDC_OUTROS, SUM(t1.VALOR_FATURA) AS VALOR_FATURA, 
SUM(t1.QTDE_CHEQUE_NOVO) AS QTDE_CHEQUE_NOVO, SUM(t1.LOB_VAI) AS LOB_VAI, sum(T1.QTDE_PROV_MES_ANTERIOR) as QTDE_PROV_MES_ANTERIOR, 
SUM(VALOR_TOTAL) AS VALOR_TOTAL, SUM(VALOR_MES_ANTERIOR) AS VALOR_MES_ANTERIOR
FROM ATACADO_1_SEGUNDO t1
GROUP BY 1;
QUIT;


DATA ATACADO_FINAL_SEGUNDO;
	MERGE ATACADO_AGENCIA_SEGUNDO ATACADO_GEREV_SEGUNDO ATACADO_SUPER_SEGUNDO ATACADO_DIR_SEGUNDO ATACADO_VICE_SEGUNDO;
	BY PrefDep;	
RUN;


data ATACADO_FINAL_SEGUNDO;
format posicao yymmdd10.;
set ATACADO_FINAL_SEGUNDO;
posicao = &D1;
run;


PROC SQL;
CREATE TABLE ATACADO_FINAL_SEGUNDO AS SELECT *
FROM NOVA_ESTRUTURA_ATACADO t1
UNION SELECT *
FROM ATACADO_FINAL_SEGUNDO;
QUIT;



PROC SQL;
CREATE TABLE NOVA_ESTRUTURA_ATACADO_200 AS SELECT t1.posicao, t1.PrefDep as prefixo, t1.CTRA as carteira, t1.QTDE_PROVENTISTAS, 
t1.QTDE_CONTAS_NOVAS, t1.VL_TRFA, t1.VL_CDC_ECF, t1.VL_CDC_SAL, t1.VL_CDC_OUTROS, t1.VALOR_FATURA, t1.QTDE_CHEQUE_NOVO, t1.LOB_VAI, T1.QTDE_PROV_MES_ANTERIOR,
t1.VALOR_TOTAL, t1.VALOR_MES_ANTERIOR
FROM ATACADO_FINAL_SEGUNDO t1;
QUIT;



PROC STDIZE DATA=NOVA_ESTRUTURA_ATACADO_200 OUT=NOVA_ESTRUTURA_ATACADO_200 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;



/******************************/
/******************************/
/******************************/
/*Varejo MCI PAGADOR - 463*/

%LET Usuario=f7176219;
%LET Keypass=W1xqrpFM8HG3L2lPNs9j9uyxPS3ZBVOnwNLKrlYs5mWizgUuvu;
%LET Rotina=fopag-dired;
%ProcessoIniciar();

PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('BASE_PGT_PJ_20', 'fopag-dired');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('DET_VAR_PAGADOR', 'detalhe');
   ;
QUIT;

%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);



/******************************/
/******************************/
/******************************/
/*Varejo MCI RECEBEDOR - 521*/

%LET Usuario=f7176219;
%LET Keypass=fopag-dired-2-XPHfOsPTYLTpVS1JKqlI2T8INbg9hBZ0YxwAHBkQ2WVdW4lsE4;
%LET Rotina=fopag-dired-2;
%ProcessoIniciar();

PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('NOVA_ESTRUTURA_VAREJO_100', 'fopag-dired-2');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('DET_VAR', 'detalhe');
   ;
QUIT;

%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);





/******************************/
/******************************/
/******************************/
/*Atacado MCI PAGADOR - 506*/

%LET Usuario=f7176219;
%LET Keypass=fopag-dired-atacado-tJCC0QuJ0qRWJKadjvwBNLqspuAjoTQk7v5r3DOQtv05oRT9lE;
%LET Rotina=fopag-dired-atacado;
%ProcessoIniciar();

PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('BASE_PGT_PJ_30', 'fopag-dired-atacado');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('DET_ATA_PAGADOR', 'detalhe');
   ;
QUIT;

%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);




/******************************/
/******************************/
/******************************/
/*Atacado MCI RECEBEDOR - 522*/

%LET Usuario=f7176219;
%LET Keypass=fopag-dired-atacado-2-LPsTZddNDLrykKNi4CQh5A9iENay27apccOLB7uMUsfFRXDYDv;
%LET Rotina=fopag-dired-atacado-2;
%ProcessoIniciar();

PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('NOVA_ESTRUTURA_ATACADO_200', 'fopag-dired-atacado-2');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('DET_ATA', 'detalhe');
   ;
QUIT;

%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);




/******************************/
/******************************/
/******************************/
x cd /dados/gecen/interno/bases/cdc;
x cd /dados/infor/producao/aux_fopag_var_dired;
x chmod 2777 *;


/*************************************************/;
/* TRECHO DE CÓDIGO INCLUÍDO PELO FF */;

%include "/dados/gestao/rotinas/_macros/macros_uteis.sas";
 
%processCheckOut(
    uor_resp = 341556
    ,funci_resp = &sysuserid
    /*,tipo = Indicador
    ,sistema = Indicador
    ,rotina = I0123 Indicador de Alguma Coisa*/
    ,mailto= 'F8369937' 'F2986408' 'F6794004' 'F7176219' 'F8176496' 'F9457977' 'F9631159'
);
