/********************************/
/********************************/
/*NOVOS CLIENTES PJ QUALIFICADOS*/
/********************************/
/********************************/ 

%include '/dados/infor/suporte/FuncoesInfor.sas';

LIBNAME TFA DB2 DATABASE=BDB2P04 SCHEMA=DB2TFA AUTHDOMAIN=DB2SGCEN;
LIBNAME MCI DB2 DATABASE=BDB2P04 SCHEMA=DB2MCI AUTHDOMAIN=DB2SGCEN;

LIBNAME BON11 '/dados/infor/producao/cielo';
LIBNAME BON12 '/dados/infor/producao/stelo';
LIBNAME BON2 '/dados/gecen/interno/bases/cop';
LIBNAME COX1 "/dados/gecen/interno/cnx_orc/2019/000000180";
LIBNAME COX "/dados/infor/conexao/2019/000000180";
LIBNAME BASEANT '/dados/infor/producao/novos_clientes_PJ';
LIBNAME AUX_1 "/dados/infor/producao/cobranca_qualificada_19";


DATA _NULL_;

D1_PRI = '01MAR2019'd;
/*D1_PRI=primeiroDiaUtilMes(DiaUtilAnterior(Today()));*/
/*CALL SYMPUT('D1_PRI',"'"||Put(D1_PRI, yymmdd10.)||"'");*/

D1 = '29MAR2019'd;
/*D1 = diaUtilAnterior(TODAY());*/
/*CALL SYMPUT('D1',COMPRESS(D1,' '));*/

ANO_ATUAL = 2019;
CALL SYMPUT('ANO_ATUAL',COMPRESS(ANO_ATUAL,' '));

MES_POSICAO = 03;
/*MES_POSICAO = Put(MONTH (D1), Z2.);*/
/*CALL SYMPUT('MES_POSICAO', COMPRESS(MES_POSICAO,' '));*/

ANOMES = 201903;
/*ANOMES = Put(D1, yymmn6.);*/
/*CALL SYMPUT('ANOMES',COMPRESS(ANOMES,' '));*/

MESANO = 032019;
/*MESANO = Put(D1, mmyyn6.);*/
/*CALL SYMPUT('MESANO',COMPRESS(MESANO,' '));*/


/*FAZENDO AS VARIAVEIS DO MES ANTERIOR*/
/*FAZENDO AS VARIAVEIS DO MES ANTERIOR*/


D1_PRI_MM_ANT = primeiroDiaUtilMes(intnx('MONTH',D1,-1));
CALL SYMPUT('D1_PRI_MM_ANT',"'"||Put(D1_PRI_MM_ANT, yymmdd10.)||"'");

D1_MM_ANT = ultimoDiaUtilMes(intnx('MONTH',D1,-1));
CALL SYMPUT('D1_MM_ANT',"'"||Put(D1_MM_ANT, yymmdd10.)||"'");

MES_POSICAO_ANT = Put(MONTH (D1_MM_ANT), Z2.);
CALL SYMPUT('MES_POSICAO_ANT', COMPRESS(MES_POSICAO_ANT,' '));

ANOMES_ANT = Put(D1_MM_ANT, yymmn6.);
CALL SYMPUT('ANOMES_ANT',COMPRESS(ANOMES_ANT,' '));

MESANO_ANT = Put(D1_MM_ANT, mmyyn6.);
CALL SYMPUT('MESANO_ANT',COMPRESS(MESANO_ANT,' '));
	
RUN;

%Put &D1_PRI &D1 &ANO_ATUAL &MES_POSICAO &ANOMES &MESANO &D1_PRI_MM_ANT &D1_MM_ANT &MES_POSICAO_ANT &ANOMES_ANT &MESANO_ANT;


/*********************************/
/*********************************/
/*******MCIS DE EXCLUSAO**********/
/*********************************/
/*********************************/


/*TRAZENDO MCIS CONTAS REATIVADAS POS 01/07/2018*/
/*TRAZENDO MCIS CONTAS REATIVADAS POS 01/07/2018*/
/*TRAZENDO MCIS CONTAS REATIVADAS POS 01/07/2018*/
/*TRAZENDO MCIS CONTAS REATIVADAS POS 01/07/2018*/


PROC SQL;
    CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
    CREATE TABLE EXCLUIR_REATIVADAS_1 AS  SELECT * FROM CONNECTION TO DB2(
        SELECT 
            t1.CD_UOR_CC AS AGENCIA,
            t1.NR_CC AS CONTA,            
            t2.DEB307_COD_BDC as MCI,
			t1.DT_ULT_RTVC_CT as DATA_ABERTURA

        FROM DB2DEB.CC_NOVO t1
        INNER JOIN DB2DEB.TDEB307 t2 ON (t1.CD_UOR_CC = t2.DEB307_AGENCIA AND t1.NR_CC = t2.DEB307_CONTA)
               
            WHERE t1.CD_TIP_PSS = 2
            AND (DT_ULT_RTVC_CT >= '01.07.2018' AND DT_ULT_RTVC_CT <= '31.12.2018') OR (MONTH(DT_ULT_RTVC_CT) <= (&MES_POSICAO. -2) AND YEAR(DT_ULT_RTVC_CT) = 2019)
            AND t2.DEB307_COD_BDC <> 0
            
         ORDER BY 4)
         ORDER BY 4;
QUIT;


PROC SQL;

   CREATE TABLE EXCLUIR_REATIVADAS_2 AS SELECT DISTINCT    

          t1.MCI		  
		  		  
      FROM EXCLUIR_REATIVADAS_1 t1;

QUIT;


/*TRAZENDO O MES ATUAL*/
/*TRAZENDO O MES ATUAL*/
/*TRAZENDO O MES ATUAL*/
/*TRAZENDO O MES ATUAL*/
/*TRAZENDO O MES ATUAL*/
/*TRAZENDO O MES ATUAL*/


/*TRAZENDO CLIENTES PJ*/
/*TRAZENDO CLIENTES PJ*/
/*TRAZENDO CLIENTES PJ*/
/*TRAZENDO CLIENTES PJ*/

/*Contas Integração*/
PROC SQL;CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
   CREATE TABLE WORK.PJ_INTEGRACAO AS SELECT * FROM CONNECTION TO DB2
   (
    SELECT A.CD_PRF_DEPE_CDU, A.NR_CTR_OPR, B.CD_PSS_CTR_OPR AS CD_CLI_TITR_CC
      FROM DB2OPR.CTR_OPR A
                        INNER JOIN DB2OPR.PRTC_PSS_CTR_OPR B ON (A.NR_UNCO_CTR_OPR = B.NR_UNCO_CTR_OPR)

                            WHERE A.CD_PRD = 6 and b.NR_SEQL_PRTC = 1 AND A.CD_MDLD = 27 AND
              (MONTH(A.DT_FRMZ) = (&MES_POSICAO.)) AND YEAR(A.DT_FRMZ) = 2019
	  
   ) ;
QUIT;
/*Contas Correntes */
PROC SQL;CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
   CREATE TABLE WORK.PJ_TOTAL AS SELECT * FROM CONNECTION TO DB2(
   SELECT t1.DEB307_AGENCIA as CD_UOR_CC,
          t1.DEB307_CONTA as NR_CC,
          t1.DEB307_DT_ABERTURA as data_abertura,
          t1.DEB307_COD_BDC as CD_CLI_TITR_CC,
		  t4.cd_prd,
		  t4.cd_mdld
      FROM DB2DEB.TDEB307 t1
      LEFT JOIN (SELECT B.CD_PSS_CTR_OPR AS CD_CLI, A.cd_prd, A.CD_MDLD
                    FROM DB2OPR.CTR_OPR A
                        INNER JOIN DB2OPR.PRTC_PSS_CTR_OPR B ON (A.NR_UNCO_CTR_OPR = B.NR_UNCO_CTR_OPR)

                            WHERE A.CD_PRD = 6 and b.NR_SEQL_PRTC = 1 AND A.CD_MDLD <> 27 AND


((A.DT_FRMZ >= '01.07.2018' AND A.DT_FRMZ <= '31.12.2018') OR (A.DT_FRMZ >= '01.01.2019' AND MONTH(A.DT_FRMZ) <= (&MES_POSICAO. -2)) OR (A.DT_FRMZ < '01.07.2018' AND B.DT_FIM_PRTC >= '01.07.2018'))

	  
)  T4 ON (T1.DEB307_COD_BDC = T4.CD_CLI)

      WHERE 

     MONTH(t1.DEB307_DT_ABERTURA) >= (&MES_POSICAO.-1) AND YEAR(t1.DEB307_DT_ABERTURA) = 2019

     AND t1.DEB307_COD_BDC <> 0
               
        and t1.DEB307_PESSOA = 2
AND T4.CD_CLI IS NULL)
order by 4;
QUIT;

/* EXCLUIR CONTAS INTEGRAÇÃO POIS AS MESMAS NÃO DEVEM SER SENSIBILIZADAS COMO CLIENTES NOVOS E NEM IMPACTAR OS CLIENTES NOVOS QUE JÁ TIVERAM ESSE TIPO DE CONTA*/
PROC SQL;
   CREATE TABLE WORK.PJ AS 
   SELECT t1.CD_UOR_CC, 
          t1.NR_CC, 
          t1.DATA_ABERTURA, 
          t1.CD_CLI_TITR_CC
      FROM WORK.PJ_TOTAL t1
           LEFT JOIN WORK.PJ_INTEGRACAO t2 
             ON ((t1.CD_UOR_CC = t2.CD_PRF_DEPE_CDU) 
                  AND (t1.NR_CC = t2.NR_CTR_OPR) 
                  AND (t1.CD_CLI_TITR_CC = t2.CD_CLI_TITR_CC))
      WHERE t2.CD_PRF_DEPE_CDU IS MISSING 
        AND t2.NR_CTR_OPR IS MISSING 
        AND t2.CD_CLI_TITR_CC IS MISSING;
QUIT;



/***********************/

/*ORGANIZANDO*/

PROC SQL;

   CREATE TABLE CLIENTES_PJ_1_ANT AS SELECT DISTINCT    

          t1.CD_UOR_CC as AGENCIA, 
          t1.NR_CC AS CONTA,
          t1.CD_CLI_TITR_CC AS MCI,
		  t1.DATA_ABERTURA FORMAT yymmdd10.
		  		  
      FROM WORK.PJ t1
	  LEFT JOIN EXCLUIR_REATIVADAS_2 t2 ON t1.CD_CLI_TITR_CC = t2.MCI
	  WHERE t2.MCI IS MISSING AND t1.DATA_ABERTURA <= &D1.
       ;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_1 AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  MIN(t1.DATA_ABERTURA) FORMAT yymmdd10. AS DATA_ABERTURA
		  		  
      FROM CLIENTES_PJ_1_ANT t1
	  GROUP BY 1, 2, 3
      ORDER BY 1, 2, 3;

QUIT;


/*TRAZENDO AS CONTAS REATIVADAS*/
/*TRAZENDO AS CONTAS REATIVADAS*/
/*TRAZENDO AS CONTAS REATIVADAS*/
/*TRAZENDO AS CONTAS REATIVADAS*/


PROC SQL;
    CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
    CREATE TABLE WORK.REATIVADAS_TOTAL AS  SELECT * FROM CONNECTION TO DB2(
        SELECT 
            t1.CD_UOR_CC AS AGENCIA,
            t1.NR_CC AS CONTA,            
            t2.DEB307_COD_BDC as MCI,
			t1.DT_ULT_RTVC_CT as DATA_ABERTURA

        FROM DB2DEB.CC_NOVO t1
        INNER JOIN DB2DEB.TDEB307 t2 ON (t1.CD_UOR_CC = t2.DEB307_AGENCIA AND t1.NR_CC = t2.DEB307_CONTA)
        

 
         LEFT JOIN (SELECT B.CD_PSS_CTR_OPR AS CD_CLI
                    FROM DB2OPR.CTR_OPR A
                        INNER JOIN DB2OPR.PRTC_PSS_CTR_OPR B ON (A.NR_UNCO_CTR_OPR = B.NR_UNCO_CTR_OPR)

                            WHERE A.CD_PRD = 6 and b.NR_SEQL_PRTC = 1 AND A.CD_MDLD <> 27 AND

 	((A.DT_FRMZ >= '01.07.2018' AND A.DT_FRMZ <= '31.12.2018') OR (A.DT_FRMZ >= '01.01.2019' AND MONTH(A.DT_FRMZ) <= (&MES_POSICAO. -2)) OR (A.DT_FRMZ < '01.07.2018' AND B.DT_FIM_PRTC >= '01.07.2018'))
            

          ) t4 ON t2.DEB307_COD_BDC = t4.CD_CLI


            WHERE t1.CD_TIP_PSS = 2
            AND MONTH(t1.DT_ULT_RTVC_CT) >= (&MES_POSICAO.-1) AND YEAR(t1.DT_ULT_RTVC_CT) = 2019
            AND t2.DEB307_COD_BDC <> 0
            AND t4.CD_CLI IS NULL

         ORDER BY 4)
         ORDER BY 4;
QUIT;

PROC SQL;
   CREATE TABLE WORK.REATIVADAS AS 
   SELECT t1.AGENCIA, 
          t1.CONTA, 
          t1.MCI, 
          t1.DATA_ABERTURA
      FROM WORK.REATIVADAS_TOTAL t1
           LEFT JOIN WORK.PJ_INTEGRACAO t2 
             ON ((t1.AGENCIA = t2.CD_PRF_DEPE_CDU) 
                  AND (t1.CONTA = t2.NR_CTR_OPR) 
                  AND (t1.MCI = t2.CD_CLI_TITR_CC))
      WHERE t2.CD_PRF_DEPE_CDU IS MISSING 
        AND t2.NR_CTR_OPR IS MISSING 
        AND t2.CD_CLI_TITR_CC IS MISSING;
QUIT;


/*ORGANIZANDO*/


PROC SQL;

   CREATE TABLE REATIVADAS_1 AS SELECT DISTINCT    

          t1.AGENCIA,
          t1.CONTA,            
          t1.MCI,
	      t1.DATA_ABERTURA FORMAT yymmdd10.
 
      FROM REATIVADAS t1
      LEFT JOIN EXCLUIR_REATIVADAS_2 t2 ON t1.MCI = t2.MCI
	  WHERE t2.MCI IS MISSING AND t1.DATA_ABERTURA <= &D1.;

QUIT;


PROC SQL;

   CREATE TABLE REATIVADAS_2 AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  MIN(t1.DATA_ABERTURA) FORMAT yymmdd10. AS DATA_ABERTURA
		  		  
      FROM REATIVADAS_1 t1
	  GROUP BY 1, 2, 3
      ORDER BY 1, 2, 3;

QUIT;


/*JUNTANDO*/
/*JUNTANDO*/


DATA CLIENTES_PJ_JUNTOS;
	MERGE CLIENTES_PJ_1 REATIVADAS_2;
	BY AGENCIA CONTA MCI DATA_ABERTURA;
RUN;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_JUNTOS_1_ANT AS SELECT DISTINCT    

          t1.MCI,
	      MIN(t1.DATA_ABERTURA) FORMAT yymmdd10. AS DATA_ABERTURA		  
 
      FROM CLIENTES_PJ_JUNTOS t1
      GROUP BY 1
      ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_JUNTOS_1 AS SELECT DISTINCT    

          t2.AGENCIA,
		  t2.CONTA,
          t1.MCI,
	      t1.DATA_ABERTURA		  
 
      FROM CLIENTES_PJ_JUNTOS_1_ANT t1
	  INNER JOIN CLIENTES_PJ_JUNTOS t2 ON t1.MCI = t2.MCI AND t1.DATA_ABERTURA = t2.DATA_ABERTURA
      GROUP BY 1, 2
      ORDER BY 1, 2;

QUIT;


/*TRAZENDO O CODIGO DO PACOTE*/
/*TRAZENDO O CODIGO DO PACOTE*/


PROC SQL;
	DROP TABLE DB2SGCEN.TABELA_PROVISORIA;
	CREATE TABLE DB2SGCEN.TABELA_PROVISORIA AS
	     	SELECT DISTINCT AGENCIA FORMAT Z20. AS AGC, CONTA FORMAT Z20. AS CTA
			FROM CLIENTES_PJ_JUNTOS_1
            ORDER BY 1,2;
QUIT;


   PROC SQL;
                CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
                CREATE TABLE BASE_TFA AS
                    SELECT AGENCIA, CONTA, COD_PCTE, DT_INI, DT_FIM
                    FROM CONNECTION TO DB2
                            (SELECT DISTINCT t1.T700COD_AGEN AS AGENCIA,
                            t1.T700NMRO_CNTA AS CONTA,
                            t1.T700COD_PCTE AS COD_PCTE,
							t1.T700DATA_ADESAO AS DT_INI,
							t1.T700DATA_FIM_VLDD AS DT_FIM                            

                            FROM DB2TFA.TTFA700 t1
                            INNER JOIN DB2SGCEN.TABELA_PROVISORIA t2 on (t1.T700COD_AGEN=t2.AGC and t1.T700NMRO_CNTA=t2.CTA) ) A
                     		 
                     ORDER BY 1, 2;
                DISCONNECT FROM DB2;
				DROP TABLE DB2SGCEN.TABELA_PROVISORIA;
    QUIT;


/*PEGANDO O PACOTE VALIDO NO PERIODO*/
/*PEGANDO O PACOTE VALIDO NO PERIODO*/


PROC SQL;

   CREATE TABLE BASE_TFA_2_ANT AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
		  t1.COD_PCTE,
		  t1.DT_INI FORMAT yymmdd10.		  
		  		  
      FROM BASE_TFA t1
      WHERE t1.COD_PCTE IN (1001 1030 1002 1031 1027 1032 1028 1033) AND t1.DT_FIM > &D1. 
      AND MONTH(t1.DT_INI) >= (&MES_POSICAO.-1) AND YEAR(t1.DT_INI) = &ANO_ATUAL. AND t1.DT_INI<= &D1.;

QUIT;


PROC SQL;

   CREATE TABLE BASE_TFA_2 AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
		  t2.COD_PCTE,
		  MAX(t1.DT_INI) FORMAT yymmdd10. AS DT_INI		  
		  		  
      FROM BASE_TFA_2_ANT t1
	  INNER JOIN BASE_TFA_2_ANT t2 ON t1.AGENCIA = t2.AGENCIA AND t1.CONTA = t2.CONTA
      GROUP BY 1, 2
      ;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_AGRUPANDO_ANT AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,		  
		  t2.COD_PCTE,
		  t2.DT_INI AS DT_PACOTE,
          IFC(t2.COD_PCTE <> 0 and t2.COD_PCTE IS NOT MISSING, "Sim", "Não") as PACOTE_OK  
		  		  
      FROM CLIENTES_PJ_JUNTOS_1 t1
      LEFT JOIN BASE_TFA_2 t2 ON t1.AGENCIA = t2.AGENCIA AND t1.CONTA = t2.CONTA
	        ;

QUIT;


PROC STDIZE DATA=CLIENTES_PJ_AGRUPANDO_ANT OUT=CLIENTES_PJ_AGRUPANDO_ANT REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*JUNTANDO OS DOIS MESES*/
/*JUNTANDO OS DOIS MESES*/
/*JUNTANDO OS DOIS MESES*/
/*JUNTANDO OS DOIS MESES*/


DATA CLIENTES_PJ_AGRUPANDO_JUNTOS;
	MERGE CLIENTES_PJ_AGRUPANDO_ANT;
	BY AGENCIA CONTA MCI DATA_ABERTURA COD_PCTE DT_PACOTE PACOTE_OK;
RUN;


/*CONTINUANDO*/
/*CONTINUANDO*/
/*CONTINUANDO*/
/*CONTINUANDO*/


PROC SQL;

   CREATE TABLE CLIENTES_PJ_AGRUPANDO AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.DT_PACOTE,
		  t1.PACOTE_OK,	
		  t2.VLR_FATURAMENTO
		  		  
      FROM CLIENTES_PJ_AGRUPANDO_JUNTOS t1
      LEFT JOIN BCN.BCN_PJ t2 ON t1.MCI = t2.MCI
      GROUP BY 1, 2, 3
      ORDER BY 1, 2, 3;

QUIT;

/*PEGA ULTIMO FATURAMENTO CADASTRADO*/

PROC SQL;

   CREATE TABLE CLIENTES_PJ_AGRUPANDO_1 AS SELECT DISTINCT  

    t1.CD_CLI_FATM,
	MAX(t1.NR_SEQL_FATM) AS NR_SEQL_FATM

      FROM MCI.FATM_CFMD_BCRO t1
	  WHERE (MONTH(t1.DT_REF_FATM) = 02 OR MONTH(t1.DT_REF_FATM) = 03) AND YEAR(t1.DT_REF_FATM) = 2019
	  GROUP BY 1
	  ORDER BY 1
      ;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_AGRUPANDO AS SELECT DISTINCT  

    t1.CD_CLI_FATM,
	t2.VL_FATM
      FROM CLIENTES_PJ_AGRUPANDO_1 t1
	  INNER JOIN MCI.FATM_CFMD_BCRO t2 ON t1.CD_CLI_FATM = t2.CD_CLI_FATM AND t1.NR_SEQL_FATM = t2.NR_SEQL_FATM
	  ORDER BY 1
      ;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_AGRUPANDO AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.DT_PACOTE,
		  t1.PACOTE_OK,	
		  t2.VL_FATM AS VLR_FATURAMENTO
		  		  
      FROM CLIENTES_PJ_AGRUPANDO_JUNTOS t1
      LEFT JOIN CLIENTES_PJ_AGRUPANDO t2 ON t1.MCI = t2.CD_CLI_FATM
      GROUP BY 1, 2, 3
      ORDER BY 1, 2, 3;

QUIT;


PROC STDIZE DATA=CLIENTES_PJ_AGRUPANDO OUT=CLIENTES_PJ_AGRUPANDO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*COLOCAR A REGRA DO PACOTE*/
/*COLOCAR A REGRA DO PACOTE*/
/*COLOCAR A REGRA DO PACOTE*/
/*COLOCAR A REGRA DO PACOTE*/
/*COLOCAR A REGRA DO PACOTE*/


PROC SQL;

   CREATE TABLE CLIENTES_PJ_ADEQUAMENTO AS SELECT DISTINCT    

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.PACOTE_OK,
          t1.DT_PACOTE,	
		  t1.VLR_FATURAMENTO AS VLR_FATURAMENTO,

		  IFC( (VLR_FATURAMENTO <= 1000000 AND t1.COD_PCTE IN (1001, 1002, 1027, 1028, 1030, 1031, 1032, 1033))
	  OR (VLR_FATURAMENTO > 1000000 AND VLR_FATURAMENTO <= 5000000 AND t1.COD_PCTE IN (1002, 1027, 1028, 1031, 1032, 1033))
	  OR (VLR_FATURAMENTO > 5000000 AND t1.COD_PCTE IN (1027, 1028, 1032, 1033)), "Sim", "Não") AS REGRA_PACOTE

		  		  
      FROM CLIENTES_PJ_AGRUPANDO t1
      GROUP BY 1, 2, 3
      ORDER BY 1, 2, 3;

QUIT;


/*HABILITAÇÃO GEFIN*/
/*HABILITAÇÃO GEFIN*/

/*
PROC SQL;

   CREATE TABLE CLIENTES_PJ_3 AS 
   SELECT  DISTINCT 

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.DT_PACOTE,
		  t1.PACOTE_OK,	
		  t1.VLR_FATURAMENTO,
		  t1.REGRA_PACOTE,
		  IFC(t2.USUARIO_GERENCIADOR_FINANCEIRO IN (1,2,3), "Sim", "Não") as GEFIN          		  
          
   FROM CLIENTES_PJ_ADEQUAMENTO t1
   LEFT JOIN BCN.BCN_PJ t2 ON t1.MCI = t2.MCI
   GROUP BY 1, 2, 3
   ORDER BY 1, 2, 3
   ;

QUIT;
*/

/*NOVO GEFIN*/
/*NOVO GEFIN*/
/*NOVO GEFIN*/
/*NOVO GEFIN*/


PROC SQL;

   CREATE TABLE ATDT_GAT AS SELECT DISTINCT    

          t1.MCI AS CD_CLI

      FROM CLIENTES_PJ_ADEQUAMENTO t1
      ORDER BY 1;

QUIT;


PROC SQL;
    DROP TABLE DB2SGCEN.HPJ_CLI_TEMP;
    CREATE TABLE DB2SGCEN.HPJ_CLI_TEMP AS
        SELECT DISTINCT
            t1.CD_CLI FORMAT=9. AS CD_CLI
        FROM WORK.ATDT_GAT t1
        ORDER BY t1.CD_CLI;
    CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
    CREATE TABLE CANAIS AS

            SELECT
            CD_CLI,

            IFN(CD_TIP_CNL=21,1,2) AS CANAL,
            DT_CNL
        FROM CONNECTION TO DB2(
            SELECT
                t1.CD_CLI,
                t1.CD_TIP_CNL,
                date(t1.TS_INRO_CLI) AS DT_CNL
            FROM DB2BIC.AUX_INRO_CLI_CMPR t1
            INNER JOIN DB2MCI.CLIENTE t2 ON (t1.CD_CLI=t2.COD)
            WHERE
                    t1.CD_CLI IN (SELECT CD_CLI FROM DB2SGCEN.HPJ_CLI_TEMP)
                AND t1.CD_TIP_CNL IN (15, 21, 26)
                AND MONTH(t1.TS_INRO_CLI) >= (&MES_POSICAO.-1) AND YEAR(t1.TS_INRO_CLI) = &ANO_ATUAL.   
                
                AND t2.COD_TIPO = 2
        
               UNION
            SELECT
                t1.CD_CLI,
                CD_TIP_CNL,
                date(t1.TS_INRO_CLI) AS DT_CNL
            FROM DB2BIC.AUX_INRO_CLI_ANT t1
            INNER JOIN DB2MCI.CLIENTE t2 ON (t1.CD_CLI=t2.COD)
            WHERE
                    t1.CD_CLI IN (SELECT CD_CLI FROM DB2SGCEN.HPJ_CLI_TEMP)
                AND t1.CD_TIP_CNL IN (15, 21, 26)
                AND MONTH(t1.TS_INRO_CLI) >= (&MES_POSICAO.-1) AND YEAR(t1.TS_INRO_CLI) = &ANO_ATUAL.  
                 
                AND t2.COD_TIPO = 2
            UNION
            SELECT
                t1.CD_CLI,
                CD_TIP_CNL,
                date(t1.TS_INRO_CLI) AS DT_CNL
            FROM DB2BIC.AUX_INRO_CLI_ATU t1
            INNER JOIN DB2MCI.CLIENTE t2 ON (t1.CD_CLI=t2.COD)
            WHERE
                    t1.CD_CLI IN (SELECT CD_CLI FROM DB2SGCEN.HPJ_CLI_TEMP)
                AND t1.CD_TIP_CNL IN (15, 21, 26)
                AND MONTH(t1.TS_INRO_CLI) >= (&MES_POSICAO.-1) AND YEAR(t1.TS_INRO_CLI) = &ANO_ATUAL. 
                
                AND t2.COD_TIPO = 2
        )
        ORDER BY CD_CLI, DT_CNL;
    DISCONNECT FROM DB2;
    DROP TABLE DB2SGCEN.HPJ_CLI_TEMP;
QUIT;


PROC SQL;

   CREATE TABLE CANAIS_1 AS SELECT DISTINCT    

          t1.cd_cli as MCI

      FROM CANAIS t1
	  WHERE t1.CANAL = 2 AND DT_CNL <= &D1.
      ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_3 AS 
   SELECT  DISTINCT 

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.DT_PACOTE,
		  t1.PACOTE_OK,	
		  t1.VLR_FATURAMENTO,
		  t1.REGRA_PACOTE,
		  IFC(t2.MCI IS NOT MISSING, "Sim", "Não") as GEFIN          		  
          
   FROM CLIENTES_PJ_ADEQUAMENTO t1
   LEFT JOIN CANAIS_1 t2 ON t1.MCI = t2.MCI
   GROUP BY 1, 2, 3
   ORDER BY 1, 2, 3
   ;

QUIT;


/*ENCARTEIRANDO*/
/*ENCARTEIRANDO*/
/*ENCARTEIRANDO*/
/*ENCARTEIRANDO*/


PROC SQL;

   CREATE TABLE CLIENTES_PJ_4 AS 
      SELECT DISTINCT 

          t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.PACOTE_OK,
          t1.DT_PACOTE,	
		  t1.VLR_FATURAMENTO,
		  t1.REGRA_PACOTE,
		  t1.GEFIN,
          t2.CD_PRF_DEPE AS PREFDEP, 
          t2.NR_SEQL_CTRA AS CARTEIRA                    
		            
      FROM CLIENTES_PJ_3 t1
      LEFT JOIN COMUM.PAI_REL_&ANOMES. t2 ON (t1.MCI = t2.CD_CLI)
      GROUP BY 1, 2, 3
      ORDER BY 1, 2, 3;

QUIT;


PROC STDIZE DATA=CLIENTES_PJ_4 OUT=CLIENTES_PJ_4 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


/*CIELO*/
/*CIELO*/
/*CIELO*/
/*CIELO*/


PROC SQL;

      CREATE TABLE CLIENTES_PJ_B_11_ANT_1 AS 
      SELECT DISTINCT 

	     t1.MCI, 
         SUM(t1.M_&ANOMES_ANT.) AS M_&ANOMES_ANT.

      FROM BON11.resumo_faturamento_2019 t1
	  WHERE t1.M_&ANOMES_ANT. IS NOT MISSING AND M_&ANOMES_ANT. > 0
      
      GROUP BY 1
      ORDER BY 1;

QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_11_ANT AS 
      SELECT DISTINCT 

	     t1.MCI, 
         SUM(t1.M_&ANOMES.) AS M_&ANOMES.

      FROM BON11.resumo_faturamento_2019 t1
	  WHERE t1.M_&ANOMES. IS NOT MISSING AND M_&ANOMES. > 0
      
      GROUP BY 1
      ORDER BY 1;

QUIT;


DATA CLIENTES_PJ_BONUS_JUNT;
	MERGE CLIENTES_PJ_B_11_ANT_1 CLIENTES_PJ_BONUS_11_ANT;
	BY MCI;
RUN;


PROC STDIZE DATA=CLIENTES_PJ_BONUS_JUNT OUT=CLIENTES_PJ_BONUS_JUNT REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_200 AS 
      SELECT DISTINCT 

	      t1.MCI,
          (t1.M_&ANOMES. + t1.M_&ANOMES_ANT.) AS M_&ANOMES. 

      FROM CLIENTES_PJ_BONUS_JUNT t1
      ORDER BY 1;

QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_11 AS 
      SELECT DISTINCT 

	      t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.PACOTE_OK,
          t1.DT_PACOTE,	
		  t1.VLR_FATURAMENTO,
		  t1.REGRA_PACOTE,
		  t1.GEFIN,
          t1.PREFDEP, 
          t1.CARTEIRA,
		  t2.M_&ANOMES. 

      FROM CLIENTES_PJ_4 t1
      LEFT JOIN CLIENTES_PJ_BONUS_200 t2 ON t1.MCI = t2.MCI
      GROUP BY 1,2,3
      ORDER BY 1,2,3;

QUIT;


PROC STDIZE DATA=CLIENTES_PJ_BONUS_11 OUT=CLIENTES_PJ_BONUS_11 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_12 AS 
      SELECT DISTINCT 

	      t1.AGENCIA, 
          t1.CONTA,
          t1.MCI,
		  t1.DATA_ABERTURA,	
		  t1.COD_PCTE,
		  t1.DT_PACOTE,
		  t1.PACOTE_OK,	
		  t1.VLR_FATURAMENTO,
		  t1.REGRA_PACOTE,
		  t1.GEFIN,
          t1.PREFDEP, 
          t1.CARTEIRA,
		  IFC(t1.M_&ANOMES. > 0, "Sim", "Não") AS CIELO

      FROM CLIENTES_PJ_BONUS_11 t1
      ORDER BY 1,2,3;

QUIT;


/*STELO*/
/*STELO*/

PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_130 AS 
      SELECT DISTINCT 

	     t1.CD_CLI AS MCI, 
         SUM(t2.F_&ANOMES_ANT.) AS F_&ANOMES_ANT.

      FROM BON12.BASE_CADASTRO t1 
      LEFT JOIN BON12.base_faturamento_2019 t2 ON t1.ID_STELO = t2.ID_STELO
	  WHERE t2.F_&ANOMES_ANT. IS NOT MISSING AND t1.CD_CLI IS NOT MISSING AND t2.F_&ANOMES_ANT. > 0
      
      GROUP BY 1
      ORDER BY 1;

QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_140 AS 
      SELECT DISTINCT 

	     t1.CD_CLI AS MCI, 
         SUM(t2.F_&ANOMES.) AS F_&ANOMES.

      FROM BON12.BASE_CADASTRO t1 
      LEFT JOIN BON12.base_faturamento_2019 t2 ON t1.ID_STELO = t2.ID_STELO
	  WHERE t2.F_&ANOMES. IS NOT MISSING AND t1.CD_CLI IS NOT MISSING AND t2.F_&ANOMES. > 0
      
      GROUP BY 1
      ORDER BY 1;

QUIT;


DATA CLIENTES_PJ_BONUS_1500;
	MERGE CLIENTES_PJ_BONUS_130 CLIENTES_PJ_BONUS_140;
	BY MCI;
RUN;


PROC STDIZE DATA=CLIENTES_PJ_BONUS_1500 OUT=CLIENTES_PJ_BONUS_1500 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_1700 AS 
      SELECT DISTINCT 

	      t1.MCI,
          (t1.F_&ANOMES. + t1.F_&ANOMES_ANT.) AS F_&ANOMES.

      FROM CLIENTES_PJ_BONUS_1500 t1
      ORDER BY 1;

QUIT;



PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_13 AS 
      SELECT DISTINCT 

	     t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.DT_PACOTE,
		 t1.PACOTE_OK,	
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
         t2.F_&ANOMES.		  

      FROM CLIENTES_PJ_BONUS_12 t1
      LEFT JOIN CLIENTES_PJ_BONUS_1700 t2 ON t1.MCI = t2.MCI
     
      GROUP BY 1,2,3
      ORDER BY 1,2,3;

QUIT;

PROC STDIZE DATA=CLIENTES_PJ_BONUS_13 OUT=CLIENTES_PJ_BONUS_13 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_14 AS 
      SELECT DISTINCT 

	     t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 IFC(t1.F_&ANOMES. > 0, "Sim", "Não") AS STELO

      FROM CLIENTES_PJ_BONUS_13 t1
      ORDER BY 1,2,3;

QUIT;


/*FOPAG*/
/*FOPAG*/


PROC SQL;
   CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
   CREATE TABLE AUX_PGT AS
   SELECT CD_CLI, CD_CTR_PGTO, DT_CTR_PGTO Format ddmmyy10.
   FROM CONNECTION TO DB2
      (SELECT CD_CLI, CD_CTR_PGTO, DT_CTR_PGTO
       FROM DB2PGT.CTR_PGTO A
	   INNER JOIN DB2MCI.CLIENTE B ON(A.CD_CLI=B.COD)
	   WHERE IN_EST_CTR_PGTO='A' AND COD_TIPO=2);
   DISCONNECT FROM DB2;
QUIT;


PROC SQL;
	CREATE TABLE PGT_FILTRADA AS
		SELECT A.* FROM AUX_PGT A
		INNER JOIN (SELECT CD_CLI, CD_CTR_PGTO, MIN(DT_CTR_PGTO) AS K
					FROM AUX_PGT GROUP BY 1, 2) B 
                    ON(A.CD_CLI=B.CD_CLI AND A.DT_CTR_PGTO=B.K)
					WHERE YEAR(DT_CTR_PGTO) = &ANO_ATUAL. AND MONTH(DT_CTR_PGTO) >= (&MES_POSICAO.-1) AND DT_CTR_PGTO <= &D1. 
		ORDER BY 1, 2;
QUIT;


PROC SQL;
	CREATE TABLE BASE_MCI AS
		SELECT DISTINCT CD_CLI
			FROM PGT_FILTRADA
				ORDER BY 1;
	CREATE INDEX CD_CLI ON BASE_MCI(CD_CLI);
QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_15 AS 
      SELECT DISTINCT 

	     t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t2.CD_CLI

      FROM CLIENTES_PJ_BONUS_14 t1
      LEFT JOIN BASE_MCI t2 ON t1.MCI = t2.CD_CLI

      GROUP BY 1,2,3
      ORDER BY 1,2,3;

QUIT;
 

PROC SQL;

      CREATE TABLE CLIENTES_PJ_BONUS_17 AS 
      SELECT DISTINCT 

	     t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 IFC(t2.CD_CLI IS NOT MISSING, "Sim", "Não") AS FOPAG
		 
      FROM CLIENTES_PJ_BONUS_15 t1
      LEFT JOIN BASE_MCI t2 ON t1.MCI = t2.CD_CLI

      ORDER BY 1,2,3;

QUIT;
 

/*Contratação de uma operação de Giro e/ou Recebíveis*/
/*Contratação de uma operação de Giro e/ou Recebíveis*/

PROC SQL;

      CREATE TABLE CLIENTES_PJ_6_BONUS_2_ANT_3 AS 
      SELECT DISTINCT 
          
          t1.MCI
		  		            
      FROM CLIENTES_PJ_BONUS_17 t1;

QUIT;


PROC SQL;

      CREATE TABLE CLIENTES_PJ_6_BONUS_2_ANT_2 AS 
      SELECT DISTINCT 

          t2.MCI AS MCI
		  		            
      FROM CLIENTES_PJ_6_BONUS_2_ANT_3 t1 
      INNER JOIN BON2.contratacao_cop t2 ON t1.MCI = t2.MCI
      WHERE t2.COD_PROD = 539 AND MONTH(t2.data) >= (&MES_POSICAO.-1) AND YEAR(t2.data) = &ANO_ATUAL. AND t2.data <= &D1.;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PJ_6_BONUS_2_ANT AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         IFC(t2.MCI IS NOT MISSING, "Sim", "Não") AS OP_CREDITO
		  		            
      FROM CLIENTES_PJ_BONUS_17 t1
    LEFT JOIN CLIENTES_PJ_6_BONUS_2_ANT_2 t2 ON t1.MCI = t2.MCI;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_31 AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 IFC(t1.PACOTE_OK = "Sim" AND t1.REGRA_PACOTE = "Sim" AND t1.GEFIN = "Sim", "Sim", "Não") AS QUALIFICADO,
		 IFN(t1.PACOTE_OK = "Sim" AND t1.REGRA_PACOTE = "Sim" AND t1.GEFIN = "Sim", 1, 0) AS PONTOS,
		 IFN(t1.CIELO = "Sim" OR t1.STELO = "Sim" OR t1.FOPAG = "Sim" OR t1.OP_CREDITO = "Sim", 1, 0) AS BONUS
		  		            
      FROM CLIENTES_PJ_6_BONUS_2_ANT t1
	  WHERE t1.PREFDEP <> 0 AND t1.CARTEIRA <> 0
    ;

QUIT;





PROC SQL;

   CREATE TABLE CLIENTES_FINAL_321 AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,
		 IFN(t1.QUALIFICADO = "Sim", (t1.BONUS + t1.PONTOS), 0) AS PONTOS
		 
		  		            
      FROM CLIENTES_FINAL_31 t1
	  ;

QUIT;


/*TIRANDO A DUPLICAÇÃO*/
/*TIRANDO A DUPLICAÇÃO*/
/*TIRANDO A DUPLICAÇÃO*/
/*TIRANDO A DUPLICAÇÃO*/


PROC SQL;

   CREATE TABLE TIRAR_DUPLI_ULT AS SELECT DISTINCT    

          t1.MCI,
	      MIN(t1.DATA_ABERTURA) FORMAT yymmdd10. AS DATA_ABERTURA		  
 
      FROM CLIENTES_FINAL_321 t1
      GROUP BY 1
      ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_321 AS SELECT DISTINCT    

                   *
             
      FROM CLIENTES_FINAL_321 t1
      INNER JOIN TIRAR_DUPLI_ULT t2 ON t1.MCI = t2.MCI AND t1.DATA_ABERTURA = t2.DATA_ABERTURA
      ORDER BY 1, 2;

QUIT;


/**/
/**/
/**/


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_322 AS 
      SELECT DISTINCT 

         t1.PREFDEP, 
         t1.MCI,		 
          
		 MAX(t1.PONTOS) AS PONTOS
 
      FROM CLIENTES_FINAL_321 t1
	  GROUP BY 1, 2;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_323 AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
         t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,          
		 t1.PONTOS,
		 IFN(t2.PREFDEP IS MISSING AND t2.MCI IS MISSING AND t2.PONTOS IS MISSING, 0, 1) AS MAXPONT
 
      FROM CLIENTES_FINAL_321 t1
	  LEFT JOIN CLIENTES_FINAL_322 t2 ON t1.PREFDEP = t2.PREFDEP AND t1.MCI = t2.MCI AND t1.PONTOS = t2.PONTOS
	  ORDER BY 11;

QUIT;


DATA CLIENTES_FINAL_325;

SET CLIENTES_FINAL_323 ;
BY PREFDEP;

IF FIRST.PREFDEP THEN SEQ = 0;

SEQ + 1;

run;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_326 AS 
      SELECT DISTINCT 

         t1.PREFDEP,
		 t1.MCI, 
		 t1.SEQ
 
      FROM CLIENTES_FINAL_325 t1
	  WHERE MAXPONT = 1
	  GROUP BY 1, 2
      ORDER BY 1, 2;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_327 AS 
      SELECT DISTINCT 

         t1.PREFDEP,
		 t1.MCI,
 
		 MAX(t1.SEQ) AS SEQ
 
      FROM CLIENTES_FINAL_326 t1
	  GROUP BY 1, 2
      ORDER BY 1, 2;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_328_B AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
         t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,          
		 t1.PONTOS,
		 IFN(t2.PREFDEP IS MISSING AND t2.MCI IS MISSING AND t2.SEQ IS MISSING, 0, 1) AS VALENDO
 
      FROM CLIENTES_FINAL_325 t1
	  LEFT JOIN CLIENTES_FINAL_327 t2 ON t1.PREFDEP = t2.PREFDEP AND t1.MCI = t2.MCI AND t1.SEQ = t2.SEQ
      GROUP BY 11 , 3
      ORDER BY 11, 3;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_550 AS 
      SELECT DISTINCT 
         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,

		 t1.QUALIFICADO,
		 IFC(t1.VALENDO = 1 AND t1.QUALIFICADO = "Sim", "Sim", "Não") as CONSIDERADO,

         t1.PONTOS,
         IFN(t1.VALENDO = 1 AND t1.QUALIFICADO = "Sim", t1.PONTOS, 0) as PTO_CONEXAO,

		 IFC(t1.VALENDO = 1, "Sim", "Não") AS VALENDO
 
      FROM CLIENTES_FINAL_328_B t1;

QUIT;


/*VERIFICANDO SE JA FORAM CONTABILIZADOS NO MES ANTERIOR*/
/*VERIFICANDO SE JA FORAM CONTABILIZADOS NO MES ANTERIOR*/
/*VERIFICANDO SE JA FORAM CONTABILIZADOS NO MES ANTERIOR*/
/*VERIFICANDO SE JA FORAM CONTABILIZADOS NO MES ANTERIOR*/


PROC SQL;
   CREATE TABLE CONEX_PROV_MES_ANT AS 
   SELECT DISTINCT 

         t1.CLI as MCI,
         t1.PREFDEP,
		 t1.VLR AS PTO_MES_ANT 

       FROM COX.cli_ind_000000180_dt&MESANO_ANT. t1
 	   WHERE t1.COMP = 3 AND t1.MMAAAA = &MESANO_ANT.
	   ORDER BY 1;
QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_COMPARA AS 
      SELECT DISTINCT 

         t1.PREFDEP AS AGENCIA,
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.AGENCIA AS PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,

		 t1.QUALIFICADO,
		 t1.CONSIDERADO,

	     t1.PONTOS,
		 t1.PTO_CONEXAO,

         t1.VALENDO,

		 t1.PTO_CONEXAO AS PTO_MES_ATU,
		 
		 COALESCE(t2.PTO_MES_ANT,0) AS PTO_MES_ANT 

 
      FROM CLIENTES_FINAL_550 t1
	  LEFT JOIN CONEX_PROV_MES_ANT t2 ON (t1.MCI = t2.MCI AND t1.PREFDEP = t2.PREFDEP)
	  
	  ;

QUIT;

PROC SQL;

   CREATE TABLE CLIENTES_FINAL_100 AS 
      SELECT DISTINCT 
         t1.PREFDEP AS AGENCIA,
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.AGENCIA AS PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,
		 t1.CONSIDERADO,
		 t1.pontos,
         t1.PTO_MES_ATU,
		 t1.PTO_MES_ANT
/**/
/*		 (t1.PTO_MES_ATU - t1.PTO_MES_ANT) AS PTO_CONEXAO*/
         
      FROM CLIENTES_COMPARA t1
	  
	  ;

QUIT;


PROC STDIZE DATA=CLIENTES_FINAL_100 OUT=CLIENTES_FINAL_100 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;

DATA NOVOS_CLI_PJ_&ANOMES_ANT;
 SET BASEANT.NOVOS_CLI_PJ_&ANOMES_ANT;
RUN;
 
PROC SQL;
   CREATE TABLE CLIENTES_FINAL_101 AS 
      SELECT DISTINCT 
         t1.AGENCIA,
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,
         IFN(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFN(t2.QUALIFICADO = "Sim", t2.COD_PCTE, t1.COD_PCTE), t1.COD_PCTE) AS COD_PCTE,
         IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim", t2.PACOTE_OK, t1.PACOTE_OK), t1.PACOTE_OK) AS PACOTE_OK,
		 CASE WHEN MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT. THEN 
		     IFN(t1.QUALIFICADO = "Sim", t2.DT_PACOTE, t1.DT_PACOTE)
		 ELSE t1.DT_PACOTE END AS DT_PACOTE,
         IFN(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFN(t2.QUALIFICADO = "Sim", t2.VLR_FATURAMENTO, t1.VLR_FATURAMENTO), t1.VLR_FATURAMENTO) AS VLR_FATURAMENTO,
         IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim", t2.REGRA_PACOTE, t1.REGRA_PACOTE), t1.REGRA_PACOTE) AS REGRA_PACOTE,
         IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim", t2.GEFIN, t1.GEFIN), t1.GEFIN) AS GEFIN,
         t1.PREFDEP,
         IFN(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFN(t2.QUALIFICADO = "Sim", t2.CARTEIRA, t1.CARTEIRA), t1.CARTEIRA) AS CARTEIRA,


         IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim",IFC(t1.pontos = 2, t2.CIELO, t1.CIELO), t1.CIELO),t1.CIELO) AS CIELO,
         IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim",IFC(t1.pontos = 2, t2.STELO, t1.STELO), t1.STELO),t1.STELO) AS STELO,
         IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim",IFC(t1.pontos = 2, t2.FOPAG, t1.FOPAG), t1.FOPAG),t1.FOPAG) AS FOPAG,
         IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim",IFC(t1.pontos = 2, t2.OP_CREDITO, t1.OP_CREDITO), t1.OP_CREDITO),t1.OP_CREDITO) AS OP_CREDITO,

		 IFC(MONTH(t1.DATA_ABERTURA) = &MES_POSICAO_ANT., IFC(t2.QUALIFICADO = "Sim",IFC(t1.pontos = 2, t2.QUALIFICADO, t1.QUALIFICADO), t1.QUALIFICADO),t1.QUALIFICADO) AS QUALIFICADO,

		 t1.PTO_MES_ANT
 
      FROM CLIENTES_FINAL_100 t1
	  LEFT JOIN NOVOS_CLI_PJ_&ANOMES_ANT. t2 on (t1.mci = t2.mci and t1.agencia = t2.agencia and t1.conta = t2.conta)
	  ;
QUIT;

PROC STDIZE DATA=CLIENTES_FINAL_101 OUT=CLIENTES_FINAL_101 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;

PROC SQL;
   CREATE TABLE CLIENTES_FINAL_102 AS 
      SELECT DISTINCT 
         t1.AGENCIA,
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,
         t1.COD_PCTE,
         t1.PACOTE_OK,
		 t1.DT_PACOTE,
         t1.VLR_FATURAMENTO,
         t1.REGRA_PACOTE,
         t1.GEFIN,
         t1.PREFDEP,
         t1.CARTEIRA,
         t1.CIELO,
         t1.STELO,
         t1.FOPAG,
         t1.OP_CREDITO,
         t1.QUALIFICADO,
         IFN(t1.PACOTE_OK = "Sim" AND t1.REGRA_PACOTE = "Sim" AND t1.GEFIN = "Sim", 1, 0) AS PT_QLF,
		 IFN(t1.CIELO = "Sim" OR t1.STELO = "Sim" OR t1.FOPAG = "Sim" OR t1.OP_CREDITO = "Sim", 1, 0) AS BONUS,
		 t1.PTO_MES_ANT,
		 IFN(t1.QUALIFICADO = "Sim", (CALCULATED BONUS + CALCULATED PT_QLF), 0) AS PONTOS
      FROM CLIENTES_FINAL_101 t1
	  ;
QUIT;

PROC SQL;
   CREATE TABLE CLIENTES_FINAL_103 AS 
      SELECT DISTINCT 
         t1.AGENCIA,
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,
         t1.COD_PCTE,
         t1.PACOTE_OK,
		 t1.DT_PACOTE,
         t1.VLR_FATURAMENTO,
         t1.REGRA_PACOTE,
         t1.GEFIN,
         t1.PREFDEP,
         t1.CARTEIRA,
         t1.CIELO,
         t1.STELO,
         t1.FOPAG,
         t1.OP_CREDITO,
         t1.QUALIFICADO,
		 t1.PTO_MES_ANT,
		 t1.PONTOS,
		 (t1.PONTOS - t1.PTO_MES_ANT) AS PTO_CONEXAO
      FROM CLIENTES_FINAL_102 t1
	  ;
QUIT;


/* daqui */



PROC SQL;

   CREATE TABLE CLIENTES_FINAL_104 AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.MCI,		 
          
		 MAX(t1.PONTOS) AS PONTOS
 
      FROM CLIENTES_FINAL_103 t1
	  GROUP BY 1, 2;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_105 AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
         t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,
         t1.PTO_MES_ANT,
		 t1.PONTOS,
		 t1.PTO_CONEXAO,
		 IFN(t2.AGENCIA IS MISSING AND t2.MCI IS MISSING AND t2.PONTOS IS MISSING, 0, 1) AS MAXPONT
 
      FROM CLIENTES_FINAL_103 t1
	  LEFT JOIN CLIENTES_FINAL_104 t2 ON t1.AGENCIA = t2.AGENCIA AND t1.MCI = t2.MCI AND t1.PONTOS = t2.PONTOS
	  ORDER BY 1;

QUIT;


DATA CLIENTES_FINAL_106;

SET CLIENTES_FINAL_105 ;
BY AGENCIA;

IF FIRST.AGENCIA THEN SEQ = 0;

SEQ + 1;

run;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_107 AS 
      SELECT DISTINCT 

         t1.AGENCIA,
		 t1.MCI, 
		 t1.SEQ
 
      FROM CLIENTES_FINAL_106 t1
	  WHERE MAXPONT = 1
	  GROUP BY 1, 2
      ORDER BY 1, 2;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_FINAL_108 AS 
      SELECT DISTINCT 

         t1.AGENCIA,
		 t1.MCI,
 
		 MAX(t1.SEQ) AS SEQ
 
      FROM CLIENTES_FINAL_107 t1
	  GROUP BY 1, 2
      ORDER BY 1, 2;

QUIT;

PROC SQL;
   CREATE TABLE CLIENTES_FINAL_328_C AS 
      SELECT DISTINCT 

         t1.AGENCIA, 
         t1.CONTA,
         t1.MCI,
         t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,          
		 IFC(t2.AGENCIA IS MISSING AND t2.MCI IS MISSING AND t2.SEQ IS MISSING, "Não",  "Sim") AS CONSIDERADO,
 		 t1.PONTOS,
		 IFN(CALCULATED CONSIDERADO = "Sim", t1.PONTOS, 0) AS PTO_MES_ATU,
		 IFN(CALCULATED CONSIDERADO = "Sim", t1.PTO_MES_ANT, 0) AS PTO_MES_ANT,
		 (CALCULATED PTO_MES_ATU - CALCULATED PTO_MES_ANT) AS PTO_CONEXAO
      FROM CLIENTES_FINAL_106 t1
	  LEFT JOIN CLIENTES_FINAL_108 t2 ON t1.AGENCIA = t2.AGENCIA AND t1.MCI = t2.MCI AND t1.SEQ = t2.SEQ
      GROUP BY 11 , 3
      ORDER BY 11, 3;
QUIT;


/* ate aqui */


%BuscarPrefixosIndicador(IND=180, MMAAAA=&MESANO., NIVEL_CTRA=1, SO_AG_PAA=1); 

PROC SQL;

   CREATE TABLE CLIENTES_FINAL_328 AS 
      SELECT DISTINCT 
	  	 t2.UOR,
         t1.AGENCIA,
         t1.CONTA,
         t1.MCI,
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,
         t1.PREFDEP, 
         t1.CARTEIRA,
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,
		 t1.CONSIDERADO,
		 t1.PTO_MES_ATU,
		 t1.PTO_MES_ANT,
		 t1.pontos,
		 IFN(t1.PTO_CONEXAO < 0, 0, t1.PTO_CONEXAO) AS PTO_CONEXAO
      FROM CLIENTES_FINAL_328_C t1
	  INNER JOIN PREFIXOS_IND_000000180 t2 ON t1.AGENCIA = t2.PREFDEP AND t1.CARTEIRA = t2.CTRA
  
	  ;

QUIT;

/**/
/*LIBNAME BASEANT '/dados/infor/producao/novos_clientes_PJ';*/
/**/
/*DATA BASEANT.NOVOS_CLI_PJ_&ANOMES.;*/
/* SET CLIENTES_FINAL_328;*/
/*RUN;*/

/* PARA CONEXÃO */
PROC SQL;

   CREATE TABLE CLIENTES_FINAL_32 AS 
      SELECT DISTINCT 

         t1.AGENCIA AS PREFDEP, 
         t1.MCI,	
         t1.CARTEIRA,
		 t1.UOR,
		 t1.QUALIFICADO,
		 t1.PTO_CONEXAO AS PONTOS	            
      FROM CLIENTES_FINAL_328 t1
      WHERE t1.CONSIDERADO = "Sim";


QUIT;


/*******************************************/
/*******************************************/
/*******************************************/
/*******************************************/

/*SUMARIZANDO PREFIXOS*/
/*SUMARIZANDO PREFIXOS*/

PROC SQL;

   CREATE TABLE CLIENTES_PREFIXO AS 
      SELECT 

      t1.PREFDEP,
      0 AS CTRA,   
	  t1.MCI,
	  t1.UOR,
      t1.PONTOS AS CONTAGEM

      FROM CLIENTES_FINAL_32 t1
	  WHERE t1.QUALIFICADO = "Sim"
	  ORDER BY 1
    ;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_PREFIXO_1 AS 
      SELECT DISTINCT 

         t1.PREFDEP, 
         t1.CTRA, 
         t1.UOR,
		 SUM(t1.CONTAGEM) AS CONTAGEM
		  		            
      FROM CLIENTES_PREFIXO t1	  
	  GROUP BY 1,2
	  ORDER BY 1,2
    ;

QUIT;


/*****SUMARIZANDO A HIERARQUIA******/
/*****SUMARIZANDO A HIERARQUIA******/
/*****SUMARIZANDO A HIERARQUIA******/
/*****SUMARIZANDO A HIERARQUIA******/


PROC SQL;
CREATE TABLE TABELA_AUXILIAR AS SELECT DISTINCT t1.PREFDEP, t2.PREFSUPREG, t2.PREFSUPEST, t2.PREFUEN, t1.CONTAGEM
FROM CLIENTES_PREFIXO_1 t1
LEFT JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.PREFDEP = input(t2.PREFDEP, 4.)
GROUP BY 1,2,3;
QUIT;


/**/

PROC SQL;
CREATE TABLE TABELA_FINAL_GEREV AS SELECT INPUT(t1.PREFSUPREG, 4.) AS PREFDEP, 0 AS CTRA, SUM(t1.CONTAGEM) AS CONTAGEM
FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE TABELA_FINAL_GEREV AS SELECT t1.PREFDEP, t1.CTRA, input(t2.UOR, 9.) AS UOR, t1.CONTAGEM
FROM TABELA_FINAL_GEREV t1
LEFT JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.PREFDEP = input(t2.PREFDEP, 4.)
;
QUIT;


/**/

PROC SQL;
CREATE TABLE TABELA_FINAL_SUPER AS SELECT INPUT(t1.PREFSUPEST, 4.) AS PREFDEP, 0 AS CTRA, SUM(CONTAGEM) AS CONTAGEM
FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE TABELA_FINAL_SUPER AS SELECT t1.PREFDEP, t1.CTRA, input(t2.UOR, 9.) AS UOR, t1.CONTAGEM
FROM TABELA_FINAL_SUPER t1
LEFT JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.PREFDEP = input(t2.PREFDEP, 4.)
;
QUIT;


/**/

PROC SQL;
CREATE TABLE TABELA_FINAL_SUPPJPF AS SELECT INPUT(t1.PREFUEN, 4.) AS PREFDEP, 0 AS CTRA, SUM(t1.CONTAGEM) AS CONTAGEM
FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE TABELA_FINAL_SUPPJPF AS SELECT t1.PREFDEP, t1.CTRA, input(t2.UOR, 9.) AS UOR, t1.CONTAGEM
FROM TABELA_FINAL_SUPPJPF t1
LEFT JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.PREFDEP = input(t2.PREFDEP, 4.)
;
QUIT;


/**/

PROC SQL;
CREATE TABLE TABELA_FINAL_DIR AS SELECT 8592 AS PREFDEP, 0 AS CTRA, 18948 AS UOR, SUM(t1.CONTAGEM) AS CONTAGEM
FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;


PROC SQL;
CREATE TABLE TABELA_FINAL_VICE AS SELECT 8166 AS PREFDEP, 0 AS CTRA, 18525 AS UOR, SUM(t1.CONTAGEM) AS CONTAGEM
FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;


/*SUMARIZANDO CARTEIRAS*/
/*SUMARIZANDO CARTEIRAS*/
/*SUMARIZANDO CARTEIRAS*/
/*SUMARIZANDO CARTEIRAS*/


%BuscarPrefixosIndicador(IND=180, MMAAAA=&MESANO., NIVEL_CTRA=1, SO_AG_PAA=1);


PROC SQL;

   CREATE TABLE CLIENTES_CARTEIRAS AS 
      SELECT DISTINCT 

         t1.PREFDEP, 
         t2.CARTEIRA AS CTRA,
         t1.MCI,
		 t1.UOR,
		 t1.CONTAGEM
		  		            
      FROM CLIENTES_PREFIXO t1

	LEFT JOIN CLIENTES_FINAL_32 t2 ON t1.PREFDEP = t2.PREFDEP AND t1.MCI = t2.MCI
	INNER JOIN PREFIXOS_IND_000000180 t3 ON t1.PREFDEP = t3.PREFDEP AND t2.CARTEIRA = t3.CTRA
    WHERE t2.CARTEIRA IS NOT MISSING
	ORDER BY 1, 3
	  
    ;

QUIT;


PROC SQL;

   CREATE TABLE CLIENTES_CARTEIRAS_1 AS 
      SELECT DISTINCT 

         t1.PREFDEP, 
         t1.CTRA,
         t1.UOR,
		 SUM(t1.CONTAGEM) AS CONTAGEM
		  		            
      FROM CLIENTES_CARTEIRAS t1
    GROUP BY 1, 2	
	ORDER BY 1, 2
	  
    ;

QUIT;


/*SUMARIZANDO PAA*/
/*SUMARIZANDO PAA*/
/*SUMARIZANDO PAA*/
/*SUMARIZANDO PAA*/


%BuscarPrefixosIndicador(IND=180, MMAAAA=&MESANO., NIVEL_CTRA=0, SO_AG_PAA=1);


PROC SQL;

   CREATE TABLE FINAL_PAA AS 
   SELECT distinct input(t2.PREFAGENC, 4.) AS PREFDEP, 0 AS CTRA, MCI, INPUT(t2.UOR, 9.) AS UOR, CONTAGEM

          FROM CLIENTES_PREFIXO t1
		  INNER JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.PREFDEP = input(t2.PREFDEP, 4.)
		  INNER JOIN PREFIXOS_IND_000000180 t3 ON input(t2.PREFAGENC, 4.) = t3.PREFDEP
		  WHERE input(t2.PREFAGENC, 4.) <> 0
	                
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE FINAL_PAA_1 AS 
   SELECT distinct PREFDEP, CTRA, UOR, SUM(CONTAGEM) AS CONTAGEM_PAA

          FROM FINAL_PAA t1
		  	        
   GROUP BY 1          
   ORDER BY 1;

QUIT;


/*SOMANDO OS PAAS NOS PREFIXOS*/
/*SOMANDO OS PAAS NOS PREFIXOS*/


DATA TABELA_PREFIXO_UNIDO;
	MERGE CLIENTES_PREFIXO_1 FINAL_PAA_1;
	BY PREFDEP CTRA UOR;
RUN;


PROC STDIZE DATA=TABELA_PREFIXO_UNIDO OUT=TABELA_PREFIXO_UNIDO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE TABELA_FINAL_700 AS 
   SELECT distinct t1.PREFDEP, t1.CTRA, T1.UOR, (t1.CONTAGEM + t1.CONTAGEM_PAA) AS CONTAGEM 

          FROM TABELA_PREFIXO_UNIDO t1
		  LEFT JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.PREFDEP = input(t2.PREFDEP, 4.)
		  	        
   GROUP BY 1, 2          
   ORDER BY 1;

QUIT;


PROC SQL;

CREATE TABLE CLIENTES_PJ_8 AS

   SELECT * FROM CLIENTES_CARTEIRAS_1
   OUTER UNION CORR 
   SELECT * FROM TABELA_FINAL_700
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_GEREV
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_SUPER
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_SUPPJPF
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_DIR
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_VICE
   ;

Quit;


/**ENVIANDO PARA O CONEXÃO**/
/**ENVIANDO PARA O CONEXÃO**/
/**ENVIANDO PARA O CONEXÃO**/
/**ENVIANDO PARA O CONEXÃO**/


PROC SQL;
    CREATE TABLE WORK.PARA_BASE_CONEXAO_COMP AS
        SELECT
            180 as ind, /*CODIGO INDICADOR 180 */
            3 as COMP, /*CODIGO COMPONENTE, SE NÃO FOR COMPONENTE USAR 0*/
            0 as COMP_PAI, /*CODIGO COMPONENTE PAI, SE NÃO FOR COMPONENTE USAR 0*/
            1 as ORD_EXI, /*ORDEM EXIBIÇÃO, SE NÃO FOR COMPONENTE USAR 0*/
            UOR,
            PREFDEP,
            CTRA,            
            CONTAGEM as VLR_RLZ, /*VALOR REALIZADO*/
            0 as VLR_ORC, /*VALOR ORÇADO*/
			0 as VLR_ATG, /*VALOR ATINGIMENTO, por padrão 0, enviar somente se o atingimento tiver regra de cálculo*/  
			&D1.  FORMAT YYMMDD10. AS POSICAO /*DATA DO VALOR LEVANTADO*/
        FROM WORK.CLIENTES_PJ_8
ORDER BY PREFDEP;
QUIT;


PROC SQL;
    CREATE TABLE WORK.PARA_BASE_CONEXAO_IND AS
        SELECT
            180 as ind, /*CODIGO INDICADOR*/
            0 as COMP, /*CODIGO COMPONENTE, SE NÃO FOR COMPONENTE USAR 0*/
            0 as COMP_PAI, /*CODIGO COMPONENTE PAI, SE NÃO FOR COMPONENTE USAR 0*/
            0 as ORD_EXI, /*ORDEM EXIBIÇÃO, SE NÃO FOR COMPONENTE USAR 0*/
            UOR,
            PREFDEP,
            CTRA,            
            CONTAGEM as VLR_RLZ, /*VALOR REALIZADO*/
            0 as VLR_ORC, /*VALOR ORÇADO*/
			0 as VLR_ATG, /*VALOR ATINGIMENTO, por padrão 0, enviar somente se o atingimento tiver regra de cálculo*/  
			&D1.  FORMAT YYMMDD10. AS POSICAO /*DATA DO VALOR LEVANTADO*/
        FROM WORK.CLIENTES_PJ_8
ORDER BY PREFDEP;
QUIT;


DATA PARA_BASE_CONEXAO;
SET PARA_BASE_CONEXAO_IND PARA_BASE_CONEXAO_COMP;
BY PREFDEP;
RUN;


/*CLIENTES*/
/*CLIENTES*/


PROC SQL;

   CREATE TABLE CLIENTES_PREFIXO_55 AS 
      SELECT DISTINCT *
		  		            
      FROM CLIENTES_PREFIXO t1
	  LEFT JOIN CLIENTES_CARTEIRAS t2 ON t1.MCI = t2.MCI
	  WHERE t2.MCI IS MISSING
	  GROUP BY 1,2
	  ORDER BY 1,2
    ;

QUIT;


PROC SQL;

CREATE TABLE CLIENTES_PJ_6 AS

   SELECT * FROM CLIENTES_CARTEIRAS
   OUTER UNION CORR 
   SELECT * FROM CLIENTES_PREFIXO_55
   OUTER UNION CORR 
   SELECT * FROM FINAL_PAA;

Quit;


PROC SQL;

    CREATE TABLE WORK.BASE_CONEXAO_CLI AS
        SELECT
            180 as IND,
            3 as COMP,
            t1.PREFDEP,
            t1.UOR,
            CTRA,
            MCI as CLI,
            &MESANO as MMAAAA,
            CONTAGEM as VLR
        FROM CLIENTES_PJ_6 t1
        WHERE CONTAGEM <> 0;

QUIT;

/**/
/*%BaseIndicadorCNX(TabelaSAS=PARA_BASE_CONEXAO);
%BaseIndicadorCNX_CLI(TabelaSAS=BASE_CONEXAO_CLI);
%ExportarCNX_CLI(IND=180, MMAAAA=&MESANO);
%ExportarCNX_IND(IND=180, MMAAAA=&MESANO, ORC=0, RLZ=1); 
%ExportarCNX_COMP(IND=180, MMAAAA=&MESANO, ORC=0, RLZ=1);*/


x cd /dados/infor/producao/cielo ;
x cd /dados/infor/producao/stelo ;
x cd /dados/gecen/interno/bases/cop ;
x cd /dados/infor/producao/cobranca_qualificada_19 ;


x chmod 2777 *;



/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/

/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/

/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/

/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/
/*****RELATORIO******/


PROC SQL;

   CREATE TABLE CLIENTES_REL_BASE AS 
      SELECT DISTINCT
         t1.UOR, 
         t1.AGENCIA,
		 t1.CONTA, 
         t1.MCI, 
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,	
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO FORMAT 32.2,
		 t1.REGRA_PACOTE,
		 t1.GEFIN, 
		 t1.PREFDEP,
         t1.CARTEIRA, 
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,
		 t1.CONSIDERADO, 
         t1.PTO_MES_ATU,
		 t1.PTO_MES_ANT,
		 t1.PONTOS,
		 t1.PTO_CONEXAO		  		            
      FROM CLIENTES_FINAL_328 t1
	  ;

QUIT;



/*****SUMARIZANDO******/
/*****SUMARIZANDO******/


PROC SQL;

   CREATE TABLE REL_1 AS 
      SELECT DISTINCT 

         t1.AGENCIA,
         t1.MCI, 
		 t1.CONTA,
         IFN(t1.PACOTE_OK = "Sim", 1, 0) as PACOTE_OK,
		 t1.VLR_FATURAMENTO,
	     IFN(t1.REGRA_PACOTE = "Sim", 1, 0) as REGRA_PACOTE,
		 IFN(t1.GEFIN = "Sim", 1, 0) as GEFIN,
		 IFN(t1.CIELO = "Sim", 1, 0) as CIELO,
		 IFN(t1.FOPAG = "Sim", 1, 0) as FOPAG,
		 IFN(t1.OP_CREDITO = "Sim", 1, 0) as OP_CREDITO,
		 IFN(t1.QUALIFICADO = "Sim", 1, 0) as QUALIFICADO,
		 IFN(t1.CONSIDERADO = "Sim", 1, 0) as CONSIDERADO,
		 t1.PTO_MES_ATU,
		 t1.PTO_MES_ANT,
		 t1.PTO_CONEXAO,
		 t1.PONTOS,
		 IFN(t1.STELO = "Sim", 1, 0) as STELO	  		            
      FROM CLIENTES_REL_BASE t1
      order by 1, 2;

QUIT;

PROC SQL;

   CREATE TABLE REL_PREFIXO AS 
      SELECT DISTINCT 

         t1.AGENCIA,
         SUM(t1.PACOTE_OK) as PACOTE_OK,
		 SUM(t1.VLR_FATURAMENTO) AS VLR_FATURAMENTO,
	     SUM(t1.REGRA_PACOTE) AS REGRA_PACOTE,
		 SUM(t1.GEFIN) AS GEFIN,
		 SUM(t1.CIELO) AS CIELO,
		 SUM(t1.FOPAG) AS FOPAG,
		 SUM(t1.OP_CREDITO) AS OP_CREDITO,
		 SUM(t1.QUALIFICADO) AS QUALIFICADO,
		 SUM(t1.CONSIDERADO) AS CONSIDERADO,
		 SUM(t1.PTO_MES_ATU) AS PTO_MES_ATU,
		 SUM(t1.PTO_MES_ANT) AS PTO_MES_ANT,
		 SUM(t1.PTO_CONEXAO) AS PTO_CONEXAO,
		 SUM(t1.PONTOS) AS PONTOS,
		 SUM(t1.STELO) AS STELO
		  		            
      FROM REL_1 t1
      GROUP BY 1;

QUIT;


/*PAA*/
/*PAA*/


%BuscarPrefixosIndicador(IND=180, MMAAAA=&MESANO., NIVEL_CTRA=0, SO_AG_PAA=1);

PROC SQL;

   CREATE TABLE REL_PREFIXO_PAA AS 
      SELECT DISTINCT 

         input(t2.PREFAGENC, 4.) AS AGENCIA,
         PACOTE_OK AS PACOTE_OK_1,
		 VLR_FATURAMENTO AS VLR_FATURAMENTO_1,
	     REGRA_PACOTE AS REGRA_PACOTE_1,
		 GEFIN AS GEFIN_1,
		 CIELO AS CIELO_1,
		 FOPAG AS FOPAG_1,
		 OP_CREDITO AS OP_CREDITO_1,
		 QUALIFICADO AS QUALIFICADO_1,
		 CONSIDERADO AS CONSIDERADO_1,
		 PTO_MES_ATU AS PTO_MES_ATU_1,
		 PTO_MES_ANT AS PTO_MES_ANT_1,
		 PTO_CONEXAO AS PTO_CONEXAO_1,
		 PONTOS AS PONTOS_1,
		 STELO AS STELO_1
		  		            
      FROM REL_PREFIXO t1
	      INNER JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.AGENCIA = input(t2.PREFDEP, 4.)
		  INNER JOIN PREFIXOS_IND_000000180 t3 ON input(t2.PREFAGENC, 4.) = t3.PREFDEP
		  WHERE input(t2.PREFAGENC, 4.) <> 0
      ORDER BY 1;

QUIT;



DATA TABELA_PREFIXO_REL_UNIDO;
	MERGE REL_PREFIXO REL_PREFIXO_PAA;
	BY AGENCIA;
RUN;

PROC STDIZE DATA=TABELA_PREFIXO_REL_UNIDO OUT=TABELA_PREFIXO_REL_UNIDO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE TABELA_PREFIXO_REL_UNIDO_2 AS 
      SELECT DISTINCT 

         t1.AGENCIA,
         (PACOTE_OK + PACOTE_OK_1) AS PACOTE_OK,
		 (VLR_FATURAMENTO + VLR_FATURAMENTO_1) AS VLR_FATURAMENTO,
	     (REGRA_PACOTE + REGRA_PACOTE_1) AS REGRA_PACOTE,
		 (GEFIN + GEFIN_1) AS GEFIN,
		 (CIELO + CIELO_1) AS CIELO,
		 (FOPAG + FOPAG_1) AS FOPAG,
		 (OP_CREDITO + OP_CREDITO_1) AS OP_CREDITO,
		 (QUALIFICADO + QUALIFICADO_1) AS QUALIFICADO,
		 (CONSIDERADO + CONSIDERADO_1) AS CONSIDERADO,
		 (PTO_MES_ATU + PTO_MES_ATU_1) AS PTO_MES_ATU,
		 (PTO_MES_ANT + PTO_MES_ANT_1) AS PTO_MES_ANT,
		 (PTO_CONEXAO + PTO_CONEXAO_1) AS PTO_CONEXAO,
		 (PONTOS + PONTOS_1) AS PONTOS,
		 (STELO + STELO_1) AS STELO
		  		            
      FROM TABELA_PREFIXO_REL_UNIDO t1
	     ORDER BY 1;

QUIT;

/*****************/


/*****SUMARIZANDO A HIERARQUIA******/
/*****SUMARIZANDO A HIERARQUIA******/
/*****SUMARIZANDO A HIERARQUIA******/
/*****SUMARIZANDO A HIERARQUIA******/


PROC SQL;
CREATE TABLE TABELA_AUXILIAR AS SELECT DISTINCT 

t1.AGENCIA, 
t2.PREFSUPREG, 
t2.PREFSUPEST, 
t2.PREFUEN,
t1.PACOTE_OK,
t1.VLR_FATURAMENTO,
t1.REGRA_PACOTE,
t1.GEFIN,
t1.CIELO,
t1.FOPAG,
t1.OP_CREDITO,
t1.QUALIFICADO,
t1.CONSIDERADO,
t1.PTO_MES_ATU,
t1.PTO_MES_ANT,
t1.PTO_CONEXAO,
t1.PONTOS,
t1.STELO

FROM REL_PREFIXO t1
LEFT JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.AGENCIA = input(t2.PREFDEP, 4.)
GROUP BY 1,2,3;
QUIT;



/**/

PROC SQL;
CREATE TABLE TABELA_FINAL_GEREV AS SELECT INPUT(t1.PREFSUPREG, 4.) AS AGENCIA,

SUM(t1.PACOTE_OK) AS PACOTE_OK,
SUM(t1.VLR_FATURAMENTO) AS VLR_FATURAMENTO,
SUM(t1.REGRA_PACOTE) AS REGRA_PACOTE,
SUM(t1.GEFIN) AS GEFIN,
SUM(t1.CIELO) AS CIELO,
SUM(t1.FOPAG) AS FOPAG,
SUM(t1.OP_CREDITO) AS OP_CREDITO,
SUM(t1.QUALIFICADO) AS QUALIFICADO,
SUM(IFN(t1.CONSIDERADO=1, 1,0)) AS CONSIDERADO,
SUM(t1.PTO_MES_ATU) AS PTO_MES_ATU,
SUM(t1.PTO_MES_ANT) AS PTO_MES_ANT,
SUM(t1.PTO_CONEXAO) AS PTO_CONEXAO,
SUM(t1.PONTOS) AS PONTOS,
SUM(t1.STELO) AS STELO

FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;



/**/


PROC SQL;
CREATE TABLE TABELA_FINAL_SUPER AS SELECT INPUT(t1.PREFSUPEST, 4.) AS AGENCIA,

SUM(t1.PACOTE_OK) AS PACOTE_OK,
SUM(t1.VLR_FATURAMENTO) AS VLR_FATURAMENTO,
SUM(t1.REGRA_PACOTE) AS REGRA_PACOTE,
SUM(t1.GEFIN) AS GEFIN,
SUM(t1.CIELO) AS CIELO,
SUM(t1.FOPAG) AS FOPAG,
SUM(t1.OP_CREDITO) AS OP_CREDITO,
SUM(t1.QUALIFICADO) AS QUALIFICADO,
SUM(IFN(t1.CONSIDERADO=1, 1,0)) AS CONSIDERADO,
SUM(t1.PTO_MES_ATU) AS PTO_MES_ATU,
SUM(t1.PTO_MES_ANT) AS PTO_MES_ANT,
SUM(t1.PTO_CONEXAO) AS PTO_CONEXAO,
SUM(t1.PONTOS) AS PONTOS,
SUM(t1.STELO) AS STELO

FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;


/**/


PROC SQL;
CREATE TABLE TABELA_FINAL_SUPPJPF AS SELECT INPUT(t1.PREFUEN, 4.) AS AGENCIA,

SUM(t1.PACOTE_OK) AS PACOTE_OK,
SUM(t1.VLR_FATURAMENTO) AS VLR_FATURAMENTO,
SUM(t1.REGRA_PACOTE) AS REGRA_PACOTE,
SUM(t1.GEFIN) AS GEFIN,
SUM(t1.CIELO) AS CIELO,
SUM(t1.FOPAG) AS FOPAG,
SUM(t1.OP_CREDITO) AS OP_CREDITO,
SUM(t1.QUALIFICADO) AS QUALIFICADO,
SUM(IFN(t1.CONSIDERADO=1, 1,0)) AS CONSIDERADO,
SUM(t1.PTO_MES_ATU) AS PTO_MES_ATU,
SUM(t1.PTO_MES_ANT) AS PTO_MES_ANT,
SUM(t1.PTO_CONEXAO) AS PTO_CONEXAO,
SUM(t1.PONTOS) AS PONTOS,
SUM(t1.STELO) AS STELO

FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;

/**/

PROC SQL;
CREATE TABLE TABELA_FINAL_DIR AS SELECT 8592 AS AGENCIA,

SUM(t1.PACOTE_OK) AS PACOTE_OK,
SUM(t1.VLR_FATURAMENTO) AS VLR_FATURAMENTO,
SUM(t1.REGRA_PACOTE) AS REGRA_PACOTE,
SUM(t1.GEFIN) AS GEFIN,
SUM(t1.CIELO) AS CIELO,
SUM(t1.FOPAG) AS FOPAG,
SUM(t1.OP_CREDITO) AS OP_CREDITO,
SUM(t1.QUALIFICADO) AS QUALIFICADO,
SUM(t1.CONSIDERADO) AS CONSIDERADO,
SUM(t1.PTO_MES_ATU) AS PTO_MES_ATU,
SUM(t1.PTO_MES_ANT) AS PTO_MES_ANT,
SUM(t1.PTO_CONEXAO) AS PTO_CONEXAO,
SUM(t1.PONTOS) AS PONTOS,
SUM(t1.STELO) AS STELO

FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;


/**/

PROC SQL;
CREATE TABLE TABELA_FINAL_VICE AS SELECT 8166 AS AGENCIA,

SUM(t1.PACOTE_OK) AS PACOTE_OK,
SUM(t1.VLR_FATURAMENTO) AS VLR_FATURAMENTO,
SUM(t1.REGRA_PACOTE) AS REGRA_PACOTE,
SUM(t1.GEFIN) AS GEFIN,
SUM(t1.CIELO) AS CIELO,
SUM(t1.FOPAG) AS FOPAG,
SUM(t1.OP_CREDITO) AS OP_CREDITO,
SUM(t1.QUALIFICADO) AS QUALIFICADO,
SUM(t1.CONSIDERADO) AS CONSIDERADO,
SUM(t1.PTO_MES_ATU) AS PTO_MES_ATU,
SUM(t1.PTO_MES_ANT) AS PTO_MES_ANT,
SUM(t1.PTO_CONEXAO) AS PTO_CONEXAO,
SUM(t1.PONTOS) AS PONTOS,
SUM(t1.STELO) AS STELO

FROM TABELA_AUXILIAR t1
GROUP BY 1;
QUIT;



PROC SQL;

CREATE TABLE RELATORIO_350 AS

   SELECT * FROM TABELA_PREFIXO_REL_UNIDO_2
   OUTER UNION CORR 
   SELECT * FROM TABELA_FINAL_GEREV
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_SUPER
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_SUPPJPF
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_DIR
   OUTER UNION CORR
   SELECT * FROM TABELA_FINAL_VICE
   ;

Quit;


PROC SQL;

CREATE TABLE RELATORIO_350 AS SELECT     *

FROM RELATORIO_350 t1
ORDER BY 1;

QUIT;

PROC SQL;
   CREATE TABLE ACRESCIMO AS 
   SELECT  

          PREFDEP AS AGENCIA,
          CONTAGEM

       FROM CLIENTES_PJ_8 t1
	   WHERE CTRA = 0
 	   
	   ORDER BY 1,2;
QUIT;


DATA JUNTANDO_RELATORIO;
	MERGE RELATORIO_350 ACRESCIMO ;
	BY AGENCIA;
RUN;


PROC STDIZE DATA=JUNTANDO_RELATORIO OUT=JUNTANDO_RELATORIO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
   CREATE TABLE RELATORIO_350 AS 
   SELECT  
          
		 t1.AGENCIA,
         t1.PACOTE_OK,
		 t1.VLR_FATURAMENTO,
		 t1.REGRA_PACOTE,
		 t1.GEFIN,         
		 t1.CIELO,		 
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,
		 CONTAGEM AS PONTOS,
         t1.STELO,
		 t1.CONSIDERADO
       FROM JUNTANDO_RELATORIO t1	    	   
	   ORDER BY 1;
QUIT;


/************************/
/************************/
/************************/
/************************/

/*CLIENTES PAA*/

%BuscarPrefixosIndicador(IND=180, MMAAAA=&MESANO., NIVEL_CTRA=0, SO_AG_PAA=1);

PROC SQL;

   CREATE TABLE CLIENTES_REL_BASE_PAA AS 
      SELECT DISTINCT 
         t1.UOR, 
         t1.AGENCIA,
		 t1.CONTA, 
         t1.MCI, 
		 t1.DATA_ABERTURA,	
		 t1.COD_PCTE,	
		 t1.PACOTE_OK,	
		 t1.DT_PACOTE,
		 t1.VLR_FATURAMENTO FORMAT 32.2,
		 t1.REGRA_PACOTE,
		 t1.GEFIN, 
		 t1.PREFDEP,
         t1.CARTEIRA, 
		 t1.CIELO,
		 t1.STELO,
		 t1.FOPAG,
         t1.OP_CREDITO,
		 t1.QUALIFICADO,
		 t1.CONSIDERADO, 
         t1.PTO_MES_ATU,
		 t1.PTO_MES_ANT,
		 t1.PONTOS,
		 t1.PTO_CONEXAO	
      FROM CLIENTES_REL_BASE t1
INNER JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.AGENCIA = input(t2.PREFDEP, 4.)
INNER JOIN PREFIXOS_IND_000000180 t3 ON input(t2.PREFAGENC, 4.) = t3.PREFDEP
WHERE input(t2.PREFAGENC, 4.) <> 0
	  ;

QUIT;

 
PROC SQL;

CREATE TABLE REL_CLIENTES_FINAL_350_A AS

   SELECT * FROM CLIENTES_REL_BASE
   OUTER UNION CORR 
   SELECT * FROM CLIENTES_REL_BASE_PAA
   ;

Quit;

PROC SQL;
   CREATE TABLE REL_CLIENTES_FINAL_350 AS 
   SELECT t1.AGENCIA, 
          t1.MCI,
          t1.CONTA, 
          t1.DATA_ABERTURA, 
          t1.COD_PCTE, 
          t1.DT_PACOTE, 
          t1.PACOTE_OK, 
          t1.VLR_FATURAMENTO, 
          t1.REGRA_PACOTE, 
          t1.GEFIN, 
          t1.CIELO, 
          t1.STELO, 
          t1.FOPAG,
          t1.OP_CREDITO, 
          t1.PREFDEP, 
          t1.CARTEIRA, 
          t1.QUALIFICADO, 
          t1.PONTOS, 
          t1.CONSIDERADO, 
          t1.PTO_MES_ATU, 
          t1.PTO_MES_ANT, 
          t1.PTO_CONEXAO
      FROM REL_CLIENTES_FINAL_350_A t1;
QUIT;


/*ORCADO*/
/*ORCADO*/

PROC SQL;

CREATE TABLE ORCADO_1 AS SELECT 
 
 t1.PREFDEP AS AGENCIA,
 t1.VLR FORMAT 32.2 AS ORCADO

FROM COX1.IND_ORC_000000180 t1
INNER JOIN PREFIXOS_IND_000000180 t2 ON t1.PREFDEP = t2.PREFDEP
WHERE t1.MMAAAA = &MESANO. AND t1.CTRA = 0;

Quit;


DATA RELATORIO_25;
	MERGE RELATORIO_350 ORCADO_1;
	BY AGENCIA;
RUN;


PROC STDIZE DATA=RELATORIO_25 OUT=RELATORIO_25 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE RELATORIO_25 AS 
      SELECT DISTINCT 
         t1.AGENCIA as PREFDEP,
         t1.PACOTE_OK,
		 t1.VLR_FATURAMENTO,
	     t1.REGRA_PACOTE,
		 t1.GEFIN,
		 t1.CIELO,
		 t1.FOPAG,
		 t1.OP_CREDITO,
		 t1.QUALIFICADO,
		 t1.PONTOS,
	     t1.STELO,
		 t1.ORCADO
/*		 t1.CONSIDERADO		  		            */
      FROM RELATORIO_25 t1
      GROUP BY 1;

QUIT;



data RELATORIO_25;
format POSICAO yymmdd10.;
set RELATORIO_25;
POSICAO = &D1;
run;


/*ENVIANDO PARA O RELATORIO*/

/*Rel   */
/**/
/*%LET Usuario=f7176219;*/
/*%LET Keypass=novos-clientes-pj-2019-IpzUY9y6pKZfRUjif0FVjaEXInKPsyQ009g1JpzYF1xFbIvGhF;*/
/*%LET Rotina=novos-clientes-pj-2019;*/
/*%ProcessoIniciar();*/
/**/
/**/
/*PROC SQL;*/
/*	DROP TABLE TABELAS_EXPORTAR_REL;*/
/*	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));*/
/*	INSERT INTO TABELAS_EXPORTAR_REL VALUES('RELATORIO_25', 'novos-clientes-pj-2019');*/
/*	INSERT INTO TABELAS_EXPORTAR_REL VALUES('REL_CLIENTES_FINAL_350', 'detalhe');*/
/*   ;*/
/*QUIT;*/
/**/
/*/**/*/
/*%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);*/
