%INCLUDE '/dados/infor/suporte/FuncoesInfor.sas';

Libname DIRAO "/dados/dirao/publico";

	%diasUteis(%sysfunc(today()), 5);
			%GLOBAL DiaUtil_D0 DiaUtil_D1;


			data arq;
				format 
					anomes yymmn6.
					mesano z6.
					DiaUtil_D1 date9.
					mes z2.
					ano 4.;
				anomes = &diaUtil_d1;
				mesano = INPUT(PUT(&diaUtil_d1, mmyyn6.),6.);
				DiaUtil_D1 = &diaUtil_d1;
				mes = month(&diaUtil_d1);
				ano = year(&diaUtil_d1);
			run;

			%put &D_mais_2;
			%put &DiaUtil_D0;

			proc sql;
				select anomes, DiaUtil_D1,   mes, ano, mesano

				into :anomes, :DiaUtil_D1, :mes, :ano, :mesano
					from arq;
			quit;

			%put &anomes &mesano &DiaUtil_D1 &ano &mes;


DATA _NULL_;
D1=DiaUtilAnterior(Today());
CALL SYMPUT('D1',D1);
run;


%Macro Encarteiramento;

	proc sql;
		create table encarteiramento as
			select put(cd_prf_depe, z4.) as prefdep,
				ifn(cd_tip_ctra in (10 16 50 56 57 60 77 303 315 321 322 323 324 328), nr_seql_ctra, 7002) as carteira,
				e.cd_cli
			from comum.pai_rel_&AnoMes e
				inner join base_mci a on(e.cd_cli=a.cd_cli)
					where cd_prf_depe not in(4777 8008 9940)
						order by 3;
	quit;

	proc sql noprint;
		select count(*) into: q
			from (select cd_cli
			from encarteiramento
				group by 1
					having count(*)>1);
	quit;

	%put &q;

	%IF &Q>0 %THEN
		%DO;

			DATA DUPLICADOS(DROP=CARTEIRA);
				SET ENCARTEIRAMENTO(Obs=0);
			RUN;

			PROC SQL;
				CREATE TABLE AUX_D AS
					SELECT CD_CLI
						FROM ENCARTEIRAMENTO
							GROUP BY 1
								HAVING COUNT(*)>1;
			QUIT;

			DATA AUX_D(DROP=Seq);
				SET AUX_D;
				Seq+1;
				Grupo=CEIL(Seq/5957);
			RUN;

			PROC SQL NOPRINT;
				SELECT MAX(Grupo) INTO: Q
					FROM AUX_D;
			QUIT;

			%DO I=1 %TO &Q;

				PROC SQL NOPRINT;
					SELECT CD_CLI INTO: Var Separated By ', '
						FROM AUX_D
							WHERE Grupo=&I;
				QUIT;

				PROC SQL;
					CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
					INSERT INTO DUPLICADOS
						SELECT Put(COD_PREF_AGEN, Z4.), COD
							FROM CONNECTION TO DB2
								(SELECT COD, COD_PREF_AGEN
									FROM DB2MCI.CLIENTE
										WHERE COD IN(&Var)
											ORDER BY COD;);
					DISCONNECT FROM DB2;
				QUIT;

				PROC SQL;
					CREATE TABLE FIM_DUP AS
						SELECT A.*, carteira
							FROM DUPLICADOS A
								INNER JOIN ENCARTEIRAMENTO B ON(A.CD_CLI=B.CD_CLI AND A.PrefDep=B.PrefDep)
									ORDER BY 2;
					DELETE FROM DUPLICADOS;
				QUIT;

				DATA ENCARTEIRAMENTO;
					SET ENCARTEIRAMENTO(WHERE=(CD_CLI NOT IN(&Var.))) FIM_DUP;
					BY CD_CLI;
				RUN;

			%END;
		%END;

	PROC DELETE DATA=FIM_DUP AUX_D;
	RUN;

	PROC SQL NOPRINT;
		SELECT COUNT(*) INTO: Q
			FROM (SELECT DISTINCT A.CD_CLI
			FROM base_mci A
				LEFT JOIN ENCARTEIRAMENTO B ON(A.CD_CLI=B.CD_CLI)
					WHERE B.CD_CLI Is Missing);
	QUIT;

	%IF &Q>0 %THEN
		%DO;

			DATA PERDIDOS;
				SET ENCARTEIRAMENTO(Obs=0);
			RUN;

			PROC SQL;
				CREATE TABLE AUX_P AS
					SELECT DISTINCT A.CD_CLI
						FROM base_mci A
							LEFT JOIN ENCARTEIRAMENTO B ON(A.CD_CLI=B.CD_CLI)
								WHERE B.CD_CLI Is Missing;
			QUIT;

			DATA AUX_P(DROP=Seq);
				SET AUX_P;
				Seq+1;
				Grupo=CEIL(Seq/5957);
			RUN;

			PROC SQL NOPRINT;
				SELECT MAX(Grupo) INTO: Q
					FROM AUX_P;
			QUIT;

			%DO I=1 %TO &Q;

				/*				PROC SQL;*/
				/*					DROP TABLE DB2SGCEN.APAGAR_180205;*/
				/*					CREATE TABLE DB2SGCEN.APAGAR_180205 AS*/
				/*						SELECT DISTINCT CD_CLI FORMAT Z9.*/
				/*							FROM AUX_P;*/
				/*				QUIT;*/
				PROC SQL NOPRINT;
					SELECT CD_CLI Format 9. INTO: Var Separated By ', '
						FROM AUX_P
							WHERE Grupo=&I;
				QUIT;

				%LET Filtro=B.TipoDep In('013' '015' '035') AND SB='00';

				PROC SQL;
					CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
					INSERT INTO PERDIDOS
						SELECT Put(COD_PREF_AGEN, Z4.) AS PrefDep, 
							7002 AS Carteira,
							COD AS CD_CLI
						FROM CONNECTION TO DB2
							(SELECT COD, 
								COD_PREF_AGEN
							FROM DB2MCI.CLIENTE A 
								/*								INNER JOIN DB2SGCEN.APAGAR_180205 B ON(A.COD=B.CD_CLI)*/
							WHERE COD IN(&Var)
								ORDER BY COD;) A
									INNER JOIN IGR.DEPENDENCIAS B ON(A.COD_PREF_AGEN=Input(B.PrefDep, 4.))
										WHERE &Filtro;
					DISCONNECT FROM DB2;

					/*					DROP TABLE DB2SGCEN.APAGAR_180205;*/
				QUIT;

			%END;

			PROC SORT DATA=PERDIDOS NODUPKEY;
				BY CD_CLI;
			RUN;

			DATA ENCARTEIRAMENTO;
				SET ENCARTEIRAMENTO PERDIDOS;
				BY CD_CLI;
			RUN;

			PROC DELETE DATA=AUX_P PERDIDOS;
			RUN;

		%END;
%Mend;



PROC SQL;
   CREATE TABLE Base_CLI AS 
   SELECT t1.CD_CLI, 
          put(t1.dt_lcto,yymmn6.) as anomes, 
       
            (SUM(t1.VL_LCTO_RAO)) FORMAT=COMMAX19.2 AS Valor
      FROM dirao.base_dirao_rao_p_dirco t1
      WHERE t1.CD_CNL_CTRC NOT IN 
           (
           1,
           1008
           ) and (calculated anomes)="&anomes"
      GROUP BY 1,2;
QUIT;


	data base_mci(keep = cd_cli);
				set Base_CLI;

			run;

			proc sort data = base_mci nodupkey;
				by cd_cli;
			run;

			%Encarteiramento;

			
PROC SQL;
   CREATE TABLE Valor_fim AS 
   SELECT t1.prefdep, 
          t1.carteira, 
          sum(t2.Valor) as valor
      FROM ENCARTEIRAMENTO t1
           INNER JOIN BASE_CLI t2 ON (t1.CD_CLI = t2.CD_CLI) group by 1,2;
QUIT;


PROC SQL;
	CREATE TABLE BBM AS
		SELECT 
			"20001530464"||REPEAT(" ",45)||PrefDep||Put(Carteira, Z5.)||"&AnoMes"||"0001+"||Put(Coalesce(Valor,0)*100, Z13.)||"F7176219"||Put("&DiaUtil_D1"d, ddmmyy10.)||"N" AS T
		FROM Valor_fim
		
			;
QUIT;

%let EB=BNRA&MES;

%GerarBBM(BBM, /dados/infor/transfer/enviar/, &EB);


/****************************/
/****************************/
/*PROCESSAMENTO DO RELATÓRIO*/
/****************************/
/****************************/

/***/


PROC SQL;

    CREATE TABLE PERDAS_ESTOQUE AS
    SELECT 
	NR_UNCO_CTR_OPR,
    CD_PSS_CLI_OPR AS MCI,
	SALDO,
	DT_PDA_POS_2010
    FROM DIRAO.LST_QLF_GECEN_PEC_Pda 
    WHERE DT_PDA_POS_2010 >= '01JUL2013'd AND DT_PDA_POS_2010 <= '31DEC2018'd;
         
QUIT;

/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_JUL
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01JUL2013'd AND DT_PDA_POS_2010 < '01JUL2018'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_JUL) AS VALOR_PERDAS_JUL
		  		  
   FROM COMP_PERDAS_JUL t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_JUL
		  		  
   FROM COMP_PERDAS_JUL t1
   LEFT JOIN comum.pai_rel_201807 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_JUL OUT=COMP_PERDAS_JUL REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_JUL) AS VALOR_PERDAS_JUL
		  		  
   FROM COMP_PERDAS_JUL t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;



/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_AGO
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01AUG2013'd AND DT_PDA_POS_2010 < '01AUG2018'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_AGO) AS VALOR_PERDAS_AGO
		  		  
   FROM COMP_PERDAS_AGO t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_AGO
		  		  
   FROM COMP_PERDAS_AGO t1
   LEFT JOIN comum.pai_rel_201808 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_AGO OUT=COMP_PERDAS_AGO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_AGO) AS VALOR_PERDAS_AGO
		  		  
   FROM COMP_PERDAS_AGO t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_SET
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01SEP2013'd AND DT_PDA_POS_2010 < '01SEP2018'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_SET) AS VALOR_PERDAS_SET
		  		  
   FROM COMP_PERDAS_SET t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_SET
		  		  
   FROM COMP_PERDAS_SET t1
   LEFT JOIN comum.pai_rel_201809 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_SET OUT=COMP_PERDAS_SET REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_SET) AS VALOR_PERDAS_SET
		  		  
   FROM COMP_PERDAS_SET t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_OUT
		  		  
   FROM PERDAS_ESTOQUE t1
    WHERE DT_PDA_POS_2010 >= '01OCT2013'd AND DT_PDA_POS_2010 < '01OCT2018'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_OUT) AS VALOR_PERDAS_OUT
		  		  
   FROM COMP_PERDAS_OUT t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_OUT
		  		  
   FROM COMP_PERDAS_OUT t1
   LEFT JOIN comum.pai_rel_201810 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_OUT OUT=COMP_PERDAS_OUT REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_OUT) AS VALOR_PERDAS_OUT
		  		  
   FROM COMP_PERDAS_OUT t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/

PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_NOV
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01NOV2013'd AND DT_PDA_POS_2010 < '01NOV2018'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_NOV) AS VALOR_PERDAS_NOV
		  		  
   FROM COMP_PERDAS_NOV t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_NOV
		  		  
   FROM COMP_PERDAS_NOV t1
   LEFT JOIN comum.pai_rel_201811 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_NOV OUT=COMP_PERDAS_NOV REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_NOV) AS VALOR_PERDAS_NOV
		  		  
   FROM COMP_PERDAS_NOV t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          MCI,
          SALDO AS VALOR_PERDAS_DEZ
		  		  
   FROM PERDAS_ESTOQUE t1
   WHERE DT_PDA_POS_2010 >= '01DEC2013'd AND DT_PDA_POS_2010 < '01DEC2018'd
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          DISTINCT MCI,
          SUM(VALOR_PERDAS_DEZ) AS VALOR_PERDAS_DEZ
		  		  
   FROM COMP_PERDAS_DEZ t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_PERDAS_DEZ
		  		  
   FROM COMP_PERDAS_DEZ t1
   LEFT JOIN comum.pai_rel_201812 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_DEZ OUT=COMP_PERDAS_DEZ REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_PERDAS_DEZ) AS VALOR_PERDAS_DEZ
		  		  
   FROM COMP_PERDAS_DEZ t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/


PROC SQL;

   CREATE TABLE COMP_PERDAS_1 AS
 
   SELECT 
            t1.PREFIXO AS PREFIXO_1, t2.PREFIXO AS PREFIXO_2, t3.PREFIXO AS PREFIXO_3, t4.PREFIXO AS PREFIXO_4, t5.PREFIXO AS PREFIXO_5, t6.PREFIXO AS PREFIXO_6,
            t1.CARTEIRA AS CARTEIRA_1, t2.CARTEIRA  AS CARTEIRA_2, t3.CARTEIRA AS CARTEIRA_3, t4.CARTEIRA AS CARTEIRA_4, t5.CARTEIRA AS CARTEIRA_5, t6.CARTEIRA AS CARTEIRA_6,
            VALOR_PERDAS_JUL, VALOR_PERDAS_AGO, VALOR_PERDAS_SET, VALOR_PERDAS_OUT, VALOR_PERDAS_NOV, VALOR_PERDAS_DEZ
          		  		  
   FROM COMP_PERDAS_JUL t1
   FULL JOIN COMP_PERDAS_AGO t2 ON t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA
   FULL JOIN COMP_PERDAS_SET t3 ON t1.PREFIXO = t3.PREFIXO AND t1.CARTEIRA = t3.CARTEIRA
   FULL JOIN COMP_PERDAS_OUT t4 ON t1.PREFIXO = t4.PREFIXO AND t1.CARTEIRA = t4.CARTEIRA
   FULL JOIN COMP_PERDAS_NOV t5 ON t1.PREFIXO = t5.PREFIXO AND t1.CARTEIRA = t5.CARTEIRA
   FULL JOIN COMP_PERDAS_DEZ t6 ON t1.PREFIXO = t6.PREFIXO AND t1.CARTEIRA = t6.CARTEIRA
   ORDER BY 1,2;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_1 OUT=COMP_PERDAS_1 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_2 AS
 
   SELECT 

   IFN(PREFIXO_1 <> 0, PREFIXO_1, IFN(PREFIXO_2 <> 0, PREFIXO_2, IFN(PREFIXO_3 <> 0, PREFIXO_3, IFN(PREFIXO_4 <> 0, PREFIXO_4, IFN(PREFIXO_5 <> 0, PREFIXO_5, PREFIXO_6))))) AS PREFIXO,
   IFN(CARTEIRA_1 <> 0, CARTEIRA_1, IFN(CARTEIRA_2 <> 0, CARTEIRA_2, IFN(CARTEIRA_3 <> 0, CARTEIRA_3, IFN(CARTEIRA_4 <> 0, CARTEIRA_4, IFN(CARTEIRA_5 <> 0, CARTEIRA_5, CARTEIRA_6))))) AS CARTEIRA,
   VALOR_PERDAS_JUL, VALOR_PERDAS_AGO, VALOR_PERDAS_SET, VALOR_PERDAS_OUT, VALOR_PERDAS_NOV, VALOR_PERDAS_DEZ,
   (VALOR_PERDAS_DEZ) AS VALOR_PERDAS_SEM
          		  		  
   FROM COMP_PERDAS_1 t1
   ORDER BY 1,2;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_3 AS
 
   SELECT 
   DISTINCT PREFIXO,
   CARTEIRA,
   
   SUM(VALOR_PERDAS_JUL) AS VALOR_PERDAS_JUL, SUM(VALOR_PERDAS_AGO) AS VALOR_PERDAS_AGO, SUM(VALOR_PERDAS_SET) AS VALOR_PERDAS_SET, SUM(VALOR_PERDAS_OUT) AS VALOR_PERDAS_OUT, 
   SUM(VALOR_PERDAS_NOV) AS VALOR_PERDAS_NOV, SUM(VALOR_PERDAS_DEZ) AS VALOR_PERDAS_DEZ, SUM(VALOR_PERDAS_SEM) AS VALOR_PERDAS_SEM
          		  		  
   FROM COMP_PERDAS_2 t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_4 AS
 
   SELECT *	  
   FROM COMP_PERDAS_3
   WHERE PREFIXO <> 0
   ORDER BY 1,2;

QUIT;


/*******************************/
/*******************************/
/*******************************/


PROC SQL;
   CREATE TABLE COMP_PERDAS_REC AS 
   SELECT DISTINCT 

   t1.CD_CLI AS MCI, 
   put(t1.dt_lcto,yymmn6.) as ANOMES, 
   (SUM(t1.VL_LCTO_RAO)) FORMAT=COMMAX19.2 AS VALOR_REC

FROM dirao.base_dirao_rao_p_dirco t1
WHERE t1.CD_CNL_CTRC NOT IN ( 1, 1008) and (calculated anomes)>="201807" And (calculated anomes)<="201812"
GROUP BY 1,2
ORDER BY 1,2;
QUIT;


/*JULHO*/

PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201807"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_JUL) AS VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_JUL_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_JUL_REC t1
   LEFT JOIN comum.pai_rel_201807 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_JUL_REC OUT=COMP_PERDAS_JUL_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_JUL_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_JUL) AS VALOR_REC_JUL
		  		  
   FROM COMP_PERDAS_JUL_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/*AGOSTO*/

PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201808"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_AGO) AS VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_AGO_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_AGO_REC t1
   LEFT JOIN comum.pai_rel_201808 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_AGO_REC OUT=COMP_PERDAS_AGO_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_AGO_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_AGO) AS VALOR_REC_AGO
		  		  
   FROM COMP_PERDAS_AGO_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/*SETEMBRO*/

PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201809"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_SET) AS VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_SET_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;

PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_SET_REC t1
   LEFT JOIN comum.pai_rel_201809 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_SET_REC OUT=COMP_PERDAS_SET_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_SET_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_SET) AS VALOR_REC_SET
		  		  
   FROM COMP_PERDAS_SET_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;

/*OUTUBRO*/

PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201810"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_OUT) AS VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_OUT_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_OUT_REC t1
   LEFT JOIN comum.pai_rel_201810 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_OUT_REC OUT=COMP_PERDAS_OUT_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_OUT_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_OUT) AS VALOR_REC_OUT
		  		  
   FROM COMP_PERDAS_OUT_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/*NOVEMBRO*/


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201811"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_NOV) AS VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_NOV_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_NOV_REC t1
   LEFT JOIN comum.pai_rel_201811 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_NOV_REC OUT=COMP_PERDAS_NOV_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_NOV_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_NOV) AS VALOR_REC_NOV
		  		  
   FROM COMP_PERDAS_NOV_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/*DEZEMBRO*/


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          MCI,
          VALOR_REC AS VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_REC t1
   WHERE ANOMES = "201812"
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          MCI,
          SUM(VALOR_REC_DEZ) AS VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_DEZ_REC t1
   GROUP BY 1
   ORDER BY 1;

QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          DISTINCT t1.MCI,
		  t2.CD_PRF_DEPE AS PREFIXO,
          t2.NR_SEQL_CTRA_ATB AS CARTEIRA,
          t1.VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_DEZ_REC t1
   LEFT JOIN comum.pai_rel_201812 t2 ON MCI = t2.CD_CLI
   ORDER BY 1;

QUIT;


PROC STDIZE DATA=COMP_PERDAS_DEZ_REC OUT=COMP_PERDAS_DEZ_REC REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_PERDAS_DEZ_REC AS
 
   SELECT 
          DISTINCT PREFIXO,
          CARTEIRA,
          SUM(t1.VALOR_REC_DEZ) AS VALOR_REC_DEZ
		  		  
   FROM COMP_PERDAS_DEZ_REC t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


/***/

PROC SQL;

   CREATE TABLE COMP_REC_1 AS
 
   SELECT 
            t1.PREFIXO AS PREFIXO_1, t2.PREFIXO AS PREFIXO_2, t3.PREFIXO AS PREFIXO_3, t4.PREFIXO AS PREFIXO_4, t5.PREFIXO AS PREFIXO_5, t6.PREFIXO AS PREFIXO_6,
            t1.CARTEIRA AS CARTEIRA_1, t2.CARTEIRA  AS CARTEIRA_2, t3.CARTEIRA AS CARTEIRA_3, t4.CARTEIRA AS CARTEIRA_4, t5.CARTEIRA AS CARTEIRA_5, t6.CARTEIRA AS CARTEIRA_6,
            VALOR_REC_JUL, VALOR_REC_AGO, VALOR_REC_SET, VALOR_REC_OUT, VALOR_REC_NOV, VALOR_REC_DEZ
          		  		  
   FROM COMP_PERDAS_JUL_REC t1
   FULL JOIN COMP_PERDAS_AGO_REC t2 ON t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA
   FULL JOIN COMP_PERDAS_SET_REC t3 ON t1.PREFIXO = t3.PREFIXO AND t1.CARTEIRA = t3.CARTEIRA
   FULL JOIN COMP_PERDAS_OUT_REC t4 ON t1.PREFIXO = t4.PREFIXO AND t1.CARTEIRA = t4.CARTEIRA
   FULL JOIN COMP_PERDAS_NOV_REC t5 ON t1.PREFIXO = t5.PREFIXO AND t1.CARTEIRA = t5.CARTEIRA
   FULL JOIN COMP_PERDAS_DEZ_REC t6 ON t1.PREFIXO = t6.PREFIXO AND t1.CARTEIRA = t6.CARTEIRA
   ORDER BY 1,2;

QUIT;


PROC STDIZE DATA=COMP_REC_1 OUT=COMP_REC_1 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_REC_2 AS
 
   SELECT 

   IFN(PREFIXO_1 <> 0, PREFIXO_1, IFN(PREFIXO_2 <> 0, PREFIXO_2, IFN(PREFIXO_3 <> 0, PREFIXO_3, IFN(PREFIXO_4 <> 0, PREFIXO_4, IFN(PREFIXO_5 <> 0, PREFIXO_5, PREFIXO_6))))) AS PREFIXO,
   IFN(CARTEIRA_1 <> 0, CARTEIRA_1, IFN(CARTEIRA_2 <> 0, CARTEIRA_2, IFN(CARTEIRA_3 <> 0, CARTEIRA_3, IFN(CARTEIRA_4 <> 0, CARTEIRA_4, IFN(CARTEIRA_5 <> 0, CARTEIRA_5, CARTEIRA_6))))) AS CARTEIRA,
   VALOR_REC_JUL, VALOR_REC_AGO, VALOR_REC_SET, VALOR_REC_OUT, VALOR_REC_NOV, VALOR_REC_DEZ,
   (VALOR_REC_JUL + VALOR_REC_AGO + VALOR_REC_SET + VALOR_REC_OUT + VALOR_REC_NOV + VALOR_REC_DEZ) AS VALOR_REC_SEM
          		  		  
   FROM COMP_REC_1 t1
   ORDER BY 1,2;

QUIT;




PROC SQL;

   CREATE TABLE COMP_REC_3 AS
 
   SELECT 
   DISTINCT PREFIXO,
   CARTEIRA,
   
   SUM(VALOR_REC_JUL) AS VALOR_REC_JUL, SUM(VALOR_REC_AGO) AS VALOR_REC_AGO, SUM(VALOR_REC_SET) AS VALOR_REC_SET, SUM(VALOR_REC_OUT) AS VALOR_REC_OUT, 
   SUM(VALOR_REC_NOV) AS VALOR_REC_NOV, SUM(VALOR_REC_DEZ) AS VALOR_REC_DEZ, SUM(VALOR_REC_SEM) AS VALOR_REC_SEM
          		  		  
   FROM COMP_REC_2 t1
   GROUP BY 1,2
   ORDER BY 1,2;

QUIT;


PROC SQL;

   CREATE TABLE COMP_REC_4 AS
 
   SELECT *	  
   FROM COMP_REC_3
   WHERE PREFIXO <> 0
   ORDER BY 1,2;

QUIT;




/*******************/
/*******************/
/*******************/
/*******************/
/**JUNTANDO PERDAS COM REC**/


PROC SQL;

   CREATE TABLE COMP_1 AS
 
   SELECT DISTINCT t1.PREFIXO AS PREFIXO_1, t2.PREFIXO AS PREFIXO_2, t1.CARTEIRA AS CARTEIRA_1, t2.CARTEIRA AS CARTEIRA_2, 

   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   VALOR_PERDAS_DEZ,  
   VALOR_REC_DEZ            
          		  		  
   FROM COMP_PERDAS_4  t1
   FULL JOIN COMP_REC_4 t2 ON t1.PREFIXO = t2.PREFIXO AND t1.CARTEIRA = t2.CARTEIRA 
   ORDER BY 1,2,3,4;

QUIT;


PROC STDIZE DATA=COMP_1 OUT=COMP_1 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_2 AS
 
   SELECT DISTINCT 

   IFN(PREFIXO_1 <> 0, PREFIXO_1, PREFIXO_2) AS PREFDEP, IFN(CARTEIRA_1 <> 0, CARTEIRA_1, CARTEIRA_2) AS CTRA,

   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   VALOR_PERDAS_DEZ,  
   VALOR_REC_DEZ            
          		  		  
   FROM COMP_1  
   ORDER BY 1,2;

QUIT;


data COMP_2;
format posicao yymmdd10.;
set COMP_2;
posicao = &D1;
run;


/*TABELA COLUNAS PARA FUNCAO SUMARIZACAO*/

PROC SQL;
DROP TABLE COLUNAS_SUMARIZAR;
CREATE TABLE COLUNAS_SUMARIZAR (Coluna CHAR(50), Tipo CHAR(10));
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_SEM', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_SEM', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_JUL', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_JUL', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_AGO', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_AGO', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_SET', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_SET', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_OUT', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_OUT', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_NOV', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_NOV', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_PERDAS_DEZ', 'SUM');
INSERT INTO COLUNAS_SUMARIZAR VALUES ('VALOR_REC_DEZ ', 'SUM');

QUIT;


/*FUNCAO DE SUMARIZACAO*/ 
%SumarizadorCNX( TblSASValores=COMP_2,  TblSASColunas=COLUNAS_SUMARIZAR,  NivelCTRA=1,  PAA_PARA_AGENCIA=0,  TblSaida=COMP_2, AAAAMM=&ANOMES.); 


PROC STDIZE DATA=COMP_2 OUT=COMP_2 REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;

   CREATE TABLE COMP_3 AS
 
   SELECT DISTINCT 
   POSICAO,
   PREFDEP,
   CTRA,
   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   VALOR_PERDAS_DEZ,  
   VALOR_REC_DEZ            
          		  		  
   FROM COMP_2  
   ORDER BY 2,3;

QUIT;


PROC SQL;

   CREATE TABLE COMP_4 AS
 
   SELECT 
   POSICAO,
   PREFDEP,
   CTRA,

   VALOR_PERDAS_SEM,
   VALOR_REC_SEM,
   (VALOR_REC_SEM / VALOR_PERDAS_SEM) *100 AS PERSEM FORMAT 32.2,

   VALOR_PERDAS_JUL,
   VALOR_REC_JUL,
   (VALOR_REC_JUL / VALOR_PERDAS_JUL) *100 AS PERJUL FORMAT 32.2,

   VALOR_PERDAS_AGO,
   VALOR_REC_AGO,
   (VALOR_REC_AGO / VALOR_PERDAS_AGO) *100 AS PERAGO FORMAT 32.2,

   VALOR_PERDAS_SET,
   VALOR_REC_SET,
   (VALOR_REC_SET / VALOR_PERDAS_SET) *100 AS PERSET FORMAT 32.2,

   VALOR_PERDAS_OUT,
   VALOR_REC_OUT,
   (VALOR_REC_OUT / VALOR_PERDAS_OUT) *100 AS PEROUT FORMAT 32.2,

   VALOR_PERDAS_NOV,
   VALOR_REC_NOV,
   (VALOR_REC_NOV / VALOR_PERDAS_NOV) *100 AS PERNOV FORMAT 32.2,

   VALOR_PERDAS_DEZ,  
   VALOR_REC_DEZ,       
   (VALOR_REC_DEZ / VALOR_PERDAS_DEZ) *100 AS PERDEZ FORMAT 32.2
          		  		  
   FROM COMP_3 
   ORDER BY 2,3;

QUIT;


/*Rel 528*/


%LET Usuario=f7176219;
%LET Keypass=bonus-rec-perdas-S58qpmu1h2mOD3TcHHc2q5tU8v0bVo5m7WZzPgrW365EzD4xIS;
%LET Rotina=bonus-rec-perdas;
%ProcessoIniciar();


PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('COMP_4', 'bonus-rec-perdas');
	;
QUIT;


%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);

x cd /dados/dirao/publico ;
x chmod 2777 *;





