
%INCLUDE '/dados/infor/suporte/FuncoesInfor.sas';

%LET Tx_Fon=6062;

%LET Excluir_data='06mar2019'd;


%CONECTARDB2(MIV);
%CONECTARDB2(REL);
%CONECTARDB2(SGCEN);
%CONECTARDB2(MCI);
%CONECTARDB2(ATB);

LIBNAME unc_ata "/dados/externo/UNC/ATA";
LIBNAME unc_gat "/dados/externo/UNC/GAT/TELEFONE";
LIBNAME AUX_TP "/dados/infor/producao/Tempo_Resposta_PF_PJ";

LIBNAME TRPJ "/dados/infor/producao/tempo_resposta";

DATA _NULL_;
	
D1 = diaUtilAnterior(today());
CALL SYMPUT('D1',COMPRESS(D1,' '));

ANOMES = Put(D1, yymmn6.);
CALL SYMPUT('ANOMES',COMPRESS(ANOMES,' '));

MMAAAA=PUT(D1,mmyyn6.);
CALL SYMPUT('MMAAAA', COMPRESS(MMAAAA,' '));

INI_MES= Put(INTNX('month',DiaUtilAnterior(D1),0), yymmdd10.);
CALL SYMPUT('INI_MES',COMPRESS(INI_MES,' '));

RUN;

%PUT &d1. &ANOMES. &MMAAAA. &INI_MES.;

LIBNAME DB2ATB DB2 DATABASE=BDB2P04 SCHEMA=DB2ATB AUTHDOMAIN=DB2SGCEN;
LIBNAME DB2UOR DB2 DATABASE=BDB2P04 SCHEMA=DB2UOR AUTHDOMAIN=DB2SGCEN;
LIBNAME DB2MST DB2 DATABASE=BDB2P04 SCHEMA=DB2MST AUTHDOMAIN=DB2SGCEN;


/*Prefixos com falecom*/
/*Prefixos com falecom*/
/*Prefixos com falecom*/
/*Prefixos com falecom*/

 
PROC SQL;
   CREATE TABLE WORK.CTRA_PJ AS
   SELECT DISTINCT t1.CD_PRF_VICE_PRSA,
          t1.CD_PRF_DRTA,
          t1.CD_PRF_SPCA,
          t1.CD_PRF_ADMC_RGNL,
          t1.CD_PRF_DEPE,
          t1.NR_SEQL_CTRA_ATB,
          t1.CD_TIP_CTRA
      FROM COMUM.PAI_REL_&ANOMES. t1
	  WHERE t1.CD_PRF_DEPE IS NOT MISSING
      ORDER BY 5,6;
QUIT;
 

PROC SQL;
   CREATE TABLE WORK.CTRA_REMOTA AS
   SELECT t1.CD_PRF_DEPE AS prefdep,
          t1.NR_SEQL_CTRA_ATB as ctra
      FROM WORK.CTRA_PJ t1
      WHERE t1.CD_TIP_CTRA IN (321,323,328);
QUIT;


PROC SQL;
   CREATE TABLE WORK.CTRA_DEMAIS AS
   SELECT DISTINCT t1.CD_PRF_DEPE AS prefdep,
          t1.NR_SEQL_CTRA as ctra
      FROM DB2REL.CTRA_CLI_RMT t1;
QUIT;


DATA WORK.CARTEIRAS_FALECOM;
    SET WORK.CTRA_REMOTA WORK.CTRA_DEMAIS;
RUN;


PROC SQL;
   CREATE TABLE WORK.AGENCIAS_FALECOM AS
   SELECT DISTINCT t1.prefdep,
          0 as ctra
      FROM WORK.CARTEIRAS_FALECOM t1
      ORDER BY 1;
QUIT;


DATA WORK.CARTEIRAS_FALECOM;
    SET WORK.CARTEIRAS_FALECOM WORK.AGENCIAS_FALECOM;
RUN;


PROC SQL;
   CREATE TABLE TRPJ.AGENCIAS_FALECOM_&ANOMES. AS
   SELECT DISTINCT input(t2.uor,z9.) as uor,
          t1.prefdep AS PREFIXO,
             t1.ctra,
          t2.NomeDep,
          1 AS FaleCom
      FROM WORK.CARTEIRAS_FALECOM t1
           INNER JOIN IGR.IGRREDE_&ANOMES. t2 ON t1.prefdep = input(t2.prefdep,z4.)
      ORDER BY 2,3;
QUIT;


PROC SQL;
   CREATE TABLE WORK.FALECOM_IMPLANTADO AS 
   SELECT DISTINCT prefdep as PREFIXO
      FROM TRPJ.tempo_resp_pj_180419
WHERE FALECOM=1;
QUIT;


/*ENCARTEIRAMENTO*/
/*ENCARTEIRAMENTO*/
/*ENCARTEIRAMENTO*/
/*ENCARTEIRAMENTO*/


PROC SQL;
	CREATE TABLE WORK.ENCARTEIRADOS AS 
		SELECT t1.CD_CLI, 
			t1.CD_PRF_DEPE, 
			t1.NR_SEQL_CTRA,
			t2.NR_SEQL_CTRA_ATB,
			t2.CD_PRF_ADMC_RGNL, 
			t2.CD_PRF_SPCA, 
			t2.CD_PRF_DRTA, 
			t2.CD_PRF_VICE_PRSA,
			t2.CD_TIP_CTRA
		FROM COMUM.PAI_REL_PJ_&ANOMES t1
			INNER JOIN COMUM.ENCARTEIRAMENTO_CONEXAO_&ANOMES T2 ON (T1.CD_CLI=T2.CD_CLI AND T1.CD_PRF_DEPE=T2.CD_PRF_DEPE AND T1.NR_SEQL_CTRA=T2.NR_SEQL_CTRA AND T1.CD_TIP_CTRA=T2.CD_TIP_CTRA);
QUIT;

	
PROC SQL;
	connect to db2 (authdomain=db2sgcen database=db23p41);
	CREATE TABLE WORK.CLIENTES_PJ AS 
		SELECT COD
			FROM connection to db2(			
				SELECT DISTINCT 
					T1.COD
				FROM DB2MCI.CLIENTE t1
					WHERE t1.COD_TIPO = 2 AND t1.COD_MERC <> 3);
	disconnect from db2;;
QUIT;


PROC SQL;
	CREATE TABLE ENCARTEIRADOS AS 
		SELECT t1.CD_CLI, 
			t1.CD_PRF_DEPE, 
			t1.NR_SEQL_CTRA, 
			t1.NR_SEQL_CTRA_ATB, 
			t1.CD_PRF_ADMC_RGNL, 
			t1.CD_PRF_SPCA, 
			t1.CD_PRF_DRTA, 
			t1.CD_PRF_VICE_PRSA, 
			t1.CD_TIP_CTRA
		FROM WORK.ENCARTEIRADOS t1
			INNER JOIN CLIENTES_PJ T2 ON (T1.CD_CLI=T2.COD)
 WHERE NR_SEQL_CTRA_ATB BETWEEN 5000 AND 7000;
;
QUIT;
	

DATA _NULL_;
	CALL SYMPUT('DTDB2',"'"||Put(&d1., yymmdd10.)||"'");
RUN;


%PUT &DTDB2;


%Put &ANOMES;

DATA _NULL_;
	CALL SYMPUT('Filtro',"'"||"&INI_MES"||"'");
RUN;

%Put &Filtro;
OPTIONS MLOGIC MPRINT SYMBOLGEN;

PROC SQL;
	connect to db2 (authdomain=db2sgcen database=db23p41);
	CREATE TABLE TX_MIV AS 
		SELECT *
			FROM connection to db2(			
				SELECT DISTINCT 
					*
				FROM DB2MIV.TX_MSG_EXPS t1
					INNER JOIN DB2MIV.DBT_ELET_MSG_EXPS t2 ON (t2.CD_CLI_MSG_EXPS = t1.CD_CLI_MSG_EXPS and t2.NR_SEQL_DBT = t1.NR_SEQL_DBT)
						WHERE t2.CD_TIP_DBT = 3 AND DATE(T1.TS_CRIC_MSG) BETWEEN &FILTRO. and &DTDB2. );
	disconnect from db2;
	;
QUIT;

data tx;
set tx_MIV;
where cd_snlc_msg in (200 201 0 1 604) and CD_ITCE_CNL_ATDT is not missing;
run;

/*BETWEEN (CURRENT DATE - (DAY(CURRENT DATE) - 1) DAYS) AND ((CURRENT DATE + 1 MONTH) - (DAY(CURRENT DATE + 1 MONTH)) DAYS))*/

PROC SQL;
	CREATE TABLE WORK.QUERY_FOR_TX AS 
		SELECT DISTINCT t1.CD_CLI_PJ, 
			t1.DT_LET_MSG, 
			t1.HR_LET_MSG, 
			CD_SNLC_MSG,
			trim(compress(TX_MSG,,'kadst')) as TX_MSG, 
			t1.CD_ITCE_CNL_ATDT
		FROM WORK.TX t1
			WHERE t1.CD_SNLC_MSG in (200 201);
QUIT;

PROC SQL;
	CREATE TABLE WORK.QUERY_FOR_TX_0001 AS 
		SELECT t1.CD_CLI_PJ, 
			t1.DT_LET_MSG, 
			t1.HR_LET_MSG,
			CD_SNLC_MSG, 
			COMPBL(TX_MSG) as TX_MSG,
			t1.CD_ITCE_CNL_ATDT
		FROM WORK.QUERY_FOR_TX t1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.QUERY_FOR_TX_0002 AS 
		SELECT t1.CD_CLI_PJ, 
			t1.DT_LET_MSG, 
			t1.HR_LET_MSG,
			CD_SNLC_MSG, 
			TX_MSG,
			index(TX_MSG,"PROTOCOLO_INICIO") as a,
			substr(TX_MSG,calculated a+25,12) as PROTOCOLO_INICIO,
			index(TX_MSG,"PROTOCOLO_FIM") as B,
			substr(TX_MSG,calculated B+27,12) as PROTOCOLO_FIM, 
			t1.CD_ITCE_CNL_ATDT
		FROM WORK.QUERY_FOR_TX_0001 t1;
QUIT;



PROC SQL;
   CREATE TABLE aux_tp.TX_ENCARTEIRADOS_&anomes AS 
   SELECT *
      FROM WORK.TX t1
INNER JOIN ENCARTEIRADOS T2 ON (T1.CD_CLI_PJ=T2.CD_CLI AND t1.cd_prf_depe and t2.cd_prf_depe and t1.nr_seql_ctra=t2.NR_SEQL_CTRA_ATB)
INNER JOIN FALECOM_IMPLANTADO T3 ON (T2.CD_PRF_DEPE=T3.PREFIXO)
WHERE (datepart(t1.TS_CRIC_MSG)) ne &Excluir_data.;
;QUIT;



/*###########################*/
/*FALE COM - TEMPO DE RETORNO*/
/*###########################*/


PROC SQL;
	CREATE TABLE WORK.TX_MSG_EXPS AS 
		SELECT DISTINCT 
			t1.CD_PRF_DEPE as PREFDEP, 
			t1.NR_SEQL_CTRA_ATB AS CARTEIRA, 
			t1.CD_CLI,
			(datepart(t1.TS_CRIC_MSG)) FORMAT=ddmmyy10. LABEL="data" AS data, 
			(timepart(t1.TS_CRIC_MSG)) FORMAT=time8. LABEL="hora" AS hora,  
			t1.TS_CRIC_MSG AS TIMESTAMP, 
			t1.CD_USU_RSP_EST_MSG AS RESPONSAVEL, 
			t1.DT_LET_MSG format=ddmmyy10. as data_leitr, 
			t1.HR_LET_MSG as hora_leitr, 
			t1.CD_SNLC_MSG, 
			trim(compress(TX_MSG,,'kadst'))  as TX_MSG
		FROM aux_tp.TX_ENCARTEIRADOS_&anomes t1
	    INNER JOIN FALECOM_IMPLANTADO T2 ON (T1.CD_PRF_DEPE=T2.PREFIXO)
;
QUIT;


PROC SQL;
   CREATE TABLE WORK.INTERACAO_CLIENTE AS 
   SELECT t1.PREFDEP, 
          t1.CARTEIRA, 
          t1.CD_CLI, 
          t1.data, 
        (MIN(t1.hora)) FORMAT=TIME8. AS hora_cliente, 
          t1.RESPONSAVEL
      FROM WORK.TX_MSG_EXPS t1
 WHERE t1.responsavel IS NULL
group by 1,2,3,4,6;
QUIT;


PROC SQL;
	CREATE TABLE INTERACAO_CLIENTE AS 
		SELECT t1.PREFDEP, 
			t1.CARTEIRA, 
			t1.CD_CLI, 
			ifn((hora_cliente>'17:0:0't),data+1,data) format ddmmyy10. as  data, 
		(case 
			when hora_cliente <'09:0:0't then '09:0:0't
			when hora_cliente>'17:0:0't then '09:0:0't 
			else hora_cliente 
		end)
		format time8. as hora_cliente,
		t1.RESPONSAVEL
	FROM WORK.INTERACAO_CLIENTE t1;
QUIT;


PROC SQL;
	CREATE TABLE WORK.INTERACAO_BB AS 
		SELECT DISTINCT
            t1.PREFDEP, 
			t1.CARTEIRA, 
			t1.CD_CLI, 
			ifn((hora>'17:0:0't),data+1,data) format ddmmyy10. as  data, 
		(case 
			when hora <'09:0:0't then '09:0:0't
			when hora>'17:0:0't then '09:0:0't 
			else hora 
		end)
		FORMAT=TIME8. AS hora, 
		t1.RESPONSAVEL
	FROM WORK.TX_MSG_EXPS t1
		WHERE t1.responsavel NOT IS NULL and CD_SNLC_MSG=0
			group by 1,2,3,6;
QUIT;

PROC SQL;
   CREATE TABLE WORK.fale_com AS 
   SELECT t1.PREFDEP, 
          t1.CARTEIRA, 
          t1.CD_CLI, 
          t1.data, 
		   t1.hora_cliente, 
		  t2.hora LABEL='' as hora_bb,
          t1.RESPONSAVEL,
		  (IFN(t2.hora IS MISSING, ('17:0:0't - t1.hora_cliente), 
           IFN(t2.hora LT t1.hora_cliente, ('17:0:0't - t1.hora_cliente), (t2.hora - t1.hora_cliente)))) FORMAT=TIME8. LABEL="tempo_start_2" AS tempo_start, 
          (WEEKDAY(t1.data)) AS dia_semana
      FROM WORK.INTERACAO_CLIENTE t1
left join INTERACAO_BB t2 on (t1.prefdep=t2.prefdep and t1.carteira=t2.carteira and t1.cd_cli=t2.cd_cli and t1.data=t2.data)
WHERE t2.hora BETWEEN '9:0:0't AND '17:0:0't AND WEEKDAY(t1.data) IN(2, 3, 4, 5, 6);;
QUIT;





PROC SQL;
   CREATE TABLE WORK.TEMPO_FALE_COM AS 
   SELECT t1.PREFDEP, 
          t1.CARTEIRA, 
          t1.CD_CLI, 
          t1.data, 
          t1.HORA_CLIENTE,
		  t1.responsavel,
         (MIN(t1.tempo_start)) FORMAT=TIME8. AS tempo_start, 
          t1.dia_semana
      FROM WORK.FALE_COM t1
GROUP BY 1,2,3,4,5,6,8;
QUIT;


PROC SQL;
   CREATE TABLE WORK.tempo_retorno_cliente AS 
   SELECT DISTINCT t1.prefdep, t1.CARTEIRA, t1.cd_cli, 
          t1.data, 
          t1.hora_cliente, 
          t1.responsavel, 
          t1.tempo_start, 
          (IFC(t1.dia_semana EQ 2, "Segunda", IFC(t1.dia_semana eq 3, "Terça", IFC(t1.dia_semana eq 
            4, "Quarta", IFC(t1.dia_semana eq 5, "Quinta", IFC(t1.dia_semana eq 6, "Sexta", "Fim de Semana"
            )))))) AS dia
      FROM WORK.TEMPO_FALE_COM t1, WORK.FALE_COM t2
      WHERE (t1.cd_cli = t2.cd_cli AND t1.data = t2.data AND t1.tempo_start = t2.tempo_start AND t1.hora_cliente = 
           t2.hora_cliente) AND t1.dia_semana IN 
           (
           2,
           3,
           4,
           5,
           6
           )
      ORDER BY t1.hora_cliente;
QUIT;




PROC SQL;
	CREATE TABLE TEMPO_RETORNO_CARTEIRA AS 
	SELECT DISTINCT t1.PREFDEP,
		   t1.CARTEIRA AS CTRA,
		   AVG(t1.tempo_start) FORMAT=TIME8. AS TEMPO_RETORNO_FC
	FROM WORK.TEMPO_RETORNO_CLIENTE t1
	GROUP BY 1,2
ORDER BY 1,2;	
QUIT;




/*#####################*/
/*FALE COM - QUANTIDADE*/
/*#####################*/


PROC SQL;
	CREATE TABLE WORK.QUERY_FOR_TX_0003 AS 
		SELECT 
			t2.CD_PRF_DEPE,
			t2.NR_SEQL_CTRA_ATB,
			t2.CD_CLI,
			t1.DT_LET_MSG, 
			t1.HR_LET_MSG, 
			t1.CD_SNLC_MSG, 
			t1.TX_MSG, 
			t1.PROTOCOLO_INICIO, 
			t1.CD_ITCE_CNL_ATDT
		FROM WORK.QUERY_FOR_TX_0002 t1
			INNER JOIN ENCARTEIRADOS T2 ON (T1.CD_CLI_PJ=T2.CD_CLI)
				WHERE CD_SNLC_MSG=200 AND TX_MSG CONTAINS ' por ';
QUIT;





PROC SQL;
	CREATE TABLE CONTATOS_FUNCI AS 
		SELECT DISTINCT 
            t1.CD_PRF_DEPE,
			t1.NR_SEQL_CTRA_ATB,
			 T1.CD_CLI,
			 t4.DT_LET_MSG, 
			t4.HR_LET_MSG, 
			t4.CD_SNLC_MSG, 
			t4.TX_MSG, 
			t4.PROTOCOLO_INICIO, 
			t4.CD_ITCE_CNL_ATDT
		FROM WORK.ENCARTEIRADOS t1
		LEFT JOIN aux_tp.TX_ENCARTEIRADOS_&anomes T2 ON (T1.CD_PRF_DEPE=T2.CD_PRF_DEPE AND T1.NR_SEQL_CTRA_ATB=T2.NR_SEQL_CTRA_ATB AND T1.CD_CLI=T2.CD_CLI)
		INNER JOIN FALECOM_IMPLANTADO T3 ON (T1.CD_PRF_DEPE=T3.PREFIXO)
		INNER JOIN WORK.QUERY_FOR_TX_0002 t4 ON (T4.CD_CLI_PJ=T1.CD_CLI)
		WHERE T4.CD_SNLC_MSG=200 AND T4.TX_MSG CONTAINS ' por ' AND T4.DT_LET_MSG IS NOT MISSING
			group by 1,2
				ORDER BY 1,2;
QUIT;



PROC SQL;
   CREATE TABLE WORK.INTERACAO_CLIENTE_PJ AS 
   SELECT DISTINCT t1.CD_CLI_PJ AS CD_CLI
      FROM AUX_TP.TX_ENCARTEIRADOS_&ANOMES t1
      WHERE t1.CD_USU_RSP_INC NOT IS MISSING;
QUIT;

PROC SQL;
	CREATE TABLE CONTATOS_FUNCI_COM_RETORNO AS 
		SELECT DISTINCT 
			t1.CD_PRF_DEPE, 
			t1.NR_SEQL_CTRA_ATB, 
			t1.CD_CLI
		FROM WORK.CONTATOS_FUNCI t1
			INNER JOIN INTERACAO_CLIENTE_PJ T2 ON (T1.CD_CLI=T2.CD_CLI);
QUIT;


PROC SQL;
   CREATE TABLE CONTATOS_CLIENTES AS 
   SELECT DISTINCT t1.CD_PRF_DEPE, 
          t1.NR_SEQL_CTRA_ATB, 
          t1.CD_CLI_PJ AS CD_CLI
      FROM AUX_TP.TX_ENCARTEIRADOS_&ANOMES t1
	WHERE T1.CD_USU_RSP_EST_MSG IS NULL;
QUIT;


DATA CONTATOS_FALECOM;
SET CONTATOS_FUNCI_COM_RETORNO CONTATOS_CLIENTES;
RUN;

PROC SQL;
	CREATE TABLE QUANTIDADE_CLIENTES AS 
		SELECT DISTINCT 
			t1.CD_PRF_DEPE, 
			t1.NR_SEQL_CTRA_ATB, 
			t1.CD_CLI
		FROM WORK.CONTATOS_FALECOM t1;
QUIT;


PROC SQL;
	CREATE TABLE QUANTIDADE_CLIENTES_MCI AS 
		SELECT DISTINCT 
            t1.CD_PRF_DEPE,
			t1.NR_SEQL_CTRA_ATB,
			 T1.CD_CLI,
			 IFN(T2.CD_CLI IS MISSING,0,1) AS CLI_FALECOM
		FROM WORK.ENCARTEIRADOS t1
		LEFT JOIN QUANTIDADE_CLIENTES T2 ON (T1.CD_PRF_DEPE=T2.CD_PRF_DEPE AND T1.NR_SEQL_CTRA_ATB=T2.NR_SEQL_CTRA_ATB AND T1.CD_CLI=T2.CD_CLI)
		INNER JOIN FALECOM_IMPLANTADO T3 ON (T1.CD_PRF_DEPE=T3.PREFIXO)
			group by 1,2
				ORDER BY 1,2;
QUIT;




PROC SQL;
	CREATE TABLE QUANTIDADE_CLIENTES_ENCARTEIRADO AS 
		SELECT DISTINCT t1.CD_PRF_DEPE,
			t1.NR_SEQL_CTRA_ATB,
			(COUNT(DISTINCT CD_CLI)) AS CLI_ENCARTEIRADOS
		FROM WORK.QUANTIDADE_CLIENTES_MCI t1
			group by 1,2
				ORDER BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE CLIENTES_FALECOM AS 
		SELECT DISTINCT t1.CD_PRF_DEPE, 
			t1.NR_SEQL_CTRA_ATB, 
			t1.CD_CLI
		FROM QUANTIDADE_CLIENTES_MCI t1 
			where CLI_FALECOM=1 GROUP BY 1,2 ORDER BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE QUANTIDADE_CLIENTES_FALECOM AS 
		SELECT DISTINCT t1.CD_PRF_DEPE, 
			t1.NR_SEQL_CTRA_ATB, 
			/* COUNT_of_CD_CLI */
	(COUNT(DISTINCT t1.CD_CLI)) AS CLI_FALECOM FROM CLIENTES_FALECOM t1 GROUP BY 1,2 ORDER BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE CTRA_CLI AS 
		SELECT t1.CD_PRF_DEPE AS PREFDEP, 
			t1.NR_SEQL_CTRA_ATB AS CTRA, 
			t1.CLI_ENCARTEIRADOS,
			T2.CLI_FALECOM
		FROM WORK.QUANTIDADE_CLIENTES_ENCARTEIRADO t1
			INNER JOIN QUANTIDADE_CLIENTES_FALECOM T2 ON (T1.CD_PRF_DEPE=T2.CD_PRF_DEPE AND T1.NR_SEQL_CTRA_ATB=T2.NR_SEQL_CTRA_ATB AND T1.NR_SEQL_CTRA_ATB=T2.NR_SEQL_CTRA_ATB)
				INNER JOIN FALECOM_IMPLANTADO T3 ON (T1.CD_PRF_DEPE=T3.PREFIXO)
				ORDER BY 1,2;
QUIT;






/*##############################################################*/
                              /*ATA*/
/*##############################################################*/


PROC SQL;
   CREATE TABLE TRPJ.AGENCIAS_ATA_&ANOMES. AS
   SELECT DISTINCT INPUT(t2.PrefDep, 4.) AS PREFIXO,
          t1.CD_UOR_BB AS UOR,
          t2.NomeDep,
          1 as ATA
      FROM DB2MST.UOR_BB t1
           INNER JOIN IGR.IGRREDE_&ANOMES. t2 ON (t1.CD_UOR_BB = INPUT(t2.UOR, 9.))
      WHERE t1.CD_CRCT_ATDT_BB = 2
      ORDER BY 1;
QUIT;


PROC SQL;
   CREATE TABLE ATA_IMPLANTADO AS 
   SELECT DISTINCT PREFDEP AS PREFIXO
      FROM TRPJ.tempo_resp_pj_180419
WHERE ATA=1 ;
QUIT;


PROC SQL;
   CREATE TABLE WORK.UNC_TB_GAT AS 
   SELECT t2.CD_PRF_DEPE,
		  t2.NR_SEQL_CTRA, 
          t1.subordinada, 
          t1.protocoloAtend, 
          t1.clienteEncarteirado, 
          t1.mci, 
          t1.chaveAdmAtend, 
          t1.tipoCarteira, 
          t1.chaveAtendente, 
          t1.prefixoAtendente, 
          t1.statusAtend, 
          t1.tipoPessoaNaoCli, 
          t1.dataSolicitacaoAtend, 
          t1.horaSolicitacaoAtend, 
          t1.dataInicioAtend, 
          t1.horaInicioAtend, 
          t1.dataFimAtend, 
          t1.horaFimAtend,
		  diasUteisEntreDatas(t1.dataSolicitacaoAtend, t1.dataFimAtend) AS qtd_dias_uteis,
          t1.dataUltimaAnotacao, 
          t1.horaUltimaAnotacao, 
          t1.horaAberturaAgencia, 
          t1.horaFechamentoAgencia
      FROM UNC_GAT.tel&ANOMES. t1
	  INNER JOIN WORK.ENCARTEIRADOS t2 ON (t1.MCI = t2.CD_CLI)
	  INNER JOIN ATA_IMPLANTADO T3 ON (T2.CD_PRF_DEPE=T3.PREFIXO)
	  WHERE t1.statusAtend = 40	AND t1.horaSolicitacaoAtend BETWEEN "9:0:0"t AND "17:0:0"t AND t1.dataFimAtend<=&d1. AND horaFimAtend>=horaSolicitacaoAtend
	  and dataSolicitacaoAtend ne &Excluir_data.
        ;
QUIT;


PROC SQL;
   CREATE TABLE WORK.MCI_GAT AS 
   SELECT t1.CD_PRF_DEPE,
		  t1.NR_SEQL_CTRA,
		  t1.MCI,
   		  t1.dataSolicitacaoAtend, 
          t1.horaSolicitacaoAtend, 
          t1.dataInicioAtend, 
          t1.horaInicioAtend, 
          t1.dataFimAtend, 
          t1.horaFimAtend,
   		  IFN(t1.qtd_dias_uteis = 1 AND (t1.horaInicioAtend - t1.horaSolicitacaoAtend) <= "0:20:0"t, 1, 0, 0) AS ATD_IMEDIATO,
		  (
			IFN(t1.qtd_dias_uteis > 2, (t1.qtd_dias_uteis - 2)* "10:0:0"t, 0, 0) +
			IFN(t1.qtd_dias_uteis >= 2, ("17:0:0"t - t1.horaSolicitacaoAtend) + (t1.horaInicioAtend - "9:0:0"t), 0, 0) +
			IFN(t1.qtd_dias_uteis = 1, t1.horaInicioAtend - t1.horaSolicitacaoAtend, 0, 0)
		  ) FORMAT=TIME8. AS TEMPO_RETORNO_GAT,
		  t1.qtd_dias_uteis
      FROM WORK.UNC_TB_GAT t1;
QUIT;


PROC SQL;
   CREATE TABLE WORK.CTRA_GAT_BASE AS 
   SELECT t1.CD_PRF_DEPE AS PREFDEP,
		  t1.NR_SEQL_CTRA_ATB AS CTRA,
		  COUNT(t2.MCI) AS QTD_CHAMADAS_GAT,
		  SUM(t2.ATD_IMEDIATO) AS QTD_CHAMADAS_IMED_GAT,
		  AVG(t2.TEMPO_RETORNO_GAT) FORMAT=TIME8. AS TEMPO_RETORNO_GAT
      FROM WORK.ENCARTEIRADOS t1
	  INNER JOIN WORK.MCI_GAT t2 ON (t1.CD_PRF_DEPE = t2.CD_PRF_DEPE AND t1.NR_SEQL_CTRA_ATB = t2.NR_SEQL_CTRA AND T1.CD_CLI=T2.MCI)
	  WHERE t2.TEMPO_RETORNO_GAT IS NOT MISSING
	  GROUP BY 1,2
ORDER BY 1,2;
QUIT;



data JUNTA_TUDO;
MERGE CTRA_CLI TEMPO_RETORNO_CARTEIRA CTRA_GAT_BASE;
BY PREFDEP CTRA;
WHERE CTRA BETWEEN 5000 AND 7000;
;
RUN;


PROC SQL;
	CREATE TABLE WORK.COM_RESPOSTA AS 
		SELECT t1.PREFDEP, 
			t1.CTRA, 
			IFN(CLI_FALECOM IS MISSING,0,1 ) AS CLI_FALECOM, 
			IFN(TEMPO_RETORNO_FC IS MISSING,0,1) AS  TEMPO_RETORNO_FC,
			IFN(TEMPO_RETORNO_GAT IS MISSING,0,1) AS  TEMPO_RETORNO_GAT,
			IFN(QTD_CHAMADAS_GAT IS MISSING,0,1) AS QTD_CHAMADAS_GAT,
			IFN(QTD_CHAMADAS_IMED_GAT IS MISSING,0,1) AS QTD_CHAMADAS_ATENDIDAS
		FROM WORK.JUNTA_TUDO t1;
QUIT;




PROC SQL;
   CREATE TABLE WORK.PREFIXOS_COM_RESPOSTA AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
          (CLI_FALECOM+TEMPO_RETORNO_FC+TEMPO_RETORNO_GAT+QTD_CHAMADAS_GAT +QTD_CHAMADAS_ATENDIDAS) AS PREFIXOS
      FROM WORK.COM_RESPOSTA t1;
QUIT;


PROC SQL;
   CREATE TABLE PARA_SUMARIZAR AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
          t1.CLI_ENCARTEIRADOS, 
          t1.CLI_FALECOM, 
		  IFN(CLI_FALECOM IS MISSING,0,1) AS POSSUI_FALECOM,
          t1.TEMPO_RETORNO_FC,
          IFN( TEMPO_RETORNO_FC IS MISSING,0,1) AS POSSUI_RETORNO_FC,
          t1.TEMPO_RETORNO_GAT,
          IFN(TEMPO_RETORNO_GAT IS MISSING,0,1) AS POSSUI_RETORNO_GAT, 
          t1.QTD_CHAMADAS_GAT, 
          t1.QTD_CHAMADAS_IMED_GAT,
		  IFN(QTD_CHAMADAS_GAT IS MISSING,0,1) AS POSSUI_CHAMADAS_GAT
      FROM WORK.JUNTA_TUDO t1
INNER JOIN PREFIXOS_COM_RESPOSTA T2 ON (T1.PREFDEP=T2.PREFDEP AND T1.CTRA=T2.CTRA)
WHERE PREFIXOS NE 0
;
QUIT;



PROC SQL;
	DROP TABLE COLS_SUM;
	CREATE TABLE COLS_SUM (Coluna CHAR(50), Tipo CHAR(10), Alias CHAR(50) );

	/*COLUNAS PARA SUMARIZACAO*/

	INSERT INTO COLS_SUM VALUES ('CLI_ENCARTEIRADOS', 'SUM', 'CLI_ENCARTEIRADOS');
	INSERT INTO COLS_SUM VALUES ('CLI_FALECOM', 'SUM', 'CLI_FALECOM');
	INSERT INTO COLS_SUM VALUES ('POSSUI_FALECOM', 'SUM', 'POSSUI_FALECOM');
	INSERT INTO COLS_SUM VALUES ('TEMPO_RETORNO_FC', 'SUM', 'TEMPO_RETORNO_FC');
	INSERT INTO COLS_SUM VALUES ('POSSUI_RETORNO_FC', 'SUM', 'POSSUI_RETORNO_FC');
	INSERT INTO COLS_SUM VALUES ('TEMPO_RETORNO_GAT', 'SUM', 'TEMPO_RETORNO_GAT');
	INSERT INTO COLS_SUM VALUES ('POSSUI_RETORNO_GAT', 'SUM', 'POSSUI_RETORNO_GAT');
	INSERT INTO COLS_SUM VALUES ('QTD_CHAMADAS_GAT', 'SUM', 'QTD_CHAMADAS_GAT');
	INSERT INTO COLS_SUM VALUES ('QTD_CHAMADAS_IMED_GAT', 'SUM', 'QTD_CHAMADAS_IMED_GAT');
	INSERT INTO COLS_SUM VALUES ('POSSUI_CHAMADAS_GAT', 'SUM', 'POSSUI_CHAMADAS_GAT');

QUIT;

%SumarizadorCNX(TblSASValores=PARA_SUMARIZAR, TblSASColunas=COLS_SUM, NivelCTRA=1, PAA_PARA_AGENCIA=0, TblSaida=RESULTADO, AAAAMM=&ANOMES);



PROC SQL;
   CREATE TABLE RESULTADO_GERAL AS 
   SELECT t1.UOR, 
          t1.PREFDEP,  
          t1.CTRA, 
          t1.CLI_ENCARTEIRADOS, 
          t1.CLI_FALECOM, 
		  (CLI_FALECOM/CLI_ENCARTEIRADOS*100) FORMAT 19.2 AS PC_USO_FALECOM,
		  t1.POSSUI_FALECOM,
          IFN(CTRA=0,TEMPO_RETORNO_FC/POSSUI_RETORNO_FC,TEMPO_RETORNO_FC) FORMAT TIME8. AS TEMPO_RETORNO_FC,
          t1.POSSUI_RETORNO_FC,
		  IFN(CTRA=0,TEMPO_RETORNO_GAT/POSSUI_RETORNO_GAT,TEMPO_RETORNO_GAT)  FORMAT TIME8. AS TEMPO_RETORNO_GAT,
		  t1.POSSUI_RETORNO_GAT,
          t1.QTD_CHAMADAS_GAT, 
          t1.QTD_CHAMADAS_IMED_GAT,
		  (QTD_CHAMADAS_IMED_GAT/QTD_CHAMADAS_GAT)*100 FORMAT 19.2 AS PC_GAT_ATDT_IMEDIATO,
		  t1.POSSUI_CHAMADAS_GAT
      FROM WORK.RESULTADO t1
GROUP BY 1,2,3;
QUIT;

PROC SQL;
	CREATE TABLE PONTUACAO_GERAL AS 
		SELECT t1.UOR, 
			t1.PREFDEP, 
			t1.CTRA, 
			t1.CLI_ENCARTEIRADOS, 
			t1.CLI_FALECOM,
			t1.PC_USO_FALECOM, 
		(CASE 
			WHEN PC_USO_FALECOM <=2.50 AND PC_USO_FALECOM >=0  THEN 0
			WHEN (PC_USO_FALECOM <=5.00  AND PC_USO_FALECOM>2.50) THEN 5
			WHEN (PC_USO_FALECOM <=7.50 AND PC_USO_FALECOM>5.00) THEN 10
			WHEN (PC_USO_FALECOM <=10.00 AND PC_USO_FALECOM>7.50) THEN 15
			WHEN (PC_USO_FALECOM <=11.00 AND PC_USO_FALECOM>10.00)  THEN 20
			WHEN PC_USO_FALECOM >11.00 THEN 25 
			ELSE . 
		END)
	AS PESO_QTD_FALECOM,
	t1.POSSUI_FALECOM,
		T1.TEMPO_RETORNO_FC,
	(CASE 
		WHEN TEMPO_RETORNO_FC>="0:0:0"t AND TEMPO_RETORNO_FC < "1:0:0"t THEN 25
		WHEN (TEMPO_RETORNO_FC >="1:0:0"t AND TEMPO_RETORNO_FC <"1:15:0"t) THEN 20
		WHEN (TEMPO_RETORNO_FC >="1:15:0"t AND TEMPO_RETORNO_FC<"1:30:0"t) THEN 15
		WHEN (TEMPO_RETORNO_FC >="1:30:0"t AND TEMPO_RETORNO_FC<"1:45:0"t) THEN 10
		WHEN (TEMPO_RETORNO_FC >="1:45:0"t AND TEMPO_RETORNO_FC<"2:0:0"t)  THEN 5
		WHEN TEMPO_RETORNO_FC >="2:0:0"t THEN 0 
		ELSE . 
	END)
AS PESO_TEMPO_RETORNO_FC,
t1.POSSUI_RETORNO_FC,
	t1.QTD_CHAMADAS_GAT, 
	t1.QTD_CHAMADAS_IMED_GAT,
	T1.PC_GAT_ATDT_IMEDIATO,
(CASE 
	WHEN PC_GAT_ATDT_IMEDIATO >=0 AND PC_GAT_ATDT_IMEDIATO <=60 THEN 0
	WHEN (PC_GAT_ATDT_IMEDIATO >60 AND PC_GAT_ATDT_IMEDIATO<=70) THEN 5
	WHEN (PC_GAT_ATDT_IMEDIATO >70 AND PC_GAT_ATDT_IMEDIATO<=80) THEN 10
	WHEN (PC_GAT_ATDT_IMEDIATO >80 AND PC_GAT_ATDT_IMEDIATO<=85) THEN 15
	WHEN (PC_GAT_ATDT_IMEDIATO >85 AND PC_GAT_ATDT_IMEDIATO<=90)  THEN 20
	WHEN PC_GAT_ATDT_IMEDIATO >90 THEN 25 
	ELSE . 
END)
AS PESO_ATDT_GAT,
t1.POSSUI_CHAMADAS_GAT,
T1.TEMPO_RETORNO_GAT,
(CASE 
WHEN TEMPO_RETORNO_GAT>="0:0:0"t AND TEMPO_RETORNO_GAT < "1:0:0"t THEN 25
WHEN (TEMPO_RETORNO_GAT >="1:0:0"t AND TEMPO_RETORNO_GAT <"1:15:0"t) THEN 20
WHEN (TEMPO_RETORNO_GAT >="1:15:0"t AND TEMPO_RETORNO_GAT<"1:30:0"t) THEN 15
WHEN (TEMPO_RETORNO_GAT >="1:30:0"t AND TEMPO_RETORNO_GAT<"1:45:0"t) THEN 10
WHEN (TEMPO_RETORNO_GAT >="1:45:0"t AND TEMPO_RETORNO_GAT<"2:0:0"t)  THEN 5
WHEN TEMPO_RETORNO_GAT >="2:0:0"t THEN 0
ELSE . 
END)
AS PESO_TEMPO_RETORNO_GAT,
t1.POSSUI_RETORNO_GAT
FROM WORK.RESULTADO_GERAL t1;
QUIT;



PROC SQL;
   CREATE TABLE POSSUI_COMPONENTES  AS 
   SELECT DISTINCT t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA, 
          IFN(POSSUI_FALECOM=0,0,1) AS POSSUI_FALECOM,
          IFN(POSSUI_RETORNO_FC=0,0,1) AS POSSUI_RETORNO_FC,
          IFN(POSSUI_CHAMADAS_GAT=0,0,1) AS POSSUI_CHAMADAS_GAT,
          IFN(POSSUI_RETORNO_GAT=0,0,1) AS POSSUI_RETORNO_GAT
      FROM WORK.PONTUACAO_GERAL t1;
QUIT;

PROC SQL;
   CREATE TABLE WORK.QUERY_FOR_POSSUI_COMPONENTES AS 
   SELECT t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA, 
          t1.POSSUI_FALECOM, 
          t1.POSSUI_RETORNO_FC, 
          t1.POSSUI_CHAMADAS_GAT, 
          t1.POSSUI_RETORNO_GAT
      FROM WORK.POSSUI_COMPONENTES t1;
QUIT;


PROC SQL;
   CREATE TABLE REDISTRIBUI_PESO AS 
   SELECT t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA, 
		  (CASE WHEN POSSUI_FALECOM=0 AND POSSUI_RETORNO_FC=0 THEN 1
          WHEN  POSSUI_FALECOM=1 AND POSSUI_RETORNO_FC=1 THEN 1
		  WHEN POSSUI_FALECOM=0 AND POSSUI_RETORNO_FC=1 THEN 2
		  WHEN POSSUI_FALECOM=1 AND POSSUI_RETORNO_FC=0 THEN 2 END)
		  AS REDISTRIBUICAO_FC,
          (CASE WHEN POSSUI_CHAMADAS_GAT=0 AND POSSUI_RETORNO_GAT=0 THEN 1
		  WHEN POSSUI_CHAMADAS_GAT=1 AND POSSUI_RETORNO_GAT=1 THEN 1
		  WHEN POSSUI_CHAMADAS_GAT=0 AND POSSUI_RETORNO_GAT=1 THEN 2
		  WHEN POSSUI_CHAMADAS_GAT=1 AND POSSUI_RETORNO_GAT=0 THEN 2 END)
		  AS REDISTRIBUICAO_GAT,
          IFN(POSSUI_FALECOM+POSSUI_RETORNO_FC=0,2,1) AS CPNT_FC,
		  IFN(POSSUI_CHAMADAS_GAT+POSSUI_RETORNO_GAT=0,2,1) AS CPNT_GAT
      FROM WORK.POSSUI_COMPONENTES t1;
QUIT;



PROC SQL;
   CREATE TABLE WORK.RESULTADO AS 
   SELECT t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA, 
          t1.CLI_ENCARTEIRADOS, 
          t1.CLI_FALECOM, 
          t1.PC_USO_FALECOM, 
		  T1.PESO_QTD_FALECOM,
          (t1.PESO_QTD_FALECOM*T2.REDISTRIBUICAO_FC)*CPNT_GAT AS PONTOS_QTD_FALECOM, 
          t1.POSSUI_FALECOM, 
          t1.TEMPO_RETORNO_FC,
		  PESO_TEMPO_RETORNO_FC,
          (t1.PESO_TEMPO_RETORNO_FC*T2.REDISTRIBUICAO_FC)*CPNT_GAT AS PONTOS_TEMPO_RETORNO_FC, 
          t1.POSSUI_RETORNO_FC, 
          t1.QTD_CHAMADAS_GAT, 
          t1.QTD_CHAMADAS_IMED_GAT, 
          t1.PC_GAT_ATDT_IMEDIATO, 
		  PESO_ATDT_GAT,
          (t1.PESO_ATDT_GAT*T2.REDISTRIBUICAO_GAT)*T2.CPNT_FC AS PONTOS_ATDT_GAT, 
          t1.POSSUI_CHAMADAS_GAT, 
          t1.TEMPO_RETORNO_GAT, 
          PESO_TEMPO_RETORNO_GAT,
          (t1.PESO_TEMPO_RETORNO_GAT*T2.REDISTRIBUICAO_GAT)*CPNT_FC AS PONTOS_TEMPO_RETORNO_GAT, 
          t1.POSSUI_RETORNO_GAT
      FROM WORK.PONTUACAO_GERAL t1
INNER JOIN REDISTRIBUI_PESO T2 ON (T1.UOR=T2.UOR AND T1.PREFDEP=T2.PREFDEP AND T1.CTRA=T2.CTRA);
QUIT;


PROC SQL;
   CREATE TABLE WORK.CONSOLIDADO AS 
   SELECT t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA, 
          t1.CLI_ENCARTEIRADOS, 
          t1.CLI_FALECOM, 
          t1.PC_USO_FALECOM, 
		  t1.PESO_QTD_FALECOM ,
		  t1.PONTOS_QTD_FALECOM AS PONTOS_QTD_FC,
          t1.TEMPO_RETORNO_FC,
          t1.PESO_TEMPO_RETORNO_FC,
		  T1.PONTOS_TEMPO_RETORNO_FC AS PONTOS_TEMPO_FC,
          t1.TEMPO_RETORNO_GAT ,
          T1.PESO_TEMPO_RETORNO_GAT,
          T1.PONTOS_TEMPO_RETORNO_GAT AS PONTOS_TEMPO_GAT,
          t1.QTD_CHAMADAS_GAT, 
          t1.QTD_CHAMADAS_IMED_GAT, 
          t1.PC_GAT_ATDT_IMEDIATO,
		   t1.PESO_ATDT_GAT,
		   T1.PONTOS_ATDT_GAT AS PONTOS_QTD_GAT
      FROM WORK.RESULTADO t1;
QUIT;


PROC SQL;
   CREATE TABLE WORK.PONTUACAO AS 
   SELECT DISTINCT t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA, 
          IFN(PONTOS_QTD_FC IS MISSING,0,PONTOS_QTD_FC) as PONTOS_QTD_FC, 
          IFN(PONTOS_TEMPO_FC IS MISSING,0,PONTOS_TEMPO_FC) as PONTOS_TEMPO_FC, 
          IFN(PONTOS_TEMPO_GAT IS MISSING,0, PONTOS_TEMPO_GAT) as PONTOS_TEMPO_GAT,
          IFN(PONTOS_QTD_GAT IS MISSING,0, pontos_qtd_GAT) as PONTOS_QTD_GAT
      FROM WORK.CONSOLIDADO t1;
QUIT;


PROC SQL;
   CREATE TABLE WORK.PONTUACAO_II AS 
   SELECT t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA, 
          (PONTOS_QTD_FC+PONTOS_TEMPO_FC+PONTOS_TEMPO_GAT+PONTOS_QTD_GAT) as REALIZADO
      FROM WORK.PONTUACAO t1
GROUP BY 1,2,3
ORDER BY 1,2,3;
QUIT;


DATA CONSOLIDADO;
SET CONSOLIDADO;
ORCADO = 80;
RUN;


PROC SQL;
CREATE TABLE WORK.CONSOLIDADO_REL AS 
SELECT &d1. FORMAT YYMMDD10. AS POSICAO, T1.UOR, T1.PREFDEP, T1.CTRA, CLI_ENCARTEIRADOS AS FC_CLI_OBJ , CLI_FALECOM AS FC_CLI_RLZ, PONTOS_QTD_FC AS FC_UTILIZACAO_PTS, TEMPO_RETORNO_FC AS FC_TR, PONTOS_TEMPO_FC AS FC_TR_PTS, PC_GAT_ATDT_IMEDIATO AS ATA_ATDT_IMED, PONTOS_QTD_GAT AS  ATA_ATDT_IMED_PTS, 
TEMPO_RETORNO_GAT AS ATA_TR, PONTOS_TEMPO_GAT AS  ATA_TR_PTS, ORCADO, T2.REALIZADO FORMAT 17.2, (T2.REALIZADO/ORCADO)*100 AS POR_ATG
FROM  WORK.CONSOLIDADO T1
INNER JOIN PONTUACAO_II T2 ON (T1.UOR=T2.UOR AND T1.PREFDEP=T2.PREFDEP AND T1.CTRA=T2.CTRA);
QUIT;


/************************************************************************************************/

/*CONEXÃO*/
/*AVALIACAO-RELACIONAMENTO*/


PROC SQL;
   CREATE TABLE CONEXAO AS 
   SELECT DISTINCT t1.POSICAO, 
          t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA,
          INPUT(t2.TD_SINERGIA, d4.) AS TipDepCnx,
          t1.REALIZADO
      FROM WORK.CONSOLIDADO_REL t1
INNER JOIN IGR.IGRREDE_&ANOMES. t2 ON T1.PREFDEP = INPUT(t2.PREFDEP, d4.);
;
QUIT;


PROC SQL;
   CREATE TABLE WORK.CONEXAO_&ANOMES AS 
   SELECT t1.POSICAO, 
          t1.UOR, 
          t1.PREFDEP, 
          ifn(TIPDEPCNX=2 and CTRA=0,7002,ctra) as CTRA,
          IFN(TIPDEPCNX=2,1,TipDepCnx) AS TipDepCnx, 
          t1.REALIZADO
      FROM WORK.CONEXAO t1	  
      ;
QUIT;


/*COMPARAÇÃO*/
/*COMPARAÇÃO*/
/*COMPARAÇÃO*/
/*COMPARAÇÃO*/


LIBNAME ANTRPJ "/dados/infor/producao/Analise_TRPJ";


PROC SQL;
   CREATE TABLE CONEXAO_COMPAR AS 
   SELECT t1.POSICAO, 
          t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA,
          t1.TipDepCnx, 
          t1.REALIZADO AS REALIZADO_NOVO,
		  IFC(t2.PREFIXO IS NOT MISSING, "Sim", "Não") as FC_RLZ_NOVO,
		  IFC(t3.PREFIXO IS NOT MISSING, "Sim", "Não") as ATA_RLZ_NOVO
      FROM CONEXAO_&ANOMES t1
	  LEFT JOIN FALECOM_IMPLANTADO t2 ON t1.PREFDEP = t2.PREFIXO
	  LEFT JOIN ATA_IMPLANTADO t3 ON t1.PREFDEP = t3.PREFIXO
      ORDER BY 1, 2, 3, 4, 5, 6, 7, 8;
QUIT;


PROC SQL;
   CREATE TABLE TESTE AS 
   SELECT *
      FROM ANTRPJ.TESTE
      ORDER BY  1, 2, 3, 4, 5, 6, 7, 8;
QUIT;


DATA COMPARACAO;
MERGE TESTE CONEXAO_COMPAR;
BY POSICAO UOR PREFDEP CTRA TipDepCnx;
RUN;


PROC STDIZE DATA=COMPARACAO OUT=COMPARACAO REPONLY MISSING=0;
	VAR _NUMERIC_;
QUIT;


PROC SQL;
   CREATE TABLE COMPARACAO_FINAL AS 
   SELECT t1.POSICAO, 
          t1.UOR, 
          t1.PREFDEP, 
          t1.CTRA,
          t1.TipDepCnx, 
          t1.REALIZADO,
          t1.REALIZADO_NOVO,
		  (t1.REALIZADO_NOVO - t1.REALIZADO) AS DEFERENCA,
		  t1.FC_RLZ,
		  IFC(t1.FC_RLZ_NOVO IS NULL, "Não", t1.FC_RLZ_NOVO) as FC_RLZ_NOVO,
          t1.ATA_RLZ,
		  IFC(t1.ATA_RLZ_NOVO IS NULL, "Não", t1.ATA_RLZ_NOVO) as ATA_RLZ_NOVO

      FROM COMPARACAO t1
	  WHERE TIPDEPCNX = 1
      ORDER BY 1, 2, 3, 4, 5;
QUIT;



/****/
/****/
/****/
/****/



PROC SQL;
    CREATE TABLE CONEXAO AS
        SELECT
            '2000153'
            ||"&Tx_Fon"
            ||REPEAT(' ',45)
            ||COMPRESS(PUT(t1.PrefDep,Z4.))
            ||COMPRESS(PUT(t1.CTRA,Z5.))
            ||"&ANOMES"
            ||put(t1.TipDepCnx,z4.)
            ||'+'
            ||PUT(ABS(t1.REALIZADO)*100,z13.)
            ||'F9457977'
            ||COMPRESS(PUT(Today(), ddmmyy10.))
            ||'N' AS L
        FROM WORK.CONEXAO_&ANOMES t1       
;QUIT;


%GerarBBM(TabelaSAS=CONEXAO, Caminho=/dados/infor/transfer/enviar/, ExtencaoBBM=M6062);



/************************************************************************************************/


/* RELATORIOS*/


data consolidadO_rel(DROP=UOR);
SET CONSOLIDADO_REL
 ;
RUN;





PROC SQL;
   CREATE TABLE WORK.QTD_CLIENTES_FC AS 
   SELECT t1.cd_prf_depe as prefdep, 
          t1.nr_seql_ctra_atb as carteira, 
          t1.cd_cli as mci, 
          t1.CLI_FALECOM
      FROM WORK.QUANTIDADE_CLIENTES_MCI t1
order by 1,2,3;
QUIT;


PROC SQL;
   CREATE TABLE WORK.TEMPO_FALECOM AS 
   SELECT t1.PREFDEP, 
          t1.CARTEIRA , 
          t1.cd_cli, 
          t1.data, 
		    put(hora_cliente,time8.) as hora_cliente, 
put(tempo_start,time8.) as tempo_start
      FROM WORK.TEMPO_RETORNO_CLIENTE t1
order by 1,2,3;
QUIT;


PROC SQL;
	CREATE TABLE WORK.TEMPO_GAT AS 
		SELECT t1.cd_prf_depe AS PREFDEP, 
			t1.nr_seql_ctra AS CARTEIRA, 
			t1.mci, 
			t1.dataSolicitacaoAtend, 
			put(horaSolicitacaoAtend,time8.) as horaSolicitacaoAtend,
			t1.dataInicioAtend,
			put(horaInicioAtend,time8.) as horaInicioAtend,
			t1.ATD_IMEDIATO, 
			put(T1.TEMPO_RETORNO_GAT,time8.) as TEMPO_RETORNO_GAT
		FROM WORK.MCI_GAT t1
				ORDER BY 1,2,3;
QUIT;



%LET Usuario=f7176219;
%LET Keypass=p91WlbrVLhMS6nD0xuBvsJeuRhaYv7SthinqocltJxnO3k1ppr;
%LET Rotina=rel-tempo-resposta-unv;
%ProcessoIniciar();

PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('WORK.CONSOLIDADO_REL', 'rel-tempo-resposta-unv');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('tempo_falecom', 'detalhe-falecom');
    INSERT INTO TABELAS_EXPORTAR_REL VALUES('qtd_clientes_fc', 'detalhe-falecom-qtd');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('tempo_gat', 'detalhe-ata');
QUIT;

%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);

