
%include '/dados/infor/suporte/FuncoesInfor.sas';
/*%LET NomeRelatorio=;*/
/*%LET NomePasta=*/
/*%LET Usuario=f9457977;*/
/*%LET Keypass=;*/
/*%LET Rotina=;*/


*/%IniciarProcessoMysql(Processo=&NomeRelatorio., Responsavel=Vanessa, XML=&NomeXML.);/*


/*#################################################################################################################*/
/*##### B I B L I O T E C A S #####*/


LIBNAME DB2SGCEN 	db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2SGCEN database=BDB2P04;
LIBNAME DB2GECEN 	db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2GECEN database=BDB2P04;

LIBNAME DB2ATB 		db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2ATB 	database=BDB2P04;
LIBNAME DB2BCD 		db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2BCD 	database=BDB2P04;
LIBNAME DB2DEB 		db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2DEB 	database=BDB2P04;

LIBNAME PUBL '/dados/infor/producao/BBCode/';





/*CONTROLE DE DATAS*/

DATA _NULL_;
	DATA_INICIO = '01Jan2017'd;
	DATA_FIM = '30Dec2020'd;
	DATA_REFERENCIA = diaUtilAnterior(TODAY());
	D1 = diaUtilAnterior(TODAY());
	D2 = diaUtilAnterior(D1);
	D3 = diaUtilAnterior(D2);
	MES_ATU = IFN((D1 <= DATA_FIM), Put(D1, yymmn6.), Put(DATA_FIM, yymmn6.));
	MES_ANT = Put(INTNX('month',primeiroDiaUtilMes(D1),-1), yymmn6.) ;
	MES_G = Put(DATA_REFERENCIA, MONTH.) ;
	ANOMES = IFN((D1 <= DATA_FIM), Put(D1, yymmn6.), Put(DATA_FIM, yymmn6.));
	DT_INICIO_SQL="'"||put(DATA_INICIO, YYMMDDD10.)||"'";
	DT_D1_SQL="'"||put(D1, YYMMDDD10.)||"'";
	DT_1DIA_MES_SQL="'"||put(primeiroDiaUtilMes(D1), YYMMDDD10.)||"'";
	DT_ANOMES_SQL=primeiroDiaUtilMes(D1);
	PRIMEIRO_DIA_MES_SQL="'"||put(primeiroDiaMes(DATA_REFERENCIA), YYMMDDD10.)||"'";
    MMAAAA=PUT(D1,mmyyn6.);

	CALL SYMPUT('DATA_HOJE',COMPRESS(TODAY(),' '));
	CALL SYMPUT('DT_1DIA_MES',COMPRESS(primeiroDiaUtilMes(D1),' '));
	CALL SYMPUT('DATA_INICIO',COMPRESS(DATA_INICIO,' '));
	CALL SYMPUT('DATA_FIM',COMPRESS(DATA_FIM,' '));
	CALL SYMPUT('D1',COMPRESS(D1,' '));
	CALL SYMPUT('D2',COMPRESS(D2,' '));
	CALL SYMPUT('D3',COMPRESS(D3,' '));
	CALL SYMPUT('MES_ATU',COMPRESS(MES_ATU,' '));
	CALL SYMPUT('MES_ANT',COMPRESS(MES_ANT,' '));
	CALL SYMPUT('ANOMES',COMPRESS(ANOMES,' '));
	CALL SYMPUT('RF',COMPRESS(ANOMES,' '));
	CALL SYMPUT('DT_ARQUIVO',put(DATA_REFERENCIA, DDMMYY10.));
	CALL SYMPUT('DT_ARQUIVO_SQL',put(DATA_REFERENCIA, YYMMDDD10.));
	CALL SYMPUT('DT_INICIO_SQL', COMPRESS(DT_INICIO_SQL,' '));
	CALL SYMPUT('DT_1DIA_MES_SQL', COMPRESS(DT_1DIA_MES_SQL,' '));
	CALL SYMPUT('DT_D1_SQL', COMPRESS(DT_D1_SQL,' '));
	CALL SYMPUT('DT_ANOMES_SQL', COMPRESS(DT_ANOMES_SQL,' '));
	CALL SYMPUT('MES_G', COMPRESS(MES_G,' '));
	CALL SYMPUT('PRIMEIRO_DIA_MES_SQL', COMPRESS(PRIMEIRO_DIA_MES_SQL,' '));
	CALL SYMPUT('MMAAAA', COMPRESS(MMAAAA,' '));
RUN;

/*ALDAIR - F5210377*/
/*CAROLINE - F1916323 INFOR*/


PROC SQL;
	CREATE TABLE PUBLICO_HABILITACAO AS 
		SELECT t1.CD_MCI_PJ AS CD_CLI,  
			t1.CD_MCI_PF, 
			t1.NOME_CLI_PJ, 
			t1.CHAVE_J, 
			t1.IND_HAB_BB_CODE, 
			t1.DT_HABILITACAO, 
			ifn(DT_HABILITACAO=.,0,1) as habilitado,
			t1.IND_FRAUDE, 
			t1.TOKEN as ind_token, 
			t1.IND_OFT_SIMPLIFICADA
		FROM PUBL.TB_PUBLICO_BBCode t1;
QUIT;




PROC SQL;
   CREATE TABLE ENCARTEIRAMENTO AS 
   SELECT t1.CD_CLI, 
          t1.CD_TIP_CTRA, 
          t1.NR_SEQL_CTRA, 
          t1.CD_PRF_DEPE
      FROM COMUM.ENCARTEIRAMENTO_CONEXAO_&ANOMES t1
inner join publico_habilitacao t2 on (t1.cd_cli=t2.cd_cli);
QUIT;


PROC SQL;
	CREATE TABLE NAO_ENCARTEIRADOS AS 
		SELECT 
			T3.CD_PRF_DEPE,
			t3.NR_SEQL_CTRA,
			t1.CD_CLI, 
			t1.CD_MCI_PF, 
			t1.NOME_CLI_PJ, 
			t1.CHAVE_J, 
			t1.IND_HAB_BB_CODE, 
			t1.DT_HABILITACAO, 
			t1.habilitado, 
			t1.IND_FRAUDE, 
			t1.IND_TOKEN, 
			t1.IND_OFT_SIMPLIFICADA
		FROM WORK.PUBLICO_HABILITACAO t1
			LEFT JOIN ENCARTEIRAMENTO T2 ON (T1.CD_CLI=T2.CD_CLI)
				INNER JOIN comum.pai_rel_&anomes. T3 ON (T1.CD_CLI=T3.CD_CLI)
					WHERE T2.CD_CLI IS MISSING
						ORDER BY 1,2,3;
QUIT;


PROC SQL;
	CREATE TABLE ENCARTEIRADOS AS 
		SELECT 
			T1.CD_PRF_DEPE,
			t1.NR_SEQL_CTRA, 
			t1.CD_CLI, 
			t2.CD_MCI_PF, 
			t2.NOME_CLI_PJ, 
			t2.CHAVE_J, 
			t2.IND_HAB_BB_CODE, 
			t2.DT_HABILITACAO, 
			t2.habilitado, 
			t2.IND_FRAUDE, 
			t2.IND_TOKEN, 
			t2.IND_OFT_SIMPLIFICADA
		FROM WORK.ENCARTEIRAMENTO t1
			INNER JOIN PUBLICO_HABILITACAO T2 ON (T1.CD_CLI=T2.CD_CLI)
				ORDER BY 1,2,3
	;
QUIT;

DATA CLIENTES;
	SET ENCARTEIRADOS NAO_ENCARTEIRADOS;
RUN;

PROC SQL;
	CREATE TABLE BBCODE_ENCARTEIRAMENTO AS 
		SELECT 
			&data_hoje. FORMAT DDMMYY10. AS POSICAO,
			T1.CD_PRF_DEPE as prefdep,
			t1.NR_SEQL_CTRA as carteira, 
			/*			t1.tp_cart, */
	t1.CD_CLI,
	t1.NOME_CLI_PJ, 
	t1.CHAVE_J, 
	DATEPART(t2.TS_HBLT_BBCD) format ddmmyy10. AS DT_HABILITACAO, 
	ifn(T2.TS_HBLT_BBCD=.,0,1) as habilitado,
	(CASE 
		WHEN t1.IND_FRAUDE = "Não" THEN 0
		ELSE 1 
	END)
	as FRAUDE,
		(CASE 
			WHEN t1.IND_TOKEN = "Não" THEN 0
			ELSE 1 
		END)
		as TOKEN,
			(CASE 
				WHEN t1.IND_OFT_SIMPLIFICADA = "Não" THEN 0
				ELSE 1 
			END)
			as OFT_SIMPLIFICADA,
				T1.CD_MCI_PF,
				(CASE 
					WHEN T2.IN_BLQ_BBCD = "S" THEN 1
					WHEN T2.IN_BLQ_BBCD = "N" THEN 0
					ELSE . 
				END)
				AS BLQ_BBCD
					FROM WORK.CLIENTES t1
						LEFT JOIN DB2BCD.BBCD T2 ON (T1.CD_MCI_PF=T2.CD_PF_DTTR_BBCD)
	;
QUIT;

PROC SQL;
	CREATE TABLE BBCODE_CARTEIRA AS 
		SELECT DISTINCT 
			t1.prefdep,
			t1.carteira,  
			COUNT(CD_CLI) AS QTD_CDCLI,
			/* SUM_of_habilitado */
	(SUM(t1.habilitado)) AS habilitado FROM WORK.BBCODE_ENCARTEIRAMENTO t1 GROUP BY t1.prefdep, t1.carteira;
QUIT;

PROC SQL;
	CREATE TABLE BBCODE_PREFIXO AS 
		SELECT DISTINCT 
			T1.PREFDEP,
			0 AS carteira, 
   (SUM(QTD_CDCLI)) AS QTD_CDCLI, 
			/* SUM_of_habilitado */
	(SUM(t1.habilitado)) AS habilitado FROM WORK.BBCODE_CARTEIRA t1 GROUP BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE BBCODE_SUPERREG AS 
		SELECT DISTINCT 
			INPUT(PREFSUREG,4.) AS prefdep, 
			0 AS carteira, 
			 (SUM(QTD_CDCLI)) AS QTD_CDCLI, 
			/* SUM_of_habilitado */
	(SUM(t1.habilitado)) AS habilitado FROM WORK.BBCODE_PREFIXO t1 INNER JOIN IGR.DEPENDENCIAS_&ANOMES T2 ON (T1.PREFDEP=INPUT(T2.PREFDEP,4.)) WHERE SB='00' AND STATUS= 'A' AND INPUT(T2.PREFSUREG,4.) NE 0 GROUP BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE BBCODE_SUPEREST AS 
		SELECT DISTINCT 
			INPUT(PREFSUPER,4.) AS prefdep, 
			0 AS carteira, 
			 (SUM(QTD_CDCLI)) AS QTD_CDCLI, 
			/* SUM_of_habilitado */
	(SUM(t1.habilitado)) AS habilitado FROM WORK.BBCODE_PREFIXO t1 INNER JOIN IGR.DEPENDENCIAS_&ANOMES T2 ON (T1.PREFDEP=INPUT(T2.PREFDEP,4.)) WHERE SB='00' AND STATUS= 'A' AND INPUT(T2.PREFSUPER,4.) NE 0 GROUP BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE BBCODE_PREFUEN AS 
		SELECT DISTINCT 
			INPUT(PREFDIR,4.) AS prefdep, 
			0 AS carteira, 
			 (SUM(QTD_CDCLI)) AS QTD_CDCLI, 
			/* SUM_of_habilitado */
	(SUM(t1.habilitado)) AS habilitado FROM WORK.BBCODE_PREFIXO t1 INNER JOIN IGR.DEPENDENCIAS_&ANOMES T2 ON (T1.PREFDEP=INPUT(T2.PREFDEP,4.)) WHERE SB='00' AND STATUS= 'A' AND INPUT(T2.PREFDIR,4.) NE 0 GROUP BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE BBCODE_VIVAP AS 
		SELECT DISTINCT 
			8166 AS prefdep, 
			t1.carteira, 
			 (SUM(QTD_CDCLI)) AS QTD_CDCLI, 
			/* SUM_of_habilitado */
	(SUM(t1.habilitado)) AS habilitado FROM WORK.BBCODE_PREFUEN t1 GROUP BY 1,2;
QUIT;

DATA JUNTA_TUDO;
	SET BBCODE_CARTEIRA BBCODE_PREFIXO BBCODE_SUPERREG BBCODE_SUPEREST BBCODE_PREFUEN BBCODE_VIVAP;
RUN;



PROC SQL;
	CREATE TABLE BBCODE_SUMARIZADO AS 
		SELECT 
			&data_hoje. FORMAT DDMMYY10. AS POSICAO,
			t1.prefdep,
			t1.carteira,
            QTD_CDCLI,  
			t1.habilitado
		FROM WORK.JUNTA_TUDO t1;
QUIT;


/*Relatório 291*/

%LET Usuario=f9457977;
%LET Keypass=50IHJp6hz2lcMxNS4cCtM3zEBlmWOh6hEGCrsWiQEg98s8TyKD;

PROC SQL;
	DROP TABLE TABELAS_EXPORTAR_REL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('BBCODE_SUMARIZADO', 'bbcode-disem');
    INSERT INTO TABELAS_EXPORTAR_REL VALUES('BBCODE_ENCARTEIRAMENTO', 'clientes');
QUIT;

%ExportarREL(TABELAS_EXPORTAR_REL, Usuario=&Usuario., Keypass=&Keypass.);

/*************************************************/;
/* TRECHO DE CÓDIGO INCLUÍDO PELO FF */;

%include "/dados/gestao/rotinas/_macros/macros_uteis.sas";
 
%processCheckOut(
    uor_resp = 341556
    ,funci_resp = &sysuserid
    /*,tipo = Indicador
    ,sistema = Indicador
    ,rotina = I0123 Indicador de Alguma Coisa*/
    ,mailto= 'F8369937' 'F2986408' 'F6794004' 'F7176219' 'F8176496' 'F9457977' 'F9631159'
);
