/*#############################################################################################################################
#####      PROGRAMA DE CÓDIGO SAS DE PROCESSAMENTO DE INDICADOR DE INDUÇÃO DA REDE DE NEGÓCIOS DO BANCO DO BRASIL       #######
###############################################################################################################################

VIVAR - Vice-Presidência de Distribuição de Varejo
DIVAR - Diretoria Comercial Varejo
GEREX METAS - Gerencia Executiva da Central de Metas de Varejo 
Gerência de Avaliação e Soluções

Os metadados e dados desde programa são confidenciais (#CONFIDENCIAL) com informações de infraestrutura estratégica, 
dados cadastrais e financeiros de clientes, oriundos de informações dos legados e bases do Banco do Brasil.

!!! ESTE PROGRAMA NÃO PODE SER ALTERADO, DIVULGADO OU DISTRIBUÍDO SEM A EXPRESSA AUTORIZAÇÃO DA GEREX METAS.

!!! É EXPRESSAMENTE PROIBIDA A DIVULGAÇÃO EXTERNA AO BANCO, DO PROGRAMA OU DOS DADOS POR ELE GERADOS.

/*############################################################################################################################*/

/*############################################################################################################################*/
/* PACOTE DE FUNÇÕES BASE ----------------------------------------------------------------------------------------------------*/

%include '/dados/infor/suporte/FuncoesInfor.sas';

/* ---------------------------------------------------------------------------------------------------------------------------*/
/*############################################################################################################################*/
/*# BIBLIOTECAS - ############################################################################################################*/

LIBNAME REL DB2 DATABASE=BDB2P04 SCHEMA=DB2REL AUTHDOMAIN=DB2SGCEN;
LIBNAME ATB DB2 DATABASE=BDB2P04 SCHEMA=DB2ATB AUTHDOMAIN=DB2SGCEN;
LIBNAME PRD DB2 DATABASE=BDB2P04 SCHEMA=DB2PRD AUTHDOMAIN=DB2SGCEN;
LIBNAME RST DB2 DATABASE=BDB2P04 SCHEMA=DB2RST AUTHDOMAIN=DB2SGCEN;
LIBNAME OPR DB2 DATABASE=BDB2P04 SCHEMA=DB2OPR AUTHDOMAIN=DB2SGCEN;
LIBNAME CNL DB2 DATABASE=BDB2P04 SCHEMA=DB2CNL AUTHDOMAIN=DB2SGCEN;
LIBNAME GAT DB2 DATABASE=BDB2P04 SCHEMA=DB2GAT AUTHDOMAIN=DB2SGCEN;
LIBNAME ARH DB2 DATABASE=BDB2P04 SCHEMA=DB2ARH AUTHDOMAIN=DB2SGCEN;
LIBNAME MST DB2 DATABASE=BDB2P04 SCHEMA=DB2MST AUTHDOMAIN=DB2SGCEN;
LIBNAME CPB DB2 DATABASE=BDB2P04 SCHEMA=DB2CPB AUTHDOMAIN=DB2SGCEN;
LIBNAME UOR DB2 DATABASE=BDB2P04 SCHEMA=DB2UOR AUTHDOMAIN=DB2SGCEN;
LIBNAME ITR DB2 DATABASE=BDB2P04 SCHEMA=DB2ITR AUTHDOMAIN=DB2SGCEN;
LIBNAME DTM DB2 DATABASE=BDB2P04 SCHEMA=DB2DTM AUTHDOMAIN=DB2SGCEN;
LIBNAME ARG DB2 DATABASE=BDB2P04 SCHEMA=DB2ARG AUTHDOMAIN=DB2SGCEN;
LIBNAME CAF DB2 DATABASE=BDB2P04 SCHEMA=DB2CAF AUTHDOMAIN=DB2SGCEN;
LIBNAME ADE '/dados/infor/conexao/apuracao/000000265/bases/';
LIBNAME INF '/dados/infor/conexao/apuracao/000000292/bases/';
LIBNAME RIV '/dados/infor/producao/receita_interna';
LIBNAME SEG '/dados/dirco/publico/Gecen';
LIBNAME REC '/dados/infor/producao/Receita_Vendas';

/*LIBNAME ADES '/dados/infor/producao/Aderencia/';*/

LIBNAME DOT '/dados/externo/UNC/PainelAtendimento';


/*############################################################################################################################*/
/*# VARIÁVEIS - ##############################################################################################################*/


DATA _NULL_;
	DATA_INICIO = '01Jan2019'd;
	DATA_FIM = '31dec2019'd;
	/*	DATA_REFERENCIA = diaUtilAnterior(MDY(10,01,2018));*/
	DATA_REFERENCIA = diaUtilAnterior(TODAY());
	D1 = DATA_REFERENCIA;
	D2 = diaUtilAnterior(D1);
	D3 = diaUtilAnterior(D2);
	D4 = diaUtilAnterior(d3);
	D5 = diaUtilAnterior(D4);
	D6 = diaUtilAnterior(D5);
	MES_ATU = IFN((D1 <= DATA_FIM), Put(D1, yymmn6.), Put(DATA_FIM, yymmn6.));
	MES_ANT = Put(INTNX('month',primeiroDiaUtilMes(D1),-1), yymmn6.);
	MES_G = Put(DATA_REFERENCIA, MONTH.);
	MES_A = Put(INTNX('month',primeiroDiaUtilMes(D1),-1), MONTH.);
	ANOMES = IFN((D2 <= DATA_FIM), Put(D2, yymmn6.), Put(DATA_FIM, yymmn6.));
	DT_INICIO_SQL="'"||put(DATA_INICIO, YYMMDDD10.)||"'";
	DT_D1_SQL="'"||put(D1, YYMMDDD10.)||"'";
	DT_1DIA_MES_SQL="'"||put(primeiroDiaUtilMes(D2), YYMMDDD10.)||"'";
	DT_ANOMES_SQL=primeiroDiaUtilMes(D1);
	PRIMEIRO_DIA_MES_SQL="'"||put(primeiroDiaMes(DATA_REFERENCIA), YYMMDDD10.)||"'";
	MMAAAA=PUT(D2,mmyyn6.);
	CALL SYMPUT('DATA_HOJE',COMPRESS(TODAY(),' '));
	CALL SYMPUT('DT_1DIA_MES',COMPRESS(primeiroDiaUtilMes(D1),' '));
	CALL SYMPUT('DATA_INICIO',COMPRESS(DATA_INICIO,' '));
	CALL SYMPUT('DATA_FIM',COMPRESS(DATA_FIM,' '));
	CALL SYMPUT('D1',COMPRESS(D1,' '));
	CALL SYMPUT('D2',COMPRESS(D2,' '));
	CALL SYMPUT('D3',COMPRESS(D3,' '));
	CALL SYMPUT('D4',COMPRESS(D4,' '));
	CALL SYMPUT('D5',COMPRESS(D5,' '));
	CALL SYMPUT('D6',COMPRESS(D6,' '));
	CALL SYMPUT('MES_ATU',COMPRESS(MES_ATU,' '));
	CALL SYMPUT('MES_ANT',COMPRESS(MES_ANT,' '));
	CALL SYMPUT('ANOMES',COMPRESS(ANOMES,' '));
	CALL SYMPUT('RF',COMPRESS(ANOMES,' '));
	CALL SYMPUT('DT_ARQUIVO',put(DATA_REFERENCIA, DDMMYY10.));
	CALL SYMPUT('DT_ARQUIVO_SQL',put(DATA_REFERENCIA, YYMMDDD10.));
	CALL SYMPUT('DT_INICIO_SQL', COMPRESS(DT_INICIO_SQL,' '));
	CALL SYMPUT('DT_1DIA_MES_SQL', COMPRESS(DT_1DIA_MES_SQL,' '));
	CALL SYMPUT('DT_D1_SQL', COMPRESS(DT_D1_SQL,' '));
	CALL SYMPUT('DT_ANOMES_SQL', COMPRESS(DT_ANOMES_SQL,' '));
	CALL SYMPUT('MES_G', COMPRESS(MES_G,' '));
    CALL SYMPUT('MES_A', COMPRESS(MES_A,' '));
	CALL SYMPUT('PRIMEIRO_DIA_MES_SQL', COMPRESS(PRIMEIRO_DIA_MES_SQL,' '));
	CALL SYMPUT('MMAAAA', COMPRESS(MMAAAA,' '));
RUN;
%PUT &ANOMES. &MES_A. &DT_1DIA_MES. &data_hoje.;


x cd /;
x cd /dados/infor/producao/Aderencia;
x cd /dados/infor/producao/Receita_Vendas;
x cd /dados/infor/conexao/apuracao/000000265/bases;
x chmod -R 2777 *; /*ALTERAR PERMISÕES*/
x chown f9457977 -R ./; /*FIXA O FUNCI*/
x chgrp -R GSASBPA ./; /*FIXA O GRUPO*/


/* DADOS ---------------------------------------------------------------------------------------------------------------------*/

%LET NM_INDICADOR= SAA (Aderência e Vendas) e  SAA (Aderência e Vendas) informativo;
%LET NR_INDICADOR=;
%LET MT_DEMANDANTE=;
%LET NM_DEMANDANTE=CELIA/TALITA;
%LET DIRETORIA=DIRAC/UAT;
%LET MT_AUTOR=F9457977;
%LET NM_AUTOR=VANESSA;
%LET VIGENCIA=2019/2;
%LET HR_EXECUCAO=;


/* ---------------------------------------------------------------------------------------------------------------------------*/

/* CONCEITO ------------------------------------------------------------------------------------------------------------------*/



DATA LOTACAO;
SET DOT.LOTACAO_MINIMA;
WHERE dt_posicao>=(INTNX('month',primeiroDiaUtilMes(&d2.),0));
RUN;

PROC SQL;
	CREATE TABLE DT_LOTACAO AS 
		SELECT DISTINCT 
			/* MIN_of_dt_posicao */
	          dt_posicao, t1.prefixo FROM WORK.LOTACAO t1 where dt_posicao=&DT_1DIA_MES. GROUP BY t1.prefixo;
QUIT;

/*exclusão do prefixo 2327 conforme email dia 24/07/2019 11h57 f9272245 talita*/

PROC SQL;
CREATE TABLE novo_lotacao_saa AS 
	SELECT DISTINCT 
		t1.dt_posicao, 
		t1.prefixo, 
		t1.lotacao_minima_supervisor, 
		t1.lotacao_minima_escriturario_saa, 
		t1.lotacao_minima_total_saa
	FROM WORK.LOTACAO t1
	inner join dt_lotacao t2 on (t1.prefixo=t2.prefixo and t1.dt_posicao=t2.dt_posicao)
	where lotacao_minima_total_saa > 0 
GROUP BY 2
ORDER BY 2;
QUIT;


PROC SQL;
	CREATE TABLE WORK.FATO_ATDT_AMB_DIA AS 
		SELECT DISTINCT
			t1.DT_REF, 
			t1.CD_UOR_DRTA, 
			t1.CD_UOR_SPCA, 
			t1.CD_UOR_RGNL, 
			t1.CD_UOR_REDE_AG, 
			t1.CD_UOR_AG, 
			t1.CD_MUN_PRCA, 
			t1.CD_MTC_USU, 
			/* LETRA_MTC_USU */
	UPCASE(SUBSTR(t1.CD_MTC_USU, 1, 1)) AS LETRA_MTC_USU,
	/* NR_MTC_USU */
	((INPUT(COMPRESS(t1.CD_MTC_USU, , "kd"), BEST.))) AS NR_MTC_USU, 
	t1.CD_AGPT_TIP_SNH, 
	t1.CD_AGPT_REF_ORGC, 
	t1.CD_FXA_HR_SNH, 
	t1.CD_TIP_LCL_ATDT, 
	t1.CD_TIP_FIN_ATDT, 
	t1.QT_ATDT, 
	t1.QT_TMP_EPR_ATDT, 
	t1.QT_TMP_ATDT, 
	t1.QT_ITVL_TMP_ATDT, 
	t1.QT_MAX_EPR_AMB, 
	t1.QT_TMP_TRBD_FUN, 
	t1.QT_TRAN_FUN, 
	t1.QT_ITVL_MAX_ATDT
	FROM
		DTM.FATO_ATDT_AMB AS t1
		WHERE CD_PERC=1 AND 
			t1.DT_REF = &d2.
			AND
			(CALCULATED LETRA_MTC_USU) = 'F'
			AND
			(CALCULATED NR_MTC_USU) > 0;
QUIT;
PROC SQL;
	CREATE TABLE WORK.FATO_ATDT_GAT AS 
		SELECT DISTINCT t1.DT_REF, 
			t1.NR_MTC_USU, 
			t1.CD_TIP_LCL_ATDT, 
			t1.QT_ATDT, 
			t1.QT_TMP_EPR_ATDT, 
			t1.QT_TMP_ATDT, 
			t1.QT_ITVL_TMP_ATDT, 
			t1.QT_MAX_EPR_AMB, 
			t1.QT_TMP_TRBD_FUN, 
			t1.QT_ITVL_MAX_ATDT
		FROM WORK.FATO_ATDT_AMB_DIA t1
			WHERE t1.CD_TIP_LCL_ATDT IN 
				(
				1,
				2
				);
QUIT;

PROC SQL;
	CREATE TABLE WORK.FUNCIS_ATDT_GAT AS 
		SELECT DISTINCT t1.NR_MTC_USU, 
			/* QT_TIP_LCL_ATD */
	(COUNT(DISTINCT(t1.CD_TIP_LCL_ATDT))) FORMAT=1. AS QT_TIP_LCL_ATD, /* QT_SENHAS_FUNCI */
	(SUM(t1.QT_ATDT)) FORMAT=COMMAX5. AS QT_SENHAS_FUNCI, /* QT_TMP_SENHAS_FUNCI */
	(SUM(t1.QT_TMP_ATDT)) FORMAT=COMMAX5. AS QT_TMP_SENHAS_FUNCI, /* TMP_MEDIO_ATDT_FUNCI */
	(ROUND(SUM(t1.QT_TMP_ATDT) / SUM(t1.QT_ATDT), .01)) FORMAT=BEST10.2 AS TMP_MEDIO_ATDT_FUNCI, /* QT_TMP_TRBD_FUN */
	(MAX(t1.QT_TMP_TRBD_FUN)) FORMAT=6. AS QT_TMP_TRBD_FUN, /* PERC_TMP_TRBD_ATDT */
	((SUM(t1.QT_TMP_ATDT)) / t1.QT_TMP_TRBD_FUN) FORMAT=PERCENT12.2 AS PERC_TMP_TRBD_ATDT FROM WORK.FATO_ATDT_GAT t1 WHERE t1.CD_TIP_LCL_ATDT IN ( 1, 2 ) AND t1.NR_MTC_USU > 0 GROUP BY t1.NR_MTC_USU;
QUIT;

PROC SQL;
	CREATE TABLE DADOS_BASICOS AS 
		SELECT INPUT(UOR, 9.) AS UOR,
			INPUT(PrefDep,4.) AS PREFIXO, 
			INPUT(SB,2.) AS COD_SUBORDINADA, 
			NomeDep AS NOME, 
			INPUT(TipoDep,3.) AS TP_DEPENDENCIA, 
			t1.Status, 
			INPUT(Nivel,1.) AS NIVEL, 
			t1.UF, 
			INPUT(PrefDir,4.) AS DIRETORIA, 
			INPUT(PrefSuper,4.) AS SUPER, 
			INPUT(PrefSureg,4.) AS GEREV
		FROM IGR.DEPENDENCIAS_&ANOMES t1
			WHERE /*t1.PrefDir IN 
				(
				'8477',
				'8592',
				'9500'
				) AND*/ t1.SB IN 
				(
				'00',
				'91'
					) AND t1.Status = 'A';
QUIT;

PROC SQL;
	CREATE TABLE WORK.agencias_dados_basicos AS 
		SELECT DISTINCT t1.UOR, 
			t1.PREFIXO, 
			t1.COD_SUBORDINADA, 
			t1.NOME, 
			t1.TP_DEPENDENCIA, 
			t1.Status, 
			t1.Nivel, 
			t1.UF, 
			t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV
		FROM WORK.DADOS_BASICOS t1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.prefixos_com_saa AS 
		SELECT DISTINCT t1.PREFIXO, 
			t1.COD_SUBORDINADA, 
			t1.UOR AS UOR_SAA
		FROM WORK.AGENCIAS_DADOS_BASICOS t1
			WHERE t1.COD_SUBORDINADA = 91;
QUIT;

PROC SQL;
	CREATE TABLE WORK.LOTACAO_MINIMA AS 
		SELECT DISTINCT t1.dt_posicao, 
			t1.prefixo, 
			t1.lotacao_minima_supervisor, 
			t1.lotacao_minima_escriturario_saa, 
			t1.lotacao_minima_total_saa
		FROM novo_lotacao_saa t1
	;
QUIT;

PROC SQL;
	CREATE TABLE WORK.agencias_com_saa AS 
		SELECT DISTINCT t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t2.UOR_SAA, 
			t1.NOME, 
			t1.UF, 
			t1.NIVEL, 
			t1.TP_DEPENDENCIA, 
			t1.STATUS, 
			t3.lotacao_minima_total_saa AS LOTAC_MIN_FUNCIS_SAA, 
			t3.lotacao_minima_supervisor AS LOTAC_MIN_SUPERV_SAA, 
			t3.lotacao_minima_escriturario_saa AS LOTAC_MIN_ESCRIT_SAA, 
			/* REGRA_CALCULO_CONEXAO */
	(CASE
		WHEN t3.lotacao_minima_total_saa = 1 AND t3.lotacao_minima_supervisor = 1 THEN 'A' 
		WHEN t3.lotacao_minima_total_saa = 1 AND t3.lotacao_minima_escriturario_saa = 1 THEN 'B' 
		WHEN t3.lotacao_minima_total_saa > 1 THEN 'C' 
		END)
	AS REGRA_CALCULO_CONEXAO FROM WORK.AGENCIAS_DADOS_BASICOS t1 INNER JOIN WORK.PREFIXOS_COM_SAA t2 ON (t1.PREFIXO = t2.PREFIXO) INNER JOIN novo_lotacao_saa t3 ON (t1.PREFIXO = t3.prefixo) WHERE t1.TP_DEPENDENCIA IN ( 13, 15, 35 ) AND (CALCULATED REGRA_CALCULO_CONEXAO) NOT IS MISSING;
QUIT;

PROC SQL;
	CREATE TABLE WORK.PONTO_FUNCI AS 
		SELECT DISTINCT t1.NR_MTC_FUN, 
			t1.DT_JTRB
		FROM ARH.LOG_PTO_ETN t1
			WHERE t1.DT_JTRB EQ &d2.;
QUIT;

PROC SQL;
	CREATE TABLE WORK.funcis_substituicao AS 
		SELECT DISTINCT t1.CD_PRF_DEPE_SBTC, 
			t1.CD_MTC_FUN, 
			t1.DT_SBTC_FUC, 
			t1.CD_TIP_CMSS_FUC
		FROM ARH.SBTC_FUC_FUN t1
			WHERE t1.DT_SBTC_FUC EQ &d2.;
QUIT;

PROC SQL;
   CREATE TABLE WORK.previa_funcis_agencias AS 
   SELECT DISTINCT t1.PREFIXO, 
          t2.MATRICULA_215, 
          t2.SITUACAO_215, 
          t2.LOCALIZACAO_215, 
          t2.COMISSAO_215, 
          t2.AFR_215, 
          t2.FUNCAO_LOCALIZACAO_215, 
          t2.DEP_LOTACAO_215, 
          t2.FUNCAO_LOTACAO_215, 
          t2.HORA_TRAB_INI_215, 
          t2.HORA_TRAB_FIM_215, 
          t2.HORA_TRAB_INTERV_INI_215, 
          t2.HORA_TRAB_INTERV_FIM_215, 
          t2.HORA_TRAB_INTERV2_INI_215, 
          t2.HORA_TRAB_INTERV2_FIM_215, 
          t2.CD_UOR_LCZC, 
          t2.CD_UOR_TRB_HBTL, 
          /* FUNCI_ALOCADO_SAA */
            ((t2.CD_UOR_PSC_FUN = t1.UOR_SAA)) FORMAT=1. AS FUNCI_ALOCADO_SAA, 
          /* CD_TIP_CMSS_FUC */
            (CASE
              WHEN t3.CD_TIP_CMSS_FUC IS NOT MISSING THEN t3.CD_TIP_CMSS_FUC
              WHEN t2.COMISSAO_215 > 0 THEN t2.COMISSAO_215
              WHEN t2.COMISSAO_215 = 0 AND t2.FUNCAO_LOCALIZACAO_215 NOT IN (0, 999) THEN t2.FUNCAO_LOCALIZACAO_215
              ELSE t2.FUNCAO_LOTACAO_215
            END)
			AS CD_TIP_CMSS_FUC, 
          /* FUNCI_EXTRAQUADRO */
            (
				t2.FUNCAO_LOCALIZACAO_215 = 999
            	OR
            	(t2.FUNCAO_LOCALIZACAO_215 = 0 AND t2.FUNCAO_LOTACAO_215 = 999)
			)
			FORMAT=1. AS FUNCI_EXTRAQUADRO, 
          /* FUNCI_QS_LIC_SAUDE */
            (
				t2.FUNCAO_LOCALIZACAO_215 = 998
            	OR 
            	(t2.FUNCAO_LOCALIZACAO_215 = 0 AND t2.FUNCAO_LOTACAO_215 = 998)
			)
			FORMAT=1. AS FUNCI_QS_LIC_SAUDE, 
          /* FUNCI_EM_SUBSTITUICAO */
            (CASE 
               WHEN t3.CD_MTC_FUN NOT IS MISSING THEN 1
            END) FORMAT=1. AS FUNCI_EM_SUBSTITUICAO, 
          t3.CD_PRF_DEPE_SBTC AS PREFIXO_SUBSTITUICAO
      FROM WORK.AGENCIAS_COM_SAA t1
           INNER JOIN ADE.ARH215_CADASTRO_BASICO_&ANOMES t2 ON (t1.PREFIXO = t2.LOCALIZACAO_215) 
/*	  	   INNER JOIN ADE.ARH215_CADASTRO_BASICO t2 ON (t1.PREFIXO = t2.LOCALIZACAO_215)*/
           LEFT JOIN WORK.FUNCIS_SUBSTITUICAO t3 ON (t2.MATRICULA_215 = t3.CD_MTC_FUN)
      WHERE t2.DT_POSICAO EQ &d2. AND t2.SITUACAO_215 not in (800 802 809 810 820 825 834 850);
QUIT;

PROC SQL;
	CREATE TABLE WORK.funcis_agencias AS 
		SELECT DISTINCT t1.PREFIXO, 
			t1.MATRICULA_215, 
			t1.SITUACAO_215, 
			t1.LOCALIZACAO_215, 
			t1.COMISSAO_215, 
			t1.AFR_215, 
			t1.FUNCAO_LOCALIZACAO_215, 
			t1.DEP_LOTACAO_215, 
			t1.FUNCAO_LOTACAO_215, 
			t1.HORA_TRAB_INI_215, 
			t1.HORA_TRAB_FIM_215, 
			t1.HORA_TRAB_INTERV_INI_215, 
			t1.HORA_TRAB_INTERV_FIM_215, 
			t1.HORA_TRAB_INTERV2_INI_215, 
			t1.HORA_TRAB_INTERV2_FIM_215, 
			t1.CD_UOR_LCZC, 
			t1.CD_UOR_TRB_HBTL, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_EXTRAQUADRO, 
			t1.FUNCI_QS_LIC_SAUDE, 
			t1.FUNCI_EM_SUBSTITUICAO, 
			t1.PREFIXO_SUBSTITUICAO, 
			t1.CD_TIP_CMSS_FUC, 
			t2.IN_ICD_PTO_ETN, 
			t2.NM_TIP_CMSS_FUC, 
			t2.QT_HH_JRTB_DRIA, 
			t2.CD_REF_ORGC, 
			/* SUJEITO_PONTO_ELETRONICO */
	(t2.IN_ICD_PTO_ETN > 0 AND t1.FUNCI_QS_LIC_SAUDE = 0) FORMAT=1. AS SUJEITO_PONTO_ELETRONICO, /* FUNCI_ESCRIT_LOCALIZACAO */
	(CASE
		WHEN t3.CD_TIP_CMSS_FUC NOT IS MISSING THEN 1 
		ELSE 0 
		END)
	FORMAT=1. AS FUNCI_ESCRIT_LOCALIZACAO, /* FUNCI_ESCRIT_LOTACAO */
	(CASE
		WHEN t4.CD_TIP_CMSS_FUC NOT IS MISSING THEN 1 
		ELSE 0 
		END)
	FORMAT=1. AS FUNCI_ESCRIT_LOTACAO, /* FUNCI_CAIEX_LOCALIZACAO */
	(t1.CD_TIP_CMSS_FUC IN (288, 394)) FORMAT=1. AS FUNCI_CAIEX_LOCALIZACAO, /* FUNCI_CAIEX_LOTACAO */
	(t1.FUNCAO_LOTACAO_215 IN (288, 394)) FORMAT=1. AS FUNCI_CAIEX_LOTACAO FROM WORK.PREVIA_FUNCIS_AGENCIAS t1 LEFT JOIN ARH.TIP_CMSS_FUC t2 ON (t1.CD_TIP_CMSS_FUC = t2.CD_TIP_CMSS_FUC) LEFT JOIN ADE.FUNCOES_EQUIV_ESCRITURARIO t3 ON (t1.CD_TIP_CMSS_FUC = t3.CD_TIP_CMSS_FUC) LEFT JOIN ADE.FUNCOES_EQUIV_ESCRITURARIO t4 ON (t1.FUNCAO_LOTACAO_215 = t4.CD_TIP_CMSS_FUC);
QUIT;

PROC SQL;
	CREATE TABLE WORK.funcis_registro_ponto AS 
		SELECT DISTINCT
			/* REGISTROU_PONTO */
	(CASE
		WHEN t2.NR_MTC_FUN IS MISSING THEN 0 
		ELSE 1 
		END)
	FORMAT=1. AS REGISTROU_PONTO, t1.PREFIXO, t1.MATRICULA_215, t1.SITUACAO_215, t1.LOCALIZACAO_215, t1.COMISSAO_215, t1.AFR_215, t1.FUNCAO_LOCALIZACAO_215, t1.DEP_LOTACAO_215, t1.FUNCAO_LOTACAO_215, t1.HORA_TRAB_INI_215, t1.HORA_TRAB_FIM_215, t1.HORA_TRAB_INTERV_INI_215, t1.HORA_TRAB_INTERV_FIM_215, t1.HORA_TRAB_INTERV2_INI_215, t1.HORA_TRAB_INTERV2_FIM_215, t1.CD_UOR_LCZC, t1.CD_UOR_TRB_HBTL, t1.FUNCI_ALOCADO_SAA, t1.FUNCI_EXTRAQUADRO, t1.FUNCI_QS_LIC_SAUDE, t1.FUNCI_EM_SUBSTITUICAO, t1.PREFIXO_SUBSTITUICAO, t1.CD_TIP_CMSS_FUC, t1.IN_ICD_PTO_ETN, t1.NM_TIP_CMSS_FUC, t1.QT_HH_JRTB_DRIA, /* QT_MINUTOS_JRTB_DRIA */
	(t1.QT_HH_JRTB_DRIA * 60) AS QT_MINUTOS_JRTB_DRIA, t1.CD_REF_ORGC, t1.SUJEITO_PONTO_ELETRONICO, t1.FUNCI_ESCRIT_LOCALIZACAO, t1.FUNCI_ESCRIT_LOTACAO, t1.FUNCI_CAIEX_LOCALIZACAO, t1.FUNCI_CAIEX_LOTACAO, /* FUNCI_SUPERVISOR */
	(t1.CD_TIP_CMSS_FUC = 4699) FORMAT=1. AS FUNCI_SUPERVISOR, /* FUNCI_CAIEX_EFETIVO */
	(t1.FUNCI_CAIEX_LOCALIZACAO = 1 AND t1.FUNCI_CAIEX_LOTACAO = 1) FORMAT=1. AS FUNCI_CAIEX_EFETIVO, /* FUNCI_ESCRITURARIO */
	(t1.FUNCI_ESCRIT_LOCALIZACAO = 1 OR (t1.FUNCI_CAIEX_LOCALIZACAO = 1 AND t1.FUNCI_ESCRIT_LOTACAO = 1)) FORMAT=1. AS FUNCI_ESCRITURARIO FROM WORK.FUNCIS_AGENCIAS t1 LEFT JOIN WORK.PONTO_FUNCI t2 ON (t1.MATRICULA_215 = t2.NR_MTC_FUN);
QUIT;

PROC SQL;
	CREATE TABLE WORK.jornada_dia AS 
		SELECT DISTINCT t1.CD_MTC_FUN, 
			t1.DT_JTRB_DIAR_FUN, 
			t1.CD_EST_JTRB_DIAR, 
			t1.TX_MVT_ENTD_FUN, 
			t1.TX_MVT_SAID_FUN, 
			t1.TX_MVT_ENTD_RGTD, 
			t1.TX_MVT_SAID_RGTD, 
			t1.CD_RSP_MVT_RGTD, 
			t1.TS_ATL_JTRB, 
			t1.HR_INC_ITVL_TRB, 
			t1.HR_FIM_ITVL_TRB, 
			t1.TX_OBS_FUN_RSP, 
			t1.QT_HH_TBRD_ATN, 
			t1.QT_HH_EXTA_DRNO, 
			t1.QT_HH_EXTA_NTNO, 
			t1.IN_CCDC_FUN, 
			t1.TS_CCDC_FUN, 
			t1.CD_USU_RSP_VLDC, 
			t1.TS_VLDC_PTO_DIAR, 
			t1.HR_ENTD_EXTA_AUTD, 
			t1.CD_USU_AUTZ_ENTD, 
			t1.TS_CON_AUTZ_ENTD, 
			t1.IN_AUTZ_DD_UTIL, 
			t1.QT_HH_PRGC_PRVR, 
			t1.TS_AUTZ_PRGC_PRVR, 
			t1.CD_USU_PRGC_PRVR, 
			t1.TX_DCR_DCDC_PTO
		FROM ARH.JTRB_DIAR_FUN t1
			WHERE t1.DT_JTRB_DIAR_FUN EQ &d2.;
QUIT;

PROC SQL;
	CREATE TABLE WORK.funcis_previstos_trabalhar AS 
		SELECT DISTINCT t1.CD_MTC_FUN, 
			t1.DT_JTRB_DIAR_FUN, 
			/* FUNCI_AUSENTE */
	(CASE
		WHEN t1.TS_ATL_JTRB IS MISSING THEN 1 
		ELSE 0 
		END)
	FORMAT=1. AS FUNCI_AUSENTE, t1.QT_HH_EXTA_DRNO AS HORAS_EXTRAS_DIURNAS, t1.QT_HH_EXTA_NTNO AS HORAS_EXTRAS_NOTURNAS, /* HORAS_EXTRAS_TOTAL */
	(SUM(t1.QT_HH_EXTA_DRNO, t1.QT_HH_EXTA_NTNO)) FORMAT=COMMAX5.2 AS HORAS_EXTRAS_TOTAL FROM WORK.JORNADA_DIA t1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.situacao_ponto_funci AS 
		SELECT DISTINCT t1.CD_MTC_FUN, 
			t1.DT_INC_EST_FUN, 
			t1.DT_FIM_EST_FUN, 
			t1.IN_EST_FUNL_PRVR, 
			t1.CD_TIP_EST_FUNL, 
			t1.QT_DD_PMC_EST, 
			t1.IN_EST_FUNL_PRVR AS IND_SITUACAO_TEMPORARIA
		FROM ARH.EST_FUN t1
			WHERE t1.DT_INC_EST_FUN LE &d2. AND t1.DT_FIM_EST_FUN GE &d2.;
QUIT;

PROC SQL;
	CREATE TABLE WORK.funcis_previa_final AS 
		SELECT DISTINCT t1.REGISTROU_PONTO, 
			t1.PREFIXO, 
			t1.MATRICULA_215, 
			t1.SITUACAO_215, 
			t1.LOCALIZACAO_215, 
			t1.COMISSAO_215, 
			t1.AFR_215, 
			t1.FUNCAO_LOCALIZACAO_215, 
			t1.DEP_LOTACAO_215, 
			t1.FUNCAO_LOTACAO_215, 
			t1.HORA_TRAB_INI_215, 
			t1.HORA_TRAB_FIM_215, 
			t1.HORA_TRAB_INTERV_INI_215, 
			t1.HORA_TRAB_INTERV_FIM_215, 
			t1.HORA_TRAB_INTERV2_INI_215, 
			t1.HORA_TRAB_INTERV2_FIM_215, 
			t1.CD_UOR_LCZC, 
			t1.CD_UOR_TRB_HBTL, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_EXTRAQUADRO, 
			t1.FUNCI_QS_LIC_SAUDE, 
			t1.FUNCI_EM_SUBSTITUICAO, 
			t1.PREFIXO_SUBSTITUICAO, 
			t1.CD_TIP_CMSS_FUC, 
			t1.IN_ICD_PTO_ETN, 
			t1.NM_TIP_CMSS_FUC, 
			t1.QT_HH_JRTB_DRIA, 
			t1.QT_MINUTOS_JRTB_DRIA, 
			t1.CD_REF_ORGC, 
			t1.SUJEITO_PONTO_ELETRONICO, 
			t1.FUNCI_ESCRIT_LOCALIZACAO, 
			t1.FUNCI_ESCRIT_LOTACAO, 
			t1.FUNCI_CAIEX_LOCALIZACAO, 
			t1.FUNCI_CAIEX_LOTACAO, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ESCRITURARIO, 
			/* FUNCI_PREVISTO_TRABALHAR */
	(CASE
		WHEN t2.CD_MTC_FUN NOT IS MISSING THEN 1 
		ELSE 0 
		END)
	FORMAT=1. AS FUNCI_PREVISTO_TRABALHAR, /* FUNCI_HORAS_EXTRAS */
	(CASE
		WHEN t2.HORAS_EXTRAS_TOTAL IS MISSING THEN 0 
		ELSE t2.HORAS_EXTRAS_TOTAL 
		END)
	FORMAT=COMMAX5.2 AS FUNCI_HORAS_EXTRAS, /* SITUACAO_PONTO_FUNCI */
	(CASE
		WHEN t3.CD_TIP_EST_FUNL IS MISSING THEN t1.SITUACAO_215 
		ELSE t3.CD_TIP_EST_FUNL 
		END)
	FORMAT=BEST3. AS SITUACAO_PONTO_FUNCI, /* FUNCI_AUSENTE */
	(CASE
		WHEN t2.FUNCI_AUSENTE IS MISSING THEN 0 
		ELSE t2.FUNCI_AUSENTE 
		END)
	FORMAT=1. AS FUNCI_AUSENTE FROM WORK.FUNCIS_REGISTRO_PONTO t1 LEFT JOIN WORK.FUNCIS_PREVISTOS_TRABALHAR t2 ON (t1.MATRICULA_215 = t2.CD_MTC_FUN) LEFT JOIN WORK.SITUACAO_PONTO_FUNCI t3 ON (t1.MATRICULA_215 = t3.CD_MTC_FUN);
QUIT;

PROC SQL;
	CREATE TABLE WORK.funcis_final AS 
		SELECT DISTINCT 
            IFN(nm_tip_cmss_fuc='GER GERAL UN',0,REGISTROU_PONTO) AS REGISTROU_PONTO, 
			REGISTROU_PONTO AS REGISTROU_2,
			t1.PREFIXO, 
			t1.MATRICULA_215, 
			t1.SITUACAO_215, 
			t2.Nome AS NOME_SITUACAO_FUNCI, 
			t2.AUSENTE AS SITUACAO_FUNCI_INDICA_AUSENCIA, 
			t1.LOCALIZACAO_215, 
			t1.COMISSAO_215, 
			t1.AFR_215, 
			t1.FUNCAO_LOCALIZACAO_215, 
			t1.DEP_LOTACAO_215, 
			t1.FUNCAO_LOTACAO_215, 
			t1.HORA_TRAB_INI_215, 
			t1.HORA_TRAB_FIM_215, 
			t1.HORA_TRAB_INTERV_INI_215, 
			t1.HORA_TRAB_INTERV_FIM_215, 
			t1.HORA_TRAB_INTERV2_INI_215, 
			t1.HORA_TRAB_INTERV2_FIM_215, 
			t1.CD_UOR_LCZC, 
			t1.CD_UOR_TRB_HBTL, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_EXTRAQUADRO, 
			t1.FUNCI_QS_LIC_SAUDE, 
			t1.FUNCI_EM_SUBSTITUICAO, 
			t1.PREFIXO_SUBSTITUICAO, 
			t1.CD_TIP_CMSS_FUC, 
			t1.IN_ICD_PTO_ETN, 
			t1.NM_TIP_CMSS_FUC, 
			t1.QT_HH_JRTB_DRIA, 
			t1.QT_MINUTOS_JRTB_DRIA, 
			t1.FUNCI_HORAS_EXTRAS, 
			t1.CD_REF_ORGC, 
			t1.SUJEITO_PONTO_ELETRONICO, 
			t1.FUNCI_ESCRIT_LOCALIZACAO, 
			t1.FUNCI_ESCRIT_LOTACAO, 
			t1.FUNCI_CAIEX_LOCALIZACAO, 
			t1.FUNCI_CAIEX_LOTACAO, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.SITUACAO_PONTO_FUNCI, 
			/* QT_HORAS_TRABALHADAS_DIA */
	(SUM(t1.QT_HH_JRTB_DRIA, t1.FUNCI_HORAS_EXTRAS)) FORMAT=BEST10.2 AS QT_HORAS_TRABALHADAS_DIA, /* QT_MINUTOS_TRABALHADOS_DIA */
	((SUM(t1.QT_HH_JRTB_DRIA, t1.FUNCI_HORAS_EXTRAS)) * 60) FORMAT=COMMAX10. AS QT_MINUTOS_TRABALHADOS_DIA, /* FUNCI_AUSENTE */
	(CASE
		WHEN t2.Cod IS NOT MISSING AND t2.AUSENTE = 1 THEN t2.AUSENTE 
		WHEN t1.SUJEITO_PONTO_ELETRONICO = 1 AND t1.REGISTROU_PONTO = 0 THEN 1 
		ELSE t1.FUNCI_AUSENTE 
		END)
	FORMAT=1. AS FUNCI_AUSENTE FROM WORK.FUNCIS_PREVIA_FINAL t1 LEFT JOIN ADE.EST_SIT_FCN_AUSENTE t2 ON (t1.SITUACAO_PONTO_FUNCI = t2.Cod);
QUIT;



/*CRIAR FUNCIONÁRIO NO PREFIXO DE DOTAÇÃO - POR SOLICITAÇÃO DA UAT*/

DATA FANTASMA_SUBSTITUICAO;
SET funcis_final;
WHERE REGISTROU_PONTO = 0 AND REGISTROU_2 = 1;
RUN;


DATA FANTASMA_ADIDO;
SET funcis_final;
WHERE SITUACAO_215=510;
RUN;

DATA JUNTA_AUSENCIAS_DEP_LOTACAO;
SET FANTASMA_SUBSTITUICAO FANTASMA_ADIDO;
RUN;

PROC SQL;
   CREATE TABLE WORK.funcis_fantasma AS 
   SELECT 0 AS REGISTROU_PONTO, 
          t1.REGISTROU_2, 
          t1.DEP_LOTACAO_215 as PREFIXO, 
          t1.MATRICULA_215, 
          t1.SITUACAO_215, 
          t1.NOME_SITUACAO_FUNCI, 
          1 AS SITUACAO_FUNCI_INDICA_AUSENCIA, 
          t1.DEP_LOTACAO_215 AS LOCALIZACAO_215, 
          t1.COMISSAO_215, 
          t1.AFR_215, 
          t1.FUNCAO_LOCALIZACAO_215 AS FUNCAO_LOTACAO_215, 
          t1.DEP_LOTACAO_215, 
          t1.FUNCAO_LOTACAO_215 AS FUNCAO_LOCALIZACAO_215, 
          0 as HORA_TRAB_INI_215, 
          0 as HORA_TRAB_FIM_215, 
          0 as HORA_TRAB_INTERV_INI_215, 
          0 as HORA_TRAB_INTERV_FIM_215, 
          0 as HORA_TRAB_INTERV2_INI_215, 
          0 as HORA_TRAB_INTERV2_FIM_215, 
          t1.CD_UOR_LCZC, 
          t1.CD_UOR_TRB_HBTL, 
          0 as FUNCI_ALOCADO_SAA, 
          0 as FUNCI_EXTRAQUADRO, 
          0 as FUNCI_QS_LIC_SAUDE, 
          t1.FUNCI_EM_SUBSTITUICAO, 
          t1.PREFIXO_SUBSTITUICAO, 
          t1.CD_TIP_CMSS_FUC, 
          t1.IN_ICD_PTO_ETN, 
          t1.NM_TIP_CMSS_FUC, 
          0 as QT_HH_JRTB_DRIA, 
          0 as QT_MINUTOS_JRTB_DRIA, 
          0 as FUNCI_HORAS_EXTRAS, 
          t1.CD_REF_ORGC, 
          1 as SUJEITO_PONTO_ELETRONICO, 
          0 as FUNCI_ESCRIT_LOCALIZACAO, 
          0 as FUNCI_ESCRIT_LOTACAO, 
          0 as FUNCI_CAIEX_LOCALIZACAO, 
          t1.FUNCI_CAIEX_LOTACAO, 
          t1.FUNCI_SUPERVISOR, 
          t1.FUNCI_CAIEX_EFETIVO, 
          t1.FUNCI_ESCRITURARIO, 
          t1.FUNCI_PREVISTO_TRABALHAR, 
          t1.SITUACAO_PONTO_FUNCI, 
          0 as QT_HORAS_TRABALHADAS_DIA, 
          0 as QT_MINUTOS_TRABALHADOS_DIA, 
          1 as FUNCI_AUSENTE
      FROM WORK.JUNTA_AUSENCIAS_DEP_LOTACAO t1;
QUIT;

data junta_funcis;
set funcis_final funcis_fantasma;
run;

PROC SQL;
	CREATE TABLE WORK.previa_agencias_localiz_alocacao AS 
		SELECT DISTINCT t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.UOR_SAA, 
			t1.NOME, 
			t1.UF, 
			t1.NIVEL, 
			t1.TP_DEPENDENCIA, 
			t1.STATUS, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			/* QTDE_FUNCIS_LCLZ_PREF */
	(COUNT(DISTINCT(t2.MATRICULA_215))) FORMAT=BEST3. AS QTDE_FUNCIS_LCLZ_PREF, /* QTDE_SUPERV_LCLZ_PREF */
	(SUM(CASE WHEN t2.FUNCI_SUPERVISOR = 1 AND t2.FUNCI_QS_LIC_SAUDE = 0 THEN 1 ELSE 0 END )) FORMAT=1. AS QTDE_SUPERV_LCLZ_PREF, /* QTDE_ESCRIT_LCLZ_PREF */
	(SUM(CASE WHEN t2.FUNCI_ESCRITURARIO = 1 AND t2.FUNCI_QS_LIC_SAUDE = 0 THEN 1 ELSE 0 END )) FORMAT=3. AS QTDE_ESCRIT_LCLZ_PREF, /* QTDE_FUNCIS_QS_LIC_SAUDE */
	(SUM(t2.FUNCI_QS_LIC_SAUDE)) FORMAT=3. AS QTDE_FUNCIS_QS_LIC_SAUDE, /* QTDE_FUNCIS_DEMAIS_LCLZ_PREF */
	(SUM(CASE WHEN t2.FUNCI_SUPERVISOR = 0 AND t2.FUNCI_ESCRITURARIO = 0 AND t2.FUNCI_QS_LIC_SAUDE = 0 THEN 1 ELSE 0 END)) FORMAT=3. AS QTDE_FUNCIS_DEMAIS_LCLZ_PREF, /* QTDE_FUNCIS_EXTRAQUADRO */
	(SUM(t2.FUNCI_EXTRAQUADRO)) FORMAT=3. AS QTDE_FUNCIS_EXTRAQUADRO, /* QTDE_FUNCIS_ALOCADOS_SAA */
	(SUM(((t2.FUNCI_SUPERVISOR = 1 OR t2.FUNCI_ESCRITURARIO = 1) AND t2.FUNCI_ALOCADO_SAA = 1 AND t2.FUNCI_QS_LIC_SAUDE = 0))) FORMAT=3. AS QTDE_FUNCIS_ALOCADOS_SAA, /* QTDE_SUPERV_ALOCADOS_SAA */
	(SUM(CASE WHEN t2.FUNCI_SUPERVISOR = 1 AND t2.FUNCI_QS_LIC_SAUDE = 0 AND t2.FUNCI_ALOCADO_SAA THEN 1 ELSE 0 END )) FORMAT=1. AS QTDE_SUPERV_ALOCADOS_SAA, /* QTDE_ESCRIT_ALOCADOS_SAA */
	(SUM(CASE WHEN t2.FUNCI_ESCRITURARIO = 1 AND t2.FUNCI_QS_LIC_SAUDE = 0 AND t2.FUNCI_ALOCADO_SAA = 1 THEN 1 ELSE 0 END )) FORMAT=3. AS QTDE_ESCRIT_ALOCADOS_SAA, /* QTDE_FUNCIS_REG_PTO */
	(SUM(t2.REGISTROU_PONTO)) FORMAT=3. AS QTDE_FUNCIS_REG_PTO, /* QTDE_ESCRIT_REG_PTO */
	(SUM((t2.FUNCI_ESCRITURARIO = 1 AND t2.REGISTROU_PONTO = 1))) FORMAT=3. AS QTDE_ESCRIT_REG_PTO, /* QTDE_SUPERV_REG_PTO */
	(SUM(t2.FUNCI_SUPERVISOR = 1 AND t2.REGISTROU_PONTO = 1)) FORMAT=3. AS QTDE_SUPERV_REG_PTO, /* QTDE_ALOC_SAA_REG_PTO */
	(SUM(((t2.FUNCI_SUPERVISOR = 1 OR t2.FUNCI_ESCRITURARIO = 1) AND t2.FUNCI_ALOCADO_SAA = 1 AND t2.REGISTROU_PONTO = 1))) FORMAT=3. AS QTDE_ALOC_SAA_REG_PTO, /* QTDE_SUPERV_SAA_REG_PTO */
	(SUM((t2.FUNCI_SUPERVISOR = 1 AND t2.FUNCI_ALOCADO_SAA = 1 AND t2.REGISTROU_PONTO = 1))) FORMAT=3. AS QTDE_SUPERV_SAA_REG_PTO, /* QTDE_ESCRIT_SAA_REG_PTO */
	(SUM((t2.FUNCI_ESCRITURARIO =1 AND t2.FUNCI_ALOCADO_SAA = 1 AND t2.REGISTROU_PONTO = 1))) FORMAT=3. AS QTDE_ESCRIT_SAA_REG_PTO, /* QTDE_FUNCIS_SUJEITOS_PONTO */
	(SUM(t2.SUJEITO_PONTO_ELETRONICO)) FORMAT=3. AS QTDE_FUNCIS_SUJEITOS_PONTO, /* QTDE_FUNCIS_REGISTRARAM_PONTO */
	(SUM(t2.REGISTROU_PONTO)) FORMAT=3. AS QTDE_FUNCIS_REGISTRARAM_PONTO, /* QTDE_FUNCIS_PREV_TRABALHAR */
	(SUM(t2.FUNCI_PREVISTO_TRABALHAR)) FORMAT=BEST5. AS QTDE_FUNCIS_PREV_TRABALHAR, /* QTDE_SUPERV_PREV_TRABALHAR */
	(SUM((t2.FUNCI_SUPERVISOR = 1 AND t2.FUNCI_PREVISTO_TRABALHAR = 1))) FORMAT=BEST2. AS QTDE_SUPERV_PREV_TRABALHAR, /* QTDE_ESCRIT_PREV_TRABALHAR */
	(SUM((t2.FUNCI_ESCRITURARIO = 1 AND t2.FUNCI_PREVISTO_TRABALHAR = 1))) FORMAT=BEST2. AS QTDE_ESCRIT_PREV_TRABALHAR, /* QTDE_FUNCIS_AUSENTES_TOTAL */
	(SUM(t2.FUNCI_AUSENTE)) FORMAT=5. AS QTDE_FUNCIS_AUSENTES_TOTAL, /* QTDE_ALOC_SAA_TRABALHOU */
	(SUM(((t2.FUNCI_SUPERVISOR = 1 OR t2.FUNCI_ESCRITURARIO = 1) AND t2.FUNCI_ALOCADO_SAA = 1 AND t2.FUNCI_AUSENTE = 0))) FORMAT=3. AS QTDE_ALOC_SAA_TRABALHOU, /* QTDE_SUPERV_SAA_TRABALHOU */
	(SUM((t2.FUNCI_SUPERVISOR = 1 AND t2.FUNCI_ALOCADO_SAA = 1 AND t2.FUNCI_AUSENTE = 0))) FORMAT=3. AS QTDE_SUPERV_SAA_TRABALHOU, /* QTDE_ESCRIT_SAA_TRABALHOU */
	(SUM((t2.FUNCI_ESCRITURARIO =1 AND t2.FUNCI_ALOCADO_SAA = 1 AND t2.FUNCI_AUSENTE = 0))) FORMAT=3. AS QTDE_ESCRIT_SAA_TRABALHOU, /* QTDE_ESCRIT_TRABALHOU */
	(SUM((t2.FUNCI_ESCRITURARIO = 1 AND t2.FUNCI_AUSENTE = 0))) FORMAT=3. AS QTDE_ESCRIT_TRABALHOU, /* QTDE_SUPERV_TRABALHOU */
	(SUM(t2.FUNCI_SUPERVISOR = 1 AND t2.FUNCI_AUSENTE = 0)) FORMAT=3. AS QTDE_SUPERV_TRABALHOU, /* QTDE_FUNCIS_TRABALHOU */
	(SUM(CASE WHEN t2.FUNCI_AUSENTE NOT = 1 THEN 1 ELSE t2.FUNCI_AUSENTE END)) FORMAT=3. AS QTDE_FUNCIS_TRABALHOU FROM WORK.AGENCIAS_COM_SAA t1 LEFT JOIN WORK.junta_funcis t2 ON (t1.PREFIXO = t2.PREFIXO) GROUP BY t1.DIRETORIA, t1.SUPER, t1.GEREV, t1.PREFIXO, t1.UOR, t1.UOR_SAA, t1.NOME, t1.UF, t1.NIVEL, t1.TP_DEPENDENCIA, t1.STATUS, t1.LOTAC_MIN_FUNCIS_SAA, t1.LOTAC_MIN_SUPERV_SAA, t1.LOTAC_MIN_ESCRIT_SAA, t1.REGRA_CALCULO_CONEXAO ORDER BY t1.PREFIXO;
QUIT;


PROC SQL;
	CREATE TABLE WORK.agencias_localizacao_alocacao AS 
		SELECT DISTINCT t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.UOR_SAA, 
			t1.NOME, 
			t1.UF, 
			t1.NIVEL, 
			t1.TP_DEPENDENCIA, 
			t1.Status, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_SUPERV_LCLZ_PREF, 
			t1.QTDE_ESCRIT_LCLZ_PREF, 
			t1.QTDE_FUNCIS_QS_LIC_SAUDE, 
			t1.QTDE_FUNCIS_DEMAIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_EXTRAQUADRO, 
			t1.QTDE_FUNCIS_ALOCADOS_SAA, 
			t1.QTDE_SUPERV_ALOCADOS_SAA, 
			t1.QTDE_ESCRIT_ALOCADOS_SAA, 
			t1.QTDE_FUNCIS_PREV_TRABALHAR, 
			t1.QTDE_FUNCIS_REG_PTO, 
			t1.QTDE_ESCRIT_REG_PTO, 
			t1.QTDE_SUPERV_REG_PTO, 
			t1.QTDE_ALOC_SAA_REG_PTO, 
			t1.QTDE_SUPERV_SAA_REG_PTO, 
			t1.QTDE_ESCRIT_SAA_REG_PTO, 
			t1.QTDE_FUNCIS_SUJEITOS_PONTO, 
			t1.QTDE_FUNCIS_REGISTRARAM_PONTO, 
			t1.QTDE_ALOC_SAA_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_TRABALHOU, 
			t1.QTDE_SUPERV_TRABALHOU, 
			t1.QTDE_FUNCIS_TRABALHOU, 
			/* QTDE_FUNCIS_AUSENTES_TOTAL */
	(CASE
		WHEN t1.QTDE_FUNCIS_AUSENTES_TOTAL IS MISSING THEN 0 
		ELSE t1.QTDE_FUNCIS_AUSENTES_TOTAL 
		END)
	FORMAT=5. AS QTDE_FUNCIS_AUSENTES_TOTAL, /* PERC_AUSENCIAS_TOTAL */

	/*            (CASE*/
	/*              WHEN t1.QTDE_FUNCIS_LCLZ_PREF > 0*/
	/*              THEN (t1.QTDE_FUNCIS_AUSENTES_TOTAL / t1.QTDE_FUNCIS_LCLZ_PREF)*/
	/*              ELSE 0*/
	/*            END) FORMAT=10.5 AS PERC_AUSENCIAS_TOTAL, */
	/* PERC_AUSENCIAS_SUJEITO_AO_PONTO*/
	(CASE
		WHEN t1.QTDE_FUNCIS_LCLZ_PREF > 0 THEN ( 1- (t1.QTDE_FUNCIS_REGISTRARAM_PONTO/t1.QTDE_FUNCIS_SUJEITOS_PONTO)) 
		ELSE 0 
		END)
	FORMAT=10.5 AS PERC_AUSENCIAS_TOTAL, /* PERC_AUSENCIAS_SUPERV */
	(CASE
		WHEN t1.QTDE_SUPERV_LCLZ_PREF > 0 THEN (1 - (t1.QTDE_SUPERV_TRABALHOU / t1.QTDE_SUPERV_LCLZ_PREF)) 
		ELSE 0 
		END)
	FORMAT=10.5 AS PERC_AUSENCIAS_SUPERV, /* PERC_AUSENCIAS_ESCRIT */
	(CASE
		WHEN t1.QTDE_ESCRIT_LCLZ_PREF > 0 THEN (1 - (t1.QTDE_ESCRIT_TRABALHOU / t1.QTDE_ESCRIT_LCLZ_PREF)) 
		ELSE 0 
		END)
	FORMAT=10.5 AS PERC_AUSENCIAS_ESCRIT, /* PERC_AUSENCIAS_SAA */
	(CASE
		WHEN t1.QTDE_FUNCIS_ALOCADOS_SAA > 0 THEN (1 - (t1.QTDE_ALOC_SAA_REG_PTO / t1.QTDE_FUNCIS_ALOCADOS_SAA)) 
		ELSE 0 
		END)
	FORMAT=10.5 AS PERC_AUSENCIAS_SAA, /* PERC_AUSENCIAS_SUPERV_SAA */
	(CASE
		WHEN t1.QTDE_SUPERV_ALOCADOS_SAA > 0 THEN (1 - (t1.QTDE_SUPERV_SAA_TRABALHOU / t1.QTDE_SUPERV_ALOCADOS_SAA)) 
		ELSE 0 
		END)
	FORMAT=10.5 AS PERC_AUSENCIAS_SUPERV_SAA, /* PERC_AUSENCIAS_ESCRIT_SAA */
	(CASE
		WHEN t1.QTDE_ESCRIT_ALOCADOS_SAA > 0 THEN (1 - (t1.QTDE_ESCRIT_SAA_TRABALHOU / t1.QTDE_ESCRIT_ALOCADOS_SAA)) 
		ELSE 0 
		END)
	FORMAT=10.5 AS PERC_AUSENCIAS_ESCRIT_SAA FROM WORK.PREVIA_AGENCIAS_LOCALIZ_ALOCACAO t1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.previa_agencias_regras_calculo AS 
		SELECT DISTINCT t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.UOR_SAA, 
			t1.NOME, 
			t1.UF, 
			t1.NIVEL, 
			t1.TP_DEPENDENCIA, 
			t1.Status, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_SUPERV_LCLZ_PREF, 
			t1.QTDE_ESCRIT_LCLZ_PREF, 
			t1.QTDE_FUNCIS_QS_LIC_SAUDE, 
			t1.QTDE_FUNCIS_DEMAIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_EXTRAQUADRO, 
			t1.QTDE_FUNCIS_PREV_TRABALHAR,
			t1.QTDE_FUNCIS_ALOCADOS_SAA, 
			t1.QTDE_SUPERV_ALOCADOS_SAA, 
			t1.QTDE_ESCRIT_ALOCADOS_SAA, 
			t1.QTDE_FUNCIS_REG_PTO, 
			t1.QTDE_ESCRIT_REG_PTO, 
			t1.QTDE_SUPERV_REG_PTO, 
			t1.QTDE_ALOC_SAA_REG_PTO, 
			t1.QTDE_SUPERV_SAA_REG_PTO, 
			t1.QTDE_ESCRIT_SAA_REG_PTO, 
			t1.QTDE_FUNCIS_SUJEITOS_PONTO, 
			t1.QTDE_FUNCIS_REGISTRARAM_PONTO, 
			t1.QTDE_ALOC_SAA_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_TRABALHOU, 
			t1.QTDE_SUPERV_TRABALHOU, 
			t1.QTDE_FUNCIS_TRABALHOU, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL, 
			t1.PERC_AUSENCIAS_TOTAL, 
			t1.PERC_AUSENCIAS_SUPERV, 
			t1.PERC_AUSENCIAS_ESCRIT, 
			t1.PERC_AUSENCIAS_SAA, 
			t1.PERC_AUSENCIAS_SUPERV_SAA, 
			t1.PERC_AUSENCIAS_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t2.DESCRICAO_REGRA, 
			t2.PESO_POR_FUNCI, 
			/* PONTUACAO_MAXIMA_REGRA */

	/*            (t1.LOTAC_MIN_FUNCIS_SAA * t2.PESO_POR_FUNCI) AS PONTUACAO_MAXIMA_REGRA, */
	SUM(
	MIN(t1.LOTAC_MIN_SUPERV_SAA, t1.QTDE_SUPERV_TRABALHOU),
	MIN(t1.LOTAC_MIN_ESCRIT_SAA, t1.QTDE_ESCRIT_TRABALHOU)
	) * t2.PESO_POR_FUNCI AS PONTUACAO_MAXIMA_REGRA,
	/* PONTUACAO_MAXIMA_REG_PTO */

	/* PONTUACAO_MAXIMA_REG_PTO */
	/*            (t1.QTDE_ALOC_SAA_REG_PTO * t2.PESO_POR_FUNCI) AS PONTUACAO_MAXIMA_REG_PTO,  REGRA ANTERIOR*/
	SUM(
	MIN(t1.LOTAC_MIN_SUPERV_SAA, t1.QTDE_SUPERV_TRABALHOU),
	MIN(t1.LOTAC_MIN_ESCRIT_SAA, t1.QTDE_ESCRIT_TRABALHOU)
	) * t2.PESO_POR_FUNCI
	AS PONTUACAO_MAXIMA_REG_PTO,
		/* PONTUACAO_MAXIMA_TRABALHOU */
	/*(t1.QTDE_ALOC_SAA_TRABALHOU * t2.PESO_POR_FUNCI) AS PONTUACAO_MAXIMA_TRABALHOU*/((QTDE_SUPERV_TRABALHOU+LOTAC_MIN_ESCRIT_SAA)* t2.PESO_POR_FUNCI) AS PONTUACAO_MAXIMA_TRABALHOU, t2.IND_UOR_PTOS_SUPERV, t2.IND_GAT_ORCADO_SUPERV, t2.IND_GAT_PTOS_SUPERV, t2.IND_UOR_PTOS_ESCRIT, t2.IND_GAT_ORCADO_ESCRIT, t2.IND_GAT_PTOS_ESCRIT FROM WORK.AGENCIAS_LOCALIZACAO_ALOCACAO t1 LEFT JOIN ADE.REGRAS_CALCULO_2019 t2 ON (t1.REGRA_CALCULO_CONEXAO = t2.REGRA_CALCULO_CONEXAO) WHERE t1.REGRA_CALCULO_CONEXAO NOT IS MISSING GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,51,52,53,54,55,56,57;
QUIT;

PROC SQL;
	CREATE TABLE WORK.agencias_regras_calculo AS 
		SELECT DISTINCT t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.UOR_SAA, 
			t1.NOME, 
			t1.UF, 
			t1.NIVEL, 
			t1.TP_DEPENDENCIA, 
			t1.Status, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_SUPERV_LCLZ_PREF, 
			t1.QTDE_ESCRIT_LCLZ_PREF, 
			t1.QTDE_FUNCIS_QS_LIC_SAUDE, 
			t1.QTDE_FUNCIS_DEMAIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_EXTRAQUADRO, 
			t1.QTDE_FUNCIS_PREV_TRABALHAR,
			t1.QTDE_FUNCIS_ALOCADOS_SAA, 
			t1.QTDE_SUPERV_ALOCADOS_SAA, 
			t1.QTDE_ESCRIT_ALOCADOS_SAA, 
			t1.QTDE_FUNCIS_REG_PTO, 
			t1.QTDE_ESCRIT_REG_PTO, 
			t1.QTDE_SUPERV_REG_PTO, 
			t1.QTDE_ALOC_SAA_REG_PTO, 
			t1.QTDE_SUPERV_SAA_REG_PTO, 
			t1.QTDE_ESCRIT_SAA_REG_PTO, 
			t1.QTDE_FUNCIS_SUJEITOS_PONTO, 
			t1.QTDE_FUNCIS_REGISTRARAM_PONTO, 
			t1.QTDE_ALOC_SAA_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_TRABALHOU, 
			t1.QTDE_SUPERV_TRABALHOU, 
			t1.QTDE_FUNCIS_TRABALHOU, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL, 
			t1.PERC_AUSENCIAS_TOTAL, 
			t1.PERC_AUSENCIAS_SUPERV, 
			t1.PERC_AUSENCIAS_ESCRIT, 
			t1.PERC_AUSENCIAS_SAA, 
			t1.PERC_AUSENCIAS_SUPERV_SAA, 
			t1.PERC_AUSENCIAS_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.DESCRICAO_REGRA, 
			t1.PESO_POR_FUNCI, 
			t1.PONTUACAO_MAXIMA_REGRA, 
			t1.PONTUACAO_MAXIMA_REG_PTO, 
			t1.PONTUACAO_MAXIMA_TRABALHOU, 
			t1.IND_UOR_PTOS_SUPERV, 
			t1.IND_GAT_ORCADO_SUPERV, 
			t1.IND_GAT_PTOS_SUPERV,
			t1.IND_UOR_PTOS_ESCRIT, 
			t1.IND_GAT_ORCADO_ESCRIT, 
			t1.IND_GAT_PTOS_ESCRIT, 
			/* AGE_COM_SUPERV_DIA */
	(CASE
		WHEN (t1.QTDE_SUPERV_LCLZ_PREF > 0) AND (t1.PERC_AUSENCIAS_SUPERV < 1) THEN 1 
		ELSE 0 
		END)
	FORMAT=1. AS AGE_COM_SUPERV_DIA, /* AGE_COM_ESCRIT_DIA */
	(CASE
		WHEN (t1.QTDE_ESCRIT_LCLZ_PREF > 0) AND (t1.PERC_AUSENCIAS_ESCRIT < 1) THEN 1 
		ELSE 0 
		END)
	FORMAT=1. AS AGE_COM_ESCRIT_DIA, /* IND_GAT_ORCADO_ADC */
	(CASE
		WHEN t1.PERC_AUSENCIAS_TOTAL > 0 THEN 180 
		ELSE 0 
		END )
	FORMAT=BEST3. AS IND_GAT_ORCADO_ADC FROM WORK.PREVIA_AGENCIAS_REGRAS_CALCULO t1 ;
QUIT;



PROC SQL;
	CREATE TABLE WORK.funcis_regras_calculo AS 
		SELECT DISTINCT t1.REGISTROU_PONTO, 
			t1.PREFIXO, 
			t1.MATRICULA_215, 
			t1.SITUACAO_215, 
			t1.LOCALIZACAO_215, 
			t1.COMISSAO_215, 
			t1.AFR_215, 
			t1.FUNCAO_LOCALIZACAO_215, 
			t1.DEP_LOTACAO_215, 
			t1.FUNCAO_LOTACAO_215, 
			t1.HORA_TRAB_INI_215, 
			t1.HORA_TRAB_FIM_215, 
			t1.HORA_TRAB_INTERV_INI_215, 
			t1.HORA_TRAB_INTERV_FIM_215, 
			t1.HORA_TRAB_INTERV2_INI_215, 
			t1.HORA_TRAB_INTERV2_FIM_215, 
			t1.CD_UOR_LCZC, 
			t1.CD_UOR_TRB_HBTL, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_EXTRAQUADRO, 
			t1.FUNCI_QS_LIC_SAUDE, 
			t1.FUNCI_EM_SUBSTITUICAO, 
			t1.PREFIXO_SUBSTITUICAO, 
			t1.CD_TIP_CMSS_FUC, 
			t1.IN_ICD_PTO_ETN, 
			t1.NM_TIP_CMSS_FUC, 
			t1.QT_HH_JRTB_DRIA, 
			t1.QT_MINUTOS_JRTB_DRIA, 
			t1.FUNCI_HORAS_EXTRAS, 
			t1.CD_REF_ORGC, 
			t1.SUJEITO_PONTO_ELETRONICO, 
			t1.FUNCI_ESCRIT_LOCALIZACAO, 
			t1.FUNCI_ESCRIT_LOTACAO, 
			t1.FUNCI_CAIEX_LOCALIZACAO, 
			t1.FUNCI_CAIEX_LOTACAO, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.funci_ausente, 
			t1.SITUACAO_PONTO_FUNCI, 
			t1.QT_HORAS_TRABALHADAS_DIA, 
			t1.QT_MINUTOS_TRABALHADOS_DIA, 
			t2.REGRA_CALCULO_CONEXAO AS REGRA_CALCULO_AGENCIA, 
			t2.DESCRICAO_REGRA AS DESCRICAO_REGRA_AGENCIA,
			t2.LOTAC_MIN_FUNCIS_SAA, 
			t2.LOTAC_MIN_SUPERV_SAA, 
			t2.LOTAC_MIN_ESCRIT_SAA,
			(CASE WHEN REGISTROU_PONTO=0 AND FUNCAO_LOCALIZACAO_215=4699 THEN 0
			WHEN REGISTROU_PONTO=1 AND FUNCAO_LOCALIZACAO_215=4699 AND LOTAC_MIN_SUPERV_SAA=0 THEN 0 ELSE PESO_POR_FUNCI end) AS PESO_POR_FUNCI
		FROM WORK.FUNCIS_FINAL t1
			LEFT JOIN WORK.AGENCIAS_REGRAS_CALCULO t2 ON (t1.PREFIXO = t2.PREFIXO);
QUIT;


PROC SQL;
	CREATE TABLE WORK.FUNCIS_ATENDIMENTO_GAT AS 
		SELECT DISTINCT t1.REGISTROU_PONTO, 
			t1.PREFIXO, 
			t1.MATRICULA_215, 
			t1.SITUACAO_215, 
			t1.LOCALIZACAO_215, 
			t1.COMISSAO_215, 
			t1.AFR_215, 
			t1.FUNCAO_LOCALIZACAO_215, 
			t1.DEP_LOTACAO_215, 
			t1.FUNCAO_LOTACAO_215, 
			t1.HORA_TRAB_INI_215, 
			t1.HORA_TRAB_FIM_215, 
			t1.HORA_TRAB_INTERV_INI_215, 
			t1.HORA_TRAB_INTERV_FIM_215, 
			t1.HORA_TRAB_INTERV2_INI_215, 
			t1.HORA_TRAB_INTERV2_FIM_215, 
			t1.CD_UOR_LCZC, 
			t1.CD_UOR_TRB_HBTL, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_EXTRAQUADRO, 
			t1.FUNCI_QS_LIC_SAUDE, 
			t1.FUNCI_EM_SUBSTITUICAO, 
			t1.PREFIXO_SUBSTITUICAO, 
			t1.CD_TIP_CMSS_FUC, 
			t1.IN_ICD_PTO_ETN, 
			t1.NM_TIP_CMSS_FUC, 
			t1.QT_HH_JRTB_DRIA, 
			t1.QT_MINUTOS_JRTB_DRIA, 
			t1.FUNCI_HORAS_EXTRAS, 
			t1.CD_REF_ORGC, 
			t1.SUJEITO_PONTO_ELETRONICO, 
			t1.FUNCI_ESCRIT_LOCALIZACAO, 
			t1.FUNCI_ESCRIT_LOTACAO, 
			t1.FUNCI_CAIEX_LOCALIZACAO, 
			t1.FUNCI_CAIEX_LOTACAO, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.SITUACAO_PONTO_FUNCI, 
			t1.QT_HORAS_TRABALHADAS_DIA, 
			t1.QT_MINUTOS_TRABALHADOS_DIA, 
			t1.REGRA_CALCULO_AGENCIA, 
			t1.DESCRICAO_REGRA_AGENCIA, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t1.PESO_POR_FUNCI, 
			t2.QT_TIP_LCL_ATD, 
			t2.QT_SENHAS_FUNCI, 
			t2.QT_TMP_SENHAS_FUNCI, 
			t2.TMP_MEDIO_ATDT_FUNCI, 
			t2.QT_TMP_TRBD_FUN, 
			t2.PERC_TMP_TRBD_ATDT
		FROM WORK.FUNCIS_REGRAS_CALCULO t1
			LEFT JOIN WORK.FUNCIS_ATDT_GAT t2 ON (t1.MATRICULA_215 = t2.NR_MTC_USU);
QUIT;

PROC SQL;
	CREATE TABLE WORK.previa_funcis_saa_gat_bic AS 
		SELECT DISTINCT t1.REGISTROU_PONTO, 
			t1.PREFIXO, 
			t1.MATRICULA_215, 
			t1.SITUACAO_215, 
			t1.LOCALIZACAO_215, 
			t1.COMISSAO_215, 
			t1.AFR_215, 
			t1.FUNCAO_LOCALIZACAO_215, 
			t1.DEP_LOTACAO_215, 
			t1.FUNCAO_LOTACAO_215, 
			t1.HORA_TRAB_INI_215, 
			t1.HORA_TRAB_FIM_215, 
			t1.HORA_TRAB_INTERV_INI_215, 
			t1.HORA_TRAB_INTERV_FIM_215, 
			t1.HORA_TRAB_INTERV2_INI_215, 
			t1.HORA_TRAB_INTERV2_FIM_215, 
			t1.CD_UOR_LCZC, 
			t1.CD_UOR_TRB_HBTL, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_EXTRAQUADRO, 
			t1.FUNCI_QS_LIC_SAUDE, 
			t1.FUNCI_EM_SUBSTITUICAO, 
			t1.PREFIXO_SUBSTITUICAO, 
			t1.CD_TIP_CMSS_FUC, 
			t1.IN_ICD_PTO_ETN, 
			t1.NM_TIP_CMSS_FUC, 
			t1.QT_HH_JRTB_DRIA, 
			t1.QT_MINUTOS_JRTB_DRIA, 
			t1.FUNCI_HORAS_EXTRAS, 
			t1.CD_REF_ORGC, 
			t1.SUJEITO_PONTO_ELETRONICO, 
			t1.FUNCI_ESCRIT_LOCALIZACAO, 
			t1.FUNCI_ESCRIT_LOTACAO, 
			t1.FUNCI_CAIEX_LOCALIZACAO, 
			t1.FUNCI_CAIEX_LOTACAO, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.SITUACAO_PONTO_FUNCI, 
			t1.QT_HORAS_TRABALHADAS_DIA, 
			t1.QT_MINUTOS_TRABALHADOS_DIA, 
			t1.REGRA_CALCULO_AGENCIA, 
			t1.DESCRICAO_REGRA_AGENCIA,
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t1.PESO_POR_FUNCI, 
			t1.QT_TIP_LCL_ATD, 
			t1.QT_SENHAS_FUNCI, 
			t1.QT_TMP_SENHAS_FUNCI, 
			t1.TMP_MEDIO_ATDT_FUNCI, 
			/* QT_TMP_TRBD_FUN */
	(MAX(t1.QT_TMP_TRBD_FUN)) AS QT_TMP_TRBD_FUN, t1.PERC_TMP_TRBD_ATDT FROM WORK.FUNCIS_ATENDIMENTO_GAT t1 ;
	;
QUIT;

PROC SQL;
	CREATE TABLE WORK.previa_agencias AS 
		SELECT DISTINCT
			t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.UOR_SAA, 
			t1.NOME, 
			t1.UF, 
			t1.NIVEL, 
			t1.TP_DEPENDENCIA, 
			t1.Status, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_SUPERV_LCLZ_PREF, 
			t1.QTDE_ESCRIT_LCLZ_PREF, 
			t1.QTDE_FUNCIS_QS_LIC_SAUDE, 
			t1.QTDE_FUNCIS_DEMAIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_EXTRAQUADRO, 
			t1.QTDE_FUNCIS_PREV_TRABALHAR,
			t1.QTDE_FUNCIS_ALOCADOS_SAA, 
			t1.QTDE_SUPERV_ALOCADOS_SAA, 
			t1.QTDE_ESCRIT_ALOCADOS_SAA, 
			t1.QTDE_FUNCIS_REG_PTO, 
			t1.QTDE_ESCRIT_REG_PTO, 
			t1.QTDE_SUPERV_REG_PTO, 
			t1.QTDE_ALOC_SAA_REG_PTO, 
			t1.QTDE_SUPERV_SAA_REG_PTO, 
			t1.QTDE_ESCRIT_SAA_REG_PTO, 
			t1.QTDE_FUNCIS_SUJEITOS_PONTO, 
			t1.QTDE_FUNCIS_REGISTRARAM_PONTO, 
			t1.QTDE_ALOC_SAA_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_TRABALHOU, 
			t1.QTDE_SUPERV_TRABALHOU, 
			t1.QTDE_FUNCIS_TRABALHOU, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL, 
			t1.PERC_AUSENCIAS_TOTAL, 
			t1.PERC_AUSENCIAS_SUPERV, 
			t1.PERC_AUSENCIAS_ESCRIT, 
			t1.PERC_AUSENCIAS_SAA, 
			t1.PERC_AUSENCIAS_SUPERV_SAA, 
			t1.PERC_AUSENCIAS_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.DESCRICAO_REGRA, 
			t1.PESO_POR_FUNCI, 
			t1.PONTUACAO_MAXIMA_REGRA, 
			t1.PONTUACAO_MAXIMA_REG_PTO, 
			t1.PONTUACAO_MAXIMA_TRABALHOU, 
			t1.IND_UOR_PTOS_SUPERV, 
			t1.IND_GAT_ORCADO_SUPERV, 
			t1.IND_GAT_PTOS_SUPERV, 
			t1.IND_UOR_PTOS_ESCRIT, 
			t1.IND_GAT_ORCADO_ESCRIT, 
			t1.IND_GAT_PTOS_ESCRIT,
			t1.AGE_COM_SUPERV_DIA, 
			t1.AGE_COM_ESCRIT_DIA, 
			t1.IND_GAT_ORCADO_ADC,
			/* IND_GAT_ORCADO_SUPERV_AJTDO */
	t1.IND_GAT_ORCADO_SUPERV AS IND_GAT_ORCADO_SUPERV_AJTDO, 
	/* IND_GAT_ORCADO_ESCRIT_AJTDO */
	t1.IND_GAT_ORCADO_ESCRIT AS IND_GAT_ORCADO_ESCRIT_AJTDO
	FROM
		WORK.AGENCIAS_REGRAS_CALCULO t1
		ORDER BY
			t1.PREFIXO;
QUIT;


PROC SQL;
	CREATE TABLE WORK.REGRA_PREVIA_SUPERVISORES_0001 AS 
		SELECT DISTINCT
			t1.PREFIXO, 
			t2.AGE_COM_SUPERV_DIA, 
			t2.AGE_COM_ESCRIT_DIA, 
			t1.MATRICULA_215, 
			t1.CD_TIP_CMSS_FUC, 
			t1.NM_TIP_CMSS_FUC, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.REGISTROU_PONTO, 
			t1.REGRA_CALCULO_AGENCIA,
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t2.QTDE_FUNCIS_LCLZ_PREF, 
			t2.QTDE_FUNCIS_AUSENTES_TOTAL,
			t1.PESO_POR_FUNCI AS PONTUACAO_MAXIMA_FUNCI, 
			/* IND_UOR_ATINGIU */
	(t1.MATRICULA_215 IS NOT MISSING) FORMAT=1. AS IND_UOR_ATINGIU, t2.IND_UOR_PTOS_SUPERV AS REGRA_IND_UOR_PTOS, /* IND_GAT_ORCADO_ADC */

	0 AS IND_GAT_ORCADO_ADC,
	t2.IND_GAT_ORCADO_SUPERV_AJTDO FORMAT=COMMAX3. AS IND_GAT_ORCADO, 
	/* IND_GAT_OBSERVADO */
	(CASE
		WHEN t1.QT_TMP_SENHAS_FUNCI IS MISSING THEN 0 
		ELSE t1.QT_TMP_SENHAS_FUNCI 
		END)
	FORMAT=COMMAX5. AS IND_GAT_OBSERVADO, /* IND_GAT_QTDE_ORCADO */

	0 AS IND_GAT_QTDE_ORCADO,
	t1.QT_SENHAS_FUNCI AS IND_GAT_QTDE_OBSERVADO,
	/* IND_GAT_ATINGIU */
	(CASE
		WHEN (t1.QT_TMP_SENHAS_FUNCI > t2.IND_GAT_ORCADO_SUPERV_AJTDO) OR t1.QT_SENHAS_FUNCI > 0 THEN 0 
		ELSE 1 
		END)
	FORMAT=1. AS IND_GAT_ATINGIU, t2.IND_GAT_PTOS_SUPERV AS REGRA_IND_GAT_PTOS FROM WORK.PREVIA_FUNCIS_SAA_GAT_BIC t1 INNER JOIN WORK.PREVIA_AGENCIAS t2 ON t2.PREFIXO = t1.PREFIXO AND t2.REGRA_CALCULO_CONEXAO = t1.REGRA_CALCULO_AGENCIA WHERE t1.FUNCI_SUPERVISOR = 1 AND t1.FUNCI_ALOCADO_SAA = 1 AND t1.FUNCI_PREVISTO_TRABALHAR = 1 AND t1.FUNCI_AUSENTE = 0;
QUIT;

PROC SQL;
	CREATE TABLE WORK.regra_previa_supervisores_002 AS 
		SELECT DISTINCT t1.PREFIXO, 
			t1.AGE_COM_SUPERV_DIA, 
			t1.AGE_COM_ESCRIT_DIA, 
			t1.MATRICULA_215, 
			t1.CD_TIP_CMSS_FUC, 
			t1.NM_TIP_CMSS_FUC, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.REGISTROU_PONTO, 
			t1.REGRA_CALCULO_AGENCIA,
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL,
			t1.IND_UOR_ATINGIU, 
			/* IND_UOR_PTOS */
	(CASE
		WHEN t1.IND_UOR_ATINGIU = 1 THEN t1.REGRA_IND_UOR_PTOS 
		ELSE 0 
		END)
	FORMAT=BEST5. AS IND_UOR_PTOS, t1.IND_GAT_ORCADO_ADC, t1.IND_GAT_ORCADO, t1.IND_GAT_OBSERVADO, t1.IND_GAT_QTDE_ORCADO, t1.IND_GAT_QTDE_OBSERVADO, t1.IND_GAT_ATINGIU, /* IND_GAT_PTOS */
	(CASE
		WHEN t1.IND_GAT_ATINGIU = 1 THEN t1.REGRA_IND_GAT_PTOS 
		ELSE 0 
		END)
	FORMAT=BEST5. AS IND_GAT_PTOS, t1.PONTUACAO_MAXIMA_FUNCI FROM WORK.REGRA_PREVIA_SUPERVISORES_0001 t1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.regra_calculo_supervisores AS 
		SELECT DISTINCT t1.PREFIXO, 
			t1.AGE_COM_SUPERV_DIA, 
			t1.AGE_COM_ESCRIT_DIA, 
			t1.MATRICULA_215, 
			t1.CD_TIP_CMSS_FUC, 
			t1.NM_TIP_CMSS_FUC, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.REGISTROU_PONTO, 
			t1.REGRA_CALCULO_AGENCIA, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL,
			t1.IND_UOR_ATINGIU, 
			t1.IND_UOR_PTOS, 
			t1.IND_GAT_ORCADO_ADC AS IND_GAT_TMP_ORCADO_ADC,
			t1.IND_GAT_ORCADO AS IND_GAT_TMP_ORCADO, 
			t1.IND_GAT_OBSERVADO AS IND_GAT_TMP_OBSERVADO, 
			t1.IND_GAT_QTDE_ORCADO,
			t1.IND_GAT_QTDE_OBSERVADO,
			t1.IND_GAT_ATINGIU, 
			t1.IND_GAT_PTOS, 

			t1.PONTUACAO_MAXIMA_FUNCI, 
			/* PONTUACAO_OBTIDA_FUNCI */
	(MIN(SUM(t1.IND_UOR_PTOS, t1.IND_GAT_PTOS), t1.PONTUACAO_MAXIMA_FUNCI)) FORMAT=BEST5. AS PONTUACAO_OBTIDA_FUNCI, /* PERC_ATING_FUNCI */
	((MIN(SUM(t1.IND_UOR_PTOS, t1.IND_GAT_PTOS), t1.PONTUACAO_MAXIMA_FUNCI)) / t1.PONTUACAO_MAXIMA_FUNCI) FORMAT=PERCENT12.2 AS PERC_ATING_FUNCI FROM WORK.REGRA_PREVIA_SUPERVISORES_002 t1;
QUIT;


PROC SQL;
	CREATE TABLE WORK.regra_previa_escriturarios_001 AS 
		SELECT DISTINCT
			t1.PREFIXO, 
			t2.AGE_COM_SUPERV_DIA, 
			t2.AGE_COM_ESCRIT_DIA, 
			t1.MATRICULA_215, 
			t1.CD_TIP_CMSS_FUC, 
			t1.NM_TIP_CMSS_FUC, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.REGISTROU_PONTO, 
			t1.REGRA_CALCULO_AGENCIA,
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t2.QTDE_FUNCIS_LCLZ_PREF, 
			t2.QTDE_FUNCIS_AUSENTES_TOTAL,
			t2.QTDE_ESCRIT_TRABALHOU,
			t2.QTDE_ESCRIT_LCLZ_PREF,
			t2.PERC_AUSENCIAS_ESCRIT,
			t1.PESO_POR_FUNCI AS PONTUACAO_MAXIMA_FUNCI, 
			/* IND_UOR_ATINGIU */
	(t1.MATRICULA_215 IS NOT MISSING) FORMAT=1. AS IND_UOR_ATINGIU, t2.IND_UOR_PTOS_ESCRIT AS REGRA_IND_UOR_PTOS, t2.IND_GAT_ORCADO_ADC, t2.IND_GAT_ORCADO_ESCRIT_AJTDO AS IND_GAT_ORCADO, /* IND_GAT_OBSERVADO */
	(CASE
		WHEN t1.QT_TMP_SENHAS_FUNCI IS MISSING THEN 0 
		ELSE t1.QT_TMP_SENHAS_FUNCI 
		END)
	FORMAT=COMMAX5. AS IND_GAT_OBSERVADO, . AS IND_GAT_QTDE_ORCADO, t1.QT_SENHAS_FUNCI AS IND_GAT_QTDE_OBSERVADO, t2.IND_GAT_PTOS_ESCRIT AS REGRA_IND_GAT_PTOS FROM WORK.PREVIA_FUNCIS_SAA_GAT_BIC t1 INNER JOIN WORK.PREVIA_AGENCIAS t2 ON t2.PREFIXO = t1.PREFIXO AND t2.REGRA_CALCULO_CONEXAO = t1.REGRA_CALCULO_AGENCIA WHERE t1.FUNCI_ESCRITURARIO = 1 AND t1.FUNCI_ALOCADO_SAA = 1 AND t1.FUNCI_PREVISTO_TRABALHAR = 1 AND t1.FUNCI_AUSENTE = 0 ORDER BY t1.PREFIXO, IND_GAT_OBSERVADO DESC;
QUIT;

/* ***************************************************************************************
TRATAMENTO DE AUSÊNCIAS - COMPENSAÇÃO EM TEMPO DE ATENDIMENTO GAT

REGRA POR AUSÊNCIA TOTAL:
Considerando apenas os funcionários sujeitos ao ponto eletrônico, a cada
01 (um) funcionário ausente na data, independente do cargo, 01 (um) dos
escriturários da SAA poderá atender por até 03 horas no ambiente interno
(caixa ou negocial).

Ex.:
- Total de escriturários localizados no prefixo: 05 escriturários
- Total de funcionários ausentes na data: 01 gerente de relacionamento e 01 assistente
- Lotação mínima da SAA: 01 supervisor e 02 escriturários
- Tempo permitido para atendimento interno:
  - Supervisor: nenhum minuto
  - 02 escriturários: até 03 horas cada (compensação pela ausência de 02 funcionários)

OBSERVAÇÃO:
Para aplicação da compensação, os escriturários são ordenados do maior para o menor
tempo de GAT observado (IND_GAT_OBSERVADO DESC). O código percorre cada escriturário
e verifica se cumpre o indicador pela regra normal. Caso não cumpra, verifica se a
aplicação da compensação permite cumprir o indicador. Caso positivo, aplica a compensação
ao escriturário atual e passa para o próximo registro, limitando-se à quantidade de
ausências total. A compensação só é utilizada nos casos em que sua aplicação permita
cumprir o indicador GAT.

Ex.:
a) No caso da ausência de 02 funcionários, se todos os escriturários alocados na SAA
   atenderem por mais do que 03 horas no ambiente interno, a compensação não será
   aplicada a nenhum deles, pois não seria suficiente para cumprir o indicador.

b) No caso da ausência de 02 funcionários, se houver 04 (quatro) escriturários alocados
   na SAA. Se 02 (dois) atenderem por mais do que 03 horas no ambiente interno, 01 (um)
   atender por 02 horas e 01 (um) atender por 45 minutos, a compensação será aplicada
   apenas ao que atendeu por 02 horas, pois:
   - a aplicação da regra não permite o cumprimento pelos funcionários com mais que 03 horas;
   - o funcionário com 02 horas não cumpre o indicador pela regra normal, mas cumpre com a compensação;
   - o funcionário com 45 minutos já cumpre o indicador pela regra normal.

*************************************************************************************** */

DATA WORK.REGRA_PREVIA_ESCRITURARIOS_002;
	SET WORK.REGRA_PREVIA_ESCRITURARIOS_001;
	BY PREFIXO;
	RETAIN COMPENSAR;

	IF first.PREFIXO THEN
		COMPENSAR = QTDE_FUNCIS_AUSENTES_TOTAL;

	/* Aplica a regra normal (Observado <= Orçado) */
	IND_GAT_ATINGIU = IFN(IND_GAT_OBSERVADO <= IND_GAT_ORCADO, 1, 0);
	IND_GAT_ORCADO_ESCRIT_AJTDO = IND_GAT_ORCADO;

	/* Caso não cumpra o indicador com a regra normal e ainda exista ausência a compensar */
	IF (IND_GAT_ATINGIU = 0) AND (COMPENSAR > 0) THEN
		DO;
			/* Aplica a regra de compensação (Observado <= Orçado Ajustado) */
			IND_GAT_ATINGIU = IFN(IND_GAT_OBSERVADO <= IND_GAT_ORCADO_ADC, 1, 0);

			/* Caso cumpra o indicador com a compensação, reduz a quantidade a compensar */
			IF IND_GAT_ATINGIU = 1 THEN
				DO;
					COMPENSAR = COMPENSAR - 1;
					IND_GAT_ORCADO_ESCRIT_AJTDO = IND_GAT_ORCADO_ADC;
				END;
		END;
RUN;

PROC SQL;
	CREATE TABLE WORK.regra_previa_escriturarios_003 AS 
		SELECT DISTINCT
			t1.PREFIXO, 
			t1.AGE_COM_SUPERV_DIA, 
			t1.AGE_COM_ESCRIT_DIA, 
			t1.MATRICULA_215, 
			t1.CD_TIP_CMSS_FUC, 
			t1.NM_TIP_CMSS_FUC, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.REGISTROU_PONTO, 
			t1.REGRA_CALCULO_AGENCIA,
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL,
			t1.IND_UOR_ATINGIU, 
			/* IND_UOR_PTOS */
	(CASE
		WHEN 1 = t1.IND_UOR_ATINGIU THEN t1.REGRA_IND_UOR_PTOS 
		ELSE 0 
		END)
	FORMAT=BEST5. AS IND_UOR_PTOS, t1.IND_GAT_ORCADO_ADC, t1.IND_GAT_ORCADO_ESCRIT_AJTDO AS IND_GAT_ORCADO, t1.IND_GAT_OBSERVADO, t1.IND_GAT_QTDE_ORCADO, t1.IND_GAT_QTDE_OBSERVADO, t1.IND_GAT_ATINGIU, /* IND_GAT_PTOS */
	(CASE
		WHEN 1 = t1.IND_GAT_ATINGIU THEN t1.REGRA_IND_GAT_PTOS 
		ELSE 0 
		END)
	FORMAT=BEST5. AS IND_GAT_PTOS, t1.PONTUACAO_MAXIMA_FUNCI FROM WORK.REGRA_PREVIA_ESCRITURARIOS_002 t1 ORDER BY PREFIXO, IND_GAT_OBSERVADO DESC;
QUIT;

PROC SQL;
	CREATE TABLE WORK.regra_calculo_escriturarios AS 
		SELECT DISTINCT
			t1.PREFIXO, 
			t1.AGE_COM_SUPERV_DIA, 
			t1.AGE_COM_ESCRIT_DIA, 
			t1.MATRICULA_215, 
			t1.CD_TIP_CMSS_FUC, 
			t1.NM_TIP_CMSS_FUC, 
			t1.FUNCI_SUPERVISOR, 
			t1.FUNCI_ESCRITURARIO, 
			t1.FUNCI_CAIEX_EFETIVO, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.FUNCI_PREVISTO_TRABALHAR, 
			t1.FUNCI_AUSENTE, 
			t1.REGISTROU_PONTO, 
			t1.REGRA_CALCULO_AGENCIA, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA,
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL,
			t1.IND_UOR_ATINGIU, 
			t1.IND_UOR_PTOS, 
			t1.IND_GAT_ORCADO_ADC AS IND_GAT_TMP_ORCADO_ADC,
			t1.IND_GAT_ORCADO AS IND_GAT_TMP_ORCADO, 
			t1.IND_GAT_OBSERVADO AS IND_GAT_TMP_OBSERVADO, 
			t1.IND_GAT_QTDE_ORCADO,
			t1.IND_GAT_QTDE_OBSERVADO,
			t1.IND_GAT_ATINGIU, 
			t1.IND_GAT_PTOS, 
			t1.PONTUACAO_MAXIMA_FUNCI, 
			/* PONTUACAO_OBTIDA_FUNCI */
	(MIN(SUM(t1.IND_UOR_PTOS, t1.IND_GAT_PTOS), t1.PONTUACAO_MAXIMA_FUNCI)) FORMAT=BEST5. AS PONTUACAO_OBTIDA_FUNCI, /* PERC_ATING_FUNCI */
	((MIN(SUM(t1.IND_UOR_PTOS, t1.IND_GAT_PTOS), t1.PONTUACAO_MAXIMA_FUNCI)) / t1.PONTUACAO_MAXIMA_FUNCI) FORMAT=PERCENT12.2 AS PERC_ATING_FUNCI FROM WORK.REGRA_PREVIA_ESCRITURARIOS_003 t1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.previa_calculo_funcis_001 AS 
		SELECT * FROM WORK.REGRA_CALCULO_SUPERVISORES
			OUTER UNION CORR 
				SELECT * FROM WORK.REGRA_CALCULO_ESCRITURARIOS;
QUIT;

PROC SQL;
	CREATE TABLE WORK.previa_calculo_funcis_002 AS 
		SELECT * FROM WORK.previa_calculo_funcis_001 ORDER BY PREFIXO, FUNCI_SUPERVISOR, FUNCI_ESCRITURARIO, PONTUACAO_OBTIDA_FUNCI DESC;
QUIT;

DATA WORK.REGRA_CALCULO_FUNCIONARIOS;
	SET WORK.previa_calculo_funcis_002;
	BY PREFIXO FUNCI_SUPERVISOR FUNCI_ESCRITURARIO DESCENDING PONTUACAO_OBTIDA_FUNCI;
	RETAIN MAX_SUPERV_SAA MAX_ESCRIT_SAA QTD_SUPERV_SAA QTD_ESCRIT_SAA;

	IF first.PREFIXO THEN
		DO;
			MAX_SUPERV_SAA = LOTAC_MIN_SUPERV_SAA;
			MAX_ESCRIT_SAA = LOTAC_MIN_ESCRIT_SAA;
			QTD_SUPERV_SAA = 0;
			QTD_ESCRIT_SAA = 0;
		END;

	IF FUNCI_SUPERVISOR = 1 THEN
		QTD_SUPERV_SAA + 1;

	IF FUNCI_ESCRITURARIO = 1 THEN
		QTD_ESCRIT_SAA + 1;
	DESCARTAR = 0;
	SELECT(REGRA_CALCULO_AGENCIA);
		WHEN ('A')
			DO;
				/* REGRA A - SAA com 01 funci (somente Supervisor) */
				IF (FUNCI_SUPERVISOR = 0)   OR (QTD_SUPERV_SAA > MAX_SUPERV_SAA) THEN
					DESCARTAR = 1;
			END;

		WHEN ('B')
			DO;
				/* REGRA B - SAA com 01 funci (somente Escriturário) */
				IF (FUNCI_ESCRITURARIO = 0) OR (QTD_ESCRIT_SAA > MAX_ESCRIT_SAA) THEN
					DESCARTAR = 1;
			END;

		WHEN ('C')
			DO;
				/* REGRA C - SAA com mais de 01 funci (com ou sem Supervisor) */
				IF (FUNCI_SUPERVISOR = 1)   AND (QTD_SUPERV_SAA > MAX_SUPERV_SAA) THEN
					DESCARTAR = 1;
				ELSE IF (FUNCI_ESCRITURARIO = 1) AND (QTD_ESCRIT_SAA > MAX_ESCRIT_SAA) THEN
					DESCARTAR = 1;
			END;

		OTHERWISE DO;
		/* ERRO - Regra não prevista/existente */
		DESCARTAR = 1;
	END;
END;
RUN;

PROC SQL;
	CREATE TABLE WORK.regra_previa_calculo_agencias AS 
		SELECT DISTINCT
			t1.PREFIXO, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.REGRA_CALCULO_AGENCIA, 
			/* QTDE_FUNCIS_CALC */
	(COUNT(DISTINCT(t1.MATRICULA_215))) FORMAT=BEST2. AS QTDE_FUNCIS_CALC, /* QTDE_FUNCIS_DESCARTADOS */
	(COUNT(DISTINCT(CASE WHEN t1.DESCARTAR = 1 THEN t1.MATRICULA_215 ELSE . END))) FORMAT=BEST2. AS QTDE_FUNCIS_DESCARTADOS, /* QTDE_FUNCI_SUPERVISOR */
	(SUM(t1.FUNCI_SUPERVISOR)) FORMAT=BEST5. AS QTDE_FUNCI_SUPERVISOR, /* QTDE_FUNCI_ESCRITURARIO */
	(SUM(t1.FUNCI_ESCRITURARIO)) FORMAT=BEST5. AS QTDE_FUNCI_ESCRITURARIO, /* QTDE_CAIEX_EFETIVO */
	(SUM(t1.FUNCI_CAIEX_EFETIVO)) FORMAT=BEST5. AS QTDE_CAIEX_EFETIVO, /* QTDE_FUNCI_ALOCADO_SAA */
	(SUM(t1.FUNCI_ALOCADO_SAA)) FORMAT=BEST5. AS QTDE_FUNCI_ALOCADO_SAA, /* QTDE_FUNCI_AUSENTE */
	(SUM(t1.FUNCI_AUSENTE)) FORMAT=BEST5. AS QTDE_FUNCI_AUSENTE, /* QTDE_REGISTROU_PONTO */
	(SUM(t1.REGISTROU_PONTO)) FORMAT=BEST5. AS QTDE_REGISTROU_PONTO, /* QTDE_IND_UOR_ATINGIU */
	(SUM(t1.IND_UOR_ATINGIU AND t1.DESCARTAR = 0)) FORMAT=BEST5. AS QTDE_IND_UOR_ATINGIU, /* QTDE_IND_GAT_ATINGIU */
	(SUM(t1.IND_GAT_ATINGIU AND t1.DESCARTAR = 0)) FORMAT=BEST5. AS QTDE_IND_GAT_ATINGIU, /* QT_SUPERV_ATG_IND_UOR */
	(SUM((t1.FUNCI_SUPERVISOR = 1 AND t1.IND_UOR_ATINGIU = 1 AND t1.DESCARTAR = 0))) FORMAT=5. AS QT_SUPERV_ATG_IND_UOR, /* SOMA_PTOS_IND_UOR_SUPERV */
	(SUM(CASE WHEN t1.FUNCI_SUPERVISOR = 1 AND t1.DESCARTAR = 0 THEN t1.IND_UOR_PTOS ELSE 0 END)) FORMAT=5. AS SOMA_PTOS_IND_UOR_SUPERV, /* QT_SUPERV_ATG_IND_GAT */
	(SUM((t1.FUNCI_SUPERVISOR = 1 AND t1.IND_GAT_ATINGIU = 1 AND t1.DESCARTAR = 0))) FORMAT=5. AS QT_SUPERV_ATG_IND_GAT, /* SOMA_PTOS_IND_GAT_SUPERV */
	(SUM(CASE WHEN t1.FUNCI_SUPERVISOR = 1 AND t1.DESCARTAR = 0 THEN t1.IND_GAT_PTOS ELSE 0 END)) FORMAT=5. AS SOMA_PTOS_IND_GAT_SUPERV, /* QT_ESCRIT_ATG_IND_UOR */
	(SUM((t1.FUNCI_ESCRITURARIO = 1 AND t1.IND_UOR_ATINGIU = 1 AND t1.DESCARTAR = 0))) FORMAT=5. AS QT_ESCRIT_ATG_IND_UOR, /* SOMA_PTOS_IND_UOR_ESCRIT */
	(SUM(CASE WHEN t1.FUNCI_ESCRITURARIO = 1 AND t1.DESCARTAR = 0 THEN t1.IND_UOR_PTOS ELSE 0 END)) FORMAT=5. AS SOMA_PTOS_IND_UOR_ESCRIT, /* QT_ESCRIT_ATG_IND_GAT */
	(SUM((t1.FUNCI_ESCRITURARIO = 1 AND t1.IND_GAT_ATINGIU = 1 AND t1.DESCARTAR = 0))) FORMAT=5. AS QT_ESCRIT_ATG_IND_GAT, /* SOMA_PTOS_IND_GAT_ESCRIT */
	(SUM(CASE WHEN t1.FUNCI_ESCRITURARIO = 1 AND t1.DESCARTAR = 0 THEN t1.IND_GAT_PTOS ELSE 0 END)) FORMAT=5. AS SOMA_PTOS_IND_GAT_ESCRIT, /* SOMA_PONTUACAO_OBTIDA_FUNCI */
	(SUM(CASE WHEN (t1.FUNCI_SUPERVISOR = 1 OR t1.FUNCI_ESCRITURARIO = 1) AND t1.DESCARTAR = 0 THEN t1.PONTUACAO_OBTIDA_FUNCI ELSE 0 END)) FORMAT=BEST5. AS SOMA_PONTUACAO_OBTIDA_FUNCI, /* MAX_PONTUACAO_OBTIDA_FUNCI */
	(MAX(CASE WHEN (t1.FUNCI_SUPERVISOR = 1 OR t1.FUNCI_ESCRITURARIO = 1) AND t1.DESCARTAR = 0 THEN t1.PONTUACAO_OBTIDA_FUNCI ELSE 0 END)) FORMAT=BEST5. AS MAX_PONTUACAO_OBTIDA_FUNCI, /* MAX_PERC_ATING_FUNCI */
	(MAX(CASE WHEN (t1.FUNCI_SUPERVISOR = 1 OR t1.FUNCI_ESCRITURARIO = 1) AND t1.DESCARTAR = 0 THEN t1.PERC_ATING_FUNCI ELSE 0 END)) FORMAT=PERCENT12.2 AS MAX_PERC_ATING_FUNCI FROM WORK.REGRA_CALCULO_FUNCIONARIOS t1 WHERE ( (t1.REGRA_CALCULO_AGENCIA = 'A' AND t1.AGE_COM_SUPERV_DIA = 1 AND t1.FUNCI_SUPERVISOR = 1) OR (t1.REGRA_CALCULO_AGENCIA = 'B' AND t1.lotac_min_superv_saa=0  AND t1.FUNCI_ESCRITURARIO = 1) OR (t1.REGRA_CALCULO_AGENCIA = 'C' AND (t1.FUNCI_SUPERVISOR = 1 OR t1.FUNCI_ESCRITURARIO = 1)) ) GROUP BY t1.PREFIXO ORDER BY t1.PREFIXO;
QUIT;

PROC SQL;
	CREATE TABLE WORK.regra_agencias_calculo AS 
		SELECT DISTINCT
			t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.NOME, 
			t1.UF, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.PERC_AUSENCIAS_TOTAL, 
			t1.IND_GAT_ORCADO_SUPERV_AJTDO, 
			t1.IND_GAT_ORCADO_ESCRIT_AJTDO, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.DESCRICAO_REGRA, 
			t1.QTDE_FUNCIS_ALOCADOS_SAA, 
			t1.QTDE_ALOC_SAA_TRABALHOU, 
			t1.QTDE_ALOC_SAA_REG_PTO, 
			t1.QTDE_SUPERV_ALOCADOS_SAA, 
			t1.QTDE_FUNCIS_PREV_TRABALHAR AS QTDE_FUNCI_PREVISTO_TRABALHAR,
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_REG_PTO, 
			t1.AGE_COM_SUPERV_DIA,
			t2.QT_SUPERV_ATG_IND_UOR, 
			t2.SOMA_PTOS_IND_UOR_SUPERV, 
			t2.QT_SUPERV_ATG_IND_GAT, 
			t2.SOMA_PTOS_IND_GAT_SUPERV, 
			/* SOMA_PTOS_TOTAL_SUPERV */
	(SUM(t2.SOMA_PTOS_IND_UOR_SUPERV, t2.SOMA_PTOS_IND_GAT_SUPERV)) FORMAT=5. AS SOMA_PTOS_TOTAL_SUPERV, t1.QTDE_ESCRIT_ALOCADOS_SAA, t1.QTDE_ESCRIT_SAA_TRABALHOU, t1.QTDE_ESCRIT_SAA_REG_PTO, t1.AGE_COM_ESCRIT_DIA, t2.QT_ESCRIT_ATG_IND_UOR, t2.SOMA_PTOS_IND_UOR_ESCRIT, t2.QT_ESCRIT_ATG_IND_GAT, t2.SOMA_PTOS_IND_GAT_ESCRIT, /* SOMA_PTOS_TOTAL_ESCRIT */
	(SUM(t2.SOMA_PTOS_IND_UOR_ESCRIT, t2.SOMA_PTOS_IND_GAT_ESCRIT)) FORMAT=5. AS SOMA_PTOS_TOTAL_ESCRIT, t1.PONTUACAO_MAXIMA_REGRA, t1.PONTUACAO_MAXIMA_REG_PTO, t1.PONTUACAO_MAXIMA_TRABALHOU, /* PONTUACAO_OBTIDA_AGENCIA */
/*	MIN(t1.PONTUACAO_MAXIMA_REGRA, t1.PONTUACAO_MAXIMA_TRABALHOU, t2.SOMA_PONTUACAO_OBTIDA_FUNCI)*/
/*	FORMAT=BEST3. AS PONTUACAO_OBTIDA_AGENCIA,*/
	/* DESCARTAR POR PERCENTUAL DE AUSÊNCIAS TOTAL */
	(t1.QTDE_FUNCIS_PREV_TRABALHAR > 0 AND t1.PERC_AUSENCIAS_TOTAL > 0.3) AS DESCARTAR_AUSENCIAS_TOTAL, /* DESCARTAR POR AUSÊNCIAS DE SUPERVISOR DE ATENDIMENTO */
	(t1.QTDE_FUNCIS_PREV_TRABALHAR > 0 AND t1.regra_calculo_conexao='A' and (t1.LOTAC_MIN_SUPERV_SAA > 0 AND t1.AGE_COM_SUPERV_DIA = 0)) AS DESCARTAR_AUSENCIA_SUPERVISOR, /* DESCARTAR POR NÃO HAVER PREVISÃO DE FUNCIONÁRIOS PARA TRABALHAR (ex.: feriado) */
	(t1.QTDE_FUNCIS_PREV_TRABALHAR = 0) AS DESCARTAR_SEM_FUNCI_PREV_TRAB FROM WORK.PREVIA_AGENCIAS t1 LEFT JOIN WORK.REGRA_PREVIA_CALCULO_AGENCIAS t2 ON (t1.PREFIXO = t2.PREFIXO) ORDER BY /* t1.REGRA_CALCULO_CONEXAO, */
	t1.PREFIXO;
QUIT;
%ZerarMissingTabela (regra_agencias_calculo);

PROC SQL;
	CREATE TABLE WORK.regra_agencias_final AS 
		SELECT DISTINCT t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.NOME, 
			t1.UF, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.PERC_AUSENCIAS_TOTAL, 
			t1.IND_GAT_ORCADO_SUPERV_AJTDO, 
			t1.IND_GAT_ORCADO_ESCRIT_AJTDO, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.DESCRICAO_REGRA, 
			t1.QTDE_FUNCI_PREVISTO_TRABALHAR,
			t1.QTDE_FUNCIS_ALOCADOS_SAA, 
			t1.QTDE_ALOC_SAA_TRABALHOU, 
			t1.QTDE_ALOC_SAA_REG_PTO, 
			t1.QTDE_SUPERV_ALOCADOS_SAA, 
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_REG_PTO, 
			t1.AGE_COM_SUPERV_DIA, 
			t1.QT_SUPERV_ATG_IND_UOR, 
			t1.SOMA_PTOS_IND_UOR_SUPERV, 
			t1.QT_SUPERV_ATG_IND_GAT, 
			t1.SOMA_PTOS_IND_GAT_SUPERV, 
			t1.SOMA_PTOS_TOTAL_SUPERV, 
			t1.QTDE_ESCRIT_ALOCADOS_SAA, 
			t1.QTDE_ESCRIT_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_SAA_REG_PTO, 
			t1.AGE_COM_ESCRIT_DIA, 
			t1.QT_ESCRIT_ATG_IND_UOR, 
			t1.SOMA_PTOS_IND_UOR_ESCRIT, 
			t1.QT_ESCRIT_ATG_IND_GAT, 
			t1.SOMA_PTOS_IND_GAT_ESCRIT, 
			t1.SOMA_PTOS_TOTAL_ESCRIT, 
			t1.PONTUACAO_MAXIMA_REGRA, 
			t1.PONTUACAO_MAXIMA_REG_PTO, 
			t1.PONTUACAO_MAXIMA_TRABALHOU, 
			(SOMA_PTOS_TOTAL_SUPERV+SOMA_PTOS_TOTAL_ESCRIT) AS PONTUACAO_OBTIDA_AGENCIA, 
			/* PERC_ATING_AGENCIA */
	(CASE
		WHEN t1.PONTUACAO_MAXIMA_REGRA > 0 THEN (SOMA_PTOS_TOTAL_SUPERV+SOMA_PTOS_TOTAL_ESCRIT) / t1.PONTUACAO_MAXIMA_REGRA 
		ELSE 0 
		END)
	FORMAT=PERCENT12.2 AS PERC_ATING_AGENCIA, t1.DESCARTAR_AUSENCIAS_TOTAL, t1.DESCARTAR_AUSENCIA_SUPERVISOR, t1.DESCARTAR_SEM_FUNCI_PREV_TRAB, MAX(t1.DESCARTAR_AUSENCIAS_TOTAL, t1.DESCARTAR_AUSENCIA_SUPERVISOR, t1.DESCARTAR_SEM_FUNCI_PREV_TRAB) AS DESCARTAR FROM WORK.REGRA_AGENCIAS_CALCULO t1 ORDER BY t1.PREFIXO;

	/*
	t1.REGRA_CALCULO_CONEXAO DESC,
	PERC_ATING_AGENCIA; */
QUIT;

PROC SQL;
	CREATE TABLE WORK.base_final_agencias AS 
		SELECT DISTINCT 
			&d2. FORMAT=DateMysql. as posicao,
			t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.UOR, 
			t1.UOR_SAA, 
			t1.NOME, 
			t1.UF, 
			t1.NIVEL, 
			t1.TP_DEPENDENCIA, 
			t1.Status, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.DESCRICAO_REGRA, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_SUPERV_LCLZ_PREF, 
			t1.QTDE_ESCRIT_LCLZ_PREF, 
			t1.QTDE_FUNCIS_QS_LIC_SAUDE, 
			t1.QTDE_FUNCIS_DEMAIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_EXTRAQUADRO, 
			t1.QTDE_FUNCIS_ALOCADOS_SAA, 
			t1.QTDE_SUPERV_ALOCADOS_SAA, 
			t1.QTDE_ESCRIT_ALOCADOS_SAA, 
			t1.QTDE_FUNCIS_REG_PTO, 
			t1.QTDE_ESCRIT_REG_PTO, 
			t1.QTDE_SUPERV_REG_PTO, 
			t1.QTDE_ALOC_SAA_REG_PTO, 
			t1.QTDE_SUPERV_SAA_REG_PTO, 
			t1.QTDE_ESCRIT_SAA_REG_PTO, 
			t1.QTDE_FUNCIS_SUJEITOS_PONTO, 
			t1.QTDE_FUNCIS_REGISTRARAM_PONTO, 
			t1.QTDE_ALOC_SAA_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_SAA_TRABALHOU, 
			t1.QTDE_ESCRIT_TRABALHOU, 
			t1.QTDE_SUPERV_TRABALHOU, 
			t1.QTDE_FUNCIS_TRABALHOU, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL, 
			t1.PERC_AUSENCIAS_TOTAL, 
			t1.PERC_AUSENCIAS_SUPERV, 
			t1.PERC_AUSENCIAS_ESCRIT, 
			t1.PERC_AUSENCIAS_SAA, 
			t1.PERC_AUSENCIAS_SUPERV_SAA, 
			t1.PERC_AUSENCIAS_ESCRIT_SAA, 
			t1.PESO_POR_FUNCI, 
			t1.PONTUACAO_MAXIMA_REGRA, 
			t1.PONTUACAO_MAXIMA_REG_PTO, 
			t1.PONTUACAO_MAXIMA_TRABALHOU, 
			t1.IND_UOR_PTOS_SUPERV, 
			t1.IND_GAT_ORCADO_SUPERV, 
			t1.IND_GAT_PTOS_SUPERV,
			t1.IND_UOR_PTOS_ESCRIT, 
			t1.IND_GAT_ORCADO_ESCRIT, 
			t1.IND_GAT_PTOS_ESCRIT,
			t1.AGE_COM_SUPERV_DIA, 
			t1.AGE_COM_ESCRIT_DIA, 
			t1.IND_GAT_ORCADO_ADC, 
			t1.IND_GAT_ORCADO_SUPERV_AJTDO, 
			t1.IND_GAT_ORCADO_ESCRIT_AJTDO, 
			t2.QTDE_FUNCI_PREVISTO_TRABALHAR,
			t2.QT_SUPERV_ATG_IND_UOR, 
			t2.SOMA_PTOS_IND_UOR_SUPERV, 
			t2.QT_SUPERV_ATG_IND_GAT, 
			t2.SOMA_PTOS_IND_GAT_SUPERV,
			t2.SOMA_PTOS_TOTAL_SUPERV, 
			t2.QT_ESCRIT_ATG_IND_UOR, 
			t2.SOMA_PTOS_IND_UOR_ESCRIT, 
			t2.QT_ESCRIT_ATG_IND_GAT, 
			t2.SOMA_PTOS_IND_GAT_ESCRIT, 
			t2.SOMA_PTOS_TOTAL_ESCRIT, 
			t2.PONTUACAO_OBTIDA_AGENCIA, 
			t2.PERC_ATING_AGENCIA,
			t2.DESCARTAR_AUSENCIAS_TOTAL,
			t2.DESCARTAR_AUSENCIA_SUPERVISOR,
			t2.DESCARTAR_SEM_FUNCI_PREV_TRAB,
			t2.DESCARTAR
		FROM WORK.PREVIA_AGENCIAS t1
			LEFT JOIN WORK.REGRA_AGENCIAS_FINAL t2 ON (t1.PREFIXO = t2.PREFIXO)
				ORDER BY t1.PREFIXO;
QUIT;

PROC SQL;
	DELETE FROM ADE.BASE_FINAL_AGENCIAS_&ANOMES WHERE POSICAO = &d2.;
RUN;

PROC APPEND OUT=ADE.BASE_FINAL_AGENCIAS_&ANOMES
	BASE=ADE.BASE_FINAL_AGENCIAS_&ANOMES
	DATA=WORK.BASE_FINAL_AGENCIAS;
RUN;

PROC SQL;
	CREATE TABLE WORK.relatorio_agencias_dia_a AS 
		SELECT DISTINCT
			t1.posicao,
			t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO, 
			t1.NOME, 
			t1.UF, 
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL, 
			t1.PERC_AUSENCIAS_TOTAL FORMAT=COMMAX10.5 AS PERC_AUSENCIAS_TOTAL, 
			t1.IND_GAT_ORCADO_ADC, 
			t1.QTDE_SUPERV_LCLZ_PREF, 
			t1.QTDE_SUPERV_TRABALHOU, 
			t1.QTDE_SUPERV_SAA_TRABALHOU, 
			/* PONTUACAO_MAX_SUPERV_DIA */
	(t1.QTDE_SUPERV_TRABALHOU * 100) FORMAT=5. AS PONTUACAO_MAX_SUPERV_DIA, /* PTOS_SUPERV_IND_UOR */
	(MIN(t1.SOMA_PTOS_IND_UOR_SUPERV, (t1.LOTAC_MIN_SUPERV_SAA * t1.IND_UOR_PTOS_SUPERV))) FORMAT=5. AS PTOS_SUPERV_IND_UOR, /* PTOS_SUPERV_IND_GAT */
	(MIN(t1.SOMA_PTOS_IND_GAT_SUPERV, (t1.LOTAC_MIN_SUPERV_SAA * t1.IND_GAT_PTOS_SUPERV))) FORMAT=5. AS PTOS_SUPERV_IND_GAT,/* PONTUACAO_TOTAL_SUPERV_DIA */
	(MIN(t1.SOMA_PTOS_TOTAL_SUPERV, (t1.LOTAC_MIN_SUPERV_SAA * t1.PESO_POR_FUNCI))) FORMAT=5. AS PONTUACAO_TOTAL_SUPERV_DIA, t1.QTDE_ESCRIT_LCLZ_PREF, t1.QTDE_ESCRIT_TRABALHOU, t1.QTDE_ESCRIT_SAA_TRABALHOU, /* PONTUACAO_MAX_ESCRIT_DIA */
	(t1.LOTAC_MIN_ESCRIT_SAA * t1.PESO_POR_FUNCI) FORMAT=5. AS PONTUACAO_MAX_ESCRIT_DIA, /* PTOS_ESCRIT_IND_UOR */
	(MIN(t1.SOMA_PTOS_IND_UOR_ESCRIT, (t1.LOTAC_MIN_ESCRIT_SAA * t1.IND_UOR_PTOS_ESCRIT))) FORMAT=5. AS PTOS_ESCRIT_IND_UOR, /* PTOS_ESCRIT_IND_GAT */
	(MIN(t1.SOMA_PTOS_IND_GAT_ESCRIT, (t1.LOTAC_MIN_ESCRIT_SAA * t1.IND_GAT_PTOS_ESCRIT))) FORMAT=5. AS PTOS_ESCRIT_IND_GAT, /* PONTUACAO_TOTAL_ESCRIT_DIA */
	(MIN(t1.SOMA_PTOS_TOTAL_ESCRIT, (t1.LOTAC_MIN_ESCRIT_SAA * t1.PESO_POR_FUNCI))) FORMAT=5. AS PONTUACAO_TOTAL_ESCRIT_DIA, t1.PONTUACAO_OBTIDA_AGENCIA, t1.PONTUACAO_MAXIMA_REGRA, t1.PERC_ATING_AGENCIA FORMAT=COMMAX10.2 AS PERC_ATING_AGENCIA, t1.DESCARTAR_AUSENCIAS_TOTAL, t1.DESCARTAR_AUSENCIA_SUPERVISOR, t1.DESCARTAR_SEM_FUNCI_PREV_TRAB, t1.DESCARTAR FROM WORK.BASE_FINAL_AGENCIAS t1;
QUIT;


PROC SQL;
   CREATE TABLE RELATORIO_AGENCIAS_DIA AS 
   SELECT t1.posicao, 
          t1.DIRETORIA, 
          t1.SUPER, 
          t1.GEREV, 
          t1.PREFIXO, 
          t1.NOME, 
          t1.UF, 
          t1.LOTAC_MIN_SUPERV_SAA, 
          t1.LOTAC_MIN_ESCRIT_SAA, 
          t1.LOTAC_MIN_FUNCIS_SAA, 
          t1.REGRA_CALCULO_CONEXAO, 
          t1.QTDE_FUNCIS_LCLZ_PREF, 
          t1.QTDE_FUNCIS_AUSENTES_TOTAL, 
          t1.PERC_AUSENCIAS_TOTAL, 
          t1.IND_GAT_ORCADO_ADC, 
          t1.QTDE_SUPERV_LCLZ_PREF, 
          t1.QTDE_SUPERV_TRABALHOU, 
          t1.QTDE_SUPERV_SAA_TRABALHOU, 
          ifn (QTDE_SUPERV_SAA_TRABALHOU=0,0,PONTUACAO_MAX_SUPERV_DIA) as PONTUACAO_MAX_SUPERV_DIA, 
          ifn (QTDE_SUPERV_SAA_TRABALHOU=0,0,PTOS_SUPERV_IND_UOR) as PTOS_SUPERV_IND_UOR,
          ifn (QTDE_SUPERV_SAA_TRABALHOU=0,0,PTOS_SUPERV_IND_GAT) as PTOS_SUPERV_IND_GAT, 
          ifn (QTDE_SUPERV_SAA_TRABALHOU=0,0,PONTUACAO_TOTAL_SUPERV_DIA) as PONTUACAO_TOTAL_SUPERV_DIA, 
          t1.QTDE_ESCRIT_LCLZ_PREF, 
          t1.QTDE_ESCRIT_TRABALHOU, 
          t1.QTDE_ESCRIT_SAA_TRABALHOU, 
          ifn (QTDE_ESCRIT_LCLZ_PREF=0,0,PONTUACAO_MAX_ESCRIT_DIA) as PONTUACAO_MAX_ESCRIT_DIA, 
		  ifn (QTDE_ESCRIT_LCLZ_PREF=0,0,PTOS_ESCRIT_IND_UOR) as PTOS_ESCRIT_IND_UOR,
          ifn(QTDE_ESCRIT_LCLZ_PREF=0,0,PTOS_ESCRIT_IND_GAT) as PTOS_ESCRIT_IND_GAT,
          IFN(QTDE_ESCRIT_LCLZ_PREF=0,0,PONTUACAO_TOTAL_ESCRIT_DIA) AS PONTUACAO_TOTAL_ESCRIT_DIA, 
          t1.PONTUACAO_OBTIDA_AGENCIA, 
          t1.PONTUACAO_MAXIMA_REGRA, 
          t1.PERC_ATING_AGENCIA, 
          t1.DESCARTAR_AUSENCIAS_TOTAL, 
          t1.DESCARTAR_AUSENCIA_SUPERVISOR, 
          t1.DESCARTAR_SEM_FUNCI_PREV_TRAB, 
          t1.DESCARTAR
      FROM WORK.RELATORIO_AGENCIAS_DIA_A t1;
QUIT;

PROC SQL;
	DELETE FROM ADE.REL_AGENCIAS_DIA_&ANOMES WHERE POSICAO = &d2.;
RUN;

PROC APPEND OUT=ADE.REL_AGENCIAS_DIA_&ANOMES
	BASE=ADE.REL_AGENCIAS_DIA_&ANOMES
	DATA=WORK.relatorio_agencias_dia;
RUN;


/**/
/**/
/*PROC SQL;*/
/*	CREATE TABLE ADE.PUBLICO_PREFIXO_&ANOMES AS */
/*		SELECT DISTINCT */
/*			T1.POSICAO,*/
/*			t1.prefixo*/
/*		FROM ADE.REL_AGENCIAS_DIA_&ANOMES t1*/
/*			WHERE DESCARTAR=0 */
/*	;*/
/*QUIT;*/


PROC SQL;
	CREATE TABLE ADE.RELATORIO_AGENCIAS_&ANOMES AS 
		SELECT 
			t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO,
			COUNT(DISTINCT(t1.POSICAO)) AS QT_DIAS,
			/* PONTUACAO_MAX_SUPERV_MES */
	SUM(t1.PONTUACAO_MAX_SUPERV_DIA) FORMAT=5. AS PONTUACAO_MAX_SUPERV_DIA, 
	/* PTOS_SUPERV_IND_UOR */
	SUM(t1.PTOS_SUPERV_IND_UOR) FORMAT=5. AS PTOS_SUPERV_IND_UOR, 
	/* PTOS_SUPERV_IND_GAT */
	SUM(t1.PTOS_SUPERV_IND_GAT) FORMAT=5. AS PTOS_SUPERV_IND_GAT, 
	/* PONTUACAO_TOTAL_SUPERV_MES */
	SUM(t1.PONTUACAO_TOTAL_SUPERV_DIA) FORMAT=5. AS PONTUACAO_TOTAL_SUPERV_MES, 
	/* PONTUACAO_MAX_ESCRIT_MES */
	SUM(t1.PONTUACAO_MAX_ESCRIT_DIA) FORMAT=5. AS PONTUACAO_MAX_ESCRIT_MES, 
	/* PTOS_ESCRIT_IND_UOR */
	SUM(t1.PTOS_ESCRIT_IND_UOR) FORMAT=5. AS PTOS_ESCRIT_IND_UOR, 
	/* PTOS_ESCRIT_IND_GAT */
	SUM(t1.PTOS_ESCRIT_IND_GAT) FORMAT=5. AS PTOS_ESCRIT_IND_GAT, 
	/* PONTUACAO_TOTAL_ESCRIT_DIA */
	SUM(t1.PONTUACAO_TOTAL_ESCRIT_DIA) FORMAT=5. AS PONTUACAO_TOTAL_ESCRIT_MES, 
	SUM(t1.PONTUACAO_OBTIDA_AGENCIA) AS PONTUACAO_OBTIDA_AGENCIA, 
	SUM(t1.PONTUACAO_MAXIMA_REGRA) AS PONTUACAO_MAXIMA_REGRA, 
	(SUM(t1.PONTUACAO_OBTIDA_AGENCIA) / SUM(t1.PONTUACAO_MAXIMA_REGRA)) FORMAT=COMMAX10.2 AS PERC_ATING_AGENCIA
	FROM ADE.REL_AGENCIAS_DIA_&ANOMES t1
		GROUP BY
			t1.DIRETORIA, 
			t1.SUPER, 
			t1.GEREV, 
			t1.PREFIXO;
QUIT;

PROC SQL;
	CREATE TABLE WORK.base_final_funcionarios AS 
		SELECT DISTINCT
			&d2. FORMAT DDMMYY10. AS POSICAO,
			t1.PREFIXO, 
			t1.REGRA_CALCULO_AGENCIA, 
			t1.DESCRICAO_REGRA_AGENCIA, 
			t1.FUNCI_ALOCADO_SAA, 
			t1.REGISTROU_PONTO, 
			/* EFETUADO_CALCULO_FUNCI */
	(CASE
		WHEN t2.MATRICULA_215 NOT IS MISSING THEN 1 
		ELSE 0 
		END)
	FORMAT=1. AS EFETUADO_CALCULO_FUNCI, t1.MATRICULA_215, t1.SITUACAO_215, t1.LOCALIZACAO_215, t1.COMISSAO_215, t1.AFR_215, t1.FUNCAO_LOCALIZACAO_215, t1.DEP_LOTACAO_215, t1.FUNCAO_LOTACAO_215, t1.HORA_TRAB_INI_215, t1.HORA_TRAB_FIM_215, t1.HORA_TRAB_INTERV_INI_215, t1.HORA_TRAB_INTERV_FIM_215, t1.HORA_TRAB_INTERV2_INI_215, t1.HORA_TRAB_INTERV2_FIM_215, t1.CD_UOR_LCZC, t1.CD_UOR_TRB_HBTL, t1.FUNCI_EXTRAQUADRO, t1.FUNCI_QS_LIC_SAUDE, t1.FUNCI_EM_SUBSTITUICAO, t1.PREFIXO_SUBSTITUICAO, t1.CD_TIP_CMSS_FUC, t1.IN_ICD_PTO_ETN, t1.NM_TIP_CMSS_FUC, t1.QT_HH_JRTB_DRIA, t1.QT_MINUTOS_JRTB_DRIA, t1.FUNCI_HORAS_EXTRAS, t1.CD_REF_ORGC, t1.SUJEITO_PONTO_ELETRONICO, t1.FUNCI_ESCRIT_LOCALIZACAO, t1.FUNCI_ESCRIT_LOTACAO, t1.FUNCI_CAIEX_LOCALIZACAO, t1.FUNCI_CAIEX_LOTACAO, t1.FUNCI_SUPERVISOR, t1.FUNCI_CAIEX_EFETIVO, t1.FUNCI_ESCRITURARIO, t1.FUNCI_PREVISTO_TRABALHAR, t1.FUNCI_AUSENTE, t1.SITUACAO_PONTO_FUNCI, t1.QT_HORAS_TRABALHADAS_DIA, t1.QT_MINUTOS_TRABALHADOS_DIA, t1.PESO_POR_FUNCI, t1.QT_TIP_LCL_ATD, t1.QT_SENHAS_FUNCI, t1.QT_TMP_SENHAS_FUNCI, t1.TMP_MEDIO_ATDT_FUNCI, t1.QT_TMP_TRBD_FUN, t1.PERC_TMP_TRBD_ATDT, t2.AGE_COM_SUPERV_DIA, t2.AGE_COM_ESCRIT_DIA, t2.IND_UOR_ATINGIU, t2.IND_UOR_PTOS, /* t2.IND_GAT_TMP_ORCADO_ADC, */
	t2.IND_GAT_TMP_ORCADO, 
	t2.IND_GAT_TMP_OBSERVADO, 
	t2.IND_GAT_QTDE_ORCADO,
	t2.IND_GAT_QTDE_OBSERVADO,
	t2.IND_GAT_ATINGIU, 
	t2.IND_GAT_PTOS, 
	t2.PONTUACAO_MAXIMA_FUNCI, 
	t2.PONTUACAO_OBTIDA_FUNCI, 
	t2.PERC_ATING_FUNCI,
	t2.DESCARTAR
	FROM WORK.PREVIA_FUNCIS_SAA_GAT_BIC t1
		LEFT JOIN WORK.REGRA_CALCULO_FUNCIONARIOS t2 ON (t1.MATRICULA_215 = t2.MATRICULA_215)
			ORDER BY t1.PREFIXO;
QUIT;

PROC SQL;
	CREATE TABLE
		WORK.TESTAR_FUNCI_NAO_CALCULADO
	AS
		SELECT
			*
		FROM
			WORK.base_final_funcionarios AS t1
		WHERE
			t1.FUNCI_ALOCADO_SAA = 1
			AND
			t1.FUNCI_AUSENTE = 0
			AND
			(
			t1.FUNCI_ESCRITURARIO = 1
			OR
			t1.FUNCI_SUPERVISOR = 1
				)
				AND
				t1.EFETUADO_CALCULO_FUNCI = 0;
RUN;

PROC SQL;
	DELETE FROM ADE.base_final_funci_&ANOMES WHERE POSICAO = &d2.;
RUN;

PROC APPEND 
	BASE=ADE.base_final_funci_&ANOMES
	DATA=WORK.base_final_funcionarios;
RUN;


/******/

data aderencia_prefixo;
set  ADE.REL_AGENCIAS_DIA_&anomes;
where descartar=1;
run;


PROC SQL;
	CREATE TABLE ADERENCIA_PREFIXO AS 
		SELECT 
			t1.PREFIXO AS PREFDEP,
			COUNT(DISTINCT(t1.POSICAO)) AS QT_DIAS,
			SUM(t1.PONTUACAO_MAX_SUPERV_DIA) FORMAT=5. AS PONTUACAO_MAX_SUPERV_DIA, 
			SUM(t1.PTOS_SUPERV_IND_UOR) FORMAT=5. AS PTOS_SUPERV_IND_UOR, 
			SUM(t1.PONTUACAO_TOTAL_SUPERV_DIA) FORMAT=5. AS PONTUACAO_TOTAL_SUPERV_MES, 
			SUM(t1.PONTUACAO_MAX_ESCRIT_DIA) FORMAT=5. AS PONTUACAO_MAX_ESCRIT_MES, 
			SUM(t1.PTOS_ESCRIT_IND_UOR) FORMAT=5. AS PTOS_ESCRIT_IND_UOR,
			SUM(t1.PTOS_ESCRIT_IND_GAT) FORMAT=5. AS PTOS_ESCRIT_IND_GAT,
			SUM(t1.PONTUACAO_TOTAL_ESCRIT_DIA) FORMAT=5. AS PONTUACAO_TOTAL_ESCRIT_MES, 
            SUM(pontuacao_obtida_agencia) as PONTUACAO_OBTIDA_AGENCIA,
			SUM(t1.PONTUACAO_MAXIMA_REGRA) AS PONTUACAO_MAXIMA_REGRA,
			SUM(t1.PTOS_SUPERV_IND_GAT) FORMAT=5. AS PTOS_SUPERV_IND_GAT 
		FROM ADE.REL_AGENCIAS_DIA_&anomes t1
			WHERE DESCARTAR=0
				GROUP BY
					t1.PREFIXO;
QUIT;

PROC SQL;
	CREATE TABLE ADERENCIA_PREFIXO AS 
		SELECT t1.PREFDEP, 
			t1.QT_DIAS, 
			t1.PONTUACAO_MAX_SUPERV_DIA, 
			t1.PTOS_SUPERV_IND_UOR, 
			t1.PONTUACAO_TOTAL_SUPERV_MES, 
			t1.PONTUACAO_MAX_ESCRIT_MES, 
			t1.PTOS_ESCRIT_IND_UOR, 
			t1.PTOS_ESCRIT_IND_GAT, 
			t1.PONTUACAO_TOTAL_ESCRIT_MES, 
			t1.PONTUACAO_OBTIDA_AGENCIA, 
			t1.PONTUACAO_MAXIMA_REGRA, 
			(PONTUACAO_OBTIDA_AGENCIA/PONTUACAO_MAXIMA_REGRA)*100 format 19.2 as PERC_ATING_AGENCIA,
			t1.PTOS_SUPERV_IND_GAT
		FROM WORK.ADERENCIA_PREFIXO t1
inner join NOVO_LOTACAO_SAA t2 on (prefdep=t2.prefixo)
where lotacao_minima_total_saa>0;
QUIT;



data REGUA_ADERENCIA;
infile DATALINES dsd missover;
input Inferior Superior Pontos;
format Inferior Superior 32.4;
CARDS;
95.00,	9999.99,	900
92.00,	94.99,	840
89.00,	91.99,	780
86.00,	88.99,	720
83.00,	85.99,	660
80.00,	82.99,	600
75.00,	79.99,	540
70.00,	74.99,	480
65.00,	69.99,	420
60.00,	64.99,	360
50.00,	59.99,	300
40.00,	49.99,	240
30.00,	39.99,	180
20.00,	29.99,	120
10.00,	19.99,	60
0.00,	9.99,	0
;
run;


PROC SQL;
	CREATE TABLE ADERENCIA AS 
		SELECT  &d2.  FORMAT=DateMysql. AS POSICAO, 
			t1.prefdep, 
			t1.QT_DIAS, 
			t1.PONTUACAO_MAX_SUPERV_DIA as PONTUACAO_MAX_superv,
			t1.PTOS_SUPERV_IND_UOR, 
			t1.PONTUACAO_TOTAL_SUPERV_MES as PONTUACAO_TOTAL_SUPERV, 
			t1.PONTUACAO_MAX_ESCRIT_MES, 
			t1.PTOS_ESCRIT_IND_UOR, 
			t1.PTOS_ESCRIT_IND_GAT, 
			t1.PONTUACAO_TOTAL_ESCRIT_MES, 
			t1.PONTUACAO_OBTIDA_AGENCIA, 
			t1.PONTUACAO_MAXIMA_REGRA, 
			t1.PERC_ATING_AGENCIA,
			(T2.PONTOS) AS PONTOS_ADE,
			t1.PTOS_SUPERV_IND_GAT
		FROM WORK.ADERENCIA_PREFIXO t1
			INNER JOIN REGUA_ADERENCIA T2 ON (PERC_ATING_AGENCIA BETWEEN T2.INFERIOR AND T2.SUPERIOR)
				GROUP BY 1,2,3,4,5;
QUIT;


/*AUSÊNCIAS ADERÊNCIA*/

PROC SQL;
	CREATE TABLE CONSULTA_ADERENCIA AS 
		SELECT DISTINCT t1.posicao, 
			T1.PREFIXO,
			t1.PERC_AUSENCIAS_TOTAL*100 AS PC_AUSENCIAS, 
			t1.DESCARTAR
		FROM ADE.REL_AGENCIAS_DIA_&anomes t1
	;
QUIT;


PROC SQL;
   CREATE TABLE MES_AUSENCIA AS 
   SELECT t1.posicao, 
          t1.PREFIXO, 
          IFN(DESCARTAR=1,1,0) AS AUSENCIAS,
          t1.DESCARTAR
      FROM WORK.CONSULTA_ADERENCIA t1;
QUIT;



PROC SQL;
   CREATE TABLE calcula_dias AS 
   SELECT DISTINCT t1.PREFIXO, 
          /* COUNT_of_posicao */
            (COUNT(t1.posicao)) AS qtd_posicao
      FROM WORK.MES_AUSENCIA t1
      GROUP BY t1.PREFIXO;
QUIT;

PROC SQL;
   CREATE TABLE conta_ausencias AS 
   SELECT DISTINCT t1.PREFIXO, 
   t1.DESCARTAR,
          /* COUNT_of_posicao */
            (COUNT(t1.posicao)) AS COUNT_of_posicao, 
          /* COUNT_of_AUSENCIAS */
            (sum(t1.AUSENCIAS)) AS COUNT_of_AUSENCIAS 
      FROM WORK.MES_AUSENCIA t1
      GROUP BY 1,2;
QUIT;

PROC SQL;
	CREATE TABLE prefixos_sem_aderencia AS 
		SELECT t1.PREFIXO, 
			t1.DESCARTAR, 
			t1.COUNT_of_posicao, 
			t1.COUNT_of_AUSENCIAS
		FROM WORK.CONTA_AUSENCIAS t1
			inner join calcula_dias t2 on (t1.prefixo=t2.prefixo and t1.COUNT_of_posicao=t2.qtd_posicao)
				where COUNT_of_posicao=COUNT_of_AUSENCIAS;
QUIT;

PROC SQL;
   CREATE TABLE ADE.PREFIXOS_SEM_ADERENCIA_&ANOMES AS 
   SELECT t1.PREFIXO AS PREFDEP, 
          600 AS PONTOS_ADE,
		  400 AS PONTOS_NEG
      FROM WORK.PREFIXOS_SEM_ADERENCIA t1;
QUIT;




										/*******************/
										/*******************/
										/****	NEGÓCIOS ****/
										/*******************/
										/*******************/

%put &mmaaaa. &anomes.;

PROC SQL;
	CREATE TABLE ADE.PUBLICO_RIV_&ANOMES AS 
		SELECT 
			t1.CD_CLI, 
			t1.CD_PRF_RSTD, 
			t1.CD_PRF_CTRA_CLI, 
			t1.CD_IPMC_ITCE_CNL, 
			t1.CD_PRD, 
			t1.CD_MDLD, 
			t1.CD_CPNT_RSTD, 
			t1.VL_CPNT_RSTD, 
			t1.VL_CPNT_RSTD_TODOS, 
			t1.VL_ULT_SDO, 
			t1.DT_APRC FORMAT DATE9., 
			t1.DT_FRMZ_SCTR
		FROM RIV.VS_CLC_RSTD_GRNL t1
			INNER JOIN IGR.IGRREDE T2 ON (T1.CD_PRF_RSTD=INPUT(T2.PREFDEP,4.))
				WHERE dt_aprc between '01aug2019'd AND &d2. and cd_cpnt_rstd=174 AND CD_IPMC_ITCE_CNL=10 AND T2.TIPODEP IN ('09' '01') AND T2.CODSITDEP='2'
					ORDER BY 2,1
;
QUIT;
/**/
/*data rvsaa_realizado_&ANOMES;*/
/*set PUBLICO_RIV;*/
/*run;*/



PROC SQL;
	CREATE TABLE ADE.RV_SEGUROS_&ANOMES AS 
		SELECT
			t1.CD_PRF_RSTD, 
			t1.CD_CLI,
			t1.CD_PRD, 
			t1.CD_MDLD, 
			t1.VLR_CPNT_RSTD AS VL_CPNT_RSTD_TODOS,
			t1.VL_CTR AS VL_ULT_SDO,
			t1.DT_APRC
		FROM SEG.RV_ACUM_2019S2 t1
			where aaaamm=&anomes. and cd_cpnt_rstd=174 AND CD_ITCE_CNL=10
				ORDER BY 1,2
	;
QUIT;
%ZerarMissingTabela(ADE.RV_SEGUROS_&ANOMES);

DATA RECEITA_VENDAS (KEEP=CD_PRF_RSTD CD_CLI CD_PRD CD_MDLD VL_CPNT_RSTD_TODOS VL_ULT_SDO DT_APRC) ;
SET ADE.PUBLICO_RIV_&ANOMES ADE.RV_SEGUROS_&ANOMES;
BY CD_PRF_RSTD CD_CLI;
RUN;

data receita_vendas;
set RECEITA_VENDAS;
where VL_CPNT_RSTD_TODOS ne 0;
run;

PROC SQL;
   CREATE TABLE DETALHE_RV AS 
   SELECT t1.CD_PRF_RSTD,
          t1.CD_CLI,
          t1.CD_PRD, 
          t1.CD_MDLD, 
          t1.VL_CPNT_RSTD_TODOS, 
          t1.VL_ULT_SDO, 
          t1.DT_APRC
      FROM WORK.RECEITA_VENDAS t1;
QUIT;
%ZerarMissingTabela (DETALHE_RV);

PROC SQL;
   CREATE TABLE PREFDEP_REALIZADO AS 
   SELECT DISTINCT t1.CD_PRF_RSTD, 
          /* SUM_of_VL_CPNT_RSTD_TODOS */
            (SUM(t1.VL_CPNT_RSTD_TODOS)) FORMAT=19.2 AS VL_CPNT_RSTD_TODOS
      FROM WORK.DETALHE_RV t1
      GROUP BY 1;
QUIT;

PROC SQL;
   CREATE TABLE PREFDEP_NEGOCIOS AS 
   SELECT DISTINCT T2.CD_PRF_RSTD as prefdep, 
          t2.orc AS ORCADO_NEGOCIOS, 
          t1.VL_CPNT_RSTD_TODOS AS RELIZADOS_NEGOCIOS,
		  (VL_CPNT_RSTD_TODOS/orc)*100 format 19.2 AS PC_ATG_NEGOCIOS
      FROM WORK.PREFDEP_REALIZADO t1
	  right JOIN REC.RVSAA_ORCADO_2S2019 t2 ON (T1.CD_PRF_RSTD=t2.CD_PRF_RSTD)
		    INNER JOIN IGR.IGRREDE_&ANOMES T3 ON (T2.CD_PRF_RSTD=INPUT(T3.PREFDEP,4.))
WHERE ANOMES=&MMAAAA. AND T3.TIPODEP IN ('09' '01') AND T3.CODSITDEP='2';
QUIT;
%ZerarMissingTabela (PREFDEP_NEGOCIOS);




data REGUA_RIV;
infile DATALINES dsd missover;
input Inferior Superior Pontos;
format Inferior Superior 32.4;
CARDS;
125.00,	9999.99, 600
120.00,	124.99,	560
118.00,	119.99,	520
115.00,	117.99,	480
112.00,	114.99,	440
100.00,	111.99,	400
90.00,	99.99,	360
80.00,	89.99,	320
70.00, 	79.99,	280
60.00,	69.99,	240
50.00,	59.99,	200
40.00,	49.99,	160
30.00,	39.99,	120
20.00,	29.99,	80
10.00,	19.99,	40
0.00,	9.99,	0
;
run;

%PUT &d2.;



PROC SQL;
   CREATE TABLE COMPONENTE_NEGOCIOS AS 
   SELECT t1.prefdep, 
          t1.ORCADO_NEGOCIOS, 
          t1.RELIZADOS_NEGOCIOS, 
          t1.PC_ATG_NEGOCIOS FORMAT 19.2,
		  (T2.PONTOS) AS PONTOS_NEG
      FROM WORK.PREFDEP_NEGOCIOS t1
	 LEFT JOIN REGUA_RIV T2 ON (PC_ATG_NEGOCIOS BETWEEN T2.INFERIOR AND T2.SUPERIOR)
	 inner join NOVO_LOTACAO_SAA t3 on (prefdep=t3.prefixo)
where lotacao_minima_total_saa>0
GROUP BY 1,2,3,4;
QUIT;



DATA JUNTA_COMPONENTES (keep=PREFDEP PONTOS_ADE ORCADO_NEGOCIOS PONTOS_NEG);
MERGE ADERENCIA COMPONENTE_NEGOCIOS;
BY prefdep;
;
run;
%ZerarMissingTabela(JUNTA_COMPONENTES)




PROC SQL;
   CREATE TABLE PREFIXOS_COM_ADERENCIA AS 
   SELECT DISTINCT t1.PREFDEP
      FROM WORK.ADERENCIA t1;
QUIT;

PROC SQL;
	CREATE TABLE WORK.PONTUACAO_SAA_COM_ADERENCIA AS 
		SELECT t1.PREFDEP, 
			t1.PONTOS_ADE, 
			IFN(ORCADO_NEGOCIOS=0, 400, PONTOS_NEG) AS PONTOS_NEG
		FROM WORK.JUNTA_COMPONENTES t1
            INNER JOIN PREFIXOS_COM_ADERENCIA T2 ON (T1.PREFDEP=T2.PREFDEP)
			INNER JOIN NOVO_LOTACAO_SAA T4 ON (T1.PREFDEP=T4.PREFIXO)
				WHERE T4.lotacao_minima_total_saa >= 1
					GROUP BY 1,2;;
QUIT;


PROC SQL;
	CREATE TABLE PONTUACAO_SAA AS 
		SELECT T1.*
			FROM WORK.PONTUACAO_SAA_COM_ADERENCIA t1
				UNION 
			SELECT T2.*
				FROM ADE.PREFIXOS_SEM_ADERENCIA_&ANOMES T2;
QUIT;
%ZerarMissingTabela(PONTUACAO_SAA)



/*CONFORME BOLETIM 2895 e 2892*/

PROC SQL;
	CREATE TABLE BOLETIM_2895 AS 
		SELECT 
			t1.PREFDEP,
			t1.PONTOS_ADE,
			t1.PONTOS_NEG, 
			ifn(prefdep=2968,PONTOS_NEG,0) as nota1,
			ifn(prefdep=5695,PONTOS_NEG,0) as nota4
		FROM WORK.PONTUACAO_SAA t1		
			GROUP BY 1,2,3,4
	;
QUIT;

PROC SQL;
	CREATE TABLE BOLETIM AS 
		SELECT t1.PREFDEP, 
			t1.PONTOS_ADE, 
			t1.PONTOS_NEG, 
			max(nota1) as nota1, 
			max(nota4) as nota4
		FROM WORK.BOLETIM_2895 t1;
QUIT;


PROC SQL;
	CREATE TABLE WORK.JUNTA_RESULTADO AS 
		SELECT 
			t1.PREFDEP,
			t1.PONTOS_ADE, 
		(case 
			when prefdep=1602 then nota1
			when prefdep=3781 then nota4 
			else pontos_neg 
		end)
	as pontos_neg
		FROM WORK.BOLETIM t1		
			GROUP BY 1
	;
QUIT;


PROC SQL;
	CREATE TABLE ADE.RESULTADO_SAA_PREFIXO AS 
		SELECT 
			&d2. FORMAT YYMMDD10. AS POSICAO,
			t1.PREFDEP,
			t1.PONTOS_ADE, 
			t1.PONTOS_NEG,
			(PONTOS_ADE+PONTOS_NEG) AS PONTOS
		FROM WORK.JUNTA_RESULTADO t1
	;
QUIT;


/* EXECUTAR PROCESSOS FILHOS (DEPENDENTES DESTE) */

%let logDate = D%sysfunc(today(),yymmddn6.).T%sysfunc(compress(%sysfunc(time(),time8.),':'));

x nohup /opt/sas94/SASFoundation/9.4/sas 
	/dados/infor/conexao/apuracao/000000265/sas/V_SAA_000000265.sas
	-sasuser /dados/infor 
	-work /saswork/infor/work 
	-altlog /dados/infor/conexao/apuracao/000000265/log/V_SAA_000000265.&logDate..log 
	-noterminal -nosyntaxcheck -nonews &;

x nohup /opt/sas94/SASFoundation/9.4/sas 
	/dados/infor/conexao/apuracao/000000292/sas/V_SAA_Infor_000000292.sas
	-sasuser /dados/infor 
	-work /saswork/infor/work 
	-altlog /dados/infor/conexao/apuracao/000000292/log/V_SAA_Infor_000000292.&logDate..log 
	-noterminal -nosyntaxcheck -nonews &;


/*############################################################################################################################*/
/*#######################################          RELATÓRIOS             #################################################*/
/*############################################################################################################################*/




/*********** ADERENCIA ***********/

/*RELATÓRIO 563 */

PROC SQL;
	CREATE TABLE detalha_agencia AS 
		SELECT DISTINCT 
			t1.PREFIXO,
			t1.posicao AS DATA,
			(CASE 
		WHEN DESCARTAR_SEM_FUNCI_PREV_TRAB=1 	THEN 'Não houve atendimento'
		WHEN DESCARTAR_AUSENCIAS_TOTAL=1 		THEN 'Ausências maior que 30%'
		/*		
		WHEN DESCARTAR_AUSENCIA_SUPERVISOR=1 	THEN 'Superv. de Atendimento ausente'*/
	end)
	as Observacao,
			t1.LOTAC_MIN_SUPERV_SAA, 
			t1.LOTAC_MIN_ESCRIT_SAA, 
			t1.LOTAC_MIN_FUNCIS_SAA, 
			t1.REGRA_CALCULO_CONEXAO, 
			t1.QTDE_FUNCIS_LCLZ_PREF, 
			t1.QTDE_FUNCIS_AUSENTES_TOTAL, 
			round(PERC_AUSENCIAS_TOTAL*100,.01) as PERC_AUSENCIAS_TOTAL, 
			t1.IND_GAT_ORCADO_ADC, /**/
	t1.QTDE_SUPERV_LCLZ_PREF, 
	t1.QTDE_SUPERV_TRABALHOU, 
	t1.QTDE_SUPERV_SAA_TRABALHOU,
	t1.PTOS_SUPERV_IND_UOR, 
	t1.PTOS_SUPERV_IND_GAT, 
	t1.PONTUACAO_TOTAL_SUPERV_DIA, 
	t1.PONTUACAO_MAX_SUPERV_DIA, 
	t1.QTDE_ESCRIT_LCLZ_PREF, 
	t1.QTDE_ESCRIT_TRABALHOU, 
	t1.QTDE_ESCRIT_SAA_TRABALHOU, 
	t1.PTOS_ESCRIT_IND_UOR, 
	t1.PTOS_ESCRIT_IND_GAT, 
	t1.PONTUACAO_TOTAL_ESCRIT_DIA, 
	t1.PONTUACAO_MAX_ESCRIT_DIA, /**/
	t1.PONTUACAO_OBTIDA_AGENCIA, 
	t1.PONTUACAO_MAXIMA_REGRA, 
	round(PERC_ATING_AGENCIA*100,.01) as PERC_ATING_AGENCIA, 
	t1.DESCARTAR_AUSENCIAS_TOTAL, 
	t1.DESCARTAR_AUSENCIA_SUPERVISOR, 
	t1.DESCARTAR_SEM_FUNCI_PREV_TRAB,
		t1.DESCARTAR
	
		FROM ADE.REL_AGENCIAS_DIA_&ANOMES t1
	;
QUIT;

PROC SQL;
   CREATE TABLE detalha_funci AS 
   SELECT 
 t1.PREFIXO as prefdep, 
 posicao as data,
         'F'||PUT(MATRICULA_215,Z7.) AS MATRICULA,
          t1.CD_TIP_CMSS_FUC, 
          t1.NM_TIP_CMSS_FUC, 
          t1.REGISTROU_PONTO, 
          t1.FUNCI_AUSENTE, 
          t1.EFETUADO_CALCULO_FUNCI, 
          t1.FUNCI_SUPERVISOR, 
          t1.FUNCI_ESCRITURARIO, 
          t1.FUNCI_ALOCADO_SAA, 
          t1.IND_UOR_ATINGIU, 
          t1.IND_UOR_PTOS, 
          t1.IND_GAT_TMP_ORCADO, 
          t1.IND_GAT_TMP_OBSERVADO, 
          t1.IND_GAT_QTDE_ORCADO, 
          t1.IND_GAT_QTDE_OBSERVADO, 
          t1.IND_GAT_ATINGIU, 
          t1.IND_GAT_PTOS,
          t1.PONTUACAO_OBTIDA_FUNCI, 
          t1.PONTUACAO_MAXIMA_FUNCI, 
          round(PERC_ATING_FUNCI*100,.01) as PERC_ATING_FUNCI,
		  		       t1.DESCARTAR 
      FROM  ADE.BASE_FINAL_FUNCI_&ANOMES t1;
QUIT;



%LET Usuario=f9457977;
%LET Keypass=saa-rFem9G6vNf5L5kKen2rohuBOxFREK6s9jGWtoyAQWaC1fdOH5p;
%LET Rotina=saa;


PROC SQL;
DROP TABLE TABELAS_EXPORTAR_REL;
CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
INSERT INTO TABELAS_EXPORTAR_REL VALUES('aderencia', 'saa');
INSERT INTO TABELAS_EXPORTAR_REL VALUES('detalha_agencia', 'detalhar-prefixo');
INSERT INTO TABELAS_EXPORTAR_REL VALUES('detalha_funci', 'detalhar-funcionarios');

QUIT;

%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);  



/***********NEGÓCIOS SAA***********/
/*RELATÓRIO 279 */

PROC SQL;
	CREATE TABLE DETALHE_RV AS 
		SELECT 
			t1.CD_PRF_RSTD as PREFDEP, 
			t1.CD_CLI,
			t1.CD_PRD, 
			t1.CD_MDLD,
			t3.NM_MDLD, 
			t1.VL_CPNT_RSTD_TODOS format 19.2, 
			t1.VL_ULT_SDO format 19.2, 
			t1.DT_APRC
		FROM WORK.RECEITA_VENDAS t1
			INNER JOIN PRD.MDLD_PRD T3 ON (T1.CD_PRD=T3.CD_PRD AND T1.CD_MDLD=T3.CD_MDLD);
	;
QUIT;

PROC SQL;
	CREATE TABLE NEGOCIOS_SAA AS 
		SELECT DISTINCT
			&d2. FORMAT YYMMDD10. AS POSICAO,
			t1.prefdep, 
			t1.ORCADO_NEGOCIOS format 19.2 as ORC_SAA, 
			t1.RELIZADOS_NEGOCIOS AS VLR_M_SAA, 
			t1.PC_ATG_NEGOCIOS AS PCT_ATG_RIV, 
			t1.PONTOS_NEG AS PONTOS_RIV
		FROM WORK.COMPONENTE_NEGOCIOS t1;
QUIT;


%LET Usuario=f9457977;
%LET Keypass=lamRISgRPpy1CdCCeDuq5Q3T9jzvPFvOclCGIUHIhLe79v7wNY;
%LET Rotina=riv-unv;

PROC SQL;
DROP TABLE TABELAS_EXPORTAR_REL;
CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
INSERT INTO TABELAS_EXPORTAR_REL VALUES('negocios_saa', 'riv-unv');
INSERT INTO TABELAS_EXPORTAR_REL VALUES('detalhe_rv', 'detalhe');
QUIT;
%ProcessoCarregarEncerrar(TABELAS_EXPORTAR_REL);  



x cd /;
x cd /dados/infor/producao/Aderencia;
x cd /dados/infor/producao/Receita_Vendas;
x cd /dados/infor/conexao/apuracao/000000265/bases;
x cd /dados/infor/conexao/apuracao/000000292/bases;
X cd //dados/externo/DIVAR/METAS/conexao/19S2/;
x chmod -R 2777 *; /*ALTERAR PERMISÕES*/
x chown f9457977 -R ./; /*FIXA O FUNCI*/
x chgrp -R GSASBPA ./; /*FIXA O GRUPO*/



/*############################################################################################################################*/
/*# GRAVA CÓPIA DO ANALÍTICO DE PRODUTO PARA VALIDAÇÃO E GERAÇÃO DE RELATÓRIOS POR TERCEIROS #################################*/
LIBNAME EXT_ANLT '/dados/externo/DIVAR/METAS/conexao/19S2/';


DATA ADE.RESULTADO_PONTOS_SAA_&ANOMES.;
SET INF.RESULTADO_INFORMATIVO_SAA_&ANOMES ADE.RESULTADO_MOBILIZACAO_SAA_&ANOMES;
RUN;

DATA ADE.SUPERS_&ANOMES. ;
SET INF.SUPER ADE.SUPER;
RUN;

DATA EXT_ANLT.PRINCIPAL_SAA_265_&anomes.;
    SET ADE.RESULTADO_PONTOS_SAA_&ANOMES.;
RUN;


DATA EXT_ANLT.SECUNDARIA_SAA_265_&anomes. ;
    SET ADE.SUPERS_&ANOMES.;
RUN;



/*%commandShell(chmod 777 '/dados/externo/DIVAR/METAS/conexao/19s2/rlzd_analitico/'anlt_&NR_INDICADOR._&anomes.*);*/
/*# GRAVA CÓPIA DO ANALÍTICO DE PRODUTO PARA VALIDAÇÃO E GERAÇÃO DE RELATÓRIOS POR TERCEIROS - FIM ###########################*/
/*############################################################################################################################*/
 

/*************************************************/;
/* TRECHO DE CÓDIGO INCLUÍDO PELO FF */;

%include "/dados/gestao/rotinas/_macros/macros_uteis.sas";
 
%processCheckOut(
    uor_resp = 341556
    ,funci_resp = &sysuserid
    /*,tipo = Indicador
    ,sistema = Indicador
    ,rotina = I0123 Indicador de Alguma Coisa*/
    ,mailto= 'F8369937' 'F2986408' 'F6794004' 'F7176219' 'F8176496' 'F9457977' 'F9631159'
);
