%include '/dados/infor/suporte/FuncoesInfor.sas';
%LET NomeRelatorio=;
%LET NomePasta=;



LIBNAME DB2SGCEN 	db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2SGCEN database=BDB2P04;
LIBNAME DB2ITR      db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2ITR 	database=BDB2P04;  
LIBNAME DB2ATB      db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2ATB 	database=BDB2P04;  
LIBNAME DB2ARH	db2 AUTHDOMAIN=DB2SGCEN 	schema=DB2ARH database=BDB2P04;



DATA _NULL_;
	DATA_INICIO = '01Jan2018'd;
	DATA_FIM = '29MAR2018'd;
	DATA_REFERENCIA = diaUtilAnterior(TODAY());
	D1 = diaUtilAnterior(TODAY());
	D2 = diaUtilAnterior(D1);
	D3 = diaUtilAnterior(D2);
	MES_ATU = IFN((D1 <= DATA_FIM), Put(D1, yymmn6.), Put(DATA_FIM, yymmn6.));
	MES_ANT = Put(INTNX('month',primeiroDiaUtilMes(D1),-1), yymmn6.) ;
	MES_G = Put(DATA_REFERENCIA, MONTH.) ;
	ANOMES = IFN((D1 <= DATA_FIM), Put(D1, yymmn6.), Put(DATA_FIM, yymmn6.));
	DT_INICIO_SQL="'"||put(DATA_INICIO, YYMMDDD10.)||"'";
	DT_D1_SQL="'"||put(D1, YYMMDDD10.)||"'";
	DT_1DIA_MES_SQL="'"||put(primeiroDiaUtilMes(D1), YYMMDDD10.)||"'";
	DT_ANOMES_SQL=primeiroDiaUtilMes(D1);
	PRIMEIRO_DIA_MES_SQL="'"||put(primeiroDiaMes(DATA_REFERENCIA), YYMMDDD10.)||"'";
    MMAAAA=PUT(D1,mmyyn6.);

	CALL SYMPUT('DATA_HOJE',COMPRESS(TODAY(),' '));
	CALL SYMPUT('DT_1DIA_MES',COMPRESS(primeiroDiaUtilMes(D1),' '));
	CALL SYMPUT('DATA_INICIO',COMPRESS(DATA_INICIO,' '));
	CALL SYMPUT('DATA_FIM',COMPRESS(DATA_FIM,' '));
	CALL SYMPUT('D1',COMPRESS(D1,' '));
	CALL SYMPUT('D2',COMPRESS(D2,' '));
	CALL SYMPUT('D3',COMPRESS(D3,' '));
	CALL SYMPUT('MES_ATU',COMPRESS(MES_ATU,' '));
	CALL SYMPUT('MES_ANT',COMPRESS(MES_ANT,' '));
	CALL SYMPUT('ANOMES',COMPRESS(ANOMES,' '));
	CALL SYMPUT('RF',COMPRESS(ANOMES,' '));
	CALL SYMPUT('DT_ARQUIVO',put(DATA_REFERENCIA, DDMMYY10.));
	CALL SYMPUT('DT_ARQUIVO_SQL',put(DATA_REFERENCIA, YYMMDDD10.));
	CALL SYMPUT('DT_INICIO_SQL', COMPRESS(DT_INICIO_SQL,' '));
	CALL SYMPUT('DT_1DIA_MES_SQL', COMPRESS(DT_1DIA_MES_SQL,' '));
	CALL SYMPUT('DT_D1_SQL', COMPRESS(DT_D1_SQL,' '));
	CALL SYMPUT('DT_ANOMES_SQL', COMPRESS(DT_ANOMES_SQL,' '));
	CALL SYMPUT('MES_G', COMPRESS(MES_G,' '));
	CALL SYMPUT('PRIMEIRO_DIA_MES_SQL', COMPRESS(PRIMEIRO_DIA_MES_SQL,' '));
	CALL SYMPUT('MMAAAA', COMPRESS(MMAAAA,' '));
RUN;

LIBNAME MOB "/dados/infor/conexao/2018/000000010";
LIBNAME MOB96 "/dados/infor/conexao/2018/000000096";





%BuscarOrcado(IND=10, MMAAAA=032018);



DATA SEGURO_V10;
SET MOB.INDICADOR_000000010;
WHERE IND=10 AND COMP=27 AND CTRA=0;
RUN;
%zerarmissingtabela(SEGURO_V10);


DATA SEGURO_V96;
SET MOB96.INDICADOR_000000096;
WHERE IND=96 AND COMP=27 AND CTRA=0;
RUN;
%zerarmissingtabela(SEGURO_V96);



DATA SEGURO_VIDA;
SET SEGURO_V10 SEGURO_V96;
RUN;
%zerarmissingtabela(SEGURO_VIDA);



DATA SEGURO_RURAL;
SET MOB.INDICADOR_000000010;
WHERE IND=10 AND COMP=2 AND CTRA=0;
RUN;
%zerarmissingtabela(SEGURO_RURAL);


DATA SEGURIDADE; /*componente seguros*/
SET MOB.INDICADOR_000000010;
WHERE IND=10 AND COMP=1 AND CTRA=0;
RUN;
%zerarmissingtabela(SEGURIDADE);



PROC SQL;
   CREATE TABLE VIDA_01 AS 
   SELECT DISTINCT 
          t1.PREFDEP, 
          t1.CTRA, 
		 (RM01+RM02+RM03) AS VL_RLZD_VIDA,
		 (OM01+OM02+OM03) AS VL_ORC_VIDA
      FROM WORK.SEGURO_VIDA t1
GROUP BY 1,2;
QUIT;


PROC SQL;
   CREATE TABLE WORK.VIDA_02 AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
		  SUM(VL_ORC_VIDA) AS VL_ORC_VIDA,
		  SUM(VL_RLZD_VIDA) AS VL_RLZD_VIDA
      FROM WORK.VIDA_01 t1
GROUP BY 1,2;
QUIT;


PROC SQL;
   CREATE TABLE WORK.VIDA_03 AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
		  VL_ORC_VIDA,
		  VL_RLZD_VIDA,
          (VL_RLZD_VIDA/VL_ORC_VIDA)*100 AS PC_ATG_VIDA 
      FROM WORK.VIDA_02 t1;
QUIT;
%zerarmissingtabela(VIDA_03);
/*componente seguros*/

PROC SQL;
   CREATE TABLE SEGURIDADE_DEPE AS 
   SELECT DISTINCT 
          t1.PREFDEP, 
          t1.CTRA, 
          t1.RM01, 
          t1.RM02, 
          t1.RM03, 
          t1.OM01, 
          t1.OM02, 
          t1.OM03
      FROM WORK.SEGURIDADE t1;
QUIT;


PROC SQL;
   CREATE TABLE SEGURIDADE_01 AS 
   SELECT DISTINCT 
          t1.PREFDEP, 
          t1.CTRA, 
		 (RM01+RM02+RM03) AS VL_RLZD_SEG,
		 (OM01+OM02+OM03) AS VL_ORC_SEG
      FROM WORK.SEGURIDADE_DEPE t1
GROUP BY 1,2;
QUIT;



PROC SQL;
   CREATE TABLE SEGURIDADE_02 AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
          t1.VL_RLZD_SEG, 
          t1.VL_ORC_SEG,
          (VL_RLZD_SEG/VL_ORC_SEG)*100 AS PC_ATG_SEG
      FROM WORK.SEGURIDADE_01 t1;
QUIT;




PROC SQL;
   CREATE TABLE SEGURIDADE_03 AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
          t1.VL_ORC_SEG, 
          t1.VL_RLZD_SEG, 
          t1.PC_ATG_SEG,
		  IFN(PC_ATG_SEG>=100,1,0) AS HAB_SEG
      FROM WORK.SEGURIDADE_02 t1
ORDER BY 1;
QUIT;
%zerarmissingtabela(SEGURIDADE_03);

/*Para dependências que não possuem orçado em Seguros Rurais habilitar - email Kelly Tamie Yoshino 14/03/2018- 14h35*/

PROC SQL;
   CREATE TABLE RURAL_01 AS 
   SELECT DISTINCT 
          t1.PREFDEP, 
          t1.CTRA, 
		 (RM01+RM02+RM03) AS VL_RLZD_RURAL,
		 (OM01+OM02+OM03) AS VL_ORC_RURAL
      FROM WORK.SEGURO_RURAL t1
GROUP BY 1,2;
QUIT;


PROC SQL;
   CREATE TABLE RURAL_02 AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
          t1.VL_RLZD_RURAL, 
          t1.VL_ORC_RURAL,
		  (VL_RLZD_RURAL/VL_ORC_RURAL)*100 AS PC_ATG_RURAL 
      FROM WORK.RURAL_01 t1;
QUIT;


PROC SQL;
   CREATE TABLE RURAL_03 AS 
   SELECT t1.PREFDEP, 
          t1.CTRA, 
          t1.VL_RLZD_RURAL, 
          t1.VL_ORC_RURAL,
		  t1.PC_ATG_RURAL,
		  IFN(PC_ATG_RURAL>=100,1,
		  IFN(VL_ORC_RURAL=0,1,0)) AS HAB_RURAL 
      FROM WORK.RURAL_02 t1
ORDER BY 1;
QUIT;
%zerarmissingtabela(RURAL_03);



PROC SQL;
   CREATE TABLE PLCR_APRD_UOR AS 
   SELECT 
   		INPUT(t2.prefdep,4.) AS PREFDEP,
		0 AS CTRA,
          t1.CD_UOR_AVLD, 
          ifn(QT_PTO_PLCR_APRD>=1000,1,0) as HAB_PLCAR
      FROM DB2ATB.PLCR_APRD_UOR t1
	  INNER JOIN IGR.DEPENDENCIAS_201803 T2 ON (T1.CD_UOR_AVLD=INPUT(T2.UOR,9.))
WHERE t1.AA_APRC_PLCR_AVLC=2018 AND t1.MM_APRC_PLCR_AVLC=3
ORDER BY 1;
QUIT;
%zerarmissingtabela(PLCR_APRD_UOR);


DATA JUNTA_COMP;
MERGE VIDA_03 SEGURIDADE_03 RURAL_03 PLCR_APRD_UOR;
BY PREFDEP CTRA;
RUN;
%zerarmissingtabela(JUNTA_COMP);



data ESCR;
SET IGR.DEPENDENCIAS_201803;
WHERE SB='00' AND NomeDep CONTAINS 'ESCR.MPE';
RUN;


data ESC;
SET IGR.DEPENDENCIAS_201803;
WHERE SB='00' AND NomeDep CONTAINS 'ESC.MPE';
RUN;


data EMPRESA;
SET IGR.DEPENDENCIAS_201803;
WHERE SB='00' AND NomeDep CONTAINS 'EMPRESA';
RUN;


data ESCRITORIO;
SET IGR.DEPENDENCIAS_201803;
WHERE SB='00' AND NomeDep CONTAINS 'ESCRITORIO MPE';
RUN;



DATA EXCLUSAO;
SET ESCR ESC EMPRESA ESCRITORIO;
RUN;



PROC SQL;
   CREATE TABLE JUNTA_COMP_01 AS             /*TIRA PAA*/
   SELECT DISTINCT t1.PREFDEP, 
          t1.VL_ORC_VIDA, 
          t1.VL_RLZD_VIDA, 
          t1.PC_ATG_VIDA, 
          t1.HAB_SEG, 
          ifn(HAB_RURAL=.,1,HAB_RURAL) as HAB_RURAL,
          t1.HAB_PLCAR,
		  (HAB_SEG+HAB_ruraL+HAB_PLCAR) as habilitado
      FROM WORK.JUNTA_COMP t1
	  INNER JOIN IGR.DEPENDENCIAS_201803 T2 ON (T1.PREFDEP=INPUT(T2.PREFDEP,4.))
 left JOIN EXCLUSAO T3 ON (T1.PREFDEP=INPUT(T3.PREFDEP,4.))
	  WHERE T2.SB='00' AND T2.TIPODEP NE '015' AND INPUT(T3.PREFDEP,4.) IS MISSING
group by 1;
QUIT;
%zerarmissingtabela(JUNTA_COMP_01);


PROC SQL;
   CREATE TABLE JUNTA_COMP_02 AS             /*TIRA PAA*/
   SELECT DISTINCT t1.PREFDEP, 
          t1.VL_ORC_VIDA, 
          t1.VL_RLZD_VIDA, 
          t1.PC_ATG_VIDA, 
          t1.HAB_SEG, 
          T1.HAB_RURAL,
          t1.HAB_PLCAR,
		  (HAB_SEG+HAB_ruraL+HAB_PLCAR) as habilitado
      FROM WORK.JUNTA_COMP_01 t1
	  group by 1;
QUIT;


PROC SQL;
   CREATE TABLE junt_comp_03 AS 
   SELECT 
      &DATA_FIM. FORMAT=DateMysql. as posicao,
t1.PREFDEP, 
          t1.VL_ORC_VIDA, 
          t1.VL_RLZD_VIDA, 
          t1.PC_ATG_VIDA, 
          t1.HAB_SEG, 
          t1.HAB_RURAL, 
          t1.HAB_PLCAR,
		  ifn(habilitado=3,1,0) as habilitado
      FROM WORK.JUNTA_COMP_02 t1
	  INNER JOIN IGR.DEPENDENCIAS_201803 T2 ON (T1.PREFDEP=INPUT(T2.PREFDEP,4.))
	  WHERE T2.SB='00' AND T2.nivel not in ('4','5','6') AND t1.PREFDEP NOT IN (1897,5905,4203,9538,8584,8481)
      ORDER BY t1.habilitado DESC;
QUIT;



/*Relatório 239*/

%LET Usuario=f9457977;
%LET Keypass= ISnKcnidhNnos3NgZ05dek3xanP1pTEZoPQOEgSBXy3D61pw8n;

/*rotina-111*/
PROC SQL;
DROP TABLE TABELAS_EXPORTAR_REL;
CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
INSERT INTO TABELAS_EXPORTAR_REL VALUES('junt_comp_03', 'mobb');
QUIT;

%ExportarREL(TABELAS_EXPORTAR_REL, Usuario=&Usuario., Keypass=&Keypass.);


/**/
/*Agência Estilo\Escritório Estilo;*/
/*Escritório Exclusivo;*/
/*Varejo Nível 1;*/
/*Varejo Nível 2;*/
/*Varejo Nível 3;*/
