/*ACEITE - sem alteração*/
/**/
/*NÃO ACEITE*/
/**/
/*    Irá Analisar*/
/*        Alta propensão*/
/*        Média propensão*/
/*    Limite de Crédito Insuficiente*/
/*    Taxa ou Tarifa Elevada*/
/**/
/*Todas as opões acima já existem na tabela utilizada pela Gecen. Bastaria capturar as informações.*/
/**/
/*Acredito que podem ser um ótimo subsídio para ações de visitação e retorno dos contatos.*/
%include '/dados/infor/suporte/FuncoesInfor.sas';
LIBNAME OGC '/dados/infor/producao/ofertas_AmpliaNegociosPJ';
LIBNAME DB2BIC 	db2 AUTHDOMAIN=DB2SGCEN schema=DB2BIC database=BDB2P04;
LIBNAME DB2PRD 	db2 AUTHDOMAIN=DB2SGCEN schema=DB2PRD database=BDB2P04;
LIBNAME DB2REL 	db2 AUTHDOMAIN=DB2SGCEN schema=DB2REL database=BDB2P04;
LIBNAME DB2COC 	db2 AUTHDOMAIN=DB2SGCEN schema=DB2COC database=BDB2P04;






%LET Mes=0;


DATA _NULL_;
	IF &Mes=0 THEN
		D1=DiaUtilAnterior(Today());
	ELSE
		DO;
			AA=Floor(&Mes/100);
			MM=&Mes-(AA*100);
			DD=IntNx('month',MDY(MM,1,AA),1);
			D1=DiaUtilAnterior(Smallest(1,DD,Today()));
		END;

	CALL SYMPUT('D1',D1);
	CALL SYMPUT('AnoMes',Put(D1, yymmn6.));
	CALL SYMPUT('MesAno',Put(D1, mmyyn6.));
	CALL SYMPUT('D1',D1);
RUN;

%Put &AnoMes &MesAno &D1;

libname db2coc db2  schema="DB2COC" database=BDB2P04 AUTHDOMAIN="DB2SGCEN";


/*Alterado o público conforme email recebido dia 16/08/2018 às 10h34 matrícula f3233886*/


PROC SQL;
   CREATE TABLE OGC.Clientes_acao_perfil_20180821 AS
   SELECT DISTINCT
          t2.CD_ACAO,
          t2.NM_ACAO,
          t2.DT_INC_VGC_ACAO,
          t2.DT_FIM_VGC_ACAO,
          t3.CD_BLOC,
          t3.NM_BLOC,
          t1.CD_CLI
      FROM DB2COC.CLI_VCLD_BLOC t1, DB2COC.ACAO_CMCO t2, DB2COC.BLOC_ACAO t3
      WHERE (t1.CD_ACAO = t2.CD_ACAO AND t1.CD_ACAO = t3.CD_ACAO AND t1.CD_BLOC = t3.CD_BLOC)
        AND
           t1.CD_ACAO IN (18401,18486,18495);
QUIT;



PROC SQL;
   CREATE TABLE PUBLICO_a AS 
   SELECT cd_acao,
          input(substr(t1.nm_bloc,1,4), 2.) as perfil,
          t1.CD_CLI
      FROM OGC.CLIENTES_ACAO_PERFIL_20180821 t1
	  where cd_acao ne 18495
;
QUIT;




PROC SQL;
   CREATE TABLE PUBLICO_b AS 
   SELECT 18320 as cd_acao,
          0 as perfil,
          t1.MCI AS CD_CLI
      FROM OGC.PUBLICO_B t1
;
QUIT;


PROC SQL;
   CREATE TABLE PUBLICO_B2 AS 
   SELECT distinct 
          T1.CD_ACAO,
          input(substr(t1.nm_bloc,1,4), 2.) as perfil,
          t1.CD_CLI,
		  IFN(T2.CD_CLI=.,0,1) AS CONVENIO
      FROM OGC.CLIENTES_ACAO_PERFIL_20180821 t1
	  LEFT JOIN PUBLICO_B T2 ON (T1.CD_CLI=T2.CD_CLI)
	  where T1.cd_acao = (18495)
;
QUIT;



data junta_publico;
set publico_b2 publico_a;
run;
PROC SORT DATA=junta_publico NODUPKEY; BY _ALL_; RUN;


PROC SORT DATA=junta_publico out=BASE_MCI (DROP=perfil) NODUPKEY;
	BY CD_CLI
;
;
RUN;
PROC SORT DATA=BASE_MCI NODUPKEY; BY _ALL_; RUN;



%MACRO TRANSPOSE_PERFIL();
	%LET TABELAS=;
	%let name_list=0 1 2 3 4 5 6 7 8 9 10 11 12;
	%local i next_name;
	%let i=1;

	%do %while (%scan(&name_list, &i) ne );
		%let next_name = %scan(&name_list, &i);

		DATA PUBLICO_&next_name. (DROP=PERFIL);
			SET JUNTA_PUBLICO;
			pfl_&next_name.=1;
			WHERE perfil=&next_name.;
		RUN;

		PROC SORT DATA=PUBLICO_&next_name. NODUPKEY;
			BY cd_cli;
		QUIT;

		%LET TABELAS = &TABELAS. PUBLICO_&next_name.;
		%let i = %eval(&i + 1);
	%end;

	DATA PUBLICO_PERFIL;
		MERGE &TABELAS.;
		BY cd_cli;
	RUN;

	%ZerarMissingTabela(PUBLICO_PERFIL);

	PROC DELETE DATA=&TABELAS.;
	RUN;

%MEND TRANSPOSE_PERFIL;

%TRANSPOSE_PERFIL();




%Macro Encarteiramento;

	PROC SQL;
		CREATE INDEX CD_CLI ON BASE_MCI(CD_CLI);
		CREATE TABLE ENCARTEIRAMENTO AS 
        SELECT Put(CD_PRF_DEPE, Z4.) AS PrefDep,
                NR_SEQL_CTRA_atb as carteira,
                case when NR_SEQL_CTRA_atb = 7002 then 700 else CD_TIP_CTRA end as tc,
                E.CD_CLI
			FROM COMUM.PAI_REL_PJ_&AnoMes A
				INNER JOIN BASE_MCI B ON(A.CD_CLI=B.CD_CLI)
					WHERE CD_PRF_DEPE NOT IN(4777 8008 9940);
		CREATE INDEX CD_CLI ON ENCARTEIRAMENTO(CD_CLI);
	QUIT;

	PROC SQL NOPRINT;
		SELECT COUNT(*) INTO :Q
			FROM (SELECT CD_CLI
			FROM ENCARTEIRAMENTO
				GROUP BY 1
					HAVING COUNT(*)>1);
	QUIT;

	%Put &Q;

	%IF &Q>0 %THEN
		%DO;

			DATA DUPLICADOS;
				SET ENCARTEIRAMENTO(Obs=0);
			RUN;

			PROC SQL;
				CREATE TABLE AUX_D AS
					SELECT CD_CLI
						FROM ENCARTEIRAMENTO
							GROUP BY 1
								HAVING COUNT(*)>1;
			RUN;

			DATA AUX_D(DROP=Seq);
				SET AUX_D;
				Seq+1;
				Grupo=CEIL(Seq/5957);
			RUN;

			PROC SQL NOPRINT;
				SELECT MAX(Grupo) INTO: Q
					FROM AUX_D;
			QUIT;

			%PUT &Q;

			%DO I=1 %TO &Q;

				PROC SQL NOPRINT;
					SELECT CD_CLI INTO: Var Separated By ', '
						FROM AUX_D
							WHERE Grupo=&I;
				QUIT;

				PROC SQL;
					CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
					INSERT INTO DUPLICADOS
						SELECT A.*, Carteira, TC
							FROM CONNECTION TO DB2
								(SELECT COD, COD_PREF_AGEN
									FROM DB2MCI.CLIENTE
										WHERE COD IN(&Var)
											ORDER BY COD;) A
												INNER JOIN ENCARTEIRAMENTO B ON(A.COD=B.CD_CLI AND A.COD_PREF_AGEN=B.PrefDep);
					DISCONNECT FROM DB2;
				QUIT;

				DATA ENCARTEIRAMENTO;
					SET ENCARTEIRAMENTO(WHERE=(CD_CLI NOT IN(&Var.)));
					BY CD_CLI;
				RUN;

			%END;

			PROC SORT DATA=DUPLICADOS;
				BY CD_CLI;
			RUN;

			DATA ENCARTEIRAMENTO;
				SET ENCARTEIRAMENTO DUPLICADOS;
				BY CD_CLI;
			RUN;

			PROC DELETE DATA=DUPLICADOS AUX_D;
			RUN;

		%END;

	PROC SQL NOPRINT;
		SELECT COUNT(*) INTO: Q
			FROM (SELECT DISTINCT A.CD_CLI
			FROM BASE_MCI A
				LEFT JOIN ENCARTEIRAMENTO B ON(A.CD_CLI=B.CD_CLI)
					WHERE B.CD_CLI Is Missing);
	QUIT;

	%Put &Q;

	%IF &Q>0 %THEN
		%DO;

			DATA PERDIDOS;
				SET ENCARTEIRAMENTO(Obs=0);
			RUN;

			PROC SQL;
				CREATE TABLE AUX_P AS
					SELECT DISTINCT A.CD_CLI
						FROM BASE_MCI A
							LEFT JOIN ENCARTEIRAMENTO B ON(A.CD_CLI=B.CD_CLI)
								WHERE B.CD_CLI Is Missing;
			RUN;

			DATA AUX_P(DROP=Seq);
				SET AUX_P;
				Seq+1;
				Grupo=CEIL(Seq/5957);
			RUN;

			PROC SQL NOPRINT;
				SELECT MAX(Grupo) INTO: Q
					FROM AUX_P;
			QUIT;

			%PUT &Q;

			%DO I=1 %TO &Q;

				PROC SQL NOPRINT;
					SELECT CD_CLI Format 9. INTO: Var Separated By ', '
						FROM AUX_P
							WHERE Grupo=&I;
				QUIT;

				PROC SQL;
					CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
					INSERT INTO PERDIDOS
						SELECT *
							FROM CONNECTION TO DB2
								(SELECT COD AS CD_CLI, COD_PREF_AGEN AS PREFIXO, 
									7002 AS CARTEIRA, 700 AS TC
								FROM DB2MCI.CLIENTE
									WHERE COD IN(&Var)
										ORDER BY COD;);
					DISCONNECT FROM DB2;
				QUIT;

			%END;

			DATA ENCARTEIRAMENTO;
				SET ENCARTEIRAMENTO PERDIDOS;
				BY CD_CLI;
			RUN;

			PROC DELETE DATA=AUX_P PERDIDOS;
			RUN;

		%END;

	PROC SQL NOPRINT;
		SELECT Input(PrefDep,4.) INTO: Var Separated By ' '
			FROM IGR.IGRREDE_&AnoMes
				WHERE PrefDep NE '4777' AND TipoDep In('01' '09') AND PrefSupEst NE '8481';
	QUIT;

	DATA ENCARTEIRAMENTO;
		SET ENCARTEIRAMENTO(WHERE=(PrefDep IN(&Var.)));

		IF TC NOT IN(303 304 315 328) THEN
			DELETE;
	RUN;

%Mend;

%Encarteiramento;

DATA ENCARTEIRAMENTO;
	SET ENCARTEIRAMENTO;

	IF TC=304 THEN
		DO;
			Carteira=7002;
			TC=700;
		END;
RUN;







%Macro Contatos;

	DATA _NULL_;
		SET OGC.O18002;
		CALL SYMPUT('Executa',DT NE Today());
	RUN;

	%Put &Executa;

	%IF &Executa=1 %THEN
		%DO;

		

			PROC SQL;
				CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
				EXECUTE (SET CURRENT QUERY ACCELERATION NONE) BY DB2;
				CREATE TABLE CONTATOS_ACM_I AS 
					SELECT *
						FROM CONNECTION TO DB2
							(SELECT D.CD_CLI, DATE(D.TS_INRO_CLI) AS DT_CTT, TX_RSTD_INRO, TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, F.CD_PRD, F.QT_ITEM_VCLD_INRO
								FROM DB2BIC.INRO_HMNO_CLI D
									INNER JOIN (SELECT A.CD_CLI, MAX(TS_INRO_CLI) AS MD
										FROM DB2BIC.INRO_HMNO_CLI A
											INNER JOIN DB2MCI.CLIENTE C ON(A.CD_CLI=C.COD)
												WHERE DATE(TS_INRO_CLI)>='2018-08-01' 
												AND ((CD_ASNT_INRO=56 AND CD_SUB_ASNT_INRO=1)) AND C.COD_TIPO=2
												GROUP BY A.CD_CLI) E ON(D.CD_CLI=E.CD_CLI AND D.TS_INRO_CLI=E.MD)
													INNER JOIN DB2BIC.AUX_INRO_CLI_Atu F ON(D.CD_CLI=F.CD_CLI AND D.TS_INRO_CLI=F.TS_INRO_CLI)
													INNER JOIN DB2BIC.SUB_RSTD_INRO G ON(F.CD_RSTD_INRO=G.CD_RSTD_INRO AND F.CD_SUB_RSTD_INRO=G.CD_SUB_RSTD_INRO)
													INNER JOIN DB2BIC.RSTD_INRO H ON(F.CD_RSTD_INRO=H.CD_RSTD_INRO)
													WHERE QT_ITEM_VCLD_INRO IN (18320, 18495));
			QUIT;


			PROC SQL;
				CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
				EXECUTE (SET CURRENT QUERY ACCELERATION NONE) BY DB2;
				CREATE TABLE CONTATOS_ACM_II AS 
					SELECT *
						FROM CONNECTION TO DB2
							(SELECT D.CD_CLI, DATE(D.TS_INRO_CLI) AS DT_CTT, TX_RSTD_INRO, TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, F.CD_PRD, F.QT_ITEM_VCLD_INRO
								FROM DB2BIC.INRO_HMNO_CLI D
									INNER JOIN (SELECT A.CD_CLI, max(TS_INRO_CLI) AS MD
										FROM DB2BIC.INRO_HMNO_CLI A
											INNER JOIN DB2MCI.CLIENTE C ON(A.CD_CLI=C.COD)
												WHERE DATE(TS_INRO_CLI)>='2018-08-01' 
													AND ((CD_ASNT_INRO=56 AND CD_SUB_ASNT_INRO=1)) AND C.COD_TIPO=2
												GROUP BY A.CD_CLI) E ON(D.CD_CLI=E.CD_CLI AND D.TS_INRO_CLI=E.MD)
													INNER JOIN DB2BIC.AUX_INRO_CLI_ATU F ON(D.CD_CLI=F.CD_CLI AND D.TS_INRO_CLI=F.TS_INRO_CLI)
													INNER JOIN DB2BIC.SUB_RSTD_INRO G ON(F.CD_RSTD_INRO=G.CD_RSTD_INRO AND F.CD_SUB_RSTD_INRO=G.CD_SUB_RSTD_INRO)
													INNER JOIN DB2BIC.RSTD_INRO H ON(F.CD_RSTD_INRO=H.CD_RSTD_INRO)
													WHERE QT_ITEM_VCLD_INRO IN (18003, 18486));
			QUIT;



			PROC SQL;
				CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
				EXECUTE (SET CURRENT QUERY ACCELERATION NONE) BY DB2;
				CREATE TABLE CONTATOS_ACM_III AS 
					SELECT *
						FROM CONNECTION TO DB2
							(SELECT D.CD_CLI, DATE(D.TS_INRO_CLI) AS DT_CTT, TX_RSTD_INRO, TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, F.CD_PRD, F.QT_ITEM_VCLD_INRO
								FROM DB2BIC.INRO_HMNO_CLI D
									INNER JOIN (SELECT A.CD_CLI, max(TS_INRO_CLI) AS MD
										FROM DB2BIC.INRO_HMNO_CLI A
											INNER JOIN DB2MCI.CLIENTE C ON(A.CD_CLI=C.COD)
												WHERE DATE(TS_INRO_CLI)>='2018-08-01' 
													AND ((CD_ASNT_INRO=56 AND CD_SUB_ASNT_INRO=1)) AND C.COD_TIPO=2
												GROUP BY A.CD_CLI) E ON(D.CD_CLI=E.CD_CLI AND D.TS_INRO_CLI=E.MD)
													INNER JOIN DB2BIC.AUX_INRO_CLI_ATU F ON(D.CD_CLI=F.CD_CLI AND D.TS_INRO_CLI=F.TS_INRO_CLI)
													INNER JOIN DB2BIC.SUB_RSTD_INRO G ON(F.CD_RSTD_INRO=G.CD_RSTD_INRO AND F.CD_SUB_RSTD_INRO=G.CD_SUB_RSTD_INRO)
													INNER JOIN DB2BIC.RSTD_INRO H ON(F.CD_RSTD_INRO=H.CD_RSTD_INRO)
													WHERE QT_ITEM_VCLD_INRO IN (18103, 18401));
			QUIT;


			DATA OGC.O18002;
				DT=Today();
			RUN;

		%END;


PROC SQL;
		CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
		EXECUTE (SET CURRENT QUERY ACCELERATION NONE) BY DB2;
		CREATE TABLE CONTATOS_ACM_V AS 
			SELECT *
				FROM CONNECTION TO DB2
					(SELECT D.CD_CLI, DATE(D.TS_INRO_CLI) AS DT_CTT, TX_RSTD_INRO, TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, F.CD_PRD, F.QT_ITEM_VCLD_INRO
						FROM DB2BIC.INRO_HMNO_CLI D
							INNER JOIN (SELECT A.CD_CLI, MIN(TS_INRO_CLI) AS MD
								FROM DB2BIC.INRO_HMNO_CLI A
									INNER JOIN DB2MCI.CLIENTE C ON(A.CD_CLI=C.COD)
										WHERE DATE(TS_INRO_CLI)>='2018-08-01'
											AND ((CD_ASNT_INRO=56 AND CD_SUB_ASNT_INRO=1))
										GROUP BY A.CD_CLI) E ON(D.CD_CLI=E.CD_CLI AND D.TS_INRO_CLI=E.MD)
											INNER JOIN DB2BIC.AUX_INRO_CLI_ANT F ON(D.CD_CLI=F.CD_CLI AND D.TS_INRO_CLI=F.TS_INRO_CLI)
											INNER JOIN DB2BIC.SUB_RSTD_INRO G ON(F.CD_RSTD_INRO=G.CD_RSTD_INRO AND F.CD_SUB_RSTD_INRO=G.CD_SUB_RSTD_INRO)
											INNER JOIN DB2BIC.RSTD_INRO H ON(F.CD_RSTD_INRO=H.CD_RSTD_INRO)
WHERE QT_ITEM_VCLD_INRO IN (18320, 18495));
	QUIT;

	
PROC SQL;
		CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
		EXECUTE (SET CURRENT QUERY ACCELERATION NONE) BY DB2;
		CREATE TABLE CONTATOS_ACM_VI AS 
			SELECT *
				FROM CONNECTION TO DB2
					(SELECT D.CD_CLI, DATE(D.TS_INRO_CLI) AS DT_CTT, TX_RSTD_INRO, TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, F.CD_PRD, F.QT_ITEM_VCLD_INRO
						FROM DB2BIC.INRO_HMNO_CLI D
							INNER JOIN (SELECT A.CD_CLI, MAX(TS_INRO_CLI) AS MD
								FROM DB2BIC.INRO_HMNO_CLI A
									INNER JOIN DB2MCI.CLIENTE C ON(A.CD_CLI=C.COD)
										WHERE DATE(TS_INRO_CLI)>='2018-08-01'
											AND ((CD_ASNT_INRO=56 AND CD_SUB_ASNT_INRO=1)) AND C.COD_TIPO=2
										GROUP BY A.CD_CLI) E ON(D.CD_CLI=E.CD_CLI AND D.TS_INRO_CLI=E.MD)
											INNER JOIN DB2BIC.AUX_INRO_CLI_ANT F ON(D.CD_CLI=F.CD_CLI AND D.TS_INRO_CLI=F.TS_INRO_CLI)
											INNER JOIN DB2BIC.SUB_RSTD_INRO G ON(F.CD_RSTD_INRO=G.CD_RSTD_INRO AND F.CD_SUB_RSTD_INRO=G.CD_SUB_RSTD_INRO)
											INNER JOIN DB2BIC.RSTD_INRO H ON(F.CD_RSTD_INRO=H.CD_RSTD_INRO)
WHERE QT_ITEM_VCLD_INRO IN (18003, 18486));
	QUIT;
	
PROC SQL;
		CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
		EXECUTE (SET CURRENT QUERY ACCELERATION NONE) BY DB2;
		CREATE TABLE CONTATOS_ACM_VII AS 
			SELECT *
				FROM CONNECTION TO DB2
					(SELECT D.CD_CLI, DATE(D.TS_INRO_CLI) AS DT_CTT, TX_RSTD_INRO, TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, F.CD_PRD, F.QT_ITEM_VCLD_INRO
						FROM DB2BIC.INRO_HMNO_CLI D
							INNER JOIN (SELECT A.CD_CLI, MAX(TS_INRO_CLI) AS MD
								FROM DB2BIC.INRO_HMNO_CLI A
									INNER JOIN DB2MCI.CLIENTE C ON(A.CD_CLI=C.COD)
										WHERE DATE(TS_INRO_CLI)>='2018-08-01'
											AND ((CD_ASNT_INRO=56 AND CD_SUB_ASNT_INRO=1)) AND C.COD_TIPO=2
										GROUP BY A.CD_CLI) E ON(D.CD_CLI=E.CD_CLI AND D.TS_INRO_CLI=E.MD)
											INNER JOIN DB2BIC.AUX_INRO_CLI_ANT F ON(D.CD_CLI=F.CD_CLI AND D.TS_INRO_CLI=F.TS_INRO_CLI)
											INNER JOIN DB2BIC.SUB_RSTD_INRO G ON(F.CD_RSTD_INRO=G.CD_RSTD_INRO AND F.CD_SUB_RSTD_INRO=G.CD_SUB_RSTD_INRO)
											INNER JOIN DB2BIC.RSTD_INRO H ON(F.CD_RSTD_INRO=H.CD_RSTD_INRO)
WHERE QT_ITEM_VCLD_INRO IN (18103, 18401));
	QUIT;


	%IF &Executa=1 %THEN
		%DO;

			PROC SQL;
	CREATE TABLE CONTATOS_ACM_IV AS
		SELECT *
			FROM CONTATOS_ACM_I
				UNION
			SELECT *
				FROM CONTATOS_ACM_II
					UNION
				SELECT *
					FROM CONTATOS_ACM_III
						UNION
					SELECT *
						FROM CONTATOS_ACM_V
							UNION
						SELECT *
							FROM CONTATOS_ACM_VI
								UNION
							SELECT *
								FROM CONTATOS_ACM_VII;
QUIT;

		%END;
	%ELSE
		%DO;

			DATA OGC.CONTATOS_ACM_IV;
				SET CONTATOS_ACM_IV OGC.CONTATOS_ACM_X  ogc.contatos_18;
				WHERE QT_ITEM_VCLD_INRO IN (18320,18495,18003, 18486, 18103, 18401);

			RUN;

		%END;
%Mend;

%Contatos;


PROC SQL;
	CREATE TABLE CONTATOS AS
		SELECT A.*
			FROM OGC.CONTATOS_ACM_IV A
				INNER JOIN (SELECT CD_CLI, MAX(DT_CTT) AS DT
					FROM OGC.CONTATOS_ACM_IV
						GROUP BY 1) B ON(A.CD_CLI=B.CD_CLI AND A.DT_CTT=B.DT)
							ORDER BY 1;
QUIT;


PROC SQL;
	DROP TABLE DB2SGCEN.AFCO_180723;
	CREATE TABLE DB2SGCEN.AFCO_180723 AS
		SELECT DISTINCT A.CD_CLI Format Z20.
			FROM CONTATOS A
				INNER JOIN BASE_MCI B ON(A.CD_CLI=B.CD_CLI)
					ORDER BY 1;
QUIT;

PROC SQL;
	CONNECT TO DB2 (AUTHDOMAIN=DB2SGCEN DATABASE=BDB2P04);
	CREATE TABLE PROPOSTAS_BASE AS
		SELECT DISTINCT *
			FROM CONNECTION TO DB2
				(SELECT DISTINCT t2.CD_CLI,
					t2.DTA_PROP,
					t2.NRO_PROP,
					t2.COD_SITU_PROP,
					t2.IND_PROP_DEFE,
					t2.DTA_PROP,
					t7.VLR_PROP_ITEM_FINC,
					t2.COD_LNCR,
					DIGITS(NRO_OPER_BASE_OPR) AS NR_UNCO
				FROM DB2COP.TCOP183 T2
					INNER JOIN DB2SGCEN.AFCO_180723 t0 ON(t2.CD_CLI=t0.CD_CLI)
					INNER JOIN DB2COP.TCOP117 T7 ON (T2.NRO_PROP = T7.NRO_PROP)
						LEFT JOIN DB2COP.TCOP100 t8 ON(t2.NRO_PROP=t8.NRO_PROP)
							WHERE T2.COD_LNCR IN(65, 74, 466)/*=466*/
								AND T7.VLR_PROP_ITEM_FINC>0
								AND t2.DTA_PROP>='2018-07-23'
							ORDER BY t2.NRO_PROP);
	DISCONNECT FROM DB2;
	DROP TABLE DB2SGCEN.AFCO_180723;
QUIT;

DATA PROPOSTAS_BASE_T(WHERE=(ORDEM NE 0));
	SET PROPOSTAS_BASE(WHERE=(COD_SITU_PROP NE 8));
	Format SITU $ 90.;

	IF COD_SITU_PROP = 001 THEN
		DO;
			SITU = 'EM ACOLHIMENTO';
			ORDEM = 1;
		END;

	IF COD_SITU_PROP = 002 THEN
		DO;
			SITU = 'ACOLHIDA';
			ORDEM = 2;
		END;

	IF COD_SITU_PROP = 003 THEN
		DO;
			SITU = 'ANALISADA';
			ORDEM = 3;
		END;

	IF COD_SITU_PROP = 004 THEN
		DO;
			SITU = 'DESPACHADA';
			ORDEM = 4;
		END;

	IF COD_SITU_PROP = 005 THEN
		DO;
			IF NR_UNCO='' THEN
				DO;
					SITU = 'FORMALIZADA';
					ORDEM = 5;
				END;
			ELSE
				DO;
					SITU='LIBERADA';
					ORDEM=6;
				END;
		END;

	IF COD_SITU_PROP = 006 THEN
		DO;
			SITU = 'CANCELADA';
			ORDEM = 0;
		END;
RUN;

PROC SORT DATA=PROPOSTAS_BASE_T;
	BY CD_CLI;
RUN;


PROC SORT DATA=ENCARTEIRAMENTO;
	BY CD_CLI;
RUN;


DATA PROPOSTAS_BASE_T;
	MERGE ENCARTEIRAMENTO(IN=A) PROPOSTAS_BASE_T;
	BY CD_CLI;

	IF A;
RUN;




PROC SQL;
	CREATE TABLE RESUMO_PROP_CLI AS
		SELECT PrefDep, IFN(TC = 304,7002,Carteira) AS Carteira, 
			CD_CLI, ORDEM, SUM(VLR_PROP_ITEM_FINC) AS VLR_PROPOSTA
		FROM PROPOSTAS_BASE_T
			GROUP BY 3, 1, 2, 4;
QUIT;

PROC TRANSPOSE DATA=RESUMO_PROP_CLI PREFIX=P_ OUT=RPC(DROP=_NAME_);
	ID ORDEM;
	VAR VLR_PROPOSTA;
	By CD_CLI PrefDep Carteira;
RUN;

DATA RPC;
	Format CD_CLI 9. PrefDep 4. Carteira 5. P_1 19.2 P_2 19.2 P_3 19.2 P_4 19.2 P_5 19.2 P_6 19.2;
	SET RPC;
	P_1=Coalesce(P_1,0);
	P_2=Coalesce(P_2,0);
	P_3=Coalesce(P_3,0);
	P_4=Coalesce(P_4,0);
	P_5=Coalesce(P_5,0);
	P_6=Coalesce(P_6,0);
RUN;

PROC SQL;
	CREATE TABLE RSM_PROPOSTAS AS
		SELECT CD_CLI, PrefDep, Carteira, 
			Sum(P_1) AS P_1, Sum(P_2) AS P_2,
			Sum(P_3) AS P_3, Sum(P_4) AS P_4,
			Sum(P_5) AS P_5, Sum(P_6) AS P_6
		FROM RPC
			GROUP BY 1, 2, 3;
QUIT;

PROC SQL;
	CREATE TABLE PRP_CRT AS
		SELECT PrefDep, Carteira,
			Sum(P_1) AS P_1, Sum(P_2) AS P_2,
			Sum(P_3) AS P_3, Sum(P_4) AS P_4,
			Sum(P_5) AS P_5, Sum(P_6) AS P_6
		FROM RSM_PROPOSTAS
			GROUP BY 1, 2;
QUIT;

PROC SQL;
	CREATE TABLE CRT AS
		SELECT PrefDep, IFN(TC=304,7002,Carteira) AS Carteira,
			Count(DISTINCT CD_CLI) AS Qtd_Cli
		FROM ENCARTEIRAMENTO
			GROUP BY 1, 2;
QUIT;

PROC SQL;
	CREATE TABLE ABRD AS
		SELECT A.PrefDep, IFN(TC=304,7002,A.Carteira) AS Carteira,
			COUNT(DISTINCT A.CD_CLI) AS QT_ABD, SUM(IFN(TX_RSTD_INRO='Aceitou',1,0)) AS Qt_Aceite,
			SUM((Coalesce(P_6,0)>0) AND (TX_RSTD_INRO='Aceitou')) AS Contratou
		FROM ENCARTEIRAMENTO A
			INNER JOIN CONTATOS B ON(A.CD_CLI=B.CD_CLI)
			INNER JOIN RSM_PROPOSTAS C ON(B.CD_CLI=C.CD_CLI)
				GROUP BY 1, 2;
QUIT;

PROC SQL;
	CREATE TABLE MG_DISP AS
		SELECT PrefDep, IFN(TC=304,7002,Carteira) AS Carteira,
			A.CD_CLI, slim_disp_205 AS MG_DISP, CD_EST_LMCR
		FROM ENCARTEIRAMENTO A
			LEFT JOIN BCN.BCN_PJ B ON(A.CD_CLI=B.MCI)
				ORDER BY 1, 2;
QUIT;

DATA MG_DISP;
	SET MG_DISP;

	IF CD_EST_LMCR NE 10 THEN
		MG_DISP=0;
RUN;

DATA CRT(DROP=Qt_Aceite);
	MERGE CRT ABRD;
	BY PrefDep Carteira;
	QT_ABD=COALESCE(QT_ABD,0);
	PC_ABD=(QT_ABD/Qtd_Cli)*100;
	QT_ACT=COALESCE(Qt_Aceite,0);

	IF QT_ABD=0 THEN
		PC_ACT=0;
	ELSE PC_ACT=(QT_ACT/QT_ABD)*100;
RUN;

PROC SQL;
	CREATE TABLE MARGEM AS
		SELECT PrefDep, Carteira, Sum(MG_DISP) AS MG_DISP
			FROM MG_DISP
				GROUP BY 1, 2;
QUIT;

DATA CRT(DROP=MG_DISP P_1 P_2 P_3 P_4 P_5 P_6);
	Format PrefDep 4. Carteira 5. MD 19.2 VC 19.2;
	MERGE CRT MARGEM PRP_CRT;
	BY PrefDep Carteira;
	MD=Coalesce(MG_DISP,0);
	E1=Coalesce(P_1,0);
	E2=Coalesce(P_2,0);
	E3=Coalesce(P_3,0);
	E4=Coalesce(P_4,0);
	E5=Coalesce(P_5,0);
	E6=Coalesce(P_6,0);
	EF=0;
	VC=E1+E2+E3+E4+E5+E6;
RUN;

PROC SQL;
	CREATE TABLE PAA AS
		SELECT A.PrefDep, 0 AS Carteira, Sum(Qtd_Cli) AS Qtd_Cli,
			Sum(QT_ABD) AS QT_ABD, 0 AS PC_ABD, Sum(QT_ACT) AS QT_ACT, 
			0 AS PC_ACT, Sum(MD) AS MD, Sum(VC) AS VC, Sum(E1) AS E1, 
			Sum(E2) AS E2, Sum(E3) AS E3, Sum(E4) AS E4, Sum(E5) AS E5, 
			Sum(E6) AS E6, 0 AS EF, Sum(Contratou) AS Contratou
		FROM CRT A 
			INNER JOIN IGR.IGRREDE_&AnoMes B ON(A.PrefDep=Input(B.PrefDep, 4.) AND B.TipoDep='01')
				GROUP BY 1;
QUIT;

DATA PAA;
	SET PAA;
	PC_ABD=(QT_ABD/Qtd_Cli)*100;

	IF QT_ABD=0 THEN
		PC_ACT=0;
	ELSE PC_ACT=(QT_ACT/QT_ABD)*100;
RUN;

PROC SQL;
	CREATE TABLE AGC AS
		SELECT IFN(TipoDep='01',Input(PrefAgenc, 4.),A.PrefDep) AS PrefDep,
			0 AS Carteira, Sum(Qtd_Cli) AS Qtd_Cli,
			Sum(QT_ABD) AS QT_ABD, 0 AS PC_ABD, Sum(QT_ACT) AS QT_ACT, 
			0 AS PC_ACT, Sum(MD) AS MD, Sum(VC) AS VC, Sum(E1) AS E1, 
			Sum(E2) AS E2, Sum(E3) AS E3, Sum(E4) AS E4, Sum(E5) AS E5, 
			Sum(E6) AS E6, 0 AS EF, Sum(Contratou) AS Contratou 
		FROM CRT A 
			INNER JOIN IGR.IGRREDE_&AnoMes B ON(A.PrefDep=Input(B.PrefDep, 4.) AND TipoDep In('01' '09'))
				GROUP BY 1;
QUIT;

DATA AGC;
	SET AGC;
	PC_ABD=(QT_ABD/Qtd_Cli)*100;

	IF QT_ABD=0 THEN
		PC_ACT=0;
	ELSE PC_ACT=(QT_ACT/QT_ABD)*100;
RUN;

PROC SQL;
	CREATE TABLE GRV AS
		SELECT Input(PrefSupReg, 4.) AS PrefDep,
			0 AS Carteira, Sum(Qtd_Cli) AS Qtd_Cli,
			Sum(QT_ABD) AS QT_ABD, 0 AS PC_ABD, Sum(QT_ACT) AS QT_ACT, 
			0 AS PC_ACT, Sum(MD) AS MD, Sum(VC) AS VC, Sum(E1) AS E1, 
			Sum(E2) AS E2, Sum(E3) AS E3, Sum(E4) AS E4, Sum(E5) AS E5, 
			Sum(E6) AS E6, 0 AS EF, Sum(Contratou) AS Contratou 
		FROM CRT A 
			INNER JOIN IGR.IGRREDE_&AnoMes B ON(A.PrefDep=Input(B.PrefDep, 4.))
				GROUP BY 1;
QUIT;

DATA GRV;
	SET GRV;
	PC_ABD=(QT_ABD/Qtd_Cli)*100;

	IF QT_ABD=0 THEN
		PC_ACT=0;
	ELSE PC_ACT=(QT_ACT/QT_ABD)*100;
RUN;

PROC SQL;
	CREATE TABLE SUP AS
		SELECT Input(PrefSupEst, 4.) AS PrefDep,
			0 AS Carteira, Sum(Qtd_Cli) AS Qtd_Cli,
			Sum(QT_ABD) AS QT_ABD, 0 AS PC_ABD, Sum(QT_ACT) AS QT_ACT, 
			0 AS PC_ACT, Sum(MD) AS MD, Sum(VC) AS VC, Sum(E1) AS E1, 
			Sum(E2) AS E2, Sum(E3) AS E3, Sum(E4) AS E4, Sum(E5) AS E5, 
			Sum(E6) AS E6, 0 AS EF, Sum(Contratou) AS Contratou 
		FROM CRT A 
			INNER JOIN IGR.IGRREDE_&AnoMes B ON(A.PrefDep=Input(B.PrefDep, 4.))
				GROUP BY 1;
QUIT;

DATA SUP;
	SET SUP;
	PC_ABD=(QT_ABD/Qtd_Cli)*100;

	IF QT_ABD=0 THEN
		PC_ACT=0;
	ELSE PC_ACT=(QT_ACT/QT_ABD)*100;
RUN;

PROC SQL;
	CREATE TABLE DIR AS
		SELECT Input(PrefUEN, 4.) AS PrefDep,
			0 AS Carteira, Sum(Qtd_Cli) AS Qtd_Cli,
			Sum(QT_ABD) AS QT_ABD, 0 AS PC_ABD, Sum(QT_ACT) AS QT_ACT, 
			0 AS PC_ACT, Sum(MD) AS MD, Sum(VC) AS VC, Sum(E1) AS E1, 
			Sum(E2) AS E2, Sum(E3) AS E3, Sum(E4) AS E4, Sum(E5) AS E5, 
			Sum(E6) AS E6, 0 AS EF, Sum(Contratou) AS Contratou 
		FROM SUP A 
			INNER JOIN IGR.IGRREDE_&AnoMes B ON(A.PrefDep=Input(B.PrefDep, 4.))
				GROUP BY 1;
QUIT;

DATA DIR;
	SET DIR;
	PC_ABD=(QT_ABD/Qtd_Cli)*100;

	IF QT_ABD=0 THEN
		PC_ACT=0;
	ELSE PC_ACT=(QT_ACT/QT_ABD)*100;
RUN;

PROC SQL;
	CREATE TABLE VIP AS
		SELECT 8166 AS PrefDep,
			0 AS Carteira, Sum(Qtd_Cli) AS Qtd_Cli,
			Sum(QT_ABD) AS QT_ABD, 0 AS PC_ABD, Sum(QT_ACT) AS QT_ACT, 
			0 AS PC_ACT, Sum(MD) AS MD, Sum(VC) AS VC, Sum(E1) AS E1, 
			Sum(E2) AS E2, Sum(E3) AS E3, Sum(E4) AS E4, Sum(E5) AS E5, 
			Sum(E6) AS E6, 0 AS EF, Sum(Contratou) AS Contratou 
		FROM SUP A 
			INNER JOIN IGR.IGRREDE_&AnoMes B ON(A.PrefDep=Input(B.PrefDep, 4.))
				GROUP BY 1;
QUIT;

DATA VIP;
	SET VIP;
	PC_ABD=(QT_ABD/Qtd_Cli)*100;

	IF QT_ABD=0 THEN
		PC_ACT=0;
	ELSE PC_ACT=(QT_ACT/QT_ABD)*100;
RUN;

DATA AUX_RPT(RENAME=(PrefDep=Prefixo) WHERE=(Prefixo NE 0) DROP=Contratou);
	Format Posicao yymmdd10.;
	SET CRT PAA AGC GRV SUP DIR VIP;
	BY PrefDep Carteira;
	Posicao=Today();

	IF QT_ACT=0 THEN
		EF=0;
	ELSE EF=(Contratou/QT_ACT)*100;
RUN;

PROC SQL;
	CREATE TABLE EXPORTAR AS
		SELECT Posicao, Prefixo, Carteira, Qtd_Cli, Qt_Abd, Pc_Abd, Qt_Act,
			Pc_Act, MD, VC, E1, E2, E3, E4, E5, E6, EF
		FROM AUX_RPT;
QUIT;

PROC SORT DATA=MG_DISP(KEEP=CD_CLI MG_DISP) NODUPKEY;
	BY _ALL_;
RUN;





PROC SQL;
   CREATE TABLE WORK.CTT_CLI_CMCO AS 
   SELECT       
          t1.CD_CLI, 
          max(TS_CTT) AS TS_CTT
      FROM DB2COC.CTT_CLI_CMCO t1
	  WHERE CD_ACAO IN (18320 18495)
GROUP BY 1;
QUIT;

DATA CONTATOS_GIRO;
SET OGC.CONTATOS_ACM_IV;
WHERE QT_ITEM_VCLD_INRO IN (18320 18495);
RUN;



PROC SQL;
   CREATE TABLE WORK.CONTATOS_18002 AS 
   SELECT t1.CD_CLI, 
          DATEPART(TS_CTT) FORMAT DDMMYY10. AS DT_CTT,
		  T2.*
      FROM WORK.CTT_CLI_CMCO t1
LEFT JOIN CONTATOS_GIRO t2 on (t1.CD_CLI=T2.CD_CLI)
GROUP BY 1,3,4,5,6;
QUIT;



DATA DET_CLIENTES;
	MERGE PROPOSTAS_BASE_T CONTATOS_18002 MG_DISP;
	BY CD_CLI;
RUN;


PROC SQL;
	CREATE TABLE EXP_GIRO AS
		SELECT Today() Format yymmdd10. AS Posicao, PrefDep AS Prefixo,
			Carteira, A.CD_CLI,  DT_CTT Format yymmdd10., TX_RSTD_INRO,
			TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, DTA_PROP Format yymmdd10.,
			NRO_PROP, VLR_PROP_ITEM_FINC, NR_UNCO, SITU, MG_DISP Format 19.2,PFL_0,
			PFL_1,PFL_2,PFL_3,PFL_4,PFL_5,PFL_6,PFL_7,PFL_8,PFL_9,PFL_10,PFL_11,PFL_12, c.convenio, e.risco, 
		  (CASE WHEN e.CD_EST_LMCR=00 THEN 'Em estudo'
		  WHEN e.CD_EST_LMCR=10 THEN 'Vigente'
		  WHEN e.CD_EST_LMCR=20 THEN 'Cancelado'
		  WHEN e.CD_EST_LMCR=25 THEN 'Cancelado - dados pendentes'
		  WHEN e.CD_EST_LMCR=30 THEN 'Cancelado - a partir vigente'
		  WHEN e.CD_EST_LMCR=40 THEN 'Vencido'
		  WHEN e.CD_EST_LMCR=50 THEN 'Impedido'
		  WHEN e.CD_EST_LMCR=60 THEN 'Indeferido'
		  WHEN e.CD_EST_LMCR=70 THEN 'Em transferência'
		  WHEN e.CD_EST_LMCR=78 THEN 'Suspenso'
          END)
           as situacao_limite_credito  
			/*			IFC(NV=.,'-',Put(NV, Z1.)) AS NV*/
	FROM DET_CLIENTES A
		RIGHT JOIN junta_publico C ON(A.CD_CLI=C.CD_CLI)
			LEFT JOIN PUBLICO_PERFIL D ON (A.CD_CLI=D.CD_CLI)
			left join comum.bcn_pj e on (a.cd_cli = e.mci)
				/*				LEFT JOIN OGC.NV_SUGERIDO_ASS B ON(A.CD_CLI=B.CD_CLI)*/
	WHERE PrefDep NE . AND C.CD_ACAO IN (18002 18320 18495)
GROUP BY 1,2,3,4;
QUIT;


PROC SQL;
   CREATE TABLE WORK.CTT_CLI_CMCO_rec AS 
   SELECT       
          t1.CD_CLI, 
          max(TS_CTT) AS TS_CTT
      FROM DB2COC.CTT_CLI_CMCO t1
	  WHERE CD_ACAO IN (18003 18486)
GROUP BY 1;
QUIT;

PROC SQL;
	CREATE TABLE CONTATOS_18003 AS 
		SELECT *
			FROM OGC.CONTATOS_ACM_IV t1
				RIGHT JOIN CTT_CLI_CMCO_rec T2 ON (T1.CD_CLI=T2.CD_CLI)
					WHERE  QT_ITEM_VCLD_INRO IN (18003 18486)
						ORDER BY 1;
QUIT;

DATA DET_RECEBIVEIS;
	MERGE PROPOSTAS_BASE_T CONTATOS_18003 MG_DISP;
	BY CD_CLI;
RUN;




PROC SQL;
	CREATE TABLE EXP_REC AS
		SELECT Today() Format yymmdd10. AS Posicao, PrefDep AS Prefixo,
			Carteira, A.CD_CLI,  DT_CTT Format yymmdd10., TX_RSTD_INRO,
			TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, DTA_PROP Format yymmdd10.,
			NRO_PROP, VLR_PROP_ITEM_FINC, NR_UNCO, SITU, MG_DISP Format 19.2,PFL_0,
			PFL_1,PFL_2,PFL_3,PFL_4,PFL_5,PFL_6
			/*			IFC(NV=.,'-',Put(NV, Z1.)) AS NV*/
	FROM DET_RECEBIVEIS A
		RIGHT JOIN junta_publico C ON(A.CD_CLI=C.CD_CLI)
			LEFT JOIN PUBLICO_PERFIL D ON (A.CD_CLI=D.CD_CLI)
				/*				LEFT JOIN OGC.NV_SUGERIDO_ASS B ON(A.CD_CLI=B.CD_CLI)*/
	WHERE PrefDep NE . AND C.CD_ACAO IN (18003 18486);
QUIT;




PROC SQL;
   CREATE TABLE WORK.CTT_CLI_CMCO_CRED AS 
   SELECT       
          t1.CD_CLI, 
          max(TS_CTT) AS TS_CTT
      FROM DB2COC.CTT_CLI_CMCO t1
	  WHERE CD_ACAO IN (180103 18401)
GROUP BY 1;
QUIT;


PROC SQL;
	CREATE TABLE CONTATOS_18103 AS 
		SELECT *
			FROM OGC.CONTATOS_ACM_IV t1 
				RIGHT JOIN CTT_CLI_CMCO_CRED T2 ON (T1.CD_CLI=T2.CD_CLI)
					WHERE  QT_ITEM_VCLD_INRO IN (180103 18401)
						ORDER BY 1;
QUIT;

DATA DET_CREDITO;
	MERGE PROPOSTAS_BASE_T CONTATOS_18103 MG_DISP;
	BY CD_CLI;
RUN;


PROC SQL;
	CREATE TABLE EXP_CRED AS
		SELECT Today() Format yymmdd10. AS Posicao, PrefDep AS Prefixo,
			Carteira, A.CD_CLI,  DT_CTT Format yymmdd10., TX_RSTD_INRO,
			TX_SUB_RSTD_INRO, CD_USU_RSP_ATDT, DTA_PROP Format yymmdd10.,
			NRO_PROP, VLR_PROP_ITEM_FINC, NR_UNCO, SITU, MG_DISP Format 19.2,PFL_0,
			PFL_1,PFL_2,PFL_3,PFL_4,PFL_5,PFL_6,PFL_7,PFL_8,PFL_9
			/*			IFC(NV=.,'-',Put(NV, Z1.)) AS NV*/
	FROM DET_CREDITO A
		RIGHT JOIN junta_publico C ON(A.CD_CLI=C.CD_CLI)
			LEFT JOIN PUBLICO_PERFIL D ON (A.CD_CLI=D.CD_CLI)
				/*				LEFT JOIN OGC.NV_SUGERIDO_ASS B ON(A.CD_CLI=B.CD_CLI)*/
	WHERE PrefDep NE . AND C.CD_ACAO in (18103 18401);
QUIT;





%LET Usuario=f9457977;
%LET Keypass=EixJ3xu9w9EaBp8OX6gEQ7W1SJLajvM1aVtOzGlNt03LRZxopK;

PROC SQL;
	CREATE TABLE TABELAS_EXPORTAR_REL (TABELA_SAS CHAR(100), ROTINA CHAR(100));
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('EXPORTAR', 'ofertas-ativas-pj');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('EXP_GIRO', 'clientes');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('EXP_REC', 'detalha-recebiveis-acao-18003');
	INSERT INTO TABELAS_EXPORTAR_REL VALUES('EXP_CRED', 'detalha-cred-invest-acao-18103');
QUIT;
%ExportarREL(TABELAS_EXPORTAR_REL, &Usuario, &Keypass);

%EncerrarProcessoMySQL(Ofertas Ativas PJ);
x cd /dados/infor/producao/ofertas_AmpliaNegociosPJ;
x chmod 2777 *;

/*************************************************/;
/* TRECHO DE CÓDIGO INCLUÍDO PELO FF */;

%include "/dados/gestao/rotinas/_macros/macros_uteis.sas";
 
%processCheckOut(
    uor_resp = 341556
    ,funci_resp = &sysuserid
    /*,tipo = Indicador
    ,sistema = Indicador
    ,rotina = I0123 Indicador de Alguma Coisa*/
    ,mailto= 'F8369937' 'F2986408' 'F6794004' 'F7176219' 'F8176496' 'F9457977' 'F9631159'
);
